### ISSUE TITLE
Preline Js is not loading in Qwik  Production build

### ISSUE THREAD

**Issue by Adarshvk98** [htmlstreamofficial/preline#100]
Added preline UI in my qwik project and followed the guide for qwik project setup. It's working fine in development mode. This is how i have loaded the preline javascript 

```
// root.tsx
<QwikCityProvider>
  ...
  <body lang="en">
    ...
    <RouterOutlet />
    ...
    <script src="./node_modules/preline/dist/preline.js">
</script>
  </body>
</QwikCityProvider>
```

But in production build, the given javascript is not loading!! 

It appears that it is attempting to load from node_modules and I believe that the production build does not have such a path.

**Comment by isaiah-banks** [comment]
I don't know anything about Qwik, but in Svelte I fixed this by getting rid of the `<script>` tag and just use `import 'preline/dist/preline.js'` in my +layout.svelte. I assume this would be similar in Qwik.

**Comment by jahaganiev** [comment]
Hey @Adarshvk98 - I'm following up to check if the issue you reported is still ongoing. We've recently had a major update, and I recommend testing with the latest version to see if the problem persists. Also, @binkycs's suggestion might help out.

Cheers!
