### ISSUE TITLE
Does Preline support NextJS 13?

### ISSUE THREAD

**Issue by sebastianbilling** [htmlstreamofficial/preline#101]
Hey

I'm wondering if Preline supports the latest version of NextJS? I'm unable to find anything in the documentation and I don't know where to import the Preline package.

**Comment by sebastianbilling** [comment]
For now I'm importing it by page, is this the best solution?

**Comment by dearmosin** [comment]
`module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    preline: {},
  },
}`

Try addning preline to postcss.config.js

**Comment by smyja** [comment]
> Hey
> 
> I'm wondering if Preline supports the latest version of NextJS? I'm unable to find anything in the documentation and I don't know where to import the Preline package.

it does.

**Comment by smyja** [comment]
> Hey
> 
> I'm wondering if Preline supports the latest version of NextJS? I'm unable to find anything in the documentation and I don't know where to import the Preline package.

it does.

**Comment by anesask** [comment]
> For now I'm importing it by page, is this the best solution?

Same question here.

**Comment by abduncan** [comment]
Same question..

**Comment by ClementCariou** [comment]
I ended up doing this :

preline.tsx
```tsx
"use client";

import React from 'react';
import { useEffect } from 'react';

export default function Preline({ children }: { children: React.ReactNode }) {
    useEffect(() => {
        // @ts-ignore
        import('preline');
    }, []);
    return <>{children}</>;
}
```

layout.tsx
```tsx
import Preline from './preline'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Preline>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Preline>
  )
}
```

**Comment by jahaganiev** [comment]
Closing the issue since it has been addressed with v2.x releases. If you are still having any issues, please open a new issue with more details. Thanks for sharing workarounds with everyone!
