### ISSUE TITLE
Navigation bar super menu, multilevel menu direction can not be customized?

### ISSUE THREAD

**Issue by guugg** [htmlstreamofficial/preline#103]
My guess is that under the super screen, all the subordinate columns are spread out in the lower right corner. I tried the document 'directions' add' [--placement:right-top] 'does not seem to be implemented, is need to rewrite js

**Comment by Mr-Zafar** [comment]
@guugg can you share more details about them? Including live examples, screenshots or video examples would help us a lot.

**Comment by jahaganiev** [comment]
Hey @guugg, we're going to mark this issue as closed for the moment. However, if you have more details to share in the future, please don't hesitate to open a new issue.
