### ISSUE TITLE
support RTL

### ISSUE THREAD

**Issue by sajjadgol** [htmlstreamofficial/preline#104]
Hi
Does Praline support RTL for Persian and Arabic language?

**Comment by Mr-Zafar** [comment]
@sajjadgol we will be in Preline v2. Stay tuned.

**Comment by Mr-Zafar** [comment]
Just to clarify, we will only be supporting what Tailwind CSS supports, which is "[Simplified RTL support with logical properties](https://tailwindcss.com/blog/tailwindcss-v3-3#simplified-rtl-support-with-logical-properties)"

**Comment by Mr-Zafar** [comment]
@sajjadgol with v2.0 live now, the above-mentioned feature is available
