### ISSUE TITLE
Table - Products Review broken on Firefox

### ISSUE THREAD

**Issue by BojanKogoj** [htmlstreamofficial/preline#107]
Table rows aren't expanding properly, other examples are fine.
![image](https://github.com/htmlstreamofficial/preline/assets/634075/77875a8f-6753-4340-9146-764b66850841)

Using
OS: Windows 10
Browser: Firefox 114.0.2

**Comment by Mr-Zafar** [comment]
```
<td class="h-px w-px whitespace-nowrap">
  <a class="block h-full p-6" href="#">
    ...
  </a>
</td>
```
Removing the `.h-full` from the anchor and adding `.align-top` to the `<td>` fixes this
```
<td class="h-px w-px whitespace-nowrap align-top">
  <a class="block p-6" href="#">
    ...
  </a>
</td>
```
