### ISSUE TITLE
Request for Navbar Offcanvas

### ISSUE THREAD

**Issue by Dezmonter** [htmlstreamofficial/preline#11]
Thanks for a great product, do you have an example Navbar with Offcanvas?

**Comment by Mr-Zafar** [comment]
Hi, @Dezmonter -

Thanks for your suggestion and for using our product. We appreciate it!

We'll add an example page with this feature shortly and keep improving them.

Feel free to contact us if you have any questions or feedback. We are here to help!

Thanks!

**Comment by Mr-Zafar** [comment]
Hi, @Dezmonter -

We added the requested feature in the latest update and it can be found [here](https://preline.co/examples/html/header-offcanvas.html).

Thanks!
