### ISSUE TITLE
Use preline without NPM

### ISSUE THREAD

**Issue by gassio** [htmlstreamofficial/preline#112]
Hi!
Is there any way to use preline and its plugins (dropdown, overlay, etc) without the CLI and NPM and just include the scripts inside html?

Thanks!

**Comment by jahaganiev** [comment]
Hey @gassio! 

Yes, definitely you can do that - you just need to download Preline package from the Github. Please keep in mind to use correct path (path_to/preline/plugin) in the tailwind.config.js file when linking plugin.js file.

Cheers!
