### ISSUE TITLE
Overlay has a parent/z-index issue

### ISSUE THREAD

**Issue by ziedHamdi** [htmlstreamofficial/preline#113]
Hello, 

Thanks for the great lib, I'm having an issue with the generated css when calling window.HSOverlay.open(overlay);

I have a logIn popin and another one I took from the offical example of a model https://preline.co/docs/modal.html

When invoking the HSOverlay.open for the SignIn popin, it works as expected: the Signin popin shows above the dark layer. But when I call it on the second popin (directly or through the button **Open Modal** from your example), the overlay is above the content of the popin

I made the example visible here https://test.cvlink.in, you'll find a button **Open Modal** that showcases the issue.

The css is very hard to debug: I tried to increase the z-index of the popin, add it a position:relative, decrease the z-index of the element with the attribute `data-hs-overlay-backdrop-template`, it seems to me there's an issue with the parent-child relationship, so the z-index doesn't apply correctly, but I'm not a a css guru, so it's just a vague guess

**Comment by Mr-Zafar** [comment]
@ziedHamdi take the modal content outside of the `<main>...</main>` tag 

from

```
<main>
	<button type="button" class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800" data-hs-overlay="#hs-static-backdrop-modal">
		Open modal
  </button>
	<div id="hs-static-backdrop-modal" class="hs-overlay hidden w-full h-full fixed top-0 left-0 z-[60] overflow-x-hidden overflow-y-auto [--overlay-backdrop:static]" data-hs-overlay-keyboard="false">
		...
	</div>
</main>
```

to

```
<main>
	<button type="button" class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800" data-hs-overlay="#hs-static-backdrop-modal">
		Open modal
  </button>
</main>

<div id="hs-static-backdrop-modal" class="hs-overlay hidden w-full h-full fixed top-0 left-0 z-[60] overflow-x-hidden overflow-y-auto [--overlay-backdrop:static]" data-hs-overlay-keyboard="false">
	...
</div>
```

**Comment by ziedHamdi** [comment]
This is kind of counter-intuitive. I'd love to know how you did to debug that

**Comment by Mr-Zafar** [comment]
@ziedHamdi Just so you know, modals, offcanvas or any kind of external windows should be outside of the main content. Otherwise, you will end up with issues like yours.

**Comment by ziedHamdi** [comment]
That's pretty hard to do in a component based app like SvelteKit or React, where the main content is defined in the layout component. I worked around this by using the popin from Flowbite, which works even being in the main element. So I think it's limiting to keep it this way
