### ISSUE TITLE
Accordion Plugin Documentation: Incorrect event listener for closed items

### ISSUE THREAD

**Issue by hassanrobinson** [htmlstreamofficial/preline#114]
Preline setup:
- Already using Preline UI as a package within a svelte project

**The following works as expected:**
`$accordionEl.addEventListener('open.hs.accordion', (evt) => {...})
`

**The following does not work as expected:**
`$accordionEl.addEventListener('close.hs.accordion', (evt) => {...})
`

**Resolution**
Update documentation to include 'hide.hs.accordion' instead of 'close.hs.accordion' for when accordion items are closed.

`$accordionEl.addEventListener('hide.hs.accordion', (evt) => {...})
`

Link to documentation:
https://preline.co/plugins/html/accordion.html

**Comment by jahaganiev** [comment]
Thanks for pointing out the typo issue in the docs!

**Comment by RSchmitzHH** [comment]
https://preline.co/plugins/html/accordion.html#js-events still has 'close'? Is this intended?
