### ISSUE TITLE
Adding backdrop blur to a div breaks the tooltip position of any element in that div

### ISSUE THREAD

**Issue by vikasr111** [htmlstreamofficial/preline#118]
I am using Preline with TailwindCSS in my NextJS project. I am noticing a strange problem with tooltips and backdrop-blur filter. I have created a simple component with a div and couple of elements inside the div. One of those elements is a button where I have added tooltip.

When I add backdrop-blur filter to the div, the tooltip position breaks and it always shows on the right side of the screen. Here's the component code for reference.

```
 <div className='hidden lg:flex items-center justify-between sticky top-0 z-10 w-full bg-slate-100/80 backdrop-blur-lg py-4 px-5 text-2xl font-semibold'>
   <span> heading </span>
    <div className='flex'>
      <div className='hs-tooltip inline-block [--placement:bottom]'>
        <button
          type='button'
          className='hs-tooltip-toggle inline-flex flex-shrink-0 justify-center items-center h-10 w-10 rounded-full text-text_default bg-slate-100 hover:bg-slate-200 focus:outline-none text-sm transition duration-200'
          data-hs-overlay='#hs-modal-user-interest'
        >
          <span className='sr-only'>Your Preference</span>
          <svg
            xmlns='http://www.w3.org/2000/svg'
            viewBox='0 0 24 24'
            fill='currentColor'
            className='w-6 h-6'
          >
            <path
              fillRule='evenodd'
              d='M9 4.5a.75.75 0 01.721.544l.813 2.846a3.75 3.75 0 002.576 2.576l2.846.813a.75.75 0 010 1.442l-2.846.813a3.75 3.75 0 00-2.576 2.576l-.813 2.846a.75.75 0 01-1.442 0l-.813-2.846a3.75 3.75 0 00-2.576-2.576l-2.846-.813a.75.75 0 010-1.442l2.846-.813A3.75 3.75 0 007.466 7.89l.813-2.846A.75.75 0 019 4.5zM18 1.5a.75.75 0 01.728.568l.258 1.036c.236.94.97 1.674 1.91 1.91l1.036.258a.75.75 0 010 1.456l-1.036.258c-.94.236-1.674.97-1.91 1.91l-.258 1.036a.75.75 0 01-1.456 0l-.258-1.036a2.625 2.625 0 00-1.91-1.91l-1.036-.258a.75.75 0 010-1.456l1.036-.258a2.625 2.625 0 001.91-1.91l.258-1.036A.75.75 0 0118 1.5zM16.5 15a.75.75 0 01.712.513l.394 1.183c.15.447.5.799.948.948l1.183.395a.75.75 0 010 1.422l-1.183.395c-.447.15-.799.5-.948.948l-.395 1.183a.75.75 0 01-1.422 0l-.395-1.183a1.5 1.5 0 00-.948-.948l-1.183-.395a.75.75 0 010-1.422l1.183-.395c.447-.15.799-.5.948-.948l.395-1.183A.75.75 0 0116.5 15z'
              clipRule='evenodd'
            />
          </svg>
          <span
            className='hs-tooltip-content hs-tooltip-shown:opacity-100 hs-tooltip-shown:visible opacity-0 transition-opacity inline-block absolute invisible z-10 py-1 px-2 bg-gray-900 text-xs font-medium text-white rounded-md shadow-sm dark:bg-slate-700'
            role='tooltip'
          >
            Your preference
          </span>
        </button>
      </div>
    </div>
 </div>
```

I am able to replicate this issue on Preline doc site as well by simply adding the backdrop filter on the parent div of tooltip element. https://preline.co/docs/tooltip.html

Help me find a solution to this.

**Comment by olegpix** [comment]
> I am using Preline with TailwindCSS in my NextJS project. I am noticing a strange problem with tooltips and backdrop-blur filter. I have created a simple component with a div and couple of elements inside the div. One of those elements is a button where I have added tooltip.
> 
> When I add backdrop-blur filter to the div, the tooltip position breaks and it always shows on the right side of the screen. Here's the component code for reference.
> 
> ```
>  <div className='hidden lg:flex items-center justify-between sticky top-0 z-10 w-full bg-slate-100/80 backdrop-blur-lg py-4 px-5 text-2xl font-semibold'>
>    <span> heading </span>
>     <div className='flex'>
>       <div className='hs-tooltip inline-block [--placement:bottom]'>
>         <button
>           type='button'
>           className='hs-tooltip-toggle inline-flex flex-shrink-0 justify-center items-center h-10 w-10 rounded-full text-text_default bg-slate-100 hover:bg-slate-200 focus:outline-none text-sm transition duration-200'
>           data-hs-overlay='#hs-modal-user-interest'
>         >
>           <span className='sr-only'>Your Preference</span>
>           <svg
>             xmlns='http://www.w3.org/2000/svg'
>             viewBox='0 0 24 24'
>             fill='currentColor'
>             className='w-6 h-6'
>           >
>             <path
>               fillRule='evenodd'
>               d='M9 4.5a.75.75 0 01.721.544l.813 2.846a3.75 3.75 0 002.576 2.576l2.846.813a.75.75 0 010 1.442l-2.846.813a3.75 3.75 0 00-2.576 2.576l-.813 2.846a.75.75 0 01-1.442 0l-.813-2.846a3.75 3.75 0 00-2.576-2.576l-2.846-.813a.75.75 0 010-1.442l2.846-.813A3.75 3.75 0 007.466 7.89l.813-2.846A.75.75 0 019 4.5zM18 1.5a.75.75 0 01.728.568l.258 1.036c.236.94.97 1.674 1.91 1.91l1.036.258a.75.75 0 010 1.456l-1.036.258c-.94.236-1.674.97-1.91 1.91l-.258 1.036a.75.75 0 01-1.456 0l-.258-1.036a2.625 2.625 0 00-1.91-1.91l-1.036-.258a.75.75 0 010-1.456l1.036-.258a2.625 2.625 0 001.91-1.91l.258-1.036A.75.75 0 0118 1.5zM16.5 15a.75.75 0 01.712.513l.394 1.183c.15.447.5.799.948.948l1.183.395a.75.75 0 010 1.422l-1.183.395c-.447.15-.799.5-.948.948l-.395 1.183a.75.75 0 01-1.422 0l-.395-1.183a1.5 1.5 0 00-.948-.948l-1.183-.395a.75.75 0 010-1.422l1.183-.395c.447-.15.799-.5.948-.948l.395-1.183A.75.75 0 0116.5 15z'
>               clipRule='evenodd'
>             />
>           </svg>
>           <span
>             className='hs-tooltip-content hs-tooltip-shown:opacity-100 hs-tooltip-shown:visible opacity-0 transition-opacity inline-block absolute invisible z-10 py-1 px-2 bg-gray-900 text-xs font-medium text-white rounded-md shadow-sm dark:bg-slate-700'
>             role='tooltip'
>           >
>             Your preference
>           </span>
>         </button>
>       </div>
>     </div>
>  </div>
> ```
> 
> I am able to replicate this issue on Preline doc site as well by simply adding the backdrop filter on the parent div of tooltip element. https://preline.co/docs/tooltip.html
> 
> Help me find a solution to this.

Hi,
It seems that the "background-blur" filter itself has problems and affects the "position" property.

[Stackoverflow 1](https://stackoverflow.com/questions/66324118/backdrop-filter-blur-not-working-on-a-position-absolute-element)
[Stackoverflow 2](https://stackoverflow.com/questions/49599095/backdrop-filter-blur-not-working/72818752#72818752)

**Comment by jahaganiev** [comment]
Hey @vikasr111 - this doesn't seem Preline exclusive issue, please feel free to let us know if that's not the case. Thanks!

**Comment by Setupboy** [comment]
Same problem here, Anyone knwo a fix?
