### ISSUE TITLE
Getting webpack error  self is not defined. I am using Preline with Gatsby 5.

### ISSUE THREAD

**Issue by prateekshaweb** [htmlstreamofficial/preline#119]
Getting webpack error  self is not defined. I am using Preline with Gatsby 5

success Building Rendering Engines - 3.135s
success Building HTML renderer - 2.594s
success Execute page configs - 0.064s
success Validating Rendering Engines - 1.674s
success Caching Webpack compilations - 0.001s
success run queries in workers - 0.046s - 1/1 21.62/s
success Merge worker state - 0.002s
success Rewriting compilation hashes - 0.002s
success Writing page-data.json and slice-data.json files to public directory - 0.025s - 1/1 40.56/s

 ERROR  UNKNOWN

self is not defined

  ReferenceError: self is not defined
  
  - preline.js:2 Object.7280
    [gatsby-starter-default]/[preline]/dist/preline.js:2:223
  
  - bootstrap:19 __webpack_require__
    /home/yuvraj/webdesign/prateeksha.com/gatsby/.cache/page-ssr/routes/webpack:/gatsby-starter-default/webpack
    /bootstrap:19:1
  
  - create fake namespace object:10 Function.__webpack_require__.t
    /home/yuvraj/webdesign/prateeksha.com/gatsby/.cache/page-ssr/routes/webpack:/gatsby-starter-default/webpack
    /runtime/create fake namespace object:10:1
  

failed Building static HTML for pages - 3.674s

 ERROR #95313  HTML.COMPILATION

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html

  186 | export function LuArrowDownLeft (props) {
  187 |   return GenIcon({"tag":"svg","attr":{"viewBox":"0 0 24 
24","fill":"none","stroke":"currentColor","strokeWidth":"2","strokeLinecap":"round","strokeLinejoin":"round"},"
child":[{"tag":"line","attr":{"x1":"17","x2":"7","y1":"7","y2":"17"}},{"tag":"polyline","attr":{"points":"17 17
 7 17 7 7"}}]})(props);
> 188 | };
      | ^
  189 | export function LuArrowDownNarrowWide (props) {
  190 |   return GenIcon({"tag":"svg","attr":{"viewBox":"0 0 24 24","fill":"none","stroke":"currentColor","stro
keWidth":"2","strokeLinecap":"round","strokeLinejoin":"round"},"child":[{"tag":"path","attr":{"d":"m3 16 4 4 
4-4"}},{"tag":"path","attr":{"d":"M7 20V4"}},{"tag":"path","attr":{"d":"M11 
4h4"}},{"tag":"path","attr":{"d":"M11 8h7"}},{"tag":"path","attr":{"d":"M11 12h10"}}]})(props);
  191 | };

  WebpackError: Worker exited before finishing task
.

**Comment by prateekshaweb** [comment]
Hi...I managed to solve this issue.
the problem was that there is no window object when we generate static pages
here are the steps that will help to solve the issue

1. do not import the js file directly. it will give an error.
use this. 

if (typeof window !== 'undefined') {
  import('preline');
}

though the file is not imported, it will help in develop.

2. in gatsby-browser.js, add this line

import './node_modules/preline/dist/preline.js';

3. in tailwind.config.js

add this line before closing the object

plugins: [
    require('preline/plugin'),
  ],

 that should solve the issue

**Comment by jahaganiev** [comment]
Awesome - thanks for sharing the workaround!
