### ISSUE TITLE
Dark Mode "Select"

### ISSUE THREAD

**Issue by zzhuravleff** [htmlstreamofficial/preline#120]
Hi. I have decided to use Tailwind CSS in conjunction with Preline UI on my website. I decided to make a theme switcher. In the official documentation I liked 'Select'. I plugged it in, everything seems to work fine, but dark mode is enabled, light mode is also enabled, but when I try to enable the system mode, it just turns on the standard (light mode), despite the fact that both in the browser and in the PC is dark mode. How can I solve this problem?

The toggle element itself is located in components/TheHeader.jsx

The js script is located in public/ChangeTheme.js

Tailwind.config.js in root

[CodeSandbox](https://codesandbox.io/p/github/zzhuravleff/testcsb/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cllmqnosa000h3o6dw5knr98p%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cllmqnos9000c3o6dwxtn2kpm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cllmqnosa000g3o6dmh4n3jlq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cllmqnosa000e3o6dz0sbpyfv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cllmqnos9000c3o6dwxtn2kpm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cllmqnos9000b3o6djkw1wmcs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cllmqnos9000c3o6dwxtn2kpm%2522%252C%2522activeTabId%2522%253A%2522cllmqnos9000b3o6djkw1wmcs%2522%257D%252C%2522cllmqnosa000e3o6dz0sbpyfv%2522%253A%257B%2522id%2522%253A%2522cllmqnosa000e3o6dz0sbpyfv%2522%252C%2522activeTabId%2522%253A%2522cllmqo4mu00xm3o6dgrtn6wj1%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cllmqo4mu00xm3o6dgrtn6wj1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cllmqnosa000g3o6dmh4n3jlq%2522%253A%257B%2522id%2522%253A%2522cllmqnosa000g3o6dmh4n3jlq%2522%252C%2522activeTabId%2522%253A%2522cllmqo42300ma3o6d3o1ylu6i%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cllmqnosa000f3o6dwmhp7ukf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cllmqnpd4001ed9f19q4pcwnt%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cllmqo42300ma3o6d3o1ylu6i%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

[GitHub Repo](https://github.com/zzhuravleff/testcsb)

[Vercel](https://codecraft-ten.vercel.app/)

**Comment by lokiwich** [comment]
Hi, I have a same problem, the auto mode only turns on the light mode,
This bug is also in the [Dark Mode](https://preline.co/docs/dark-mode.html#dark-mode-select) documents

**Comment by iozcelik** [comment]
Dark mode select also not working with Astro. I add the select but nothing happen.

**Comment by 2a5A1Ghu1** [comment]
It's hackish but this works.

add this to tailwind.config.cjs

```javascript
/** @type {import('tailwindcss').Config} */
import preline from 'preline/plugin.js';
module.exports = {
	content: [
		'./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}',
		'node_modules/preline/dist/*.js'
	],
	darkMode: 'class',
	theme: {
		extend: {},
	},
	plugins: [
		preline,
	],
}
```

then make a file called ThemeSwitcher.astro and put it in your src/component directory(make one if you don't have one)

```javascript
<div>
  <a
    class='hs-dark-mode-active:hidden block hs-dark-mode group flex items-center text-gray-600 hover:text-blue-600 font-medium dark:text-gray-400 dark:hover:text-gray-500'
    href='javascript:;'
    data-hs-theme-click-value='dark'
  >
    <svg
      class='w-4 h-4'
      xmlns='http://www.w3.org/2000/svg'
      width='16'
      height='16'
      fill='currentColor'
      viewBox='0 0 16 16'
    >
      <path
        d='M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278zM4.858 1.311A7.269 7.269 0 0 0 1.025 7.71c0 4.02 3.279 7.276 7.319 7.276a7.316 7.316 0 0 0 5.205-2.162c-.337.042-.68.063-1.029.063-4.61 0-8.343-3.714-8.343-8.29 0-1.167.242-2.278.681-3.286z'
      ></path>
    </svg>
  </a>
  <a
    class='hs-dark-mode-active:block hidden hs-dark-mode group flex items-center text-gray-600 hover:text-blue-600 font-medium dark:text-gray-400 dark:hover:text-gray-500'
    href='javascript:;'
    data-hs-theme-click-value='light'
  >
    <svg
      class='w-4 h-4'
      xmlns='http://www.w3.org/2000/svg'
      width='16'
      height='16'
      fill='currentColor'
      viewBox='0 0 16 16'
    >
      <path
        d='M8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6zm0 1a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z'
      ></path>
    </svg>
  </a>
</div>
```

Assuming this is a fresh install with no theme, replace everything in Layout.astro with

```javascript
---
import ThemeSwitcher from "../components/ThemeSwitcher.astro";

interface Props {
  title: string;
}

const { title } = Astro.props;
---

<!doctype html>
<html lang='en'>
  <head>
    <meta charset='UTF-8' />
    <meta name='description' content='Astro description' />
    <meta name='viewport' content='width=device-width' />
    <link rel='icon' type='image/svg+xml' href='/favicon.svg' />
    <meta name='generator' content={Astro.generator} />
    <title>{title}</title>
    <script is:inline src='./node_modules/preline/dist/preline.js'></script>
    <script src='../libs/ThemeSwitcher.js'></script>
  </head>
  <body class='dark:bg-slate-900 bg-gray-100'>
    <ThemeSwitcher />
    <slot />
    <style is:global>
      :root {
        --accent: 136, 58, 234;
        --accent-light: 224, 204, 250;
        --accent-dark: 49, 10, 101;
        --accent-gradient: linear-gradient(
          45deg,
          rgb(var(--accent)),
          rgb(var(--accent-light)) 30%,
          white 60%
        );
      }
      html {
        font-family: system-ui, sans-serif;
        background-size: 224px;
      }
      code {
        font-family:
          Menlo,
          Monaco,
          Lucida Console,
          Liberation Mono,
          DejaVu Sans Mono,
          Bitstream Vera Sans Mono,
          Courier New,
          monospace;
      }
    </style>
  </body>
</html>
```

Preline doesn't play well with most things and I suspect this solution to be buggy"ish" at best. Especially since you have to link directly to the libs in node_modules directory. A better solution might be to "install" preline in a directory such as src/libs or the public directory.

Hope this helps

**Comment by nguyenvuhoang** [comment]
> ```js
> plugins: [
> 		preline,
> 	],
> ```

This work for me

**Comment by jahaganiev** [comment]
Hey folks, we've just added new plugins page "Theme Switch" with updated components docs page:

https://preline.co/plugins/html/theme-switch.html
https://preline.co/docs/dark-mode.html

Cheers!
