### ISSUE TITLE
Close modal and background overlay

### ISSUE THREAD

**Issue by RSchmitzHH** [htmlstreamofficial/preline#121]
Hi there,

Many thanks for your great library! I am using Vue 3 and ts and preline works great so far. However, I encounter the following problem which I do not know how to solve: 

I want to move your modal code to a separate Vue component and include that in my parent component. What I did so far:

In my component file Modal.vue, I
- used your html from an example from https://preline.co/docs/modal.html for my `<template></template>` (except the "Open modal" button, of course)
- added a @click.stop to the "close" and "save changes" buttons of the examples, where the code fragment basically looks like (*** shall denote the new part)
`<button type="button" class="hs-dropup-toggle ... " data-hs-overlay="#hs-slide-up-animation-modal" ***@click.stop="declineModal"***>`
- defined two methods in my `<script setup></script>` that shall handle the button clicks through emit('confirmed') or emit ('declined'), e.g., 
`
function declineModal() {
  emit('declined')
};`

In the parent component, I included the Modal by
`<Modal v-if="showModal" @confirmed=handleConfirmed @declined=handleDeclined />`

where the methods handleConfirmed and handleDeclined reset the reactive state variable showModal back to false 
`showModal.value = false`
and then do some stuff.

This works fine - apart from the fact that the grey background overlay stays there even if the modal is closed. 

If, for instance, the "close" button of the modal is hit, "declineModal()" is called, the event 'declined' is emitted in Modal.vue. In the parent component, the 'declined' event is received correctly and handleDeclined is called. Once showModal.value is set to false, the modal itself does indeed vanish. However, the grey background overlay stays in place. 

How do I solve this problem and get the background overlay removed? What did I get wrong? 

Is it that the `data-hs-overlay="#hs-slide-up-animation-modal"` part of the button does not get executed? 

How can I move the modal example code to a separate component that works properly? 

Many thanks for your help!

**Comment by Bakho0707** [comment]
Hey @RSchmitzHH, 

For the issue you're facing, please try using Preline's methods for Modals, like:

`HSOverlay.open($modalEl)` and `HSOverlay.close($modalEl)`


Here’s a basic example for using them in a Vue 3 component:

```
<template>
  <div ref="modalEl">.....</div>
</template>

<script setup lang="ts">
const emit = defineEmits(['update:modelValue']);
const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
});

const modalEl = ref();
watch(
  () => props.modelValue,
  (newVal, oldVal) => {
    if (newVal) {
      HSOverlay.open(modalEl.value);
    } else {
      HSOverlay.close(modalEl.value);
    }
  }
);
const handleClose = () => {
  HSOverlay.close(modalEl.value);
};
onMounted(() => {
  nextTick(() => {
    modalEl.value.addEventListener('close.hs.overlay', (evt) => {
      emit('update:modelValue', false);
    });
  });
});
</script>
```
Hope that helps!

**Comment by RSchmitzHH** [comment]
Oh wow, this was really (I mean: REALLY) helpful! Thank you SO much!!

P.S. Thanks also for the EventListener in onMounted -- would have been my next question on how to handle close events thru backdrop click or if people hit Esc key. Thanks!!
