### ISSUE TITLE
How can I create a button group?

### ISSUE THREAD

**Issue by waleedrana777** [htmlstreamofficial/preline#125]
![image](https://github.com/htmlstreamofficial/preline/assets/37755440/107c8aa6-713f-4da3-9cd1-9ea3826a5739)

I browsed all the docs and couldn't find this specific button group component, it is quite ironic that you used it on the docs site but no components of it are present, I could make your site in next js! The current version loads the page reloads the page every time new component is selected, resetting the scroll position, hence you have to rescroll all the way down again to reach the component!

**Comment by jahaganiev** [comment]
Hey @waleedrana777,

Please note at the moment, Preline site's source is not open source and there might be in some places custom solutions which we might not have in the Preline UI docs but we are more than happy to include if there's any suggestions. However, this isn't the case. You may find the example in [Navs](https://preline.co/docs/navs.html#segment) page under **Segment** option.

Regarding the UX enhancements, soon we will release v2.0 which will have scroll resetting position improvement and we will consider in future SPA like experience in docs.

Hope that helps!

Cheers!
