### ISSUE TITLE
Calendar component?

### ISSUE THREAD

**Issue by adospace** [htmlstreamofficial/preline#127]
Hi all, 

is there any plan for a Calendar component? for example one that shows the current month in a date picker.

Thank you very much for your work,

Adolfo

**Comment by jahaganiev** [comment]
Hey Adolfo,

Yes, we are considering integrating a datepicker/calendar plugin into Preline UI. However, we haven't decided on which one to choose, as currently it doesn't seem that there are any unstyled, Tailwind friendly (headless) datepicker plugins available.

If you have any suggestions, please feel free to let us know.

Cheers!

**Comment by adospace** [comment]
Hi @jahaganiev, 
thank you for your prompt reply, yes the plugin part is the hard part (it's not easy to find one) :).

Using native tailwind plugins is one of the main reasons I like so much the Preline UI compared to the other tailwind-based frameworks: for example, I'm building a blazor-based integration for Preline UI and it's much easier with Preline UI as I don't have to deal with the dropdowns scripts etc.

May I suggest for the starter to provide just the calendar component? I know the "official" tailwind CSS UI releases just that for example. 

Adolfo

**Comment by jahaganiev** [comment]
Hey @adospace - here we go https://preline.co/docs/datepicker.html 🎉 

Please feel free to open a new issue if you have more suggestions!

Cheers!

**Comment by adospace** [comment]
Wow thank you so much!

**Comment by ibmo12** [comment]
Hi @adospace 

I'm interested in understanding how to effectively use Preline UI within a Blazor project. 
would you be open to sharing a repository or a template? 

Thanks in advance

**Comment by hallelujah** [comment]
@jahaganiev I stumble upon this https://github.com/uvarov-frontend/vanilla-calendar-pro

It looks like really great for the calendar component. They already use tailwindcss as base but it can have custom styling, more than other date picker plugins I have seen out there.

**Comment by jahaganiev** [comment]
Hey @hallelujah, 

Yes! The great news is that it's already fully integrated internally and will be available soon in the upcoming release with the Tailwind v4 update.

Cheers!
