### ISSUE TITLE
Is this project open source?

### ISSUE THREAD

**Issue by mschipperheyn** [htmlstreamofficial/preline#129]
Hi, I like the look of this library but the license gives me pause. It seems to suggest an open source approach, but it looks a bit thrown together TBH and the reference to "Figma" throws me off. If this library is open source, would it be possible to consider applying an MIT license just to leave any doubts aside? Or is there in fact a commercial license aspect I should consider? If so, what is it? Nothing against commercial. Just want to know what I'm dealing with

**Comment by jahaganiev** [comment]
Hey @mschipperheyn,

Preline UI is fully open source and is licensed under the MIT License, as @billturner mentioned.

Please note that we consider Preline Figma to be a completely separate product category. For this reason, it comes with its own custom license, which allows for free use in both commercial and personal projects.

If you have any concerns or questions, please let us know. We're happy to provide further information.

Cheers!
Jaha
