### ISSUE TITLE
Stacked Overlays

### ISSUE THREAD

**Issue by hoangnghiem** [htmlstreamofficial/preline#134]
Hi,

I see the example of the 2 modals: open first modal, then in second modal, there is button back to modal 1. How to keep both modals open? When modal 2 open, modal 1 should also remain in open state.

My issue in my app is I have an offcanvas, there is a button to open a modal in the offcanvas. When the modal open, the offcanvas is closed. I want to keep the offcanvas open.

**Comment by jahaganiev** [comment]
Hey @hoangnghiem, Stacked Overlays feature has been added with v2.0.3 release - https://preline.co/docs/modal.html#stacked-overlays
