### ISSUE TITLE
Docs sidebar back to top on every route change

### ISSUE THREAD

**Issue by AissaSemaoui** [htmlstreamofficial/preline#135]
Hi Preline Team, 
Thanks for this amazing library, A small issue leads to a bad user experience in the Docs, which is the sidebar goes back to the top on every route change, and then we've to search about the component I was in every time, I hope you can take this in consideration, Thanks!

Best, 
Aissa

**Comment by jahaganiev** [comment]
Hey @AissaSemaoui, 

Thanks for your feedback. We've improved the docs sidebar behaviour. 

Cheers!
