### ISSUE TITLE
Dropdown plugin documentation: hs-dropdown-open and hs-dropdown-active

### ISSUE THREAD

**Issue by MangoMarcus** [htmlstreamofficial/preline#138]
The documentation for the dropdown plugin classes isn't very clear and mentions `hs-dropdown-active` which doesn't seem to exist anywhere else in the documentation or in the source code.

 It sounds like the description of `hs-dropdown-active` should actually be for `hs-dropdown-open` - which is a Tailwind modifier used for state - unlike `hs-dropdown` and `hs-dropdown-toggle` which are both just used to reference elements. 

<img width="809" alt="Screenshot 2023-10-05 at 20 16 57" src="https://github.com/htmlstreamofficial/preline/assets/72021142/04a4b974-5955-49db-b177-5ca6103ec275">

Tangentially related to #82 and #137

**Comment by jahaganiev** [comment]
Hey @MangoMarcus - thanks for catching and letting us know!
