### ISSUE TITLE
Tabs select on mobile

### ISSUE THREAD

**Issue by Dezmonter** [htmlstreamofficial/preline#14]
Where long content doesn't fit on the screen, change the tab bar to <select> on mobile.
Bad idea, it seems more convenient to add a kingpin from right to left for tabs...

**Comment by jahaganiev** [comment]
Hey @Dezmonter, thanks for the feedback. We will consider adding more options in future updates. Meanwhile, please feel free to let us know if you have more suggestions. Thanks!

**Comment by jahaganiev** [comment]
Hey @Dezmonter - you may check out this feature here https://preline.co/docs/tabs.html#select-on-mobile
