### ISSUE TITLE
Feature request: autocomplete

### ISSUE THREAD

**Issue by astuanax** [htmlstreamofficial/preline#140]
Not sure if this is the right place, 
but are there any plans for an autocomplete component?

**Comment by lenart** [comment]
I think you could re-use https://preline.co/docs/advanced-select.html#search-inside-dropdown It has all the styling - just feed it some data.

**Comment by jahaganiev** [comment]
Hey @astuanax - it's live now!

https://preline.co/docs/combobox.html
