### ISSUE TITLE
Components for Advanced Forms?

### ISSUE THREAD

**Issue by PaulMest** [htmlstreamofficial/preline#141]
Our design team loves Preline's Figma. However, our engineering team can't seem to find any reference components for "Advanced Forms". Do these exist somewhere? Or would we need to build these components ourselves from scratch? 🤔 

<img width="234" alt="image" src="https://github.com/htmlstreamofficial/preline/assets/1721104/fa8f4d19-c386-4be4-a7fd-24ce9f160322">

<img width="810" alt="image" src="https://github.com/htmlstreamofficial/preline/assets/1721104/12b98dec-1d11-406e-8994-4fe27cd06b33">

<img width="386" alt="image" src="https://github.com/htmlstreamofficial/preline/assets/1721104/51aeee60-0e50-44dd-a793-6cca687fa258">

**Comment by jahaganiev** [comment]
Hey @PaulMest - super happy to hear that your team is loving Preline! Figma comes with additional component options. However, we've just released v2.0 Preline which closes the gap between Figma and coded components. Hope that helps!

cc duplicated topic #60 

Cheers!
