### ISSUE TITLE
modal can be bypassed by using the tab key

### ISSUE THREAD

**Issue by ItsTarikBTW** [htmlstreamofficial/preline#142]
When I use a [model,](https://preline.co/docs/modal.html) I expect the user to have limited access to the page. but when using **the tab key** he can bypass it which can lead to some error cases the developer didn't think of. 

If I'm missing something please let me know and thank you in advance :)

**Comment by jahaganiev** [comment]
Hey @ItsTarikBTW - thanks for the feedback! It seems it's duplicated with the issue #128 which we've addressed in our latest update. Cheers!
