### ISSUE TITLE
Bug in application-layout-dark-header.html - dropdowns stay invisible

### ISSUE THREAD

**Issue by iamdadmin** [htmlstreamofficial/preline#143]
Steps to reproduce

1. Download examples/html/application-layout-dark-header.html
2. Script tags include preline and dropdown plugin
3. Include tailwindcss v3.3.3 from CDN
4. Open the webpage
5. Click any of the nav items in the top right and they don't actually change the opacity from 0

Environment

Firefox 118.0.2 64-bit on Ubuntu 22.04.03 LTS via Snap
Firefox 118.0.2 64-bit on Windows 10 Pro 22H2
Chromium (ungoogled-chromium) 108.0.5359.125

When using F12 dev tools on Firefox, and viewing the 'calculated' CSS, opacity of the item remains 0 with the `hs-dropdown-open:opacity-100` modifier never being actually triggered, although the "hidden" class does get removed.

`<div class="hs-dropdown-menu transition-[opacity,margin] duration hs-dropdown-open:opacity-100 opacity-0 hidden`

**Comment by iamdadmin** [comment]
Update 1.

Removed this from the classes
`hs-dropdown-open:opacity-100 opacity-0 `

When you activate the menu, based on the settings, the the `block` class is added and the `hidden` class is removed, and the follow style tag is added to the html element
`style="position: fixed; inset: 0px auto auto 0px; margin: 0px; transform: translate(1481px, 64px);"`

At this point the menu is visible and active, the links could be clicked etc.

When you click off the menu i.e. to close it, the javascript does NOT remove `block` and return `hidden`, and the style tag which was added remains, however is changed to this
`style="position: fixed; inset: 0px auto auto 0px; transform: translate(1481px, 64px);"`

i.e. `margin: 0px;` is removed not the full style tag, which seems weird.

**Comment by iamdadmin** [comment]
No matter what I copy from the example applications, or whether I manually wget the preline.js and modules you've got on the preline.co website it just fails to remove "block" and replace "hidden" in the code of the dropdown-menu div.

**Comment by jahaganiev** [comment]
Hey @iamdadmin, we suggest to try out with the latest version of the Preline UI. Hope the issue will be resolved, if not please feel free to let us know.
