### ISSUE TITLE
Uncaught TypeError: t4.target.closest is not a function

### ISSUE THREAD

**Issue by alvin** [htmlstreamofficial/preline#144]
Uncaught TypeError: t4.target.closest is not a function

I am not using preline tooltips (simple css only ones) but when i mouse over a tooltip element I get this error from preline in the console (firefox)

`Uncaught TypeError: t4.target.closest is not a function`

Here is my markup:

`<span data-over-tt="tooltip text" data-tt-placement="bottom">Some text</span>`

And here is the css for the external tooltips (preline tips were buggy, did not go away when mousing over)

```

[data-over-tt] {
  position: relative;
  cursor: default;
}
[data-over-tt]:hover::before {
  content: attr(data-over-tt);
  font-size: 14px;
  text-align: center;
  position: absolute;
  display: block;
  left: 50%;
  min-width: 150px;
  max-width: 200px;
  bottom: calc(100% + 10px);
  transform: translate(-50%);
  animation: fade-in 300ms ease;
  background: rgba(39, 39, 39, 1);
  border-radius: 4px;
  padding: 10px;
  color: #fff;
  z-index: 1;
}
[data-over-tt]:hover::after {
  content: '';
  position: absolute;
  display: block;
  left: 50%;
  width: 0;
  height: 0;
  bottom: calc(100% + 6px);
  margin-left: - 3px;
  border: 1px solid black;
  border-color: rgba(39, 39, 39, 1) transparent transparent transparent;
  border-width: 4px 6px 0;
  animation: fade-in 300ms ease;
  z-index: 1;
}
[data-over-tt][data-tt-placement="bottom"]:hover::before {
  bottom: auto;
  top: calc(100% + 10px);
}
[data-over-tt][data-tt-placement="bottom"]:hover::after {
  bottom: auto;
  top: calc(100% + 6px);
  border-color: transparent transparent rgba(39, 39, 39, 1);
  border-width: 0 6px 4px;
}
@keyframes fade-in {
  from {
    opacity: 0;
 }
  to {
    opacity: 1;
 }
}
```

Any help you can offer?  I'm using SvelteKit but that part works okay using onMount import();

**Comment by olegpix** [comment]
> Uncaught TypeError: t4.target.closest is not a function
> 
> I am not using preline tooltips (simple css only ones) but when i mouse over a tooltip element I get this error from preline in the console (firefox)
> 
> `Uncaught TypeError: t4.target.closest is not a function`
> 
> Here is my markup:
> 
> `<span data-over-tt="tooltip text" data-tt-placement="bottom">Some text</span>`
> 
> And here is the css for the external tooltips (preline tips were buggy, did not go away when mousing over)
> 
> ```
> 
> [data-over-tt] {
>   position: relative;
>   cursor: default;
> }
> [data-over-tt]:hover::before {
>   content: attr(data-over-tt);
>   font-size: 14px;
>   text-align: center;
>   position: absolute;
>   display: block;
>   left: 50%;
>   min-width: 150px;
>   max-width: 200px;
>   bottom: calc(100% + 10px);
>   transform: translate(-50%);
>   animation: fade-in 300ms ease;
>   background: rgba(39, 39, 39, 1);
>   border-radius: 4px;
>   padding: 10px;
>   color: #fff;
>   z-index: 1;
> }
> [data-over-tt]:hover::after {
>   content: '';
>   position: absolute;
>   display: block;
>   left: 50%;
>   width: 0;
>   height: 0;
>   bottom: calc(100% + 6px);
>   margin-left: - 3px;
>   border: 1px solid black;
>   border-color: rgba(39, 39, 39, 1) transparent transparent transparent;
>   border-width: 4px 6px 0;
>   animation: fade-in 300ms ease;
>   z-index: 1;
> }
> [data-over-tt][data-tt-placement="bottom"]:hover::before {
>   bottom: auto;
>   top: calc(100% + 10px);
> }
> [data-over-tt][data-tt-placement="bottom"]:hover::after {
>   bottom: auto;
>   top: calc(100% + 6px);
>   border-color: transparent transparent rgba(39, 39, 39, 1);
>   border-width: 0 6px 4px;
> }
> @keyframes fade-in {
>   from {
>     opacity: 0;
>  }
>   to {
>     opacity: 1;
>  }
> }
> ```
> 
> Any help you can offer? I'm using SvelteKit but that part works okay using onMount import();

Hi,
We will fix this in the next update.

**Comment by jahaganiev** [comment]
Hey @alvin - we've just released a new version which includes a fix for this issue, please give a try and let us know if you have any issues. Thanks!
