### ISSUE TITLE
Preline v2 overlays behavior compared to v1.9

### ISSUE THREAD

**Issue by roiLeo** [htmlstreamofficial/preline#149]
Tested with Nuxt:
- v1.9: https://stackblitz.com/edit/nuxt-starter-ydge8e?file=plugins%2Fpreline.client.ts,tailwind.config.ts
- v2.0: https://stackblitz.com/edit/nuxt-starter-aetnvo?file=plugins%2Fpreline.client.ts,tailwind.config.ts

Modal don't open on v2, same goes for sidebar.

edit: related with #146

**Comment by olegpix** [comment]
> Tested with Nuxt:
> 
> * v1.9: https://stackblitz.com/edit/nuxt-starter-ydge8e?file=plugins%2Fpreline.client.ts,tailwind.config.ts
> * v2.0: https://stackblitz.com/edit/nuxt-starter-aetnvo?file=plugins%2Fpreline.client.ts,tailwind.config.ts
> 
> Modal don't open on v2, same goes for sidebar.
> 
> edit: related with #146

You need to set defineNuxtConfig({ ssr: true, ... }), our plugins now work with instances instead of document.on([event]) event.target, and now you need a collection of initialized elements.
Nuxt erases the collection of initialized elements every time the page is reloaded in the mode when sir is disabled

**Comment by roiLeo** [comment]
> You need to set defineNuxtConfig({ ssr: true, ... }), our plugins now work with instances instead of document.on([event]) event.target, and now you need a collection of initialized elements. Nuxt erases the collection of initialized elements every time the page is reloaded in the mode when ssr is disabled

Yep, does work with `ssr: true`.
Thank for the clarification but my current stack doesn't support ssr (might need to update doc example).
Keep up the good work! 🚀

**Comment by olegpix** [comment]
> > You need to set defineNuxtConfig({ ssr: true, ... }), our plugins now work with instances instead of document.on([event]) event.target, and now you need a collection of initialized elements. Nuxt erases the collection of initialized elements every time the page is reloaded in the mode when ssr is disabled
> 
> Yep, does work with `ssr: true`. Thank for the clarification but my current stack doesn't support ssr (might need to update doc example). Keep up the good work! 🚀

I found a solution for your case. In cases where you have a collection, adding new elements will be ignored, but if you don't have a collection, the elements will be initialized every time the page is refreshed.
But remember that in this case you should use .ts files and work with classes. In your case, I think this will work.
For example, if you need to add some kind of overlay (like in your example) you need to use the HSOverlay constructor. If you need to create a dropdown, you need to import the HSDropdown constructor and work with it and so on. I think it's clear.

```
import { HSOverlay } from "preline";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook("page:finish", () => {
    document.querySelectorAll("[data-hs-overlay]").forEach((el: any) => {
      if (!!window.$hsOverlayCollection) new HSOverlay(el);
    });
  });
});
```

**Comment by shanke-pvex** [comment]
> > > You need to set defineNuxtConfig({ ssr: true, ... }), our plugins now work with instances instead of document.on([event]) event.target, and now you need a collection of initialized elements. Nuxt erases the collection of initialized elements every time the page is reloaded in the mode when ssr is disabled
> > 
> > 
> > Yep, does work with `ssr: true`. Thank for the clarification but my current stack doesn't support ssr (might need to update doc example). Keep up the good work! 🚀
> 
> I found a solution for your case. In cases where you have a collection, adding new elements will be ignored, but if you don't have a collection, the elements will be initialized every time the page is refreshed. But remember that in this case you should use .ts files and work with classes. In your case, I think this will work. For example, if you need to add some kind of overlay (like in your example) you need to use the HSOverlay constructor. If you need to create a dropdown, you need to import the HSDropdown constructor and work with it and so on. I think it's clear.
> 
> ```
> import { HSOverlay } from "preline";
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   nuxtApp.hook("page:finish", () => {
>     const overlays: HTMLElement[] = Array.from(
>       document.querySelectorAll("[data-hs-overlay]")
>     );
> 
>     overlays.forEach((el: HTMLElement) => {
>       if (!!window.$hsOverlayCollection) new HSOverlay(el);
>     });
>   });
> });
> ```

Can you give an example on how to do this initialisation in Laravel 10 with inertia and vue3?
