### ISSUE TITLE
V2 not working on Laravel Inertia

### ISSUE THREAD

**Issue by MelvishNiz** [htmlstreamofficial/preline#150]
i've upgrade from v1.9.0 all fine but when i upgrade to v2.0.0 the JS is broken, all component requred JS not working.
sorry i can't give the example code but, it's same like your guide on documentation

**Comment by trumpetstech** [comment]
Not working with Laravel Livewire too.

**Comment by trumpetstech** [comment]
I guess its related to typescript. As the main index file is index.d.ts which is a dynamic import and vite is having some issue including it.

**Comment by jahaganiev** [comment]
duplicated issue #146 - let's keep one the same page for now.

**Comment by shanke-pvex** [comment]
I use Laravel 10 Inertia Vue 3 Tailwind an Preline UI. I have the same problem - none of the javascript works with preline v2.0
