### ISSUE TITLE
Preline plugins don't work

### ISSUE THREAD

**Issue by blackslayR** [htmlstreamofficial/preline#151]
Still new to Preline, my bad if it's a newbie question.
Everytime I try to implement any plugin, it doesn't work, I'll give  an example, which includes the mega dropdown.

It gives me an error of undefined  HSDropdown, though I have downloaded the plugin through npm.
By the way, when I use CDN everything works fine.

The code I have used is the same as of the example on the website.

**Comment by jahaganiev** [comment]
Hey @blackslayR - could you please share the source code of the tailwind.config.js file?

**Comment by blackslayR** [comment]
hey @jahaganiev, yeah of course, here you go

```js 
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    'node_modules/preline/dist/*.js',
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('preline/plugin'),
  ],
}

```
