### ISSUE TITLE
data-hs not working with Svelte

### ISSUE THREAD

**Issue by Eric-Arz** [htmlstreamofficial/preline#153]
How are you supposed to use components that make use of the data-hs tags like this when using a Framework like Svelte or React?

```
        <p data-hs-toggle-count='{
            "target": "#toggle-count",
            "min": 19,
            "max": 29
          }' class="text-gray-800 font-semibold text-3xl dark:text-gray-200">
          19
        </p>
```

This doesn't seem to be valid Syntax in JSX, etc. I am just getting a parse error. I tried wrapping the data-hs object like this:

```
        <p data-hs-toggle-count={{
            "target": "#toggle-count",
            "min": 19,
            "max": 29
          }} class="text-gray-800 font-semibold text-3xl dark:text-gray-200">
          19
        </p>
```

The component then renders but nothing works.

**Comment by olegpix** [comment]
> <p data-hs-toggle-count={{
>             "target": "#toggle-count",
>             "min": 19,
>             "max": 29
>           }} class="text-gray-800 font-semibold text-3xl dark:text-gray-200">
>           19
>         </p>

it must be a string. Our plugins are primarily designed for HTML.
Try enclosing the parameter in single quotes.
```
<p data-hs-toggle-count={'{
    "target": "#toggle-count",
    "min": 19,
    "max": 29
}'} class="text-gray-800 font-semibold text-3xl dark:text-gray-200">
    19
</p>
```

**Comment by Eric-Arz** [comment]
That doesn't work either. This results in an unterminated string literal error. I tried using template strings:

```
<!-- Select -->
<div class="relative">
    <select data-hs-select={`{
        "placeholder": "Select option...",
        "toggleTag": "<button type=\"button\"></button>",
        "toggleClasses": "hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 relative py-3 px-4 pe-9 flex text-nowrap w-full cursor-pointer bg-white border border-gray-200 rounded-lg text-start text-sm focus:border-blue-500 focus:ring-blue-500 before:absolute before:inset-0 before:z-[1] dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600",
        "dropdownClasses": "mt-2 z-50 w-full max-h-[300px] p-1 space-y-0.5 bg-white border border-gray-200 rounded-lg overflow-hidden overflow-y-auto dark:bg-slate-900 dark:border-gray-700",
        "optionClasses": "py-2 px-4 w-full text-sm text-gray-800 cursor-pointer hover:bg-gray-100 rounded-lg focus:outline-none focus:bg-gray-100 dark:bg-slate-900 dark:hover:bg-slate-800 dark:text-gray-200 dark:focus:bg-slate-800",
        "optionTemplate": "<div class=\"flex justify-between items-center w-full\"><span data-title></span><span class=\"hidden hs-selected:block\"><svg class=\"flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500\" xmlns=\"http:.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"20 6 9 17 4 12\"/></svg></span></div>"
      }`} class="hidden">
      <option value="">Choose</option>
      <option>Name</option>
      <option>Email address</option>
      <option>Description</option>
      <option>User ID</option>
    </select>
  
    <div class="absolute top-1/2 end-3 -translate-y-1/2">
      <svg class="flex-shrink-0 w-3.5 h-3.5 text-gray-500 dark:text-gray-500" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m7 15 5 5 5-5"/><path d="m7 9 5-5 5 5"/></svg>
    </div>
</div>
<!-- End Select --> 
```

This is 1:1 the code from https://preline.co/docs/advanced-select.html Basic Usage example just with the extra {}. Throws:

Uncaught SyntaxError: Expected ',' or '}' after property value in JSON at position 81 (line 3 column 37)
    at JSON.parse (<anonymous>)
    at preline.js:2:98616
    at NodeList.forEach (<anonymous>)
    at preline.js:2:98547

**Comment by olegpix** [comment]
> That doesn't work either. This results in an unterminated string literal error. I tried using template strings:
> 
> ```
> 
> <div class="relative">
>     <select data-hs-select={`{
>         "placeholder": "Select option...",
>         "toggleTag": "<button type=\"button\"></button>",
>         "toggleClasses": "hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 relative py-3 px-4 pe-9 flex text-nowrap w-full cursor-pointer bg-white border border-gray-200 rounded-lg text-start text-sm focus:border-blue-500 focus:ring-blue-500 before:absolute before:inset-0 before:z-[1] dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600",
>         "dropdownClasses": "mt-2 z-50 w-full max-h-[300px] p-1 space-y-0.5 bg-white border border-gray-200 rounded-lg overflow-hidden overflow-y-auto dark:bg-slate-900 dark:border-gray-700",
>         "optionClasses": "py-2 px-4 w-full text-sm text-gray-800 cursor-pointer hover:bg-gray-100 rounded-lg focus:outline-none focus:bg-gray-100 dark:bg-slate-900 dark:hover:bg-slate-800 dark:text-gray-200 dark:focus:bg-slate-800",
>         "optionTemplate": "<div class=\"flex justify-between items-center w-full\"><span data-title></span><span class=\"hidden hs-selected:block\"><svg class=\"flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500\" xmlns=\"http:.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"20 6 9 17 4 12\"/></svg></span></div>"
>       }`} class="hidden">
>       <option value="">Choose</option>
>       <option>Name</option>
>       <option>Email address</option>
>       <option>Description</option>
>       <option>User ID</option>
>     </select>
>   
>     <div class="absolute top-1/2 end-3 -translate-y-1/2">
>       <svg class="flex-shrink-0 w-3.5 h-3.5 text-gray-500 dark:text-gray-500" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m7 15 5 5 5-5"/><path d="m7 9 5-5 5 5"/></svg>
>     </div>
> </div>
>  
> ```
> 
> This is 1:1 the code from https://preline.co/docs/advanced-select.html Basic Usage example just with the extra {}. Throws:
> 
> Uncaught SyntaxError: Expected ',' or '}' after property value in JSON at position 81 (line 3 column 37) at JSON.parse () at preline.js:2:98616 at NodeList.forEach () at preline.js:2:98547

Try just a line without {}. If that doesn't help, upload your code to codeandbox and give us the link.

```
<select data-hs-select='{
        "placeholder": "Select option...",
        "toggleTag": "<button type=\"button\"></button>",
        "toggleClasses": "hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 relative py-3 px-4 pe-9 flex text-nowrap w-full cursor-pointer bg-white border border-gray-200 rounded-lg text-start text-sm focus:border-blue-500 focus:ring-blue-500 before:absolute before:inset-0 before:z-[1] dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600",
        "dropdownClasses": "mt-2 z-50 w-full max-h-[300px] p-1 space-y-0.5 bg-white border border-gray-200 rounded-lg overflow-hidden overflow-y-auto dark:bg-slate-900 dark:border-gray-700",
        "optionClasses": "py-2 px-4 w-full text-sm text-gray-800 cursor-pointer hover:bg-gray-100 rounded-lg focus:outline-none focus:bg-gray-100 dark:bg-slate-900 dark:hover:bg-slate-800 dark:text-gray-200 dark:focus:bg-slate-800",
        "optionTemplate": "<div class=\"flex justify-between items-center w-full\"><span data-title></span><span class=\"hidden hs-selected:block\"><svg class=\"flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500\" xmlns=\"http:.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"20 6 9 17 4 12\"/></svg></span></div>"
      }' class="hidden">
      <option value="">Choose</option>
      <option>Name</option>
      <option>Email address</option>
      <option>Description</option>
      <option>User ID</option>
    </select>
```

**Comment by Eric-Arz** [comment]
This works in React, but as i said you **can't** do that in Svelte: https://codesandbox.io/s/preline-svelte-error-wl357w?file=/App.svelte

**Comment by olegpix** [comment]
> That doesn't work either. This results in an unterminated string literal error. I tried using template strings:
> 
> ```
> 
> <div class="relative">
>     <select data-hs-select={`{
>         "placeholder": "Select option...",
>         "toggleTag": "<button type=\"button\"></button>",
>         "toggleClasses": "hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 relative py-3 px-4 pe-9 flex text-nowrap w-full cursor-pointer bg-white border border-gray-200 rounded-lg text-start text-sm focus:border-blue-500 focus:ring-blue-500 before:absolute before:inset-0 before:z-[1] dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600",
>         "dropdownClasses": "mt-2 z-50 w-full max-h-[300px] p-1 space-y-0.5 bg-white border border-gray-200 rounded-lg overflow-hidden overflow-y-auto dark:bg-slate-900 dark:border-gray-700",
>         "optionClasses": "py-2 px-4 w-full text-sm text-gray-800 cursor-pointer hover:bg-gray-100 rounded-lg focus:outline-none focus:bg-gray-100 dark:bg-slate-900 dark:hover:bg-slate-800 dark:text-gray-200 dark:focus:bg-slate-800",
>         "optionTemplate": "<div class=\"flex justify-between items-center w-full\"><span data-title></span><span class=\"hidden hs-selected:block\"><svg class=\"flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500\" xmlns=\"http:.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"20 6 9 17 4 12\"/></svg></span></div>"
>       }`} class="hidden">
>       <option value="">Choose</option>
>       <option>Name</option>
>       <option>Email address</option>
>       <option>Description</option>
>       <option>User ID</option>
>     </select>
>   
>     <div class="absolute top-1/2 end-3 -translate-y-1/2">
>       <svg class="flex-shrink-0 w-3.5 h-3.5 text-gray-500 dark:text-gray-500" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m7 15 5 5 5-5"/><path d="m7 9 5-5 5 5"/></svg>
>     </div>
> </div>
>  
> ```
> 
> This is 1:1 the code from https://preline.co/docs/advanced-select.html Basic Usage example just with the extra {}. Throws:
> 
> Uncaught SyntaxError: Expected ',' or '}' after property value in JSON at position 81 (line 3 column 37) at JSON.parse () at preline.js:2:98616 at NodeList.forEach () at preline.js:2:98547

this code works for me
https://codesandbox.io/s/preline-svelte-error-forked-mvrsk5?file=/App.svelte

**Comment by Eric-Arz** [comment]
This gets parsed but the component does not work. Other components that require js but dont use data-hs work fine.

**Comment by olegpix** [comment]
> This gets parsed but the component does not work. Other components that require js but dont use data-hs work fine.

Try this way

```
 <select data-hs-select={`{
		"placeholder": "Select option...",
		"toggleTag": "<button type='button'></button>",
		"toggleClasses": "hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 relative py-3 px-4 pe-9 flex text-nowrap w-full cursor-pointer bg-white border border-gray-200 rounded-lg text-start text-sm focus:border-blue-500 focus:ring-blue-500 before:absolute before:inset-0 before:z-[1] dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600",
		"dropdownClasses": "mt-2 z-50 w-full max-h-[300px] p-1 space-y-0.5 bg-white border border-gray-200 rounded-lg overflow-hidden overflow-y-auto dark:bg-slate-900 dark:border-gray-700",
		"optionClasses": "py-2 px-4 w-full text-sm text-gray-800 cursor-pointer hover:bg-gray-100 rounded-lg focus:outline-none focus:bg-gray-100 dark:bg-slate-900 dark:hover:bg-slate-800 dark:text-gray-200 dark:focus:bg-slate-800",
		"optionTemplate": "<div class='flex justify-between items-center w-full'><span data-title></span><span class='hidden hs-selected:block'><svg class='flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500' xmlns='http:.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polyline points='20 6 9 17 4 12'/></svg></span></div>"
	}`} class="hidden">
    <option value="">Choose</option>
    <option>Name</option>
    <option>Email address</option>
    <option>Description</option>
    <option>User ID</option>
  </select>
```

The problem was with \"

**Comment by Eric-Arz** [comment]
Nope doesn't work. Nothing is visible, the stuff from the data-hs-select is not rendered.

**Comment by olegpix** [comment]
> Nope doesn't work. Nothing is visible, the stuff from the data-hs-select is not rendered.

please, check it one more time.
https://codesandbox.io/p/sandbox/preline-svelte-error-forked-mvrsk5?file=%2Fpublic%2Findex.html%3A1%2C1

It works here. But I moved Preline to the "public" folder. It's not styled right now because Tailwind isn't configured, but you can see the functionality.

**Comment by Eric-Arz** [comment]
i think this might be related to SvelteKIT. When i refresh the page i see it for a fraction of a second (styled aswell) and it then just disappears. Almost seems like SvelteKIT rerenders the component without the preline script running again.

**Comment by olegpix** [comment]
please check this ticket https://github.com/htmlstreamofficial/preline/issues/149#issuecomment-1805728611
It could be the same situation.
If yes, then you also need to initialize your components on the "mounted" event.

> i think this might be related to SvelteKIT. When i refresh the page i see it for a fraction of a second (styled aswell) and it then just disappears. Almost seems like SvelteKIT rerenders the component without the preline script running again.

**Comment by MarkoGjorgjievski** [comment]
Same issue here, and still doesn't work after initializing the component after `onMount`

**Comment by Eric-Arz** [comment]
@olegpix got it to work using something similar:

```
<script lang="ts">
    import { onMount } from 'svelte';

    onMount(async () => {
        const HSSelect = (await import('preline')).HSSelect;

        const selects: HTMLElement[] = Array.from(document.querySelectorAll('[data-hs-select]'));

        selects.forEach((element: HTMLElement) => {
            new HSSelect(element);
        });
    });
</script>
```

Sadly, it seems like you have to do this for everything that uses data-hs.

**Comment by Eric-Arz** [comment]
I think this needs to be in the docs. If you just follow the steps in https://preline.co/docs/frameworks-svelte.html most if not all of the JS stuff doesn't work properly.

**Comment by olegpix** [comment]
> I think this needs to be in the docs. If you just follow the steps in https://preline.co/docs/frameworks-svelte.html most if not all of the JS stuff doesn't work properly.
> 
> Also i am till trying to figure something out. Writing an onMount for **every** preline selector basicaly means rewriting most of the stuff the preline.js script that you ref in your html is supposed to do. That can't be the right solution.

Thank you,

We are currently improving our plugins and will update the documentation soon.

We appreciate your comments.

**Comment by Eric-Arz** [comment]
by the way, this: 

```
// app.html
<script src="/node_modules/preline/dist/preline.js"></script>
```

is also something that doesn't work with SvelteKit. That only works during development.

**Comment by jahaganiev** [comment]
Hey everyone,

Our team just recently updated [Framework Guides](https://preline.co/docs/frameworks.html) pages including Svelte docs page with live playground demos for all v2 JS components. Please try out with the latest version and let us know if you still have any issues.

Cheers!

**Comment by Eric-Arz** [comment]
As i said in my **last** comment you can't

<script src="node_modules/preline/preline.js"></script>

when using Svelte**Kit**. This only works with plain Svelte + Vite.

**Comment by jahaganiev** [comment]
Hey @Eric-Arz, you may try out [this](https://github.com/htmlstreamofficial/preline/issues/110) approach - seems it worked for other devs.

**Comment by jahaganiev** [comment]
Hey @Eric-Arz, please check out the latest version of Framework Guides - we've added some additional information to handle the build production process based on the earlier mentioned [post](https://github.com/htmlstreamofficial/preline/issues/110).

**Comment by PriyanshIotWiz** [comment]
<div class="relative">
    <select data-hs-select='&#123;
        "placeholder": "Select option...",
        "toggleTag": "<button type=\"button\"></button>",
        "toggleClasses": "hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 relative py-3 px-4 pe-9 flex text-nowrap w-full cursor-pointer bg-white border border-gray-200 rounded-lg text-start text-sm focus:border-blue-500 focus:ring-blue-500 before:absolute before:inset-0 before:z-[1] dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600",
        "dropdownClasses": "mt-2 z-50 w-full max-h-[300px] p-1 space-y-0.5 bg-white border border-gray-200 rounded-lg overflow-hidden overflow-y-auto dark:bg-slate-900 dark:border-gray-700",
        "optionClasses": "py-2 px-4 w-full text-sm text-gray-800 cursor-pointer hover:bg-gray-100 rounded-lg focus:outline-none focus:bg-gray-100 dark:bg-slate-900 dark:hover:bg-slate-800 dark:text-gray-200 dark:focus:bg-slate-800",
        "optionTemplate": "<div class=\"flex justify-between items-center w-full\"><span data-title></span><span class=\"hidden hs-selected:block\"><svg class=\"flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500\" xmlns=\"http:.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"20 6 9 17 4 12\"/></svg></span></div>"
        &#125;' class="hidden">
      <option value="">Choose</option>
      <option>Name</option>
      <option>Email address</option>
      <option>Description</option>
      <option>User ID</option>
    </select>
  
    <div class="absolute top-1/2 end-3 -translate-y-1/2">
      <svg class="flex-shrink-0 w-3.5 h-3.5 text-gray-500 dark:text-gray-500" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m7 15 5 5 5-5"/><path d="m7 9 5-5 5 5"/></svg>
    </div>
</div>
 
Repalce this
&#123; = {
&#125; = }

**Comment by PriyanshIotWiz** [comment]
> > This gets parsed but the component does not work. Other components that require js but dont use data-hs work fine.
> 
> Try this way
> 
> ```
>  <select data-hs-select={`{
> 		"placeholder": "Select option...",
> 		"toggleTag": "<button type='button'></button>",
> 		"toggleClasses": "hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 relative py-3 px-4 pe-9 flex text-nowrap w-full cursor-pointer bg-white border border-gray-200 rounded-lg text-start text-sm focus:border-blue-500 focus:ring-blue-500 before:absolute before:inset-0 before:z-[1] dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600",
> 		"dropdownClasses": "mt-2 z-50 w-full max-h-[300px] p-1 space-y-0.5 bg-white border border-gray-200 rounded-lg overflow-hidden overflow-y-auto dark:bg-slate-900 dark:border-gray-700",
> 		"optionClasses": "py-2 px-4 w-full text-sm text-gray-800 cursor-pointer hover:bg-gray-100 rounded-lg focus:outline-none focus:bg-gray-100 dark:bg-slate-900 dark:hover:bg-slate-800 dark:text-gray-200 dark:focus:bg-slate-800",
> 		"optionTemplate": "<div class='flex justify-between items-center w-full'><span data-title></span><span class='hidden hs-selected:block'><svg class='flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500' xmlns='http:.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polyline points='20 6 9 17 4 12'/></svg></span></div>"
> 	}`} class="hidden">
>     <option value="">Choose</option>
>     <option>Name</option>
>     <option>Email address</option>
>     <option>Description</option>
>     <option>User ID</option>
>   </select>
> ```
> 
> The problem was with
> 
> ```
> \"
> ```
{`{ replace this with '&#123; and  
}`} replace this with &#125;'

**Comment by ttytm** [comment]
What to look for when working with SvelteKit and using the `data-hs-<plugin>` html attribute.
No need for additional dynamic onMount imports.

Diffs are comparing with the vanilla version.

- The main thing is to pass plugin properties as string. 
  For SvelteKit, do it by using backticks:
  ```diff
  - data-hs-select='{
  + data-hs-select={`{
  ```
  
- The main caveat is that plugin properties must be valid JSON

  - E.g. string keys and values of the plugin properties must be quoted
    (At time of testing with SvelteKit double-quotes were required).
  ```diff
  data-hs-select={`{
  -	placeholder: 'Select option...',
  +	"placeholder": "Select option...",
  	...
  ```

  - E.g. a trailing comma is a mistake:
  ```svelte
  <select data-hs-select={`{
  	"placeholder": "Select option...",
  	"toggleTag": "<button type='button'></button>", <-- Mistake 
  }`}
  ```

**Comment by LukasMueller187** [comment]
I had to escape the \ characters as well, resulting in e.g. as I would otherwise get `[Error] Unhandled Promise Rejection: SyntaxError: JSON Parse error: Expected '}'`

```
data-hs-select={`{
...
- "toggleTag": "<button type=\"button\"></button>",
+ "toggleTag": "<button type=\\"button\\"></button>",
...`
```

**Comment by ttytm** [comment]
> I had to escape the \ characters as well, resulting in e.g. as I would otherwise get `[Error] Unhandled Promise Rejection: SyntaxError: JSON Parse error: Expected '}'`
> 
> ```
> data-hs-select={`{
> ...
> - "toggleTag": "<button type=\"button\"></button>",
> + "toggleTag": "<button type=\\"button\\"></button>",
> ...`
> ```

@LukasMueller187 Just remove the escape characters as shown in the post above under the point "Remove backslashes inside the "backticked" string"
