### ISSUE TITLE
Installing Preline UI does not work with Vite + React

### ISSUE THREAD

**Issue by vim-diesel** [htmlstreamofficial/preline#154]
Any attempt to follow Preline UIs documentation fails [when including Preline as a plugin](https://preline.co/docs/index.html#require-via-npm)

![image](https://github.com/htmlstreamofficial/preline/assets/37084860/7e07df48-8cb7-4eb9-97a8-0c379308cb0f)

**Comment by olegpix** [comment]
> Any attempt to follow Preline UIs documentation fails [when including Preline as a plugin](https://preline.co/docs/index.html#require-via-npm)
> 
> ![image](https://user-images.githubusercontent.com/37084860/281800096-7e07df48-8cb7-4eb9-97a8-0c379308cb0f.png)

Your error is not directly related to the plugin. As far as I can see, your environment is not configured to correctly support the "required" system of modules
