### ISSUE TITLE
Install prelineui does not work with SvelteKit / Vite / Bun (/npm)

### ISSUE THREAD

**Issue by T0mThomson** [htmlstreamofficial/preline#155]
I am trying to install prelineui with SvelteKit. I followed the instructions from https://preline.co/docs/frameworks-svelte.html. I am using bun and vite. I also testet it with npm. The effect where the same.

1. When running in development mode `vite dev` the javascript functionality first works as expected. However on page navigation it breaks. It seems like the javascript is not loaded anymore. After reloading the page, it works again.
2. When building using `vite build` the javascript is not found anymore: `Error: Not found: /node_modules/preline/dist/preline.js`.

I think I need to find a way to import the js inside the component, Otherwise vite won't know to bundle the js file with the package.

**Comment by olegpix** [comment]
> I am trying to install prelineui with SvelteKit. I followed the instructions from https://preline.co/docs/frameworks-svelte.html. I am using bun and vite. I also testet it with npm. The effect where the same.
> 
> 1. When running in development mode `vite dev` the javascript functionality first works as expected. However on page navigation it breaks. It seems like the javascript is not loaded anymore. After reloading the page, it works again.
> 2. When building using `vite build` the javascript is not found anymore: `Error: Not found: /node_modules/preline/dist/preline.js`.
> 
> I think I need to find a way to import the js inside the component, Otherwise vite won't know to bundle the js file with the package.

Please, try to change the path from /node_modules/preline/dist/preline.js to /node_modules/preline/dist/index.js or /node_modules/preline/preline.js
I believe it will help.

**Comment by olegpix** [comment]
> > > I am trying to install prelineui with SvelteKit. I followed the instructions from https://preline.co/docs/frameworks-svelte.html. I am using bun and vite. I also testet it with npm. The effect where the same.
> > > 
> > > 1. When running in development mode `vite dev` the javascript functionality first works as expected. However on page navigation it breaks. It seems like the javascript is not loaded anymore. After reloading the page, it works again.
> > > 2. When building using `vite build` the javascript is not found anymore: `Error: Not found: /node_modules/preline/dist/preline.js`.
> > > 
> > > I think I need to find a way to import the js inside the component, Otherwise vite won't know to bundle the js file with the package.
> > 
> > 
> > Please, try to change the path from /node_modules/preline/dist/preline.js to /node_modules/preline/dist/index.js or /node_modules/preline/preline.js I believe it will help.
> 
> Both don't work. `Error: Not found: /node_modules/preline/preline.js`

try copying Preline from node_modules to any location inside the "public" folder and connecting Preline from there.

**Comment by ricko-v** [comment]
I have same issue with using SvelteKit, but after see example at [https://stackblitz.com/edit/preline-svelte?file=tailwind.config.js](https://stackblitz.com/edit/preline-svelte?file=tailwind.config.js) and i found different version preline.

I think the problem is preline with version 2? Because after i change to preline version 1.7.0, my issue is solved 😃

**Comment by jahaganiev** [comment]
Hey everyone,

Our team just recently updated [Framework Guides](https://preline.co/docs/frameworks.html) page with live playground demos for all v2 JS components. Please try out with the latest version and let us know if you still have any issues.

Cheers!

**Comment by jahaganiev** [comment]
If you are still having an issue, please open a new issue with a stackblitz/codesandbox link to your source code. Thanks!
