### ISSUE TITLE
Re-open plugins don't work

### ISSUE THREAD

**Issue by blackslayR** [htmlstreamofficial/preline#156]
Since my ticket was closed though I have replied to it, here I re-open another one, since I have trying to solve this issue for a while.

The ticket that was closed: https://github.com/htmlstreamofficial/preline/issues/151

Here I link my tailwind config file again,

```js

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    'node_modules/preline/dist/*.js',
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('preline/plugin'),
  ],
}

```

Would really appreciate any help, as am looking forward to use it's components.

**Comment by dminhhoang26** [comment]
Me too, it has not worked since v2.0.0.
I use  HSOverlay static method to open dialog in my angular app, nothing happen. But it worked at the root of the app module

**Comment by GitHubish** [comment]
Exactly, the same goes for me. Dropdown / tooltip rarely work. For your information, I also use Preline (2.0.0) within Angular. I have the impression that the Preline script doesn't initialize at the right time, when I press F5 sometimes it works but when I navigate in the application and go to the page in question, very rarely does it work.

**Comment by hieuhuynh93** [comment]
I also got this issue with HSOverlay
I posted the issue here: #176

**Comment by jahaganiev** [comment]
Hey everyone,

Our team just recently updated [Framework Guides](https://preline.co/docs/frameworks.html) pages with live playground demos for all v2 JS components. Please try out with the latest version and let us know if you still having any issues.

Cheers!

**Comment by sajjadgol** [comment]
this problem same  for me  !!!


@hieuhuynh93 even this line not work !!!

**Comment by sajjadgol** [comment]
> > this problem same  for me  !!!
> > @hieuhuynh93 even below line not work !!!
> > import { HSOverlay } from 'preline'
> > I use laravel and vite and tailwind  and not working for me
> 
> Try use `import { HSOverlay } from 'preline/preline'`

unfortunately not work !!!! 😟

**Comment by sajjadgol** [comment]
hi @blackslayR 
I use Laravel and Vite for managing js package and same problem and find solution

if you look in bootstap.js in laravel has below code 
```
 import axios from 'axios';
 window.axios = axios;`
```
then in app.js adding below code for every plugin in preline

```
import  {HSOverlay} from "preline";
window.HSOverlay = HSOverlay;
```
and use below method for calling HSOverly

`HSOverlay.open('#hs-vertically-centered-modal')
`

**Comment by jahaganiev** [comment]
@blackslayR hope the issue has been resolved, please let us know if you are still having the same issue, and we will re-visit.

Cheers!
