### ISSUE TITLE
Plugins stop working

### ISSUE THREAD

**Issue by warlisson** [htmlstreamofficial/preline#158]
The plugin stops working when browsing using Vue and Inertia js in version ^2.0.0.

**Comment by afcreative** [comment]
same here, even i use nextjs 14

**Comment by warlisson** [comment]
> same here, even i use nextjs 14

I'm using version ^1.9.0. With this version the problem does not occur.

**Comment by lenart** [comment]
Very likely a duplicate of https://github.com/htmlstreamofficial/preline/issues/171

**Comment by jahaganiev** [comment]
Hey everyone, please keep track at #171 issue for the latest conversations and updates. However, if you are having any other issue, please feel free to open a new issue with more details. Thanks!
