### ISSUE TITLE
[Nextjs 14/Preline v2.0] none of JS functionality working

### ISSUE THREAD

**Issue by waynewaynetsai** [htmlstreamofficial/preline#160]
- Versions:

Next.js Version: 14.x
Preline Version: 2.0

- Comparison with preline v1.9.0:

After downgrading preline to v1.9.0, the related functionality is restored.
- Relative Issue: #146 

- tailwind.config.js

```
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "../node_modules/preline/dist/*.js",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
    require("preline/plugin"),
  ],
};
export default config;

```

- layout.tsx

```
"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Ref: https://github.com/htmlstreamofficial/preline/issues/83#issuecomment-1671325442
  useEffect(() => { import("preline") }, []);
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>{children}</body>
    </html>
  );
}

```

**Comment by jeraldlashy** [comment]
> * Versions:
> 
> Next.js Version: 14.x Preline Version: 2.0
> 
> * Comparison with preline v1.9.0:
> 
> After downgrading preline to v1.9.0, the related functionality is restored.
> 
> * Relative Issue: [None of JS Functionality Working #146](https://github.com/htmlstreamofficial/preline/issues/146)
> * tailwind.config.js
> 
> ```
> import type { Config } from "tailwindcss";
> 
> const config: Config = {
>   content: [
>     "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
>     "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
>     "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
>     "../node_modules/preline/dist/*.js",
>   ],
>   theme: {
>     extend: {},
>   },
>   plugins: [
>     require('@tailwindcss/forms'),
>     require("preline/plugin"),
>   ],
> };
> export default config;
> ```
> 
> * layout.tsx
> 
> ```
> "use client";
> 
> import { Inter } from "next/font/google";
> import "./globals.css";
> import { useEffect } from "react";
> 
> const inter = Inter({ subsets: ["latin"] });
> 
> export default function RootLayout({
>   children,
> }: {
>   children: React.ReactNode;
> }) {
>   // Ref: https://github.com/htmlstreamofficial/preline/issues/83#issuecomment-1671325442
>   useEffect(() => { import("preline") }, []);
>   return (
>     <html lang="en" className="h-full">
>       <body className={`${inter.className} h-full`}>{children}</body>
>     </html>
>   );
> }
> ```
Refer to this https://github.com/htmlstreamofficial/preline/issues/159#issue-1989438551

**Comment by jahaganiev** [comment]
Hey @waynewaynetsai, our team just recently updated Framework Guides page for Next.js 14 with live playground demos - https://preline.co/docs/frameworks-nextjs.html

Cheers!
