### ISSUE TITLE
Does preline compatible with turbo(rails)?

### ISSUE THREAD

**Issue by chenjau** [htmlstreamofficial/preline#166]
Hello everyone, I would like to ask whether preline is compatible with Turbo (Rails)?

**Comment by kwhandy** [comment]
> Hello everyone, I would like to ask whether preline is compatible with Turbo (Rails)?

it works incl. it's js, but some js plugins may be buggy like `@preline/remove-element`, it won't close flash msg

**Comment by lenart** [comment]
Latest version is currently not working correctly with Turbo. Until this is fixed you can use 1.9.

**Comment by jahaganiev** [comment]
By right Preline UI works everywhere where TailwindCSS runs. Please have a looks some workarounds at #171 as Lenart mentioned.

@kwhandy Please open a new issue with more details - we will address if there's any bugs. Details like some code samples, screenshots or video example will help to debug the issue.

Thanks!
