### ISSUE TITLE
Preline 2.0.0 broken on Nuxt.js

### ISSUE THREAD

**Issue by Asuniia** [htmlstreamofficial/preline#168]
Preline installs correctly but doesn't work. No element is responsive to actions

**Comment by roiLeo** [comment]
check out #149, it need SSR `true` to work

**Comment by jahaganiev** [comment]
Hey @Asuniia - please have a look into #149 for the suggested solution. Also, our team updated the docs with live playground demo for Next.js here - https://preline.co/docs/frameworks-nuxtjs.html

Cheers!
