### ISSUE TITLE
Where to import the `<script>` tag to my Next.js TypeScript project

### ISSUE THREAD

**Issue by AlphaByte-RedTeam** [htmlstreamofficial/preline#17]
Hello, I am using prelineUI in my side project. Btw I am using the latest version of Next.js and Yarn. I wanted to use the preline navbar that has the dropdown component. But when I click on my web, it doesn't pop up. Yes, I did not add the `<script>` tag into my project, because I am confused where to add it.

```html
<script src="./assets/vendor/preline/dist/hs-ui.bundle.js"></script>
```
How to add this code into my project? Thanks a low

Edited: By the way I use TypeScript for my Next.js project

**Comment by HydraNhani** [comment]
I think you just have to import it in the **_app.tsx**, since Webpack bundles your imported css from there too.


```
import "../index.css";
import "preline";
```

**Comment by AlphaByte-RedTeam** [comment]
> I think you just have to import it in the **_app.tsx**, since Webpack bundles your imported css from there too.
> 
> ```tsx
> import "../index.css";
> import "preline";
> ```

I don't know, I've just tried to import it, but it shows a `ReferenceError: self is not defined`

Here is the full error
```
error - ReferenceError: self is not defined
    at Object.<anonymous> (I:\AndrewData\IT\GitHub\himabios\node_modules\preline\dist\hs-ui.bundle.js:2:224)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.preline (I:\AndrewData\IT\GitHub\himabios\.next\server\pages\_app.js:43:18)
    at __webpack_require__ (I:\AndrewData\IT\GitHub\himabios\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.tsx:9:65) {
  page: '/'
}
```

**Comment by jshnaidman** [comment]
I also encountered this issue when trying to get started and the workaround I found was to copy the hs-ui.bundle.js from node_modules into public/ and then add a Script tag like:

`<Script src="/hs-ui.bundle.js" />`

e.g:

```
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Script from 'next/script'

function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <Script src="/hs-ui.bundle.js" />
    <Component {...pageProps} />
  </>
}

export default MyApp
```

**Comment by AlphaByte-RedTeam** [comment]
Closing: Now I switched from Preline to ChakraUI.

**Comment by green-cats** [comment]
@AlphaByte-RedTeam Hello! 

Sorry for getting back with some delays but hope the below guidelines will be helpful.

You may try to add preline in pages/_app.js file dynamic import like example below:


```
useEffect(() => {
  import('preline')
}, [])
```

You may  also use async/await if necessary:

```
useEffect(() => {
  const initPreline = async () => {
    await import('preline')
  }
  initPreline()
}, [])
```

Please feel free to let us know if it works.

Thanks!

**Comment by bonesoul** [comment]
this should be documented in readme.

**Comment by jahaganiev** [comment]
> this should be documented in readme.

Definitely! Framework Guides is coming soon in v1.2 release.

**Comment by tkennedy13** [comment]
Is it possible to provide a full _app.tsx as an example? I'm totally new to Next.js and and I don't know how to add 

```
useEffect(() => {
  import('preline')
}, [])
```

to my _app.tsx without getting an error.



> @AlphaByte-RedTeam Hello!
> 
> Sorry for getting back with some delays but hope the below guidelines will be helpful.
> 
> You may try to add preline in pages/_app.js file dynamic import like example below:
> 
> ```
> useEffect(() => {
>   import('preline')
> }, [])
> ```
> 
> You may also use async/await if necessary:
> 
> ```
> useEffect(() => {
>   const initPreline = async () => {
>     await import('preline')
>   }
>   initPreline()
> }, [])
> ```
> 
> Please feel free to let us know if it works.
> 
> Thanks!

**Comment by trungpham-syncly** [comment]
Type definition should be implemented along with any export.

**Comment by j0hnm4r5** [comment]
When I `import("preline")`, I get a TypeScript error that it couldn't find the declaration file. I don't see any types in the actual package, so I'm assuming this project just doesn't work with TypeScript?
