### ISSUE TITLE
v2 only works once after page reload

### ISSUE THREAD

**Issue by shanke-pvex** [htmlstreamofficial/preline#171]
I use Laravel 10 with inertia and vue3.
Every javascript trigger only works after a page reload. 
When navigating to another page and go back in my SPA none of the javascript is working.

With version 1.9.0 everything is fine (except the new added plugins :)).

Is version 2.0 compatible with inertia?

**Comment by ashikck** [comment]
Same for me with react and vite.

**Comment by sebastianbilling** [comment]
Same for me with React and NextJS

**Comment by hiteshjoshi** [comment]
Same

**Comment by lenart** [comment]
Seems like it's the same story with Rails and Turbo. It works on initial page load but not after page is navigated.

**Comment by jahaganiev** [comment]
Hey everyone, 

Our team just recently updated [Framework Guides](https://preline.co/docs/frameworks.html) page with live playground demos for all v2 JS components. Please try out with the latest version and let us know if you still have any issues.

Cheers!

**Comment by ashikck** [comment]
Worked for me. Thanks alot

**Comment by ndrshnsn** [comment]
> Seems like it's the same story with Rails and Turbo. It works on initial page load but not after page is navigated.

hey @lenart have you find any way to solve this? its working only with turbo: false...

**Comment by ndrshnsn** [comment]
> > Seems like it's the same story with Rails and Turbo. It works on initial page load but not after page is navigated.
> 
> hey @lenart have you find any way to solve this? its working only with turbo: false...

Just found myself and used other solutions as reference. Call Preline loaders into turbo:load event.

document.addEventListener("turbo:load", function(event) {
  HSAccordion.autoInit();
  HSDropdown.autoInit();
  HSOverlay.autoInit();
  HSSelect.autoInit();
  ...
});

**Comment by shanke-pvex** [comment]
> Hey everyone, 
> 
> 
> 
> Our team just recently updated [Framework Guides](https://preline.co/docs/frameworks.html) page with live playground demos for all v2 JS components. Please try out with the latest version and let us know if you still have any issues.
> 
> 
> 
> Cheers!

It works

**Comment by lenart** [comment]
> > > Seems like it's the same story with Rails and Turbo. It works on initial page load but not after page is navigated.
> > 
> > 
> > hey @lenart have you find any way to solve this? its working only with turbo: false...
> 
> Just found myself and used other solutions as reference. Call Preline loaders into turbo:load event.
> 
> ```js
> document.addEventListener("turbo:load", function(event) {
>     HSAccordion.autoInit();
>     HSDropdown.autoInit();
>     HSOverlay.autoInit();
>     HSSelect.autoInit();
> });
> ```
> 
> and call it from your main application.js

@ndrshnsn haven't had a chance to try it out myself but it seems like you should call `HSStaticMethods.autoInit();` and don't have to deal with individual components. I'd probably put that code to `turbo:visit` dom event.

**Comment by sajjadgol** [comment]
I copied DOM when dropdown menu work incorrectly , below code generated :

` <div class="hs-dropdown-menu  min-w-[18rem] transition-[opacity,margin] duration-[0.1ms] sm:duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 sm:w-48 z-10 bg-white sm:shadow-md rounded-lg p-2 dark:bg-gray-800 sm:dark:border dark:border-gray-700 dark:divide-gray-700 before:absolute top-full sm:border before:-top-5 before:start-0 before:w-full before:h-5 block" data-popper-escaped="" data-popper-placement="bottom-start" style="position: fixed; inset: 0px auto auto 0px; transform: translate(1290px, 70px);">`

and copied Dom when dropdown and other element work  correctly , below code

`<div class="hs-dropdown-menu min-w-[18rem] transition-[opacity,margin] duration-[0.1ms] sm:duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 sm:w-48 z-10 bg-white sm:shadow-md rounded-lg p-2 dark:bg-gray-800 sm:dark:border dark:border-gray-700 dark:divide-gray-700 before:absolute top-full sm:border before:-top-5 before:start-0 before:w-full before:h-5 hidden" style="">`

many different , you can use Meld software for tracking differents

**Comment by ndrshnsn** [comment]
> > > > Seems like it's the same story with Rails and Turbo. It works on initial page load but not after page is navigated.
> > > 
> > > 
> > > hey @lenart have you find any way to solve this? its working only with turbo: false...
> > 
> > 
> > Just found myself and used other solutions as reference. Call Preline loaders into turbo:load event.
> > ```js
> > document.addEventListener("turbo:load", function(event) {
> >     HSAccordion.autoInit();
> >     HSDropdown.autoInit();
> >     HSOverlay.autoInit();
> >     HSSelect.autoInit();
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and call it from your main application.js
> 
> @ndrshnsn haven't had a chance to try it out myself but it seems like you should call `HSStaticMethods.autoInit();` and don't have to deal with individual components. I'd probably put that code to `turbo:visit` dom event.
> 
> **UPDATE: I did what I said above and it works.**

Thanks, worked like a charm. Noted that if you need to use one of these components + Stimulus (dependent dropdowns, for ex) you should call them again in controller - like HSSelect.autoInit() in controller connect 

Just sharing my findings ;)

**Comment by VishalLudhrani** [comment]
> Huge thanks everyone for the updates and sharing the workaround with others - your contributions are truly appreciated!
> 
> @sebastianbilling @hiteshjoshi if you are still having an issue, please open a new issue with more details.
> 
> Cheers!

I still am facing issues.

I referred to the updated documentation, and made changes accordingly.
It works as intended during the development.

However, the build fails with `ReferenceError: Self is not defined`.

Please find the details [here](https://github.com/htmlstreamofficial/preline/issues/177#issuecomment-1829254354)

**Comment by hiteshjoshi** [comment]
> Hey everyone,
> 
> Our team just recently updated [Framework Guides](https://preline.co/docs/frameworks.html) page with live playground demos for all v2 JS components. Please try out with the latest version and let us know if you still have any issues.
> 
> Cheers!

Still the same. If I add a new item on the fly after preline load, it won't work.

**Comment by hiteshjoshi** [comment]
Yup, it behaves very strange. Had to go back to v1.9.0

So at whatever point my dom adds a new dropdown it works in 1.9.0 
but with 2.0.2 it doesnt work (sometimes it works after a few clicks but not always)

**Comment by zerobig** [comment]
I solved it.

./node_modules/preline/preline.d.ts
add lines:
```typescript
declare global {
	interface Window {
		HSStaticMethods: {
			afterTransition(el: HTMLElement, cb: Function): void;
			getClassPropertyAlt(el: HTMLElement, prop?: string, val?: string): string;
			getClassProperty(el: HTMLElement, prop?: string, val?: string): string;
			autoInit(collection: string | string[] = 'all'): void;
		};
	}
}
```

./components/PrelineScript.tsx
change line:
```typescript
  useEffect(() => {
    setTimeout(() => {
-      HSStaticMethods.autoInit();
+      window.HSStaticMethods.autoInit();
    }, 100);
  }, [path]);
```

**Comment by zerobig** [comment]
I solved it.

./node_modules/preline/preline.d.ts
add lines:
```typescript
declare global {
	interface Window {
		HSStaticMethods: {
			afterTransition(el: HTMLElement, cb: Function): void;
			getClassPropertyAlt(el: HTMLElement, prop?: string, val?: string): string;
			getClassProperty(el: HTMLElement, prop?: string, val?: string): string;
			autoInit(collection: string | string[] = 'all'): void;
		};
	}
}
```

./components/PrelineScript.tsx
change two lines:
```typescript
  useEffect(() => {
    setTimeout(() => {
-     HSStaticMethods.autoInit();
+     window.HSStaticMethods.autoInit();
-   }, 100);
+   }, 300);
  }, [path]);
```

**Comment by sajjadgol** [comment]
> I solved it.
> 
> ./node_modules/preline/preline.d.ts add lines:
> 
> ```ts
> declare global {
> 	interface Window {
> 		HSStaticMethods: {
> 			afterTransition(el: HTMLElement, cb: Function): void;
> 			getClassPropertyAlt(el: HTMLElement, prop?: string, val?: string): string;
> 			getClassProperty(el: HTMLElement, prop?: string, val?: string): string;
> 			autoInit(collection: string | string[] = 'all'): void;
> 		};
> 	}
> }
> ```



it work fine ♥️

**Comment by koossaayy** [comment]
I can confirm this; using Livewire, and preline v2.0.2, but rolling back to v1.9.0 it works perfectly.

**Comment by umaraziz0** [comment]
Can confirm, JS features like tabs don't work properly in v2, it stops working on HMR or page navigation, hopefully a fix will come soon

**Comment by Sicria** [comment]
@umaraziz0 Check out #205 it has an approach that may work for you.

**Comment by billymosis** [comment]
> > > Seems like it's the same story with Rails and Turbo. It works on initial page load but not after page is navigated.
> > 
> > 
> > hey @lenart have you find any way to solve this? its working only with turbo: false...
> 
> Just found myself and used other solutions as reference. Call Preline loaders into turbo:load event.
> 
> ```js
> document.addEventListener("turbo:load", function(event) {
>     HSAccordion.autoInit();
>     HSDropdown.autoInit();
>     HSOverlay.autoInit();
>     HSSelect.autoInit();
> });
> ```
> 
> and call it from your main application.js

Hi for anybody here and using HTMX and sent partial HTML from server we can use htmx load event like this

```js
    document.addEventListener('htmx:load', function() {
    ....
    }
```

**Comment by hiteshjoshi** [comment]
https://github.com/htmlstreamofficial/preline/issues/197#issuecomment-1896250156

**Comment by jaseemuddinn** [comment]
> > > > Seems like it's the same story with Rails and Turbo. It works on initial page load but not after page is navigated.
> > > 
> > > 
> > > hey @lenart have you find any way to solve this? its working only with turbo: false...
> > 
> > 
> > Just found myself and used other solutions as reference. Call Preline loaders into turbo:load event.
> > ```js
> > document.addEventListener("turbo:load", function(event) {
> >     HSAccordion.autoInit();
> >     HSDropdown.autoInit();
> >     HSOverlay.autoInit();
> >     HSSelect.autoInit();
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and call it from your main application.js
> 
> @ndrshnsn haven't had a chance to try it out myself but it seems like you should call `HSStaticMethods.autoInit();` and don't have to deal with individual components. I'd probably put that code to `turbo:visit` dom event.
> 
> **UPDATE: I did what I said above and it works.**

Could you please share your file of app.jsx??

**Comment by jaseemuddinn** [comment]
@ode96-dev thanks

**Comment by javid-gulamaliyev** [comment]
On Rails 7, I am finding that even with 
```js
document.addEventListener("turbo:load", function(event) {
    HSAccordion.autoInit();
    HSDropdown.autoInit();
    HSOverlay.autoInit();
    HSSelect.autoInit();
});
```
none of the JS is working...

**Comment by omar-shaheen** [comment]
I have the same issue, but with the latest version of NUXT 3.
Does anyone have a solution?
I'm encountering an issue when switching between layouts — such as from a layout-less login page to the dashboard.vue layout. Some utility classes like [lg:hs-overlay-layout-open:ps-72] are not being reset and remain active across layout transitions.
