### ISSUE TITLE
React application broken after update from 2.0.0 to 2.0.1

### ISSUE THREAD

**Issue by MorWalPiz** [htmlstreamofficial/preline#174]
After update the package from 2.0.0 to

```json
"@preline/overlay": "^2.0.1",
"preline": "^2.0.1",
```
the compiler prompts

`Module not found: Error: Can't resolve 'preline' in '<path-to-file>'`

These file contains
- import { HSOverlay } from "preline"; (home.js)
- import('preline') (app.js)

I check your last commit and i find out this change in package.json

```
- "main": "dist/preline.js",
+ "main": "index.js",
```

Is it related to this issue?

**Comment by MorWalPiz** [comment]
UPDATE
PR #175

**Comment by jahaganiev** [comment]
Thanks @MorWalPiz for the quick catch and PR!
