### ISSUE TITLE
Can not use HSOverlay on AdonisJS

### ISSUE THREAD

**Issue by hieuhuynh93** [htmlstreamofficial/preline#176]
When I use the method ```HSOverlay.open()``` to fire the open event, I get the error "ReferenceError: HSOverlay is not defined". 
Here is my code, I don't know where I went wrong. 
Note: it only works when I use ```data-hs-overlay="#hs-full-screen-modal"``` instead of javascript.
I'm using v2.0.2

![iLZ1q7O5 -2023-11-24 at 11 44 52@2x](https://github.com/htmlstreamofficial/preline/assets/10773568/101824a3-6bbd-4635-8d9c-20aa60aada1d)
![cf6FDLnS -2023-11-24 at 11 45 18@2x](https://github.com/htmlstreamofficial/preline/assets/10773568/cac4881e-138d-4cb6-bb34-caa667e3502a)

**Comment by VishalLudhrani** [comment]
try this:
`import { HSOverlay } from "preline";`

**Comment by hieuhuynh93** [comment]
> try this: `import { HSOverlay } from "preline";`

OMG, it works. Thank you so much.
