### ISSUE TITLE
[v2.0.2] JavaScript functionality not working for Next.js v13.5.3 (using app router)

### ISSUE THREAD

**Issue by VishalLudhrani** [htmlstreamofficial/preline#177]
The following components are not responding upon clicks:
- dropdown for navbar
- accordion (using @preline/accordion v2.0.1)

Here's my tailwind config:
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/assets/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    'node_modules/preline/dist/*.js',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [
    require('preline/plugin')
  ],
}
```

Here's `layout.jsx`
```jsx
import './globals.css'
import { Inter } from 'next/font/google'
import { PrelineLoader } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <head>
        ...
      </head>
      <body className={`${inter.className} bg-slate-900 dark`}>
        <PrelineLoader />
        {children}
      </body>
    </html>
  )
}
```

Here's `PrelineLoader.jsx`
```jsx
"use client";

import { useEffect } from "react";

export default function PrelineLoader() {
  useEffect(() => {
    import("preline");
  }, [])

  return <></>
}
```

Additionally, `tailwind.config.js` throws the following error:
![image](https://github.com/htmlstreamofficial/preline/assets/59205958/972c1eb9-b2a0-4b14-87e4-023046dba368)

**Comment by sebastianbilling** [comment]
Some javascript functionality is not working correctly in the latest 2.X.X builds.

**Comment by VishalLudhrani** [comment]
After referring to @jahaganiev 's [comment](https://github.com/htmlstreamofficial/preline/issues/171#issuecomment-1828754800), here are the changes I did in my code for `PrelineLoader.jsx` component (rest of the code remains the same as shown above).
```jsx
"use client";

import HSAccordion from "@preline/accordion";
import { usePathname } from "next/navigation";
import { HSDropdown } from "preline/preline";
import { useEffect } from "react";

export default function PrelineLoader() {
  const path = usePathname();

  useEffect(() => {
    import("preline/preline");
  }, []);

  useEffect(() => {
    setTimeout(() => {
      HSAccordion.autoInit();
      HSDropdown.autoInit();
    }, 100)
  }, [path])

  return <></>
}
```

Everything runs fine in development mode with some errors as shown below:
![image](https://github.com/htmlstreamofficial/preline/assets/59205958/7779eb77-d618-4e12-9b6c-26013975f76a)

But the build fails with the error `ReferenceError: self is not defined`
![image](https://github.com/htmlstreamofficial/preline/assets/59205958/2e63d120-7fef-47af-880a-b4a1f5ccc144)

**Comment by zCastleM** [comment]
+1

**Comment by VishalLudhrani** [comment]
v2 is now working fine.
There's issues with running build.
Creating a new issue for the same
