### ISSUE TITLE
Please fix dark mode toggle 

### ISSUE THREAD

**Issue by justnotiyann** [htmlstreamofficial/preline#181]
Hi, I found a feature that is incomplete, when light mode is activated and moved to another page it automatically goes to dark mode again.

The website : https://preline.co/plugins/overview.html

https://github.com/htmlstreamofficial/preline/assets/100482628/1ea4b4de-ba99-4731-b21a-9be9c7e86036

**Comment by jahaganiev** [comment]
Hey @justnotiyann - it's fixed! Please hard-refresh the page or clean the cache to be able to see the fix. Thanks!
