### ISSUE TITLE
I got issue with HSPinInput

### ISSUE THREAD

**Issue by hieuhuynh93** [htmlstreamofficial/preline#184]
Hi there,
Here is a detail of the issue I'm facing. It seems it can not find the "verify-code" ID. I'm using AdonisJS, Preline v2.0.2. Everyone can help me solve it? Thank you.

![ii6pRvOT -2023-11-28 at 09 02 46@2x](https://github.com/htmlstreamofficial/preline/assets/10773568/a07b829e-8300-4c31-afcb-781613f080ab)
![jUzNo0Ha -2023-11-28 at 09 03 21@2x](https://github.com/htmlstreamofficial/preline/assets/10773568/6c1dbc0c-6646-4859-82e3-1f8b35188f4d)
![Tnj5jISb -2023-11-28 at 09 03 27@2x](https://github.com/htmlstreamofficial/preline/assets/10773568/1b19d574-b919-4768-b781-b5346e43bdf9)

**Comment by VishalLudhrani** [comment]
Try importing it from "preline/preline":
`import { HSOverlay, HSPinInput } from "preline/preline"`

**Comment by hieuhuynh93** [comment]
> Try importing it from "preline/preline": `import { HSOverlay, HSPinInput } from "preline/preline"`

I changed it but nothing changed. Only the `HSOverlay` working.

**Comment by hieuhuynh93** [comment]
@VishalLudhrani  It seems the problem is in the `getInstance` method, I tried this way to fire the model open but I got same issue with `HSPinput`
```javascript
const { element } = HSOverlay.getInstance('.pin-code-modal', true)
```

**Comment by VishalLudhrani** [comment]
v2 has had quite some breaking changes in terms of the underlying code.
I looked at the source code and there's clear distinction when you compare the previous code (say v1.9) with v2.
The approach and naming conventions have been changed.
That's what is causing this confusion possibly.

**Comment by hieuhuynh93** [comment]
> v2 has had quite some breaking changes in terms of the underlying code. I looked at the source code and there's clear distinction when you compare the previous code (say v1.9) with v2. The approach and naming conventions have been changed. That's what is causing this confusion possibly.

I found the cause of the problem, it was actually because I accidentally placed the `getInstance` method outside `window.onload()` 
In fact, as you said, v2 has changed too much, but it has changed for the better.

**Comment by VishalLudhrani** [comment]
I see.
Thanks for your inputs.

And I agree with you.
I see improvements in terms of code style.
It's inspiring.
I could observe and use some patterns for my projects as well!
