### ISSUE TITLE
remove unnecessary console.log

### ISSUE THREAD

**Issue by roiLeo** [htmlstreamofficial/preline#185]
```ts
all
```

is throwed in console.log

Step to reproduce:
check out [Nuxt slackblitz](https://stackblitz.com/edit/preline-v2-nuxt-3?file=plugins%2Fpreline.client.ts) console

**Comment by vadimmelnicuk** [comment]
I second that, please look into removing "all" being logged in web console on every refresh.

**Comment by jahaganiev** [comment]
Thanks for the report and suggestion - it will be enhanced in the next update.

ref. #209

**Comment by jahaganiev** [comment]
Hey @roiLeo, @vadimmelnicuk - we've just released v2.0.3 update, which includes the improvements. Thanks!
