### ISSUE TITLE
`HSStaticMethods` type

### ISSUE THREAD

**Issue by roiLeo** [htmlstreamofficial/preline#186]
<img width="428" alt="Capture d’écran 2023-11-28 à 10 30 09 AM" src="https://github.com/htmlstreamofficial/preline/assets/9987732/45d26c5f-3471-42f8-9931-3cc756747a1b">

On [Nuxt example](https://stackblitz.com/edit/preline-v2-nuxt-3?file=plugins%2Fpreline.client.ts)

`Cannot find name 'HSStaticMethods'.`

How to import type?

**Comment by VishalLudhrani** [comment]
Refer `PrelineLoader.jsx` [here](https://github.com/htmlstreamofficial/preline/issues/177#issuecomment-1829254354).

**Comment by zCastleM** [comment]
I had the same problem, the solution I found so far is to ignore this error.
```
"use client";
import { usePathname } from "next/navigation";
import { useEffect } from "react";

declare global {
    var HSStaticMethods: any;
  }

export default function PrelineScript() {
  const path = usePathname();

  useEffect(() => {
    import("preline/preline");
  }, []);

  useEffect(() => {
    setTimeout(() => {
      HSStaticMethods.autoInit();
    }, 100);
  }, [path]);

  return null;
}
```

Tenho dúvidas se pode quebrar algo mais para frente, até agora tudo ok!

**Comment by zCastleM** [comment]
edit: 
![image](https://github.com/htmlstreamofficial/preline/assets/116334877/28479925-7af2-4221-9bb1-ba5a4516fa46)
In the official Quick Next.js setup example, the same problem is occurring.

**Comment by roiLeo** [comment]
kinda works but wanted to import from preline directly

btw in some components I need to do:
```vue
onMounted(() => {
  setTimeout(() => {
    HSStaticMethods.autoInit()
  }, 100)
})
```
in order to make js work (overlay, dropdown etc..) it look like the `page:finish` hook is not enough, any idea why?

**Comment by olegpix** [comment]
> kinda works but wanted to import from preline directly
> 
> btw in some components I need to do:
> 
> ```
> onMounted(() => {
>   setTimeout(() => {
>     HSStaticMethods.autoInit()
>   }, 100)
> })
> ```
> 
> in order to make js work (overlay, dropdown etc..) it look like the `page:finish` hook is not enough, any idea why?

because the element must be in the DOM when you try to initialize it, and it seems that when you try to initialize the element right after hook, it doesn't seem to be visible to the plugin

**Comment by roiLeo** [comment]
> because the element must be in the DOM when you try to initialize it, and it seems that when you try to initialize the element right after hook, it doesn't seem to be visible to the plugin

Okay, that's what I thought. I need to find a better global hook to initialise or else I'll have to copy `onMounted` on each components that use js part of preline.
Thanks for the answers, close issue as resolved for now.
