### ISSUE TITLE
Unable to open Modal on Top of Another Modal Despite Providing Different ID and Z-Index to Modal Div

### ISSUE THREAD

**Issue by Jenish-Dhanani** [htmlstreamofficial/preline#189]
Description: 
I am currently facing an issue with preline UI a modal on top of another modal, even after providing distinct IDs and Z-index values to both modal divs. Despite these efforts, the intended behavior is not being achieved. The goal is to ensure that one modal is displayed on top of the other when both modals are active.

Steps to Reproduce:

Initialize two modals, let's call them Modal A and Modal B.
Assign unique IDs to both modals.
Set different Z-index values for each modal to control their stacking order.
Trigger the display of both modals simultaneously, expecting Modal A to be on top of Modal B based on the given Z-index values and IDs.
Expected Behavior: Modal A should be effectively on top of Modal B when both modals are active, as determined by the assigned IDs and Z-index values.

**Comment by jahaganiev** [comment]
Hey @Jenish-Dhanani - Stacked Overlays feature currently is not available and it's in our roadmap. Duplicated #134

**Comment by Jenish-Dhanani** [comment]
Hi @jahaganiev If this is feature is in roadmap for next development then could you please share expected timeline of release it?

**Comment by jahaganiev** [comment]
Hey @Jenish-Dhanani, here we go - https://preline.co/docs/modal.html#stacked-overlays
