### ISSUE TITLE
Scrollspy not working as expected

### ISSUE THREAD

**Issue by JoshWeb** [htmlstreamofficial/preline#19]
1. [Examples aren't working as expected in the docs](https://preline.co/docs/scrollspy.html)

2. It may be intentional, but doesn't work when ID's are nested in the `data-hs-scrollspy` container

**Comment by Mr-Zafar** [comment]
Hi, @JoshWeb -

Thank you for reporting this issue.

It's [fixed](https://preline.co/docs/scrollspy.html) now. You can also find more examples [here](https://preline.co/examples.html#scrollspy-navigation).

Thanks!
