### ISSUE TITLE
AdvancedSelect change toggleClasses dynamically not working

### ISSUE THREAD

**Issue by shanke-pvex** [htmlstreamofficial/preline#190]
I use Laravel 10, inertia and vue3.
For form validation i use the nomal laravel backend validation.
If an error occurs i change some classes in the option "toggleClasses" to red as shown here: https://preline.co/docs/advanced-select.html#validation-states

If i inspect the DOM the new classes are assigned but the select ui is not refreshed. 
Calling the following init on success does not work:
onFinish: () => {
    setTimeout(() => {
        HSStaticMethods.autoInit();
    }, 100);
},

Is it possible to re-initialize the select?

**Comment by shanke-pvex** [comment]
Same behaviour.

**Comment by shanke-pvex** [comment]
Has anybody a working example for the change event?

const el = HSSelect.getInstance('#select');
el.on('change', (val) => {...});

In vue-file my import ist: import { HSSelect } from "preline";

I always get: Uncaught TypeError: Cannot read properties of null (reading 'on')

**Comment by VishalLudhrani** [comment]
hey @shanke-pvex can you try:
```js
const el = HSSelect.getInstance('#select');
if (el) { // check if the element exists on dom
  el.onchange = (val) => {...}
}
```

**Comment by shanke-pvex** [comment]
// part of imports
import PvexAdvancedSelect from "@/Components_Pvex/PvexAdvancedSelect.vue";
import { HSSelect } from "preline";

// onMounted Hook
onMounted(() => {
    setTimeout(() => {
        HSStaticMethods.autoInit();
        const el = HSSelect.getInstance("#select");
        if (el) {
            // check if the element exists on dom
            el.onchange = (val) => {
                console.log(val);
            };
        } else {
            console.log("no element found");
        }
    }, 100);
});

// select in template

<div class="relative">
  <PvexInputLabel
      for="number_busbars"
      value="Anzahl Busbars"
  />
  <PvexAdvancedSelect
      id="select"
      class="mt-1 block w-full"
      v-model="form.number_busbars"
      :options="[
          {
              value: 'keine Angabe',
              label: 'keine Angabe',
              selected: true,
          },
          { value: 0, label: '0' },
          { value: 1, label: '1' },
          { value: 2, label: '2' },
          { value: 3, label: '3' },
          { value: 4, label: '4' },
          { value: 5, label: '5' },
          { value: 6, label: '6' },
          { value: 7, label: '7' },
          { value: 8, label: '8' },
          { value: 9, label: '9' },
          { value: 10, label: '10' },
      ]"
      :message="form.errors.number_busbars"
  />
  <PvexInputError
      class="mt-2"
      :message="form.errors.number_busbars"
  />
</div>


The select is correctly initialized on page but console says: no element found - very strange

**Comment by shanke-pvex** [comment]
<img width="687" alt="Bildschirmfoto 2023-12-01 um 17 38 52" src="https://github.com/htmlstreamofficial/preline/assets/148051376/82ad0767-0d73-4949-8be2-ab6ceef48a34">

**Comment by shanke-pvex** [comment]
<img width="423" alt="Bildschirmfoto 2023-12-01 um 17 42 22" src="https://github.com/htmlstreamofficial/preline/assets/148051376/3569e277-c1db-471f-abea-78a932991f53">

**Comment by jagabs** [comment]
do you guys know how to add initial value to HSSelect? i used

`const el = HSSelect.getInstance("#select");
el.value = [1,2,3,4];`

it works only after the onchange is triggered when i click a new item.

**Comment by olegpix** [comment]
> Is there another way to change the border color to red (of the select) when an error is present from the backend laravel validation? I use inertia and vue3

Hello,
We will add the hs-error and hs-success classes to the plugin.js file in version 2.1.0. After this you will be able to add an error/success class like this:
```
<div class="relative" :class="{error: hasError}">
	<select data-hs-select='{
		"toggleClasses": "hs-error:border-red-500 hs-success:border-teal-500 hs-error:focus:border-red-500 hs-success:focus:border-teal-500 hs-error:focus:ring-red-500 hs-success:focus:ring-teal-500",
…
```
