### ISSUE TITLE
BUG : javascript components

### ISSUE THREAD

**Issue by sajjadgol** [htmlstreamofficial/preline#191]
Many times don't work component that need JavaScript like dropdown and other component, and must refresh need to work correctly

**Comment by lenart** [comment]
Do a search before blindly creating a new issue. This adds unnecessary load on project maintainers. See https://github.com/htmlstreamofficial/preline/issues/171 for answer to your problems.

**Comment by jahaganiev** [comment]
Hey @sajjadgol - thanks for checking out Preline UI. Please provide more context about the issue with some example codes, screenshots etc. - meanwhile, closing the issue. Thanks!
