### ISSUE TITLE
Next.js build fails with ReferenceError: Self is not defined

### ISSUE THREAD

**Issue by VishalLudhrani** [htmlstreamofficial/preline#192]
When in development mode:
![image](https://github.com/htmlstreamofficial/preline/assets/59205958/f1e03b64-1169-4f81-b0a6-fb9ca7fed416)

When trying to run build:
![image](https://github.com/htmlstreamofficial/preline/assets/59205958/80d6e688-a4c2-4185-8ff7-694c0050bcae)

**Comment by roiLeo** [comment]
Do you use something like `HSAccordion`? if so, you can try to dynamic import it from preline once page is displayed (`const { HSAccordion } = await import('preline')`)

**Comment by VishalLudhrani** [comment]
Referring to [this comment](https://github.com/htmlstreamofficial/preline/issues/198#issuecomment-1839771480), I was able to fix the issue.

Updated code for `PrelineLoader.jsx`:

```jsx
"use client";

import { usePathname } from "next/navigation";
import { useEffect } from "react";

const isBrowser = typeof window !== undefined; // check if component is rendered in a browser

export default function PrelineLoader() {
  const path = usePathname();

  useEffect(() => {
    if (isBrowser) {
      // if this component is rendered on a browser, import preline
      import("preline/preline");
    }
  }, [])

  useEffect(() => {
    setTimeout(() => {
      if (isBrowser) {
        // if this component is rendered on a browser, import relevant preline plugins
        import("preline/preline").then(({ HSAccordion, HSDropdown }) => {
          HSAccordion.autoInit();
          HSDropdown.autoInit();
        })
      }
    }, 100)
  }, [path])

  return <></>
}
```
