### ISSUE TITLE
Uncaught ReferenceError: `HSOverlay` is not defined

### ISSUE THREAD

**Issue by roiLeo** [htmlstreamofficial/preline#193]
trying to close modals programmatically

`HSOverlay` is not defined on window (https://preline.co/plugins/html/overlay.html#js-methods) even after `HSStaticMethods.autoInit()`

**Comment by roiLeo** [comment]
nevermind fixed by `import { HSOverlay } from 'preline'` (ref #176)

**Comment by sajjadgol** [comment]
i use laravel and livewire 
but not work for me
