### ISSUE TITLE
Could not open HSOverlay using public method (Javascript)

### ISSUE THREAD

**Issue by vkgautham** [htmlstreamofficial/preline#194]
I am working with Htmx and Preline UI and having trouble with HSOverlay. I have the following code and is not working as expected. `modal.open()` is not showing the modal but when I toggle the `hidden` and `open` classes directly on the `modal <div>` the `overlay` is shown. However in this way, I am not able to add backdrop classes, transitions etc.,

Any idea, what I am doing wrong?

Thanks

```
addEventListener("htmx:afterSettle", () => {
    const modal = new HSOverlay(document.querySelector('#hs-basic-modal'));
    const overlay = document.querySelector("#hs-basic-modal");
    const openBtn = document.querySelector('[data-hs-overlay]');

    openBtn.addEventListener('click', () => {

        //**this working**
        overlay.classList.remove("hidden");
        overlay.classList.add("hs-overlay-backdrop-open:bg-blue-900/[.5]")  // but backdrop is not visible
        overlay.classList.add("open");
        console.log('...');

        //**this is not working**
        modal.open();
    });
});
```

I have the following in my tailwind config file.

```
/** @type {import('tailwindcss').Config} */
const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
    darkMode: "class",
    content: [
        "./templates/**/*.html",
        "./node_modules/preline/dist/*.js",       
    ],
    theme: {
        container: {
            center: true,
            padding: '2rem',
        },
        extend: {
            fontFamily: {
                sans: ["Inter var", ...defaultTheme.fontFamily.sans],
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('preline/plugin'),        
        function ({ addVariant }) {
            addVariant("peer-group-checked", ".peer:checked ~ .peer-group &"),
                addVariant(
                    "peer-group-required",
                    ".peer:required ~ .peer-group &"
                ),
                addVariant("peer-group-valid", ".peer:valid ~ .peer-group &");
        },
    ],
};

```

**Comment by jeydi243** [comment]
I have also the same issue when i try with data-hs-overlay='#idOfMyDrawerContent'
nothing happen. this is after migrating to V2.0.0

**Comment by hieuhuynh93** [comment]
Try this
```javascript
import {HSOverlay} from 'preline/preline'

addEventListener("htmx:afterSettle", () => {
    const openBtn = document.querySelector('button_you_want_to_click');
    openBtn.addEventListener('click', () => {
        HSOverlay.open('#hs-basic-modal');
    });
});
```

**Comment by jahaganiev** [comment]
@vkgautham have you tried @hieuhuynh93's suggestions for the workaround? Please do let us know if you still having the issue.

**Comment by sajjadgol** [comment]
I use Laravel and Vite for managing js package and same problem and find solution

if you look in bootstap.js in laravel has below code 
```
 import axios from 'axios';
 window.axios = axios;`
```
then in app.js adding below code for every plugin in preline

```
import  {HSOverlay} from "preline";
window.HSOverlay = HSOverlay;
```
and use below method for calling HSOverly

`HSOverlay.open('#hs-vertically-centered-modal')
`

**Comment by PruthviPraj00** [comment]
@hieuhuynh93 suggested using a static method which worked, but @vkgautham's question pertained to a public method that wasn't working.

I attempted @vkgautham's method, but instead of targeting the modal directly, I had to pass the button ID as follows:

```javascript
addEventListener("htmx:afterSettle", () => {
    const modal = new HSOverlay(document.querySelector('#open-btn'));
    const openBtn = document.querySelector('[data-hs-overlay]');

    openBtn.addEventListener('click', () => {
        // This is not working
        modal.open();
    });
});
```

Additionally, for this to function, we need to set `data-hs-overlay` for that button:

```html
<button type="button" id="open-btn" data-hs-overlay="#modal">
    Open modal
</button>
```

If we are using a public method to initialize the modal, why is it necessary to set `data-hs-overlay`?

**Comment by pranavpremarajan** [comment]
```
import {HSOverlay} from 'preline/preline';

// Inside the component

 const handleOpenButtonClick = () => {
    HSOverlay.open("#modal-id");
  };

<button onClick={handleOpenButtonClick}>open</button>
```

**Comment by cquinoneso** [comment]
> ```
> import {HSOverlay} from 'preline/preline';
> 
> // Inside the component
> 
>  const handleOpenButtonClick = () => {
>     HSOverlay.open("#modal-id");
>   };
> 
> <button onClick={handleOpenButtonClick}>open</button>
> ```


shows an error when pressing the button again to open the modal

**Comment by ginalsyah** [comment]
this is not working
