### ISSUE TITLE
Auto init in 2.0.2

### ISSUE THREAD

**Issue by hiteshjoshi** [htmlstreamofficial/preline#197]
So my html components, including html required for plugin gets build up on the fly (client side).

It used to work perfectly with 1.9.0 but with 2.0.2, I have to manually trigger `HSStaticMethods.autoInit();`

Can we go back to the same way 1.9.0 used to work? The breaking changes without a changelog or direction are very sad.
I understand preline team has spend time writing documentation of implementing in various frameworks etc. but thats mostly the same as 1.9.0. In my case of Astro, its actually same.

But then something fundamentally has changed, and I can no longer generate preline dependent html on the fly.

**Comment by supermx1** [comment]
I have the same issue. When I open up a page with a dropdown component(in Svelte), sometimes the dropdown works, sometimes it doesn't. It is so weird. I followed every step of the setup guide, but it is buggy at best. 1.9.0 did act like this

**Comment by olegpix** [comment]
> So my html components, including html required for plugin gets build up on the fly (client side).
> 
> It used to work perfectly with 1.9.0 but with 2.0.2, I have to manually trigger `HSStaticMethods.autoInit();`
> 
> Can we go back to the same way 1.9.0 used to work? The breaking changes without a changelog or direction are very sad. I understand preline team has spend time writing documentation of implementing in various frameworks etc. but thats mostly the same as 1.9.0. In my case of Astro, its actually same.
> 
> But then something fundamentally has changed, and I can no longer generate preline dependent html on the fly.

You will be able to work with components as standard ES6 classes in version 2, thanks to this you can initialize your newly created component through the constructor.
For example:
import {HSSelect} from "prelien/preline";
...
btn.on('click', () => {
    // create some select with id on the fly
    const newSelect = new HSSelect("#new-added-select-id");
});

**Comment by jagabs** [comment]
do you guys have any idea how to add initial value to hsslect?

const select = new HSSelect(document.querySelector('#select'), {
      value: this.selectedValues,
      dropdownSpace: 1,
    });
    
    i tried this but no luck
    
    i also tried select.value = this.selectedValues;
    
    it works after i trigger the onchange

**Comment by hiteshjoshi** [comment]
@armenr what alternatives you considering?

**Comment by olegpix** [comment]
> We have the same issue. In our Nuxt app, the autoInit() seems to fire at the wrong time.
> 
> Our Navbar layout component seems to be interactive (the `hs-*` stuff works...accordians, drop downs etc work), but on the SAME page, components which require menus etc (that also utilize preline's baked-in JS) do not work.
> 
> Currently, our work-around is to have to do this:
> 
> ```
> // import 'preline/preline'
> // import type { IStaticMethods } from 'preline/preline'
> 
> // declare global {
> //   interface Window {
> //     HSStaticMethods: IStaticMethods
> //   }
> // }
> 
> // export default defineNuxtPlugin((nuxtApp) => {
> //   nuxtApp.hook('page:finish', () => {
> //     window.HSStaticMethods.autoInit()
> //   })
> // })
> 
> declare global {
>   interface HSStaticMethods {
>     autoInit(): void
>   }
>   interface Window {
>     HSStaticMethods: HSStaticMethods
>   }
> }
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   nuxtApp.hook('page:finish', () => {
>     const router = useRouter()
> 
>     watchEffect(() => {
>       import('preline/preline')
>     })
> 
>     watchEffect(() => {
>       const _route = router.currentRoute.value
> 
>       setTimeout(() => {
>         window.HSStaticMethods.autoInit()
>       }, 100)
> 
>       setTimeout(() => {
>         window.HSStaticMethods.autoInit()
>       }, 300)
> 
>       setTimeout(() => {
>         window.HSStaticMethods.autoInit()
>       }, 500)
> 
>       setTimeout(() => {
>         window.HSStaticMethods.autoInit()
>       }, 700)
> 
>       setTimeout(() => {
>         window.HSStaticMethods.autoInit()
>       }, 900)
> 
>       setTimeout(() => {
>         window.HSStaticMethods.autoInit()
>       }, 1100)
> 
>       setTimeout(() => {
>         window.HSStaticMethods.autoInit()
>       }, 1300)
> 
>       setTimeout(() => {
>         window.HSStaticMethods.autoInit()
>       }, 1500)
> 
>       setTimeout(() => {
>         window.HSStaticMethods.autoInit()
>       }, 1700)
> 
>       setTimeout(() => {
>         window.HSStaticMethods.autoInit()
>       }, 1900)
>     })
>   })
> })
> ```
> 
> This is very bad. Please advise.

The only thing ``window.HSStaticMethods.autoInit()`` does is that it automatically initializes the DOM elements, it doesn't do any magic, make sure that when you try to call this method, all the elements are already in the DOM and call the method. I don't understand why you need to call this method every 200 milliseconds... I don’t know the specifics of your project, but I can assume that some components are loaded after event ``page:finish``, which means you need to run this method after this component has loaded. You can also use this method to initialize only some components, for example ``window.HSStaticMethods.autoInit(['dropdown'])``.
You can use Preline components as regular classes via ``new``, maybe this approach will work better for your case.
Post your code on Codesanbox or another service for a better understanding of your case.

**Comment by robm94** [comment]
It seems in v1 the event listeners were attached to the document. so on every click, all event listener were fired and then filtered based on if the target element had the correct class.

In v2 the the event listeners are now added directly to each element on init, so if components are rendered after page load we need to call autoInit again to add new event listeners.

Here is what I've put in my nuxt plugin it watches the `<div id="page-container">` I've wrapped around the changing content for dom changes and calls the autoInit function which is debounced using perfect-debounce.

```
import "preline/preline"
import { type IStaticMethods } from "preline/preline"
import { debounce } from 'perfect-debounce'
declare global {
  interface Window {
    HSStaticMethods: IStaticMethods
  }
}

export default defineNuxtPlugin((nuxtApp) => {
  onNuxtReady(() => {
    const targetNode = document.getElementById("page-container")
    if (targetNode) {
      const config = { childList: true, subtree: true }
      const callback = debounce(async () => {
        window.HSStaticMethods.autoInit()
      }, 100)
      const observer = new MutationObserver(callback)
      observer.observe(targetNode, config)
    }
  })
})

```

**Comment by hiteshjoshi** [comment]
Yeah, I figured that too. I am now using Plugin.autInit(); like HSTabs.autoInit(); onMount of svelte. Closing this.

**Comment by ode96-dev** [comment]
I had the same issue. I resolved it by maintaining the guidelines...Preline maintains that: "projects_root_directory/app/components/PrelineScript.tsx", meaning the PrelineScript.tsx component must be housed within a components folder in the app directory.

**Comment by max-programming** [comment]
In my case, for some reason, nothing worked except for this. I am using Blazor. Let me know if there's a better way. Or if the `autoInit` method is expensive

![image](https://github.com/htmlstreamofficial/preline/assets/51731966/17a3b801-df05-45eb-a443-a8c95d3fc899)
