### ISSUE TITLE
Feature request: Combobox

### ISSUE THREAD

**Issue by roiLeo** [htmlstreamofficial/preline#199]
Examples:
- Shadcn -> https://ui.shadcn.com/docs/components/combobox
- HeadlessUI -> https://headlessui.com/react/combobox

**Comment by jahaganiev** [comment]
duplicated with #140

Meanwhile, you may consider using Advanced Select with search box - https://preline.co/docs/advanced-select.html#search-inside-dropdown

**Comment by jahaganiev** [comment]
Hey @roiLeo - it's live now!

https://preline.co/docs/combobox.html
