### ISSUE TITLE
Don't find any asset folder that should contain the hs-ui-bundle.js file

### ISSUE THREAD

**Issue by kazi331** [htmlstreamofficial/preline#2]
I installed preline ui today and the docs instruct me to link the hs-ui-bundle.js file at the bottom of the body tag.

but, where do I get the file?

theres no asset folder inside of react app.

**Comment by green-cats** [comment]
@kazi331 Hello! 
Thank you for report. 
Seems there was a typo in the path, we’ve just fixed the docs page. The hs-ui.bundle.js file is located at preline/dist/..

Cheers!

**Comment by jahaganiev** [comment]
Hey @kazi331, hope it worked out. Closing this issue since it's fixed already. Please feel free to let us know if you come across with any issues. Thanks!
