### ISSUE TITLE
Keyboard navigation not working in advanced select

### ISSUE THREAD

**Issue by lenart** [htmlstreamofficial/preline#202]
If you go to https://preline.co/docs/advanced-select.html#search-inside-dropdown open the countries dropdown and search for `en` and then try to use arrow keys to get to _England_ (for example) it won't work. Arrow keys do work, however, when there's no search string present.

**Comment by olegpix** [comment]
> If you go to https://preline.co/docs/advanced-select.html#search-inside-dropdown open the countries dropdown and search for `en` and then try to use arrow keys to get to _England_ (for example) it won't work. Arrow keys do work, however, when there's no search string present.

Thanks, we'll improve it in the next minor version. Stay tuned!

**Comment by jahaganiev** [comment]
Hey @lenart - we've just released v2.0.3 update with the fix. Thanks!
