### ISSUE TITLE
Cannot find name 'HSStaticMethods' in Next.js 14

### ISSUE THREAD

**Issue by Joatancarlos** [htmlstreamofficial/preline#205]
When following the steps in the documentation to install preline, I came across the error mentioned in the title when creating the PrelineScript.tsx component.

```js
// PrelineScript.tsx 
"use client";

import { usePathname } from "next/navigation";
import { useEffect } from "react";

export default function PrelineScript() {
  const path = usePathname();

  useEffect(() => {
    import("preline/preline");
  }, []);

  useEffect(() => {
    setTimeout(() => {
      HSStaticMethods.autoInit();
    }, 100);
  }, [path]);

  return null;
}

 ```
 
 When I click on the imported file in the "import(preline/preline" line) I noticed that there is no HSStaticMethods. So, what do I do?
 
 ```js
// layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import { openSans } from './components/fonts'
import Link from 'next/link'
import PrelineScript from './components/PrelineScript'
import Footer from './components/footer'


export const metadata: Metadata = {
  title: 'Austron',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>{children}</body>
      <Footer />
      <PrelineScript />
    </html>
  );
}

 ```

**Comment by ankurgajurel** [comment]
same issue hm

**Comment by botraunak** [comment]
update PrelineScript.jsx, a hacky fix as the type is not available in preline.d.ts, although it can be found in [https://github.com/htmlstreamofficial/preline/blob/main/src/plugins/base-plugin/index.ts](https://github.com/htmlstreamofficial/preline/blob/main/src/plugins/base-plugin/index.ts)

Fixed the builds for me on next 13 for now
```ts
'use client';

import { usePathname } from 'next/navigation';
import { useEffect } from 'react';

declare global {
  interface Window {
    HSStaticMethods: any;
  }
}

export default function PrelineScript() {
  const path = usePathname();
  useEffect(() => {
    import('preline/preline');
  }, []);

  useEffect(() => {
    setTimeout(() => {
      window.HSStaticMethods.autoInit();
    }, 100);
  }, [path]);

  return null;
}
```

**Comment by jahaganiev** [comment]
@Joatancarlos, @ankurgajurel you may check out the issue #206 for work around

**Comment by Joatancarlos** [comment]
@botraunak After implementing your code, a hydration problem appeared:
![Captura de tela de 2023-12-10 12-53-31](https://github.com/htmlstreamofficial/preline/assets/95449499/610810d4-9c1e-4591-a358-9ca5a6afda9b)
![Captura de tela de 2023-12-10 12-53-45](https://github.com/htmlstreamofficial/preline/assets/95449499/8cebb488-a944-462c-891c-73f75de1416c)

**Comment by fernandonetom** [comment]
same here

**Comment by Sicria** [comment]
I've noticed that sometimes the `autoInit` method would fail due to it not being initialised at the time of being called. Here's a script that retries it when it fails 5 times with extended delays to ensure that it will hopefully succeed.

```
'use client';
import { usePathname } from 'next/navigation';
import { useEffect } from 'react';

export function initPreline(times = 0) {
  setTimeout(
    () => {
      try {
        window.HSStaticMethods.autoInit();
      } catch (error) {
        if (times <= 5) {
          initPreline(times + 1);
        } else {
          throw error;
        }
      }
    },
    100 * (times + 1),
  );
}

export default function PrelineScript() {
  const path = usePathname();

  useEffect(() => {
    import('preline/preline');
  }, []);

  useEffect(() => {
    initPreline();
  }, [path]);

  return null;
}
```

**Comment by kezzlock** [comment]
Hello! 

I added Sicria code: https://github.com/htmlstreamofficial/preline/issues/205#issuecomment-1857354120
to components/PrelineScript.tsx

and created in main project folder file: **global.d.ts** :
```
interface HSStaticMethods {
    autoInit: () => void;
}

interface Window {
    HSStaticMethods: HSStaticMethods;
}
```

and it works for me, new (Next.js 14) project deployed to Vercel.

Hope it will help!
Regards

**Comment by DarkestSeconds** [comment]
The @kezzlock code with @Sicria code is working! Thanks you so much! 😊

**Comment by Joatancarlos** [comment]
@kezzlock Thank you for your help. It finally worked

**Comment by jahaganiev** [comment]
Hey everyone, we've just updated the Freamwork Guides pages and released minor [v2.0.3](https://preline.co/docs/changelog.html) update with other improvements and bug fixes.

**Comment by derrikfleming** [comment]
still having the issue here on 2.0.3, Next 14.

**Comment by derrikfleming** [comment]
i'm encountering this issue on 2.0.3, Next 14.
