### ISSUE TITLE
Update DOCS - Next JS

### ISSUE THREAD

**Issue by thefubon** [htmlstreamofficial/preline#206]
Hi. Please update the documentation for NextJS. There is no code in the documentation. It gives an error.

<img width="966" alt="Снимок экрана 2023-12-08 в 20 37 39" src="https://github.com/htmlstreamofficial/preline/assets/43171309/6f28e332-2abb-448b-9e48-dbc260ae8134">

```
declare var HSStaticMethods: {
  autoInit(collection?: string | string[]): void;
};
```

https://preline.co/docs/frameworks-nextjs.html

```tsx
"use client";

import { usePathname } from "next/navigation";
import { useEffect } from "react";

declare var HSStaticMethods: {
  autoInit(collection?: string | string[]): void;
};

export default function PrelineScript() {
  const path = usePathname();

  useEffect(() => {
    import("preline/preline");
  }, []);

  useEffect(() => {
    setTimeout(() => {
      HSStaticMethods.autoInit();
    }, 100);
  }, [path]);

  return null;
}
```

**Comment by perryraskin** [comment]
These adjustments solved it for me in my Next.js 13 project (**pages** router).

Adding `HSStaticMethods` as an attribute to `window`.

```
declare global {
  interface Window {
    HSStaticMethods: any
  }
}
```

Using `window` to access `HSStaticMethods` and changing the `setTimeout` time to `1000`.

```
setTimeout(() => {
   window.HSStaticMethods.autoInit()
 }, 1000)
```

Full code:

```
/* eslint-disable @typescript-eslint/no-explicit-any */
import { usePathname } from "next/navigation"
import { useEffect } from "react"

declare global {
  interface Window {
    HSStaticMethods: any
  }
}

export default function PrelineScript() {
  const path = usePathname()
  useEffect(() => {
    import("preline/preline")
  }, [])

  useEffect(() => {
    setTimeout(() => {
      window.HSStaticMethods.autoInit()
    }, 1000)
  }, [path])

  return null
}

```

**Comment by jahaganiev** [comment]
Hey everyone, the Next.js docs page is updated - https://preline.co/docs/frameworks-nextjs.html 

Thanks!

**Comment by insivika** [comment]
Im seeing the error `SyntaxError: Expected ',' or '}' after property value in JSON at position 70`

**Comment by insivika** [comment]
@jahaganiev @perryraskin is there a way to load the script without the setTimeout?
