### ISSUE TITLE
Preline Laravel Vue.js, couldn't find a declaration file for this plugin.

### ISSUE THREAD

**Issue by rlc1990** [htmlstreamofficial/preline#207]
![image](https://github.com/htmlstreamofficial/preline/assets/18001692/82c5c9fe-5fce-4c8b-89ed-0e77c1e52c86)

tailwind.config.js
`plugins: [
        require('preline/plugin'), forms
    ]`

**Comment by rlc1990** [comment]
![image](https://github.com/htmlstreamofficial/preline/assets/18001692/a9660bad-710c-4be0-b204-dea3ffeb91a8)

I import preline/plugin to be able to work with modals, and etc. I still don't know if i solved the issue with the Tailwindcss plugin thing.

**Comment by jahaganiev** [comment]
> I import preline/plugin in resources/js/app.js to be able to work with modals, and etc.

If Preline plugins are working, most likely the classes are being generated and everything is working fine.

You may also check out our stackblitz/codesandbox example playgrounds from the [Framework Guides](https://preline.co/docs/frameworks.html) pages.

If you're still having an issue, please feel free to share a stackblitz/codesandbox link with your setup.

Cheers!
