### ISSUE TITLE
Discovered a console.log in the wild

### ISSUE THREAD

**Issue by jimmiejackson414** [htmlstreamofficial/preline#209]
Obviously not a big deal, but there looks to be an undeleted console.log that gets displayed on page load. I have v2.0.2 installed, and it comes from the `HSStaticMethods.autoInit()` function in my preline.client.ts file. My guess is that it's from [this line](https://github.com/htmlstreamofficial/preline/blob/8ce63b72ee59d808a40eb3ee9a5dd82e663159c1/src/plugins/base-plugin/index.ts#L243C15-L243C15).

**Comment by jahaganiev** [comment]
Hey @jimmiejackson414 - we've just released v2.0.3 update, which includes the improvements. Thanks!
