### ISSUE TITLE
Preline JavaScript bundle not working

### ISSUE THREAD

**Issue by John-droid-dotcom** [htmlstreamofficial/preline#21]
### Discussed in https://github.com/htmlstreamofficial/preline/discussions/20

<div type='discussions-op-text'>

<sup>Originally posted by **John-droid-dotcom** August 22, 2022</sup>
Hey everyone, I tried to add a dropdown component in my vue project(tailwindCSS installed in NPM) but its functionality is not working. I followed the documentation's instruction but it doesn't seem to help. Anyone can you help me with this?
</div>

**Comment by Mr-Zafar** [comment]
Hi, @John-droid-dotcom -

Can you please send a link to the code? 

Thanks

**Comment by Mr-Zafar** [comment]
Hi, @John-droid-dotcom -

Since we have not received a response from you, we are closing this issue. 

Thanks!
