### ISSUE TITLE
Bug with the carousel component

### ISSUE THREAD

**Issue by codelover44** [htmlstreamofficial/preline#215]
Hi! There's an issue with the carousel component. It's listinning to swipe events on the whole document instead of the carousel instance. It's also triggering the image change on swipe up and down. This problem can even be seen on the carousel doc page on preline.co.

**Comment by jahaganiev** [comment]
Hey @codelover44 - we've just released v2.0.3 with the fix. Thanks for reporting the issue!

**Comment by codelover44** [comment]
Wow! What a reactivity! Thanks a lot. It is in fact fixed in my project as well.
