### ISSUE TITLE
Add option to remove keydown listener on advanced select

### ISSUE THREAD

**Issue by roiLeo** [htmlstreamofficial/preline#216]
## Component

- https://preline.co/docs/advanced-select.html#tags

when typing and press enter it will create a new tag

**Comment by olegpix** [comment]
> ## Component
> * https://preline.co/docs/advanced-select.html#tags
> 
> when typing and press enter it will create a new tag

Thanks, we'll improve it in the next minor version. Stay tuned!

**Comment by jahaganiev** [comment]
Hey @roiLeo, v2.0.3 has just been released, which includes a bunch of improvements for Advanced Select. Thanks!
