### ISSUE TITLE
Preline throws error in production but works in dev mode with SvelteKit

### ISSUE THREAD

**Issue by Wizzel1** [htmlstreamofficial/preline#223]
I have followed the instructions to install preline for svelte ( https://preline.co/docs/frameworks-svelte.html ) but when I build and preview my app, preline throws an error: 

![Unbenannt](https://github.com/htmlstreamofficial/preline/assets/43343510/1fd49b7e-c57e-49ad-b6f7-7cfa9e09d5eb)

My tailwind config looks like this :

```ts
const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{html,js,svelte,ts}', './node_modules/preline/preline.js'],
	theme: {
		extend: {
			fontFamily: {
				sans: ['Noto Sans', ...defaultTheme.fontFamily.sans]
			}
		},
		minWidth: {
			'1/2': '50%'
		}
	},
	plugins: [require('preline/plugin')]
};
```
and I have added the preline script to my app.html like so:

```html
<script src="node_modules/preline/preline.js"></script>
```
For some reason this only happens in production. 

What is the problem here?

**Comment by jahaganiev** [comment]
Could you please try with `<script src="%sveltekit.assets%/preline/preline.js"></script>` and let us know If it works?

This workaround was shared on #110 by @digitaldrreamer

**Comment by Wizzel1** [comment]
@jahaganiev Yes it worked but I also had to create a folder in static as was said in this comment https://github.com/htmlstreamofficial/preline/issues/110#issuecomment-1652721951

**Comment by jahaganiev** [comment]
Awesome! We will add to docs this additional info.
