### ISSUE TITLE
Preline doesn't function at all in SPA and preline components which are rendered after page load don't work at all

### ISSUE THREAD

**Issue by mani-hash** [htmlstreamofficial/preline#224]
### Preline version
- v2.0.0

### Issue triggered via:
- Laravel 10.x and Livewire 3.x application (Triggered by navigating to page with **wire:navigate**)

### Similar problems in Discussion
- #162  
- #208  

### Issue explained

Preline components do not function at all when they are loaded in via **DOM manipulation**. This renders preline completely unusable when implementing in a **SPA (Single Page Application)** because preline doesn't know about the components!! 

### Steps to reproduce

- Install preline `npm install preline` and tailwind
- Link preline and tailwind to your index.html
- Select a simple component which has a JS functionality (Eg: dropdown button)
- Use javascript to implement a function to add the above component to the DOM manually (Eg: Through a button click)
- Reload page and click the button
- Now try clicking on the preline component. The preline component will not function!

### Temporary fix
- Refresh page
- Avoid using preline ui in SPA
- Avoid adding preline components via any sort of DOM manipulation

**Comment by olegpix** [comment]
> ### Preline version
> * v2.0.0
> 
> ### Issue triggered via:
> * Laravel 10.x and Livewire 3.x application (Triggered by navigating to page with **wire:navigate**)
> 
> ### Similar problems in Discussion
> * [Plugins stop working with SPA/Vue application #162](https://github.com/htmlstreamofficial/preline/discussions/162)
> * [Initialize preline JS components in a page displayed with ajax #208](https://github.com/htmlstreamofficial/preline/discussions/208)
> 
> ### Issue explained
> Preline components do not function at all when they are loaded in via **DOM manipulation**. This renders preline completely unusable when implementing in a **SPA (Single Page Application)** because preline doesn't know about the components!!
> 
> ### Steps to reproduce
> * Install preline `npm install preline` and tailwind
> * Link preline and tailwind to your index.html
> * Select a simple component which has a JS functionality (Eg: dropdown button)
> * Use javascript to implement a function to add the above component to the DOM manually (Eg: Through a button click)
> * Reload page and click the button
> * Now try clicking on the preline component. The preline component will not function!
> 
> ### Temporary fix
> * Refresh page
> * Avoid using preline ui in SPA
> * Avoid adding preline components via any sort of DOM manipulation

Hey,
You can use a static function to automatically reinitialize a component when you navigate to another page. In the Preline there is the following function for this ``window.HSStaticMethods.autoInit()``

I think this should help https://laracasts.com/discuss/channels/laravel/how-to-reload-the-js-plugin-after-comComponent-refresh-in-livewire you can call the ``autoInit`` function on some event. 

Sorry, I'm not an expert in Laravel and don't know all the events, but I think the principle is the same.

**Comment by alongninjya** [comment]
I have same problem. i add 

> > ### 预行版本
> > 
> > * v2.0.0
> > 
> > ### 问题通过以下方式触发：
> > 
> > * Laravel 10.x 和 Livewire 3.x 应用程序（通过使用**wire:navigate**导航到页面触发）
> > 
> > ### 讨论中的类似问题
> > 
> > * [插件停止与 SPA/Vue 应用程序一起使用 #162](https://github.com/htmlstreamofficial/preline/discussions/162)
> > * [在使用 ajax 显示的页面中初始化 preline JS 组件 #208](https://github.com/htmlstreamofficial/preline/discussions/208)
> > 
> > ### 问题解释
> > **Preline 组件在通过DOM 操作**加载时根本不起作用。**这使得 preline 在SPA（单页应用程序）**中实现时完全无法使用，因为 preline 不知道组件！
> > ### 重现步骤
> > 
> > * 安装前线`npm install preline`和顺风
> > * 将 preline 和 tailwind 链接到您的 index.html
> > * 选择一个具有 JS 功能的简单组件（例如：下拉按钮）
> > * 使用javascript实现手动将上述组件添加到DOM的功能（例如：通过单击按钮）
> > * 重新加载页面并单击按钮
> > * 现在尝试单击 preline 组件。前线组件将无法运行！
> > 
> > ### 临时修复
> > 
> > * 刷新页面
> > * 避免在 SPA 中使用 preline ui
> > * 避免通过任何类型的 DOM 操作添加预行组件
> 
> 嘿， 您可以使用静态函数在导航到另一个页面时自动重新初始化组件。在 Preline 中有以下函数：`window.HSStaticMethods.autoInit()`
> 
> 我认为这应该有帮助https://laracasts.com/discuss/channels/laravel/how-to-reload-the-js-plugin-after-comComponent-refresh-in-livewire您可以`autoInit`在某些事件上调用该函数。
> 
> 抱歉，我不是 Laravel 专家，不知道所有事件，但我认为原理是相同的。

Thank you very much。

i have same problem.  i add  this code to my `layout.vue.` it works very well。
```
import { onMounted } from 'vue';
import {HSCopyMarkup as HSStaticMethods} from "preline";

onMounted(() => {
  window.HSStaticMethods.autoInit()
});
```

**Comment by mani-hash** [comment]
Thank you. The `window.HSStaticMethods.autoInit()` works fine. 

By including the following in the main script, preline UI works fine with livewire's wire:navigate

```
document.addEventListener("livewire:navigated", ()=> {
    window.HSStaticMethods.autoInit();
});
```

**Comment by ShaungBhone** [comment]
When building the assets `npm run build`, that solution has not worked.!
