### ISSUE TITLE
Error when using Radix components together

### ISSUE THREAD

**Issue by luanfonsecap** [htmlstreamofficial/preline#226]
With the new instruction to start `HSStaticMethods`:
```js
const location = useLocation();

useEffect(() => {
    HSStaticMethods.autoInit();
  }, [location.pathname]);
```
Described here https://preline.co/docs/frameworks-react.html.

Using tabs component from Radix, application crash with error when reload the page.
![image](https://github.com/htmlstreamofficial/preline/assets/43269295/d8c92b70-bf23-43bf-b24c-ca271b7bcead)

Or when paste the tabs component radix code without reload the page, the [Carousel](https://preline.co/docs/carousel.html) component does not work inside a `Tabs.Content`. 
![image](https://github.com/htmlstreamofficial/preline/assets/43269295/7b32cdde-5d6a-4f37-b2c8-9d8048537290)

https://github.com/htmlstreamofficial/preline/assets/43269295/53d1e14a-675f-4c7f-9c82-4afbd3379d81

# Update
I have founded where is the problem, when starting `HSStaticMethods` and using Radix components that uses `role` attributes were also used by Preline on query selector's inside `autoInit` method, they found radix components when crash when execute some constructor logic.

The query for Preline tabs component to find them inside `auotInit` method  the expression used for query selection does not work as expected, even using the class "prevent-on-load-init", the element is found.

The correct expression should be: `[role="tablist"]:not(select):not(.prevent-on-load-init)`.

And i suggest to use another attribute to load Preline components on `autoInit` to not merge non Preline components to prevent errors like this, something like `[role="tablist"][data-preline]:not(select):not(.prevent-on-load-init)`.

**Comment by jahaganiev** [comment]
Hey @luanfonsecap - thanks for the details and the PR, I've just left a comment on the PR page. Unfortunately, we couldn't verify the issue from our side and for now we will close the issue and keep an eye for other reports. Thanks!
