### ISSUE TITLE
data-hs-select attribute disables onchange methods in Qwik framework

### ISSUE THREAD

**Issue by Bootstrap-Paradox** [htmlstreamofficial/preline#229]
# Description

if data-hs-select attribute is used on select, it disables onchange on the element as well as on listeners, so there's no way to track selected value in qwik.

## Guide
- Qwik -v 1.3.1
- Preline -v 2.0.2
- tailwindcss -v 3.3.6

**Comment by jahaganiev** [comment]
Hey @Bootstrap-Paradox - could you please try it out with the latest version of Preline? We had a bunch of improvements and new features on v2.0.3 update.

If you are still having an issue, please share a source code example on StackBlitz. You may fork ready to use Preline example from our StackBlitz examples.

Cheers!

**Comment by Bootstrap-Paradox** [comment]
Hey @jahaganiev, i did tried it with the latest version, but the bug still persists, it's like if the data-hs-select attribute is used on the select the onChange is never triggered, so to track the change on Select have to use an click event listener i.e useOn in qwik.

If the class hidden and data-hs-select attribute is removed it all works as intended

You could try it out here
https://stackblitz.com/edit/preline-v2-qwik-uj6exj?file=src%2Fcomponents%2Fselect-item%2Fselect-item.tsx
You can view the console for the change, it won't appear if the attribute is present 
Just make sure remove class "hidden"

**Comment by Desgue** [comment]
I am having the same issue. onChange works if i remove data-hs-select and class "hidden".

**Comment by Bootstrap-Paradox** [comment]
Hey @Desgue! Been quite a while, but does it still persist?
