### ISSUE TITLE
Initialize preline JS components in a page displayed with ajax

### ISSUE THREAD

**Issue by lethunder** [htmlstreamofficial/preline#231]
### Discussed in https://github.com/htmlstreamofficial/preline/discussions/208

<div type='discussions-op-text'>

<sup>Originally posted by **lethunder** December  9, 2023</sup>
Hello guys,
all preline js components like tabs inside a page i hide and show with ajax and append to DOM are no more working. How do i initialize preline in jquery on ajax:success

Exemple code
$(document).on('ajax:success', ".display-in-offcanvas-js", function (event) {

var detail = event.detail;

var data = detail[0].body.innerHTML, status = detail[1], xhr = detail[2];

$(".application-offcanvas-js .content").html(data);

});
 
data contains html with preline js components
</div>

**Comment by nocodelab** [comment]
Hi, did you solve this issue?

**Comment by lethunder** [comment]
hey,
nope

**Comment by jahaganiev** [comment]
Hey @lethunder - we've added an example here https://preline.co/docs/preline-javascript.html
