### ISSUE TITLE
3-grids with an Overlay Card Link Being Cut off from overflow-hidden

### ISSUE THREAD

**Issue by deronsizemore** [htmlstreamofficial/preline#234]
<img width="1366" alt="Screenshot 2023-12-30 at 2 51 06 PM" src="https://github.com/htmlstreamofficial/preline/assets/68437/b189c18d-f53f-4c7f-9d95-044aa0696812">

Was using the 3-grids with overlay card layout in a design and noticed that the "read more" link on hover wasn't completely underlined. It seems the overlow-hidden in the parent div is what's causing it. It also appears that same parent container has rounded-xl applied and I'm not sure why given there's no rounded corners on any container except the third one. Removing either rounded-xl or overlow-hidden from the two left-most containers fixes this "issue"

Is this by design or just a small oversight?

**Comment by Mr-Zafar** [comment]
Hi @deronsizemore,

Yep, that's a small oversight and removing `rounded-xl` with the `overlow-hidden` class fixes it. Thanks for the heads up! We also updated the live demo.

**Comment by deronsizemore** [comment]
Thanks so much for the response and quick fix!
