### ISSUE TITLE
Dropdown plugin doesn't work

### ISSUE THREAD

**Issue by fatherofinvention** [htmlstreamofficial/preline#235]
See the following JS Fiddle, which copies the HTML from the docs and includes Preline and the drop down plugin via CDN:

https://jsfiddle.net/tm7j3ouq/1/

**Comment by jahaganiev** [comment]
Preline works as a plugin on TailwindCSS and doesn't work via CDN like that. However, CDNs could be used on production sites.

**Comment by jahaganiev** [comment]
Yes, unfortunately in a development environment, Preline first should be installed as a plugin. However, for production, there's no issue as all the needed classes would've already been generated.

**Comment by jahaganiev** [comment]
Nope, we don't provide CSS files. You may consider using StackBlitz where you can install Preline and play around with it.
