### ISSUE TITLE
Is the Svelte setup guide still correct?

### ISSUE THREAD

**Issue by thelastfantasy** [htmlstreamofficial/preline#239]
https://preline.co/docs/frameworks-svelte.html

I mean the step 3 & step 4.
I cannot get what to copy from step 3.

![图片](https://github.com/htmlstreamofficial/preline/assets/6077584/a9cb1989-bf14-44ed-ae12-f9e3260deeb6)

**Comment by jahaganiev** [comment]
You may check out [this issue](https://github.com/htmlstreamofficial/preline/issues/110) discussed for more context.

Please feel free to open an issue with more details if you're having any.

Hope that helps!
