### ISSUE TITLE
ScrollSpy component has debug code which floods the console.

### ISSUE THREAD

**Issue by very-random-man** [htmlstreamofficial/preline#24]
There is a `console.log` inside the scrollspy component which generates a lot of console activity. I'm guessing it's debug code so I've raised a PR to fix it. :-)

https://github.com/htmlstreamofficial/preline/pull/23

**Comment by Mr-Zafar** [comment]
Hi, @very-random-man 

We appreciate you for providing details about the issue and your efforts toward resolving it. We've merged your commit and it's live now.

Thanks!
