### ISSUE TITLE
All input forms in sign up modal component do not have border 

### ISSUE THREAD

**Issue by michaelcozzolino** [htmlstreamofficial/preline#243]
![image](https://github.com/htmlstreamofficial/preline/assets/41123653/b49bb4be-77b4-49f6-9d8a-3f25d0870dc4)
in the code snippet on https://preline.co/examples/overlays-modals.html#content for the sign up component, every input is missing the class "border"

**Comment by jahaganiev** [comment]
Please note that Preline UI uses the [Tailwind CSS Forms](https://github.com/tailwindlabs/tailwindcss-forms) plugin in all form components. Don't forget to install it if you haven't done so already.

**Comment by michaelcozzolino** [comment]
i'm refferring to the inputs such as 
`<input type="email" id="email" name="email" class="py-3 px-4 block w-full border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600" required aria-describedby="email-error">
`
the right code must be 
` <input type="email" id="email" name="email" class="py-3 px-4 block w-full border border-gray-200 rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-gray-400 dark:focus:ring-gray-600" required aria-describedby="email-error">
` 
i added the border class.
