### ISSUE TITLE
[feature] Tag editor

### ISSUE THREAD

**Issue by gregmsanderson** [htmlstreamofficial/preline#245]
It would be nice to have a form text input that could act as a tag editor. Where you can type e.g _example_, press Enter/Return, and have it shown as a tag.

The _closest_ seems to be https://preline.co/docs/advanced-select.html#tags but that assumes pre-made values (a select).

I was thinking something like _this_ (I didn't write it):

https://codepen.io/atomgiant/pen/QWjWgKz

**Comment by olegpix** [comment]
> It would be nice to have a form text input that could act as a tag editor. Where you can type e.g _example_, press Enter/Return, and have it shown as a tag.
> 
> The _closest_ seems to be https://preline.co/docs/advanced-select.html#tags but that assumes pre-made values (a select).
> 
> I was thinking something like _this_ (I didn't write it):
> 
> https://codepen.io/atomgiant/pen/QWjWgKz

Thanks for the suggested improvements. We will definitely think about introducing them in future versions.

**Comment by RSchmitzHH** [comment]
> It would be nice to have a form text input that could act as a tag editor. Where you can type e.g _example_, press Enter/Return, and have it shown as a tag.
> 
> The _closest_ seems to be https://preline.co/docs/advanced-select.html#tags but that assumes pre-made values (a select).
> 
> I was thinking something like _this_ (I didn't write it):
> 
> https://codepen.io/atomgiant/pen/QWjWgKz

This would indeed be extremely cool!

**Comment by RSchmitzHH** [comment]
Is there something for this in Pro? Or planned to be introduced? 

Btw I have seen that, before the first item is selected, the advanced select actually has the desired behaviour. You can freely type anything and create a new tag. This is not anymore the case if a first tag is select, i.e., you cannot type anything not in the list of options then. 

So may it be possible to achieve this behaviour also if there is something selected?

**Comment by jahaganiev** [comment]
Hey @RSchmitzHH - yes, as @olegpix mentioned, it's on the roadmap.

Just a quick note, Preline Pro is built right on top of Preline UI. This means you won't miss out on any JS (JavaScript) components. Everything you see in Pro is also in the open-source Preline UI. We want to make sure developers get all the js features, no matter which version they pick.

Cheers!

**Comment by jahaganiev** [comment]
Hey folks, requested tags feature has been added with the new release v2.1.0 - https://preline.co/docs/advanced-select.html#tags

Cheers!
