### ISSUE TITLE
HSTabs.getInstance not working : Cannot read properties of null (reading 'on')

### ISSUE THREAD

**Issue by essamalsaloum** [htmlstreamofficial/preline#248]
```
		window.onload = function () {	
			const el = HSTabs.getInstance('#hs-tab-to-select-1' ,true);
			if(el) {
				el.on('change', ({ el, prev, current }) => {
					console.log('change ***********++++++', el, prev, current)
						
				});
			} else {
				console.log('el is null',el)
			}
	
		}
```

**Problem:** Encountering a null reference error when trying to use HSTabs.getInstance within window.onload. The variable el is expected to hold an instance but is consistently null, leading to issues when trying to access its properties or methods.

**Comment by olegpix** [comment]
> ```
> 		window.onload = function () {	
> 			const el = HSTabs.getInstance('#hs-tab-to-select-1' ,true);
> 			if(el) {
> 				el.on('change', ({ el, prev, current }) => {
> 					console.log('change ***********++++++', el, prev, current)
> 						
> 				});
> 			} else {
> 				console.log('el is null',el)
> 			}
> 	
> 		}
> ```
> 
> **Problem:** Encountering a null reference error when trying to use HSTabs.getInstance within window.onload. The variable el is expected to hold an instance but is consistently null, leading to issues when trying to access its properties or methods.

Hello,
Could you create an example and share it with us on Stacklblitz? We have not yet encountered such a problem during testing and use, perhaps this is a specific case.
Thank you in advance!

**Comment by essamalsaloum** [comment]
Sure! Here is the link. Thank you very much!

https://stackblitz.com/edit/stackblitz-starters-bzuiv3?file=index.html

**Comment by olegpix** [comment]
> Sure! Here is the link. Thank you very much!
> 
> https://stackblitz.com/edit/stackblitz-starters-bzuiv3?file=index.html

Thanks for the live link!
The problem is that you need to use a different selector, by default the plugin looks for all selectors ``[role="tablist"]:not(select):not(.--prevent-on-load-init)``, in your case, you need to use the ``[hs-data-tab-select="#tab-select"]`` selector when trying to get the instance.
You can check a working example [here](https://stackblitz.com/edit/stackblitz-starters-zsentv?file=index.html)

**Comment by essamalsaloum** [comment]
@olegpix 

Thanks for the rapid response this is awesome! But i think good to mention that on the documentation. Thanks for the help and have a great time.

**Comment by essamalsaloum** [comment]
Hello ,

This is not working any more is v2.4.0

https://stackblitz.com/edit/stackblitz-starters-bzuiv3?file=index.html

**Comment by olegpix** [comment]
@essamalsaloum Hi,
I think it is related to the Chrome update. We have released a hot-fix due to the Chrome update.
Please update to Preline 2.4.1 and if the error persists after updating Preline, please post here again.

**Comment by essamalsaloum** [comment]
Hi, @olegpix

I just updated it to version 2.4.1. It functions well with button elements, but it doesn't work with the select inputs when viewing on mobile and resizing the screen.

**Comment by olegpix** [comment]
@essamalsaloum You need to get an instance of tab, but you're trying to get an instance of select. Select doesn't have an `on` event.
Please, try this:
```
<script>
      window.onload = function () {
        const el = HSTabs.getInstance('[hs-data-tab-select="#tab-select"]');

        el.on('change', ({ el, prev, current }) => {
          alert('change ***********++++++', el, prev, current);
        });
      };
    </script>
```

**Comment by essamalsaloum** [comment]
@olegpix 
I've been using it as you mentioned for a long time, but after updating to v2.4.0 or v2.4.1, it's still not working. I have updated the example.

https://stackblitz.com/edit/stackblitz-starters-bzuiv3?file=index.html

**Comment by essamalsaloum** [comment]
@olegpix 
any suggestions

**Comment by essamalsaloum** [comment]
the issue is this `data-hs-tab-select="#tab-select"` in the older version was `hs-data-tab-select="#tab-select"`
So data Attribute for Tab Selection: Changed hs-data-tab-select to data-hs-tab-select. this is really hard to find. but it is working now @olegpix
