### ISSUE TITLE
Cannot find module 'preline/preline' or its corresponding type declarations. (Nextjs)

### ISSUE THREAD

**Issue by Nisthar** [htmlstreamofficial/preline#251]
I added `PrelineScript.tsx` into my components folder

components/PrelineScript.tsx:
```ts
"use client";

import { usePathname } from "next/navigation";
import { useEffect } from "react";

import { IStaticMethods } from "preline/preline";
declare global {
    interface Window {
        HSStaticMethods: IStaticMethods;
    }
}

export default function PrelineScript() {
    const path = usePathname();

    useEffect(() => {
        import("preline/preline");
    }, []);

    useEffect(() => {
        setTimeout(() => {
            window.HSStaticMethods.autoInit();
        }, 100);
    }, [path]);

    return null;
}
```

I am getting "Cannot find module 'preline/preline' or its corresponding type declarations."

**Comment by olegpix** [comment]
> I added `PrelineScript.tsx` into my components folder
> 
> components/PrelineScript.tsx:
> 
> ```ts
> "use client";
> 
> import { usePathname } from "next/navigation";
> import { useEffect } from "react";
> 
> import { IStaticMethods } from "preline/preline";
> declare global {
>     interface Window {
>         HSStaticMethods: IStaticMethods;
>     }
> }
> 
> export default function PrelineScript() {
>     const path = usePathname();
> 
>     useEffect(() => {
>         import("preline/preline");
>     }, []);
> 
>     useEffect(() => {
>         setTimeout(() => {
>             window.HSStaticMethods.autoInit();
>         }, 100);
>     }, [path]);
> 
>     return null;
> }
> ```
> 
> I am getting "Cannot find module 'preline/preline' or its corresponding type declarations."

The main reason I'm guessing this might be is that your webpack is configured incorrectly and for some reason it can't import a file without a .js extension, like ``import("preline/preline.js" )``.
Secondly, make sure Preline is installed in the root of your project to ``node_modules`` folder.
I just tested it locally with Next 14 and it works well...
I also checked NPM and ``preline.js`` is stored there.
We also have an example on [Codesandbox](https://codesandbox.io/p/devbox/preline-nextjs14-fyyztg), you can check it out too.
If all else fails, please create and share with us a Codesandbox example and we'll try to figure it out.

**Comment by Nisthar** [comment]
@olegpix Ok for some reason, `npm i preline` is installing an old version of preline. I manually installed the latest version specifying the version and its working.
