### ISSUE TITLE
Stacked Overlays issue on Example page

### ISSUE THREAD

**Issue by hieuhuynh93** [htmlstreamofficial/preline#253]
When I open the 2nd Modal, the 1st Modal is still on top of the 2nd Modal. I have to turn off the 1st Modal to see the 2nd Modal.
![Gsya4Pkx -2024-01-15 at 23 57 15](https://github.com/htmlstreamofficial/preline/assets/10773568/7183da1f-3486-4123-b1f1-b93e24ee5608)

**Comment by jagabs** [comment]
also how do i disable the close on esc for the 1st modal when 2nd modal is opened?
cos currently when i stack modals and press escaped it closes. 

```
const secondOverlay = HSOverlay.getInstance(
      document.querySelector('#second-overlay'),
      true
    );
 const element = (secondOverlay as any).element;
  element.isClosePrev = false;
  element.open();
```

**Comment by olegpix** [comment]
> When I open the 2nd Modal, the 1st Modal is still on top of the 2nd Modal. I have to turn off the 1st Modal to see the 2nd Modal. ![Gsya4Pkx -2024-01-15 at 23 57 15](https://private-user-images.githubusercontent.com/10773568/296821144-7183da1f-3486-4123-b1f1-b93e24ee5608.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTIxMzgsIm5iZiI6MTcwNjAxMTgzOCwicGF0aCI6Ii8xMDc3MzU2OC8yOTY4MjExNDQtNzE4M2RhMWYtMzQ4Ni00MTIzLWIxZjEtYjkzZTI0ZWU1NjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZDYxNDZkZTFiOTg2ZWUyZjYyMTE5YzhiYTAzNjU5ODA5NDEwMWI4OWZmZGY5ZjFjMzM2OWIwZjAwNzdlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SCc_tdPysQtIqloXNay3rbi7fcr215gCdTDk_a2IB-E) [ ![Gsya4Pkx -2024-01-15 at 23 57 15](https://private-user-images.githubusercontent.com/10773568/296821144-7183da1f-3486-4123-b1f1-b93e24ee5608.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTIxMzgsIm5iZiI6MTcwNjAxMTgzOCwicGF0aCI6Ii8xMDc3MzU2OC8yOTY4MjExNDQtNzE4M2RhMWYtMzQ4Ni00MTIzLWIxZjEtYjkzZTI0ZWU1NjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZDYxNDZkZTFiOTg2ZWUyZjYyMTE5YzhiYTAzNjU5ODA5NDEwMWI4OWZmZGY5ZjFjMzM2OWIwZjAwNzdlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SCc_tdPysQtIqloXNay3rbi7fcr215gCdTDk_a2IB-E) ](https://private-user-images.githubusercontent.com/10773568/296821144-7183da1f-3486-4123-b1f1-b93e24ee5608.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTIxMzgsIm5iZiI6MTcwNjAxMTgzOCwicGF0aCI6Ii8xMDc3MzU2OC8yOTY4MjExNDQtNzE4M2RhMWYtMzQ4Ni00MTIzLWIxZjEtYjkzZTI0ZWU1NjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZDYxNDZkZTFiOTg2ZWUyZjYyMTE5YzhiYTAzNjU5ODA5NDEwMWI4OWZmZGY5ZjFjMzM2OWIwZjAwNzdlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SCc_tdPysQtIqloXNay3rbi7fcr215gCdTDk_a2IB-E) [ ](https://private-user-images.githubusercontent.com/10773568/296821144-7183da1f-3486-4123-b1f1-b93e24ee5608.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTIxMzgsIm5iZiI6MTcwNjAxMTgzOCwicGF0aCI6Ii8xMDc3MzU2OC8yOTY4MjExNDQtNzE4M2RhMWYtMzQ4Ni00MTIzLWIxZjEtYjkzZTI0ZWU1NjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZDYxNDZkZTFiOTg2ZWUyZjYyMTE5YzhiYTAzNjU5ODA5NDEwMWI4OWZmZGY5ZjFjMzM2OWIwZjAwNzdlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SCc_tdPysQtIqloXNay3rbi7fcr215gCdTDk_a2IB-E)

The z-index of the first element was wrong, it should be 60, instead of 80. This will solve the problem

**Comment by jahaganiev** [comment]
Hey @hieuhuynh93 - it's been fixed, thanks for reporting!
