### ISSUE TITLE
Cannot read properties of undefined (reading 'autoInit')

### ISSUE THREAD

**Issue by Slddev** [htmlstreamofficial/preline#256]
<img width="693" alt="image" src="https://github.com/htmlstreamofficial/preline/assets/74999267/94ef2aee-e63e-4ce0-b669-92270105cd32">

**Comment by ollebergkvist** [comment]
Also seeing this

**Comment by luguanhui** [comment]
Also seeing this

**Comment by jordankimsey** [comment]
I'm facing the same issue.

**Comment by VishalLudhrani** [comment]
I see many of us are getting confused by `HSStaticMethods`.
It's just a way of saying that you need to import HS<method-name> (eg.: HSAccordion) and call `autoInit` on its instance.

Here's the `PrelineLoader.jsx` from one of my (Next.js) projects:
```jsx
"use client";

import HSAccordion from "@preline/accordion";
import { usePathname } from "next/navigation";
import { HSDropdown } from "preline/preline";
import { useEffect } from "react";

export default function PrelineLoader() {
  const path = usePathname();

  useEffect(() => {
    import("preline/preline");
  }, []);

  useEffect(() => {
    setTimeout(() => {
      HSAccordion.autoInit();
      HSDropdown.autoInit();
    }, 100)
  }, [path])

  return <></>
}
```

I hope this helps. :)

**Comment by Wigglor** [comment]
@VishalLudhrani So do I need to add HSDropdown instance if I want to ad the dropdown components? I'm still not getting them to work.

**Comment by MeromTh** [comment]
Try setTimeout to 200?

**Comment by olegpix** [comment]
> <img alt="image" width="693" src="https://private-user-images.githubusercontent.com/74999267/299954577-94ef2aee-e63e-4ce0-b669-92270105cd32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzc3OTcsIm5iZiI6MTcwOTEzNzQ5NywicGF0aCI6Ii83NDk5OTI2Ny8yOTk5NTQ1NzctOTRlZjJhZWUtZTYzZS00Y2UwLWI2NjktOTIyNzAxMDVjZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2MjQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZmYxYTVmYjIxZjdiNDNlZWJlZDgzNzFmMDhkYWExYzNlMmMxYzFiMmRiMDlmOTk0Mzc2ODMzZWEwMGFhODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lOGpBqv6opFY9czQHbIG4Xn5Z75iCcylDhO5kFrIszc">

Hi!
Please check out the official documentation here [Preline - Next.js](https://preline.co/docs/frameworks-nextjs.html)
You should add the following code to prevent TS warnings:
```
import { IStaticMethods } from "preline/preline";
declare global {
  interface Window {
    HSStaticMethods: IStaticMethods;
  }
}
```

**Comment by VishalLudhrani** [comment]
> @VishalLudhrani So do I need to add HSDropdown instance if I want to ad the dropdown components? I'm still not getting them to work.

Yup. That is how it worked for me.

If you weren't able to get those to work, here's an alternative approach:

```jsx
"use client";

import { usePathname } from "next/navigation";
import { useEffect } from "react";

const isBrowser = typeof window !== undefined;

export default function PrelineLoader() {
  const path = usePathname();

  useEffect(() => {
    if (isBrowser) {
      // if this component is rendered on a browser, import preline
      import("preline/preline");
    }
  }, [])

  useEffect(() => {
    setTimeout(() => {
      if (isBrowser) {
        // if this component is rendered on a browser, import relevant preline plugins
        import("preline/preline").then(({ HSAccordion, HSDropdown, HSCollapse }) => {
          HSAccordion.autoInit();
          HSDropdown.autoInit();
          HSCollapse.autoInit();
        })
      }
    }, 100)
  }, [path])

  return <></>
}
```

@Wigglor

**Comment by insivika** [comment]
> I see many of us are getting confused by `HSStaticMethods`. It's just a way of saying that you need to import HS (eg.: HSAccordion) and call `autoInit` on its instance.
> 
> Here's the `PrelineLoader.jsx` from one of my (Next.js) projects:
> 
> ```js
> "use client";
> 
> import HSAccordion from "@preline/accordion";
> import { usePathname } from "next/navigation";
> import { HSDropdown } from "preline/preline";
> import { useEffect } from "react";
> 
> export default function PrelineLoader() {
>   const path = usePathname();
> 
>   useEffect(() => {
>     import("preline/preline");
>   }, []);
> 
>   useEffect(() => {
>     setTimeout(() => {
>       HSAccordion.autoInit();
>       HSDropdown.autoInit();
>     }, 100)
>   }, [path])
> 
>   return <></>
> }
> ```
> 
> I hope this helps. :)

Hi can you please explain how `HSAccordion` is related to `HSStaticMethods`?

**Comment by VishalLudhrani** [comment]
@insivika `HSStaticMethods` could be a placeholder (just a way to say your plugin would go here).
You would need to replace it with all the plugins you're using in your project.

So, in my case, I replaced it with `HSAccordion` and `HSDropdown` since I was using both.

**Comment by Nishitbaria** [comment]
> > I see many of us are getting confused by `HSStaticMethods`. It's just a way of saying that you need to import HS (eg.: HSAccordion) and call `autoInit` on its instance.
> > Here's the `PrelineLoader.jsx` from one of my (Next.js) projects:
> > ```js
> > "use client";
> > 
> > import HSAccordion from "@preline/accordion";
> > import { usePathname } from "next/navigation";
> > import { HSDropdown } from "preline/preline";
> > import { useEffect } from "react";
> > 
> > export default function PrelineLoader() {
> >   const path = usePathname();
> > 
> >   useEffect(() => {
> >     import("preline/preline");
> >   }, []);
> > 
> >   useEffect(() => {
> >     setTimeout(() => {
> >       HSAccordion.autoInit();
> >       HSDropdown.autoInit();
> >     }, 100)
> >   }, [path])
> > 
> >   return <></>
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope this helps. :)
> 
> Hi can you please explain how `HSAccordion` is related to `HSStaticMethods`?

This Code is work for me ✨

**Comment by jahaganiev** [comment]
Hey folks, seems the issue has been addressed by the community. We've also added Preline JavaScript page with some explanation how Preline JavaScript works.

https://preline.co/docs/preline-javascript.html

Cheers!
