### ISSUE TITLE
node_modules/preline/dist/preline.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by juanulis3s** [htmlstreamofficial/preline#260]
I am not using any JS framework. The step 3 in installation is:

Add the Preline UI JavaScript 
`// index.html<script src="./node_modules/preline/dist/preline.js"></script>`

I do not think it it is the best practice to upload a node_modules folder. I tried applying a script similar to Tailwindcss sugggestions:

```
{
  "name": "project",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "tailwindcss -i ./src/input.css -o ./assets/css/style.css",
    "watch": "tailwindcss -i ./src/input.css -o ./assets/css/style.css && ./node_modules/preline/dist/preline.js -o ./assets/js/preline.js --watch"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "tailwindcss": "^3.3.3"
  },
  "dependencies": {
    "@builder.io/partytown": "^0.8.1",
    "preline": "^2.0.3"
  }
}

```

But npm wont let me and gave me an error 
```
./node_modules/preline/dist/preline.js: line 1: syntax error near unexpected token `t,e'
```

What is the best way to copy this file to a dist folder without uploading the node_modules folder?

This is my tailwing config:
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    'node_modules/preline/dist/*.js',
  ],
  darkMode: 'class',
  plugins: [
    require('preline/plugin'),
  ],
}
```

**Comment by jahaganiev** [comment]
Hey @juanulis3s! You can download the source files from GitHub and link them as you prefer. For instance:

`<script src="./assets/vendor/preline/dist/preline.js"></script>
`

The way you organize your file structure is entirely up to you. While we don't prescribe a 'best' method, we believe the approach above is commonly used.

Hope that helps!
