### ISSUE TITLE
 Enhance Functionality and Responsiveness of Preline Date Picker (Consider MUI Inspiration)

### ISSUE THREAD

**Issue by mohamedahmed-cloud** [htmlstreamofficial/preline#264]
I'm currently encountering issues with the functionality and responsiveness of the Preline Date Picker. It doesn't behave as expected in several ways, hindering my user experience.

**Comment by jahaganiev** [comment]
At the moment, Preline doesn't include JS functionality, and it's stated on the Datapicker docs page.

Could you please share more details about the responsive issue?

Thanks!

**Comment by mohamedahmed-cloud** [comment]
![image](https://github.com/htmlstreamofficial/preline/assets/81932663/b50dec48-fc55-487b-a61e-5d5708bd9c1f)

- The date picker component looks distorted and doesn't adapt well to different screen sizes in the picture.

**Comment by jahaganiev** [comment]
We don't see in our live demos similar issues. If you find any, please share a link with the screenshots and our team will look into it.
