### ISSUE TITLE
Application sidebar's backdrop element not being removed/hidden after resizing screen size from lg size to md/sm size

### ISSUE THREAD

**Issue by MarkCay** [htmlstreamofficial/preline#267]
I just tried Preline today and it was great, until I encountered an issue. The application sidebar's backdrop element is not being removed after resizing screen size from lg size to md/sm size.

### How to reproduce?
1. Visit https://preline.co/examples/html/application-layout-sidebar.html
2. Resize your screen to md size (https://tailwindcss.com/docs/screens)
3. Click the menu icon
4. Resize your screen to lg size or higher (https://tailwindcss.com/docs/screens)

Now after completing these steps, you can now reproduce the application sidebar's backdrop element that cannot be toggled to close. For now, I temporarily used JavaScript to remove the element.

**Comment by MarkCay** [comment]
Here's a screen recording that also demonstrates how the issue can be reproduced.

![ezgif-2-570b251800](https://github.com/htmlstreamofficial/preline/assets/44314383/60706b0b-bcbf-4378-9729-a337df9eae41)

(As you can see, the only way to remove/hide the backdrop (without altering the code) is to click the backdrop and then click an accordion item.)

**Comment by olegpix** [comment]
> Here's a screen recording that also demonstrates how the issue can be reproduced.
> 
> ![ezgif-2-570b251800](https://private-user-images.githubusercontent.com/44314383/302634879-60706b0b-bcbf-4378-9729-a337df9eae41.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzgyOTcsIm5iZiI6MTcwOTEzNzk5NywicGF0aCI6Ii80NDMxNDM4My8zMDI2MzQ4NzktNjA3MDZiMGItYmNiZi00Mzc4LTk3MjktYTMzN2RmOWVhZTQxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2Nzc1YjI3ZjMzMzY1OTcxMTE3Njc0NTBjMTcwNjlkYjQwNTY0ZTZkMzc0YjVlNDhmOWJkMzc0MGNmYTliOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Be-cRdodKV9KIgq_qB9ZicbBsaheaNWCRQLXqLzj-0o) [ ![ezgif-2-570b251800](https://private-user-images.githubusercontent.com/44314383/302634879-60706b0b-bcbf-4378-9729-a337df9eae41.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzgyOTcsIm5iZiI6MTcwOTEzNzk5NywicGF0aCI6Ii80NDMxNDM4My8zMDI2MzQ4NzktNjA3MDZiMGItYmNiZi00Mzc4LTk3MjktYTMzN2RmOWVhZTQxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2Nzc1YjI3ZjMzMzY1OTcxMTE3Njc0NTBjMTcwNjlkYjQwNTY0ZTZkMzc0YjVlNDhmOWJkMzc0MGNmYTliOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Be-cRdodKV9KIgq_qB9ZicbBsaheaNWCRQLXqLzj-0o) ](https://private-user-images.githubusercontent.com/44314383/302634879-60706b0b-bcbf-4378-9729-a337df9eae41.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzgyOTcsIm5iZiI6MTcwOTEzNzk5NywicGF0aCI6Ii80NDMxNDM4My8zMDI2MzQ4NzktNjA3MDZiMGItYmNiZi00Mzc4LTk3MjktYTMzN2RmOWVhZTQxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2Nzc1YjI3ZjMzMzY1OTcxMTE3Njc0NTBjMTcwNjlkYjQwNTY0ZTZkMzc0YjVlNDhmOWJkMzc0MGNmYTliOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Be-cRdodKV9KIgq_qB9ZicbBsaheaNWCRQLXqLzj-0o) [ ](https://private-user-images.githubusercontent.com/44314383/302634879-60706b0b-bcbf-4378-9729-a337df9eae41.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzgyOTcsIm5iZiI6MTcwOTEzNzk5NywicGF0aCI6Ii80NDMxNDM4My8zMDI2MzQ4NzktNjA3MDZiMGItYmNiZi00Mzc4LTk3MjktYTMzN2RmOWVhZTQxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2Nzc1YjI3ZjMzMzY1OTcxMTE3Njc0NTBjMTcwNjlkYjQwNTY0ZTZkMzc0YjVlNDhmOWJkMzc0MGNmYTliOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Be-cRdodKV9KIgq_qB9ZicbBsaheaNWCRQLXqLzj-0o)
> 
> (As you can see, the only way to remove/hide the backdrop (without altering the code) is to click the backdrop and then click an accordion item.)

Hi! This issue will be solved in the next update.

**Comment by jahaganiev** [comment]
Hey @MarkCay - just to update you, the issue has been fixed. Thanks!

**Comment by MarkCay** [comment]
Hi @jahaganiev , thanks for the update!
