### ISSUE TITLE
Error when dynamically adding items to the advanced select with search

### ISSUE THREAD

**Issue by userlip** [htmlstreamofficial/preline#268]
I am dynamically adding and removing items to the select based on what is being typed into the search field, since I have so many options it lags otherwise if I load them all at once.

This is the code I am using:

           `
          var select = window.HSSelect.getInstance(document.getElementById('channel-select'));

            // Count the number of options in the dropdown
            var optionsCount = document.getElementById('channel-select').length;

            // Remove all the options including the first one
            select.removeOption(Array.from({
                length: optionsCount
            }, (_, i) => i));

            // Add the first option
            select.addOption({
                title: "All Channels",
                val: "ALL"
            });

            // Add the search results to the dropdown
            channelSearchResults.forEach(function(channel) {
                select.addOption({
                    title: channel.name,
                    val: channel.id
                });
            });
`
            
            
 And it all works but when I select an item this error shows up:

<img width="530" alt="image" src="https://github.com/htmlstreamofficial/preline/assets/19856578/8ab79db1-d642-4c9a-ad79-94bc9b1cf0eb">

**Comment by AronVanBroekhuijsen** [comment]
I also get this error when i addOption a new value, but it works when i add multiple="" to the select.
Any one who can help?
