### ISSUE TITLE
Rendering issue of toogle button and drop-down list 

### ISSUE THREAD

**Issue by upaingsoethu** [htmlstreamofficial/preline#272]
Hello, Today I am created vite with react js and  preline ui  project.I am using JSX file.Then installation step by step documation guide.My home component page in Navbar.jsx component and Dashboard component page in Sidebar.jsx  components.These Navbar and Sidebar components in  preline ui components of code copy and paste.Then running localhost my app.Preline ui is working and beautifully of home page is appearing.Then go to  Dashboard Page.Then clicked menu dropdown list.But it  is't  response.Then  Browser in refresh this sidebar page.And then menu drop-down list clicked.This time menu dropdown list is working.Then go to  home page clicked and screen resized.Navbar toogle button is paper on right corner of screen.Then clicked this toogle button.But it is't working.Then browser refresh home page and toogle button is working.I am reading  framework installation guide of react in recommend tsx and app.tsx in useEffect hook for rendering preline ui.I am not using typescript.I think ever rendering problem is this state of my react app.jsx.Are you sure this state of my problem?How to do App.jsx in useEffect hook for preline ui? Please help me explain and reference tutorial link.Thank you.

**Comment by olegpix** [comment]
> Hello, Today I am created vite with react js and preline ui project.I am using JSX file.Then installation step by step documation guide.My home component page in Navbar.jsx component and Dashboard component page in Sidebar.jsx components.These Navbar and Sidebar components in preline ui components of code copy and paste.Then running localhost my app.Preline ui is working and beautifully of home page is appearing.Then go to Dashboard Page.Then clicked menu dropdown list.But it is't response.Then Browser in refresh this sidebar page.And then menu drop-down list clicked.This time menu dropdown list is working.Then go to home page clicked and screen resized.Navbar toogle button is paper on right corner of screen.Then clicked this toogle button.But it is't working.Then browser refresh home page and toogle button is working.I am reading framework installation guide of react in recommend tsx and app.tsx in useEffect hook for rendering preline ui.I am not using typescript.I think ever rendering problem is this state of my react app.jsx.Are you sure this state of my problem?How to do App.jsx in useEffect hook for preline ui? Please help me explain and reference tutorial link.Thank you.

Hi!
Please check the example we provided in the official documentation [Stackblitz - React](https://stackblitz.com/edit/preline-v2-react-react-router?file=tailwind.config.js), or upload your code to the Stackblitz or similar service.

**Comment by Vacilando** [comment]
Same issue!

**Comment by zadiki** [comment]
I had the same issue and fixed it by changing the  tailwind config file to
/** @type {import('tailwindcss').Config} */
import preline from "preline/plugin"; // take not of this
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/preline/dist/*.js",
  ],
  theme: {
    extend: {},
  },
  plugins: [preline], take not of this
};
