### ISSUE TITLE
Unnecessary console.log calls for the dropdown plugin

### ISSUE THREAD

**Issue by gregmsanderson** [htmlstreamofficial/preline#273]
Hello,

I noticed that each time I interact with the dropdown plugin https://preline.co/plugins/html/dropdown.html, the up/down key is logged to the console. I don't think it's needed for accessibility, so is this simply left from debugging?

Can that line be removed?

```
Key code: ArrowDown
```

![Screenshot 2024-02-08 at 17 22 16](https://github.com/htmlstreamofficial/preline/assets/10390169/c1d3d9d1-2712-41c6-a604-f5b452018b6f)

**Comment by olegpix** [comment]
> Hello,
> 
> I noticed that each time I interact with the dropdown plugin https://preline.co/plugins/html/dropdown.html, the up/down key is logged to the console. I don't think it's needed for accessibility, so is this simply left from debugging?
> 
> Can that line be removed?
> 
> ```
> Key code: ArrowDown
> ```
> 
> ![Screenshot 2024-02-08 at 17 22 16](https://private-user-images.githubusercontent.com/10390169/303426737-c1d3d9d1-2712-41c6-a604-f5b452018b6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzgzNjAsIm5iZiI6MTcwOTEzODA2MCwicGF0aCI6Ii8xMDM5MDE2OS8zMDM0MjY3MzctYzFkM2Q5ZDEtMjcxMi00MWM2LWE2MDQtZjViNDUyMDE4YjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2MzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyOTg1MDkzNDYwMTlkNTMyZmMxMzI5MmJmYzJkNGNhYTU5ZDFjN2ZhODY0ZTAxOGVkYjRjMjE2N2JhYjViNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qn3oMP3ueocwxtP23HTIBfvX5PgpEKGxzY3vvjMY4Xw)

Thank you! We’ll remove unnecessary `console.logs` in the next update.

**Comment by jahaganiev** [comment]
Hey @gregmsanderson - the issue has been fixed. Thanks!
