### ISSUE TITLE
When using the toaster example in a laravel 10 app, the dismiss functionality does not work

### ISSUE THREAD

**Issue by ejjaquet** [htmlstreamofficial/preline#275]
Hi!

I am loving the Preline components! I am using the pro version and implementing a Toaster functionality in a Laravel 10 app, using Livewire3 and Alpine. I have followed the integration guide with Laravel and other components like the drawer are working fine. I am having an issue with the dismiss functionality for the alert in the toaster. I am using the example from the site, but for some reason I cant remove the alert (dismiss) when I click on the cross.

It is on the same page as the drawer, so maybe there is an issue with the two working together?

Hope you can help.

Erik-Jan

**Comment by olegpix** [comment]
> Hi!
> 
> I am loving the Preline components! I am using the pro version and implementing a Toaster functionality in a Laravel 10 app, using Livewire3 and Alpine. I have followed the integration guide with Laravel and other components like the drawer are working fine. I am having an issue with the dismiss functionality for the alert in the toaster. I am using the example from the site, but for some reason I cant remove the alert (dismiss) when I click on the cross.
> 
> It is on the same page as the drawer, so maybe there is an issue with the two working together?
> 
> Hope you can help.
> 
> Erik-Jan

Hi! Thank you for your high assessment of our work.
Could you please provide the markup that is causing the problem? I am sure that the problem here is the nesting of components and it is unlikely to be related to a specific stack.

**Comment by jahaganiev** [comment]
Hey @ejjaquet - closing the issue due to inactivity. If will have any bugs, please feel free to open a new issue with more details.
