### ISSUE TITLE
Dropdowns not working after page refresh 

### ISSUE THREAD

**Issue by Wigglor** [htmlstreamofficial/preline#278]
I have a React application and the [dropdowns](https://preline.co/pro/examples/dropdowns.html), selects etc stop working after I have refreshed the page. They do however work after I navigate to a page where those components exist. It is only after a browser refresh that this issue occurs for me. Any idea of why this is the case?

**Comment by samnj** [comment]
Same here. Had to downgrade to 1.9.0 and it works just fine

**Comment by olegpix** [comment]
> I have a React application and the [dropdowns](https://preline.co/pro/examples/dropdowns.html), selects etc stop working after I have refreshed the page. They do however work after I navigate to a page where those components exist. It is only after a browser refresh that this issue occurs for me. Any idea of why this is the case?

Hi!
Please check the solution provided here https://github.com/htmlstreamofficial/preline/issues/286 issue by [MuriloAkita](https://github.com/MuriloAkita)

**Comment by Wigglor** [comment]
Yes, any solutions for React and Next?

**Comment by matiaspunx** [comment]
Hello! any solutions for Astro and ViewTransition? 

Its working fine if I hard refresh the page, navigate between pages make dropdown stop working :(
