### ISSUE TITLE
pin input plugin not working in nuxt 3.10.1 (tailwind 3.4.1) unless HSStaticMethods.autoInit is called multiple times 

### ISSUE THREAD

**Issue by kindlychung** [htmlstreamofficial/preline#279]
Here is my workaround:

```js
import 'preline/preline';

declare var HSStaticMethods: {
    autoInit(collection?: string | string[]): void;
};

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.hook('page:finish', () => {
            setInterval(() => {
                HSStaticMethods.autoInit();
            }, 1000);
    });
});
```

**Comment by olegpix** [comment]
> Here is my workaround:
> 
> ```js
> import 'preline/preline';
> 
> declare var HSStaticMethods: {
>     autoInit(collection?: string | string[]): void;
> };
> 
> export default defineNuxtPlugin((nuxtApp) => {
>     nuxtApp.hook('page:finish', () => {
>             setInterval(() => {
>                 HSStaticMethods.autoInit();
>             }, 1000);
>     });
> });
> ```

Hi!
Please also provide the markup, or better yet, upload an example to Stackblitz or a similar service.
