### ISSUE TITLE
Is TS support planned ?

### ISSUE THREAD

**Issue by nicolasey** [htmlstreamofficial/preline#28]
Hello there ^^

Is TypeScript support planned ?
Do you require help doing so (if yes) ?
In that case, what do you expect from me / us ?

**Comment by jahaganiev** [comment]
Hello @nicolasey,

Currently, no plans but if there will be enough demand we will definitely consider. 

And yes, we'd appreciate any help offered - especially on the testing stage in future.

Thanks!

**Comment by BWBama85** [comment]
Would love TS support as well.

**Comment by frasza** [comment]
Yeah absolutely would love TS support.

**Comment by jahaganiev** [comment]
Thanks for the feedback! We've added TypeScript to our roadmap.

**Comment by sbertoeth** [comment]
So far, just make a types folder at root level, then declare the module "preline" like this 

`declare module 'preline';`

And name this file **preline.d.ts**

Now you can import preline in TypeScript projects :)

**Comment by jahaganiev** [comment]
Hey folks,

TypeScript is live! 

Please feel free to share your thoughts and feedback.

Cheers!
