### ISSUE TITLE
[Stacked overlays] Window scroll is re-enabled when the top overlay is closed irrespective of Bottom overlay.

### ISSUE THREAD

**Issue by naagas-syft** [htmlstreamofficial/preline#281]
## Background
We are using stacked overlays. (Modal over Modal). 
We disable body-scroll when modal is shown. using `--body-scroll:false`. This disables body scroll when the modal is opened. 
https://github.com/htmlstreamofficial/preline/blob/main/src/plugins/overlay/index.ts#L207

When modal is closed we reset the body scroll behavior. (as shown here: 
https://github.com/htmlstreamofficial/preline/blob/main/src/plugins/overlay/index.ts#L262). 

## Bug
The closing modal should respect the configuration needed by the bottom Modal.

**Comment by olegpix** [comment]
> ## Background
> We are using stacked overlays. (Modal over Modal). We disable body-scroll when modal is shown. using `--body-scroll:false`. This disables body scroll when the modal is opened. https://github.com/htmlstreamofficial/preline/blob/main/src/plugins/overlay/index.ts#L207
> 
> When modal is closed we reset the body scroll behavior. (as shown here: https://github.com/htmlstreamofficial/preline/blob/main/src/plugins/overlay/index.ts#L262).
> 
> ## Bug
> The closing modal should respect the configuration needed by the bottom Modal.

Thanks for noticing! We will fix this in the next update.

**Comment by jahaganiev** [comment]
Hey @naagas-syft - thanks for reporting the issue. We've just pushed the fixes in the v2.1.0 update. Thanks!
