### ISSUE TITLE
Tabs don't always work in Angular

### ISSUE THREAD

**Issue by rl-carno** [htmlstreamofficial/preline#283]
When conditionally rendering a set of tabs they don't always work, its random.

If i refresh the view, sometimes the tabs work sometimes they don't they just do nothing when clicked. Feels like an async or initialisation issue.

As it stands i've had to revert to using angular state to mimic tabs. Really frustrating. Please fix.

**Comment by olegpix** [comment]
> When conditionally rendering a set of tabs they don't always work, its random.
> 
> If i refresh the view, sometimes the tabs work sometimes they don't they just do nothing when clicked. Feels like an async or initialisation issue.
> 
> As it stands i've had to revert to using angular state to mimic tabs. Really frustrating. Please fix.

Hi!
Please use `HSStaticMethods.autoInit();` whenever you change the page or in cases where an element has been removed from the page and added to the page again. Preline is not a framework library (React, Vue, Angular), it is a set of plugins for customizing the view.
