### ISSUE TITLE
How can "Advanced Select" work with dynamic data in Angular?

### ISSUE THREAD

**Issue by GitHubish** [htmlstreamofficial/preline#284]
I don't see how to make Advanced Select work in the Angular framework if I want the selectable options to be dynamic (they come from the API). Is this possible? I'm looking for a combobox component with Tailwind that works with Angular

**Comment by Splinteer** [comment]
Same probem for me. Edited the official demo to log change event on the select element but the function is never called:
https://stackblitz.com/edit/preline-v2-angular-vomd3k?file=src%2Fapp%2Fcomponents%2Fselect-item%2Fselect-item.component.ts

**Comment by jahaganiev** [comment]
Hey folks,

Our team couldn't very the issue internally. We've added a new Preline JavaScript page with some explanation how Preline JavaScript works: https://preline.co/docs/preline-javascript.html

If you are believe the plugin has bugs, please feel free to open a new issue with step by step details to reproduce the issue with some error screenshots etc.

Cheers!
