### ISSUE TITLE
Tabbing input inside modal

### ISSUE THREAD

**Issue by roiLeo** [htmlstreamofficial/preline#288]
random focus when tabbing inside modal

Check for example: https://preline.co/examples/overlays-modals.html#modal-signup

It works well on doc/Iframe, but when coppied into app it doesn't behave the same way.
I suspect there may be a link with backdrop content.

**Comment by roiLeo** [comment]
related with #249, works when using `[--tab-accessibility-limited:false]`

**Comment by robertmerten** [comment]
Hey,

is this now supposed to work without setting `[--tab-accessibility-limited:false]`?

For me it still only works with the workaround.
