### ISSUE TITLE
Modal component : static backdrop not working

### ISSUE THREAD

**Issue by Abdourrahman** [htmlstreamofficial/preline#29]
When I set the backdrop to static and click outside the modal it closes the modal
`data-hs-overlay-backdrop="static"`

**Comment by jahaganiev** [comment]
Thanks for the bug report, we'll fix with the upcoming update.

**Comment by Mr-Zafar** [comment]
Hi, @Abdourrahman -

We've fixed it! See [Modal Static Backdrop](https://preline.co/docs/modal.html#static-backdrop)

Thanks!

**Comment by xysun** [comment]
Hello, in this [example](https://preline.co/plugins/html/overlay.html) on overlay doc page, it does not set `--overlay-backdrop:static` in the classes, yet it does not close when clicking outside of the modal. Am I missing something?

**Comment by Mr-Zafar** [comment]
Hi @xysun,

Thanks for the heads up!

Here's a complete code of that example with the fix.

<pre>
<code>
&lt;button type=&quot;button&quot; class=&quot;py-3 px-4 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-white dark:hover:bg-gray-800 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600&quot; data-hs-overlay=&quot;#hs-basic-modal&quot;&gt;
  Open modal
&lt;/button&gt;

&lt;div id=&quot;hs-basic-modal&quot; class=&quot;hs-overlay hidden w-full h-full fixed top-0 start-0 z-[60] overflow-x-hidden overflow-y-auto pointer-events-none&quot;&gt;
  &lt;div class=&quot;hs-overlay-open:opacity-100 hs-overlay-open:duration-500 opacity-0 transition-all sm:max-w-lg sm:w-full m-3 sm:mx-auto&quot;&gt;
    &lt;div class=&quot;flex flex-col bg-white border shadow-sm rounded-xl pointer-events-auto dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]&quot;&gt;
      &lt;div class=&quot;flex justify-between items-center py-3 px-4 border-b dark:border-gray-700&quot;&gt;
        &lt;h3 class=&quot;font-bold text-gray-800 dark:text-white&quot;&gt;
          Modal title
        &lt;/h3&gt;
        &lt;button type=&quot;button&quot; class=&quot;flex justify-center items-center w-7 h-7 text-sm font-semibold rounded-full border border-transparent text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none dark:text-white dark:hover:bg-gray-700 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600&quot; data-hs-overlay=&quot;#hs-basic-modal&quot;&gt;
          &lt;span class=&quot;sr-only&quot;&gt;Close&lt;/span&gt;
          &lt;svg class=&quot;flex-shrink-0 w-4 h-4&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;24&quot; height=&quot;24&quot; viewBox=&quot;0 0 24 24&quot; fill=&quot;none&quot; stroke=&quot;currentColor&quot; stroke-width=&quot;2&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;&gt;&lt;path d=&quot;M18 6 6 18&quot;/&gt;&lt;path d=&quot;m6 6 12 12&quot;/&gt;&lt;/svg&gt;
        &lt;/button&gt;
      &lt;/div&gt;
      &lt;div class=&quot;p-4 overflow-y-auto&quot;&gt;
        &lt;p class=&quot;mt-1 text-gray-800 dark:text-gray-400&quot;&gt;
          This is a wider card with supporting text below as a natural lead-in to additional content.
        &lt;/p&gt;
      &lt;/div&gt;
      &lt;div class=&quot;flex justify-end items-center gap-x-2 py-3 px-4 border-t dark:border-gray-700&quot;&gt;
        &lt;button type=&quot;button&quot; class=&quot;py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:bg-slate-900 dark:border-gray-700 dark:text-white dark:hover:bg-gray-800 dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600&quot; data-hs-overlay=&quot;#hs-basic-modal&quot;&gt;
          Close
        &lt;/button&gt;
        &lt;a class=&quot;py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1 dark:focus:ring-gray-600&quot; href=&quot;#&quot;&gt;
          Save changes
        &lt;/a&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
</code>
</pre>

Where it was missing two `pointer-events-none` and `pointer-events-auto` classes

<pre>
<code>
&lt;div id=&quot;hs-basic-modal&quot; class=&quot;hs-overlay ... pointer-events-none&quot;&gt;
  &lt;div class=&quot;hs-overlay-open:&quot;&gt;
    &lt;div class=&quot;... pointer-events-auto ...&quot;&gt;
      ...
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
</code>
</pre>

**Comment by xysun** [comment]
Thank you!
