### ISSUE TITLE
Dropdown stops working after navigation in SPA

### ISSUE THREAD

**Issue by stescacom** [htmlstreamofficial/preline#291]
I have noticed using livewire 3 with preline. the dropdown stop working after navigation. 

Lets assume we have 2 top level navigation

1. Dashboard `<a href="..." wire:navigate>Dashboard</a>`
2. Dropdown Menu (preline code)
2.1 Nav 1 `<a href="..." wire:navigate>Nav 1</a>`
...

When the page changes the dropdown will not show. It will only show if you refresh the whole page.

**Comment by MuriloAkita** [comment]
Try adding this in `app.js`:
```js
document.addEventListener("livewire:navigating", () => {
    HSStaticMethods.autoInit();
});

document.addEventListener("livewire:navigated", () => {
    HSStaticMethods.autoInit();
});
```
