### ISSUE TITLE
accordion stops working when { important: true}  is declared

### ISSUE THREAD

**Issue by ssjogus** [htmlstreamofficial/preline#293]
Hi

i am using v2.0.0. The plugins like tooltip, accordion work well. but they stop when I try to use the !Important modifier of tailwind. So when I am writing this in tailwind.config file, the preline plugins stop working. Can you please help?

module.exports = {
  **important: true,**
  content: [
    'node_modules/preline/dist/*.js',
    '*.{html,js,css}',
  ],
  theme: {
    extend: {},
  },
  plugins: [
    // require('@tailwindcss/forms'),
      require('preline/plugin'),
  ],
}

**Comment by jahaganiev** [comment]
Hey, please try out with with the latest version. Thanks!
