### ISSUE TITLE
Preline Ui doesn't work with SPA in Qwik

### ISSUE THREAD

**Issue by Bootstrap-Paradox** [htmlstreamofficial/preline#295]
When using spa navigation using <Link/≥ in the qwik preline does not track events. I'll upload a video of the bug, on navigation no functionality works, but if page is refreshed it works as intended.

i had downloaded this code from -> https://stackblitz.com/edit/preline-v2-qwik-eeekju?file=src%2Fglobal.css
it works fine on stackblitz but as i downloaded it to my machine it bugs out.

The video link
https://github.com/htmlstreamofficial/preline/assets/53016712/b3232bd9-3354-4403-964f-06e124d72a55

**Comment by LazyClicks** [comment]
issue is related to preline docs for qwik not being correct and missing important pieces
first is how to import preline script in a correct way
inside root.tsx
```
import PrelineUI from "../node_modules/preline/preline.js?raw";
\\
\\
\\
 <script dangerouslySetInnerHTML={PrelineUI as string} />
```

and then inside layout.tsx or inside the routes that need preline.js
```
import type { IStaticMethods } from "preline/preline";

declare global {
  interface Window {
    HSStaticMethods: IStaticMethods;
  }
}```
```
  useVisibleTask$(() => {
    window.HSStaticMethods.autoInit();
  });```

im more than happy to make a pr for the docs for qwik if the preline team is okey with that
if not just giving me the page which contains the specific qwik docs and ill update it correctly

**Comment by jahaganiev** [comment]
@LazyClicks thanks for sharing the workaround! We've added a backlink in our [docs](https://preline.co/docs/frameworks-qwik.html) for this solution. Cheers!

**Comment by LazyClicks** [comment]
> @LazyClicks thanks for sharing the workaround! We've added a backlink in our [docs](https://preline.co/docs/frameworks-qwik.html) for this solution. Cheers!

is it possible to change the qwik docs or mention that this workaround is required to get preline js to work with qwik on production apps?

**Comment by LazyClicks** [comment]
it's back to not working :(

**Comment by jahaganiev** [comment]
Hey @LazyClicks - could you please describe the issue?

**Comment by LazyClicks** [comment]
> Hey @LazyClicks - could you please describe the issue?

Yeah, anything that requires preline JavaScript seems to not work anymore now, drop down or side bars for example , if I click on them nothing would happen and the component would show it's stuck in the clicked state visually, no errors in console tho

**Comment by jahaganiev** [comment]
Preline v3.0 is built on Tailwind v4. To use Preline v3 or later, you'll need to update your project to Tailwind v4 first.

**Comment by LazyClicks** [comment]
> Preline v3.0 is built on Tailwind v4. To use Preline v3 or later, you'll need to update your project to Tailwind v4 first.

im trying it here on a new qwik project using tailwind v4

**Comment by jahaganiev** [comment]
Qwik with Tailwind v4 guides not out yet as we've stated on the docs page. You may check out the [default](https://preline.co/docs/index.html) installation guide and follow Step 2 in your project.

**Comment by jahaganiev** [comment]
@LazyClicks alternatively you may check out some of the just updated framework guides e.g. [Vue](https://preline.co/docs/frameworks-vuejs.html) - they all share similar changes for the Step 2 in general.

**Comment by LazyClicks** [comment]
> Qwik with Tailwind v4 guides not out yet as we've stated on the docs page. You may check out the [default](https://preline.co/docs/index.html) installation guide and follow Step 2 in your project.

okay so the problem was the change in the location of the index.js file that needs to be ran from node-modules folder
btw seems the navbar examples are broken in preline v3
while trying to see if v2.7.0 works i noticed that

**Comment by LazyClicks** [comment]
> [@LazyClicks](https://github.com/LazyClicks) alternatively you may check out some of the just updated framework guides e.g. [Vue](https://preline.co/docs/frameworks-vuejs.html) - they all share similar changes for the Step 2 in general.

ill find a clean way for the qwik guide with preline v3, rn im trying to figure out how to get it to work when using qwik spa routing, because when using spa routing preline components that rely on the autoInit stop working

**Comment by jahaganiev** [comment]
Preline v3.0.1 is just released which includes the fix for the navbar dropdown. If you are referring to different issue, could you please share more details?

**Comment by LazyClicks** [comment]
yeah it was for that navbar drop down
also i've found a solution for qwik to work with preline 3.0
it's also a better solution than the one i had before (speaking in terms of performance)
how can i share it with you?

**Comment by jahaganiev** [comment]
Great, that would be helpful - you may just share here the steps, github supports full markdown.

**Comment by LazyClicks** [comment]
**npm run qwik add tailwind**
**npm i -D preline**


**global.css**
`
@import "tailwindcss";

@import "preline/variants.css";
`


**root.tsx file**
`
import PrelineUI from "../node_modules/preline/dist/index.js?raw";
//
//
<body>
<script dangerouslySetInnerHTML={PrelineUI} />
</body>
`


**layout.tsx file**
`
import type { IStaticMethods } from "preline/preline";
//this should be on top of the export default component$
declare global {
  interface Window {
    HSStaticMethods: IStaticMethods;
  }
}

//
//

export default component$(() => {
  const location = useLocation();
// we use useTask$ here instead of useVisibleTask$ as useTask$ does not run eagerly, and since we only need to run the autoInit() // on navigation, useTask$ would be better performance wise as it only runs on navigation
// we achieve this using qwik's useLocation(), with it we can track changes to the 'location.url' variable and whenever it changes 
// the task would execute 
  useTask$(({track}) => {
    track(() => location.url);
// we use isServer here to prevent the task from executing in the server as tasks run atleast once but there's no 'window' in server
    if (isServer) return;
    window.HSStaticMethods.autoInit();
  });
  return <Slot />;

`

**Comment by LazyClicks** [comment]
> Great, that would be helpful - you may just share here the steps, github supports full markdown.

there you go!

**Comment by jahaganiev** [comment]
Thanks a lot, this will be definitely helpful - our team will review in details and update the docs.
