### ISSUE TITLE
Does this free version can use in next.js with interactive ui??

### ISSUE THREAD

**Issue by emaduddin678** [htmlstreamofficial/preline#297]
![image](https://github.com/htmlstreamofficial/preline/assets/97534952/494c158d-36ce-4f47-be63-889cb3861383)

I am facing problem with interactive. I use default navbar html and change into jsx. is it possible to make this interactive?

**Comment by jahaganiev** [comment]
You may check our docs here https://preline.co/docs/frameworks-nextjs.html
