### ISSUE TITLE
i.current is undefined when setTimeout to load HSStaticMethods.autoInit();

### ISSUE THREAD

**Issue by DevChrisVaz** [htmlstreamofficial/preline#298]
![Captura de pantalla 2024-03-06 183841](https://github.com/htmlstreamofficial/preline/assets/120761095/73592b0d-cb82-44fa-8ac5-53ea404a8616)

**Comment by jahaganiev** [comment]
Not enough information. Please read our [framework guides](https://preline.co/docs/frameworks.html) docs. Thanks!
