### ISSUE TITLE
Overlay Component Issues : public method & events not working

### ISSUE THREAD

**Issue by ajaypatelaj** [htmlstreamofficial/preline#299]
Hi @jahaganiev,

Thanks for creating such a wonderful library for TailwindCSS World.

We were eager to start our project with PrelineJS, but unfortunately, we're facing some issues with methods, events, and options as per the documentation.

Here is the example code link: https://stackblitz.com/edit/stackblitz-starters-efdd17?file=js%2Fmodal.js

### Common
1. The first doubt us was, **we whether should use `data-hs-overlay="#hs-basic-modal"` while using the JS Method** to open and close the modal.
As per your JS, we realize that the plugin finds the modal id from `data-hs-overlay="#hs-basic-modal"`, according to that it becomes mandatory to use `data-hs-overlay="#hs-basic-modal"` even you are using JS open method.

![image](https://github.com/htmlstreamofficial/preline/assets/749684/4ba2102b-bd07-4b8b-8bff-6a92f44f8040)

### Methods 
1. Open item (public method) expecting modal as per the documentation, and it didn't work.

![image](https://github.com/htmlstreamofficial/preline/assets/749684/58f47333-e8c0-4bd0-b0e7-7804c89eb654)

Then we tried using the button element node and it worked.

```js
const openBtn = new HSOverlay(document.querySelector('#open-btn'));
openBtn.open();
```
2. Open item (static method) working as it should but again we have to use the attribute with button `data-hs-overlay="#hs-basic-modal"` which makes no purpose for using this method as it can also work by default with `data-hs-overlay="#hs-basic-modal"`.
3. Open item (mixed) worked and the conclusion could be the same as point no 3.

### Events 
1. The events code doesn't seem working as per the docs

![image](https://github.com/htmlstreamofficial/preline/assets/749684/9c0f327c-bb31-415a-ac94-16b89a4eca29)

Then we tried this (getting instances as per the mixed method) and it seems to work. 

Finally, this worked for us.

```js
window.onload = function (e) {
const el = HSOverlay.getInstance('#hs-basic-modal', true).element;
  el.on('open', (instance) => {
    console.log('open-event', instance);
  });
  el.on('close', (instance) => {
    console.log('close-event', instance);
  });
};
```

But we don't know why we have to wrap it with a `window.onload` method as using `document.addEventListener('DOMContentLoaded', () => {});` create an error like

`Uncaught TypeError: Cannot read properties of undefined (reading 'find')`

**Also, we're facing almost similar issues with other components like collapsible, accordion, and dropdown as per the documentation.**

Could you please let us know if are we using this method or event in the wrong way? Or something we need to improve in PrelineJS docs?

Cheers~

**Comment by olegpix** [comment]
> Hi @jahaganiev,
> 
> Thanks for creating such a wonderful library for TailwindCSS World.
> 
> We were eager to start our project with PrelineJS, but unfortunately, we're facing some issues with methods, events, and options as per the documentation.
> 
> Here is the example code link: https://stackblitz.com/edit/stackblitz-starters-efdd17?file=js%2Fmodal.js
> 
> ### Common
> 1. The first doubt us was, **we whether should use `data-hs-overlay="#hs-basic-modal"` while using the JS Method** to open and close the modal.
>    As per your JS, we realize that the plugin finds the modal id from `data-hs-overlay="#hs-basic-modal"`, according to that it becomes mandatory to use `data-hs-overlay="#hs-basic-modal"` even you are using JS open method.
> 
> ![image](https://private-user-images.githubusercontent.com/749684/311239417-4ba2102b-bd07-4b8b-8bff-6a92f44f8040.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjYxMTksIm5iZiI6MTcxMTAyNTgxOSwicGF0aCI6Ii83NDk2ODQvMzExMjM5NDE3LTRiYTIxMDJiLWJkMDctNGI4Yi04YmZmLTZhOTJmNDRmODA0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQxMjU2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDNjNmU5MjY4Nzc2ODc2MTYwNTFjMjk3OWEwMDQ4NjgyYjg5NzlhNmYxZmE0NzQ1MWQ1ZDIxNDhjZWI0NjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DAZ5UTzh-pHznGHrRXGwxqVboJIlj8z9WR0uX4Cp2JQ)
> 
> ### Methods
> 1. Open item (public method) expecting modal as per the documentation, and it didn't work.
> 
> ![image](https://private-user-images.githubusercontent.com/749684/311241914-58f47333-e8c0-4bd0-b0e7-7804c89eb654.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjYxMTksIm5iZiI6MTcxMTAyNTgxOSwicGF0aCI6Ii83NDk2ODQvMzExMjQxOTE0LTU4ZjQ3MzMzLWU4YzAtNGJkMC1iMGU3LTc4MDRjODllYjY1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQxMjU2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGI5YWRiNTNmOTQ2ZjY5YWM1ZmM0Y2I3NGIwZjZmY2U3NzQyOWEwYWIyZjdjZWZhZDM5MzRhYzZkMjllZTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0psFOr5fPs5HX1LU_AdxMS5jrwY-ucLdSBPECURGGUw)
> 
> Then we tried using the button element node and it worked.
> 
> ```js
> const openBtn = new HSOverlay(document.querySelector('#open-btn'));
> openBtn.open();
> ```
> 
>  2. Open item (static method) working as it should but again we have to use the attribute with button `data-hs-overlay="#hs-basic-modal"` which makes no purpose for using this method as it can also work by default with `data-hs-overlay="#hs-basic-modal"`.
> 3. Open item (mixed) worked and the conclusion could be the same as point no 3.
> 
> ### Events
> 1. The events code doesn't seem working as per the docs
> 
> ![image](https://private-user-images.githubusercontent.com/749684/311243225-9c0f327c-bb31-415a-ac94-16b89a4eca29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjYxMTksIm5iZiI6MTcxMTAyNTgxOSwicGF0aCI6Ii83NDk2ODQvMzExMjQzMjI1LTljMGYzMjdjLWJiMzEtNDE1YS1hYzk0LTE2Yjg5YTRlY2EyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQxMjU2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjZlOGU5MWE3MTdlM2VkNzUyYWUyODU1MGIzZDYyZjczYWFmMDNiOTlmYmYxYmY4YTBiYTBjNGYwOGY4YTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1yQYhIB9eFPR99VYTfVkdEzMEa2YTnpOHpD2dLXKQRI)
> 
> Then we tried this (getting instances as per the mixed method) and it seems to work.
> 
> Finally, this worked for us.
> 
> ```js
> window.onload = function (e) {
> const el = HSOverlay.getInstance('#hs-basic-modal', true).element;
>   el.on('open', (instance) => {
>     console.log('open-event', instance);
>   });
>   el.on('close', (instance) => {
>     console.log('close-event', instance);
>   });
> };
> ```
> 
> But we don't know why we have to wrap it with a `window.onload` method as using `document.addEventListener('DOMContentLoaded', () => {});` create an error like
> 
> `Uncaught TypeError: Cannot read properties of undefined (reading 'find')`
> 
> **Also, we're facing almost similar issues with other components like collapsible, accordion, and dropdown as per the documentation.**
> 
> Could you please let us know if are we using this method or event in the wrong way? Or something we need to improve in PrelineJS docs?
> 
> Cheers~

Hi,
All elements that are initialized automatically, through initialization by class name, inside the plugin occur precisely according to the `load` event. Thus, when you try to manipulate an element in the `DOMContentLoaded` event, the initialized elements are not yet available for manipulation. 

If you want to manipulate elements in the `DOMContentLoaded` event, first exclude it from automatic initialization by adding the `--prevent-on-load-init` class. And then initialize it for any event you need, like this:

```
document.addEventListener(‘DOMContentLoaded’, () => {
    document.querySelectorAll(‘.hs-dropdown.-prevent-on-load-init’).forEach((el) => new HSDropdown(el));
});
```
