### ISSUE TITLE
may I ask how to install for nuxt3?

### ISSUE THREAD

**Issue by yashika** [htmlstreamofficial/preline#3]
Thank you

**Comment by green-cats** [comment]
Hey, @yashika!

You may try out these steps to achieve it:

1) Create preline.client.js in plugins directory

2) Add JavaScript insisde preline.client.js

import preline from 'preline/dist/hs-ui.bundle'
export default defineNuxtPlugin(() => {})

3) Include the preline plugin in tailwind.config.js in plugins array
plugins: [
  require('preline/plugin')
]

Done! Please, let us know if the above steps worked out for you.

Thanks!

**Comment by yashika** [comment]
> Hey, @yashika!
> 
> You may try out these steps to achieve it:
> 
> 1. Create preline.client.js in plugins directory
> 2. Add JavaScript insisde preline.client.js
> 
> import preline from 'preline/dist/hs-ui.bundle' export default defineNuxtPlugin(() => {})
> 
> 3. Include the preline plugin in tailwind.config.js in plugins array
>    plugins: [
>    require('preline/plugin')
>    ]
> 
> Done! Please, let us know if the above steps worked out for you.
> 
> Thanks!

-------

Thank you so much.
![QQ截图20220614134615](https://user-images.githubusercontent.com/199247/173502570-4b49dce8-bb7d-47da-8574-6f4776adceb0.jpg)


It works well in ' yarn dev' mode. but I got below warnning message after I ran "yarn build" , please check it.
