### ISSUE TITLE
Closing the modal

### ISSUE THREAD

**Issue by frasza** [htmlstreamofficial/preline#30]
Hello,

First of all, thank you for great library. I am using it with Vue 3 and TS and so far it works well.
I have usecase I don't know how to solve. Basically I would like to navigate from view with open modal to another view but I have to close the modal before navigation (otherwise backdrop stays). I did check the docs (https://preline.co/plugins/html/modal.html#js-methods) but I feel like I don't understand docs enough to implement programmatic closing of the modal.
How can I close the modal with Vue method on button click?

**Comment by jahaganiev** [comment]
Hey @frasza - Closing this issue for the moment. Once you've got a test link with the source code, please feel free to open a new issue. Thanks!
