### ISSUE TITLE
Issue: Some JavaScript behavior options are not functioning correctly, and there is a lack of precise documentation regarding their usage

### ISSUE THREAD

**Issue by SHVM-09** [htmlstreamofficial/preline#300]
While working on my project using Preline and TailwindCSS, I encountered an issue with certain JavaScript behavior options for my modal, which utilizes the overlay plugin in Preline.

I meticulously tested each JS behavior option from [here](https://preline.co/plugins/html/overlay.html#js-behavior), but I observed that some worked flawlessly while others did not. The reasons for their malfunction could be attributed to the following:

1. Incorrect syntax or incorrect placement of option classes.
2. Possible bugs in the implementation from your end.
3. Missing implementation steps in the documentation.

I have provided a demo project where I have listed the JS options I tried, indicating which ones worked and which ones did not.

To replicate the issue, please download the zip file, run npm install, and then execute npm run watch for continuous Tailwind CSS watch. You can open the HTML file using the Live Server extension in VS Code.

[js-options.zip](https://drive.google.com/drive/folders/1LBSO36CS6_Wmonxi7ATb51g32JxVGDci?usp=sharing)

Here's a breakdown of my findings:

**Working Options (Functioning Properly):**

1. data-hs-overlay
2. isClosePrev
3. autofocus
4. [--overlay-backdrop:*]
5. [--auto-hide:*]
6. hs-overlay-open
7. hs-overlay-backdrop-open

**Working but Exhibiting Strange Behavior:**

1. [--tab-accessibility-limited:*]
2. data-hs-overlay-backdrop-container

**Not Working or Exhibiting Unknown Behavior:**

1. hiddenClass
2. backdropClasses
3. data-hs-overlay-keyboard
4. [--body-scroll:*]
5. [--has-autofocus:*]
6. hs-overlay-toggle (I couldn't find any documentation on this in your repository.)

I would greatly appreciate it if you could provide guidelines on how to use these options that are not working correctly or behaving strangely. This guidance would immensely assist me in advancing my project.

Any assistance you can provide would be highly valued.

**Comment by SHVM-09** [comment]
After additional attempts, I managed to utilize several options in the modal overlay component and comprehend their functionality. However, there are three options that remained unclear to me:

**1. data-hs-overlay-backdrop-container
2. data-hs-overlay-keyboard
3. hs-overlay-toggle (This term appears to be absent from the entire repository.)**

I would greatly appreciate your guidance on how to properly use these options, as they are either not functioning as expected or behaving inconsistently. Your assistance in clarifying these matters would be invaluable in progressing with my project.

Thank you for any support you can offer.

**Comment by olegpix** [comment]
@SHVM-09 Hi,
Could you describe the strange behavior you noticed for `[--tab-accessibility-limited:*]` please.

**Comment by olegpix** [comment]
@SHVM-09 `[--has-autofocus:*]`
I checked it. As I see it works fine. Please describe the problems you noticed. Because I don't see any problems at the moment.
`hs-overlay-toggle` is just an old thing, thanks for noticing! We will close the ticket at this time. Please describe the problem you are experiencing in detail and reopen your request.
Thank you in advance!

https://github.com/htmlstreamofficial/preline/assets/20664129/9cf8009b-d152-47ff-82d1-233ce5e02829

**Comment by SHVM-09** [comment]
> After additional attempts, I managed to utilize several options in the modal overlay component and comprehend their functionality. However, there are three options that remained unclear to me:
> 
1. data-hs-overlay-backdrop-container 
2. data-hs-overlay-keyboard 
4. hs-overlay-toggle (This term appears to be absent from the entire repository.)**
> 
> I would greatly appreciate your guidance on how to properly use these options, as they are either not functioning as expected or behaving inconsistently. Your assistance in clarifying these matters would be invaluable in progressing with my project.
> 
> Thank you for any support you can offer.

Hi @olegpix,

Thank you for your response. However, it seems you may have missed a message from me where I mentioned that everything worked later on. I encountered issues with only three of the options. Could you please confirm the functionality and usage of these specific options?

**Comment by SHVM-09** [comment]
> @SHVM-09 `[--has-autofocus:*]` I checked it. As I see it works fine. Please describe the problems you noticed. Because I don't see any problems at the moment. `hs-overlay-toggle` is just an old thing, thanks for noticing! We will close the ticket at this time. Please describe the problem you are experiencing in detail and reopen your request. Thank you in advance!
> 
>  _01.1.mp4

Cant view this video!

**Comment by SHVM-09** [comment]
> @SHVM-09 Hi, Could you describe the strange behavior you noticed for `[--tab-accessibility-limited:*]` please.

This works fine now after the update!!
