### ISSUE TITLE
Instructions for Selecting an Option in HSSelect

### ISSUE THREAD

**Issue by wallacecorreafontes** [htmlstreamofficial/preline#302]
I wanted to share a solution I recently found for selecting a specific option in an HSSelect dropdown when there was no information available in the official documentation.

Recently, I came across the need to select a specific option in an HSSelect dropdown based on a predefined value. After scouring the documentation and searching the repository, I realized there were no explicit instructions for this functionality.

After a bit of trial and error, I managed to find a solution that worked perfectly for my case. Here is the code snippet I used:

```
const {
    element: Select
} = HSSelect.getInstance('#HSSelect', true);

// current_selected_id is the ID of the desired option to be selected

// Find the desired option element by its data-value attribute
const desiredOption = Select.dropdown.querySelector(`[data-value="${current_selected_id}"]`);

// If the desired option element is found, simulate a click event to select it
if (desiredOption) {
    desiredOption.click();
} else {
    // Log an error message if the desired option is not found
    console.error('The desired option was not found.');
}
```

This solution allowed me to select an option in the HSSelect dropdown based on a specific value, even in the absence of formal instructions or examples.

I hope this tip helps other developers who may be facing similar issues and looking for guidance on how to programmatically select options

**Comment by jahaganiev** [comment]
Hey @wallacecorreafontes - may I ask why ask why default "selected" value hasn't worked out?

**Comment by wallacecorreafontes** [comment]
@jahaganiev 
Hey whats up.
So, the data was filled in based on the api, to give a better context, I have 3 selects, where each one has a predefinition (Ids) and based on these ids I searched the apis, and after that I selected those items, I tried anyway using `selected` but I was not successful, so after researching a lot, analyzing the code, I successfully reached this result using the example mentioned above.
