### ISSUE TITLE
 Documentation needs improvements regarding JS options & methods , with some options not working or lacking information!

### ISSUE THREAD

**Issue by SHVM-09** [htmlstreamofficial/preline#303]
Hello @jahaganiev,

I've previously contacted you via email regarding inconsistencies in the documentation and insufficient details on JS options. To improve the experience for all users of this outstanding library, I've compiled a list of issues concerning the documentation and JS options. Could you kindly verify the accuracy of these issues or let me know if there's anything I might have overlooked or misunderstood in the documentation, or perhaps if the documentation itself is incorrect?

I've utilized all available options and methods in three plugins (dropdown, overlay, and select) so far, and while the majority of options in them worked well, there are a few that didn't function properly or may have been misinterpreted by me.

Regarding the non-working JS options:

**Overlay options:**
1. data-hs-overlay-backdrop-container
2. data-hs-overlay-keyboard
3. hs-overlay-toggle (This term appears to be absent from the entire repository.)

**Select options:**
1. isAddTagOnEnter
2. descriptionClasses
3. iconClasses

Additionally, Are points 2 and 3 for data-hs-select-option, as shown within the following code snippet:

```
data-hs-select-option='{
    "description": "desc_some",
    "icon": "icon_url"
}'
```

**Dropdown options:**
1. data-hs-dropdown-transition (unclear where to provide this option and its functionality)

<hr>

### Documentation Issues

**Overlay Plugin Docs**

- Public method

The public method functions correctly, but it assigns events to the triggering button instead of the modal (overlay component). This discrepancy is evident in the documentation where the modal's ID is displayed, but it should be the ID of the button.

![Screenshot 2024-03-14 at 3 30 26 PM](https://github.com/themeselection/sneat-tailwindcss/assets/110282392/ef7d87e9-205b-46ea-bd57-0d7d6fccde38)

Moreover, a larger question arises: Should event methods be linked with the modal (overlay) rather than the trigger, as they are in static and mixed methods? Additionally, why is the `data-hs-overlay="#hs-basic-modal"` attribute necessary for the button? Its absence renders JavaScript functionality ineffective.

- Static & Mixed method, Events

Static and mixed methods work as described in the documentation, with window load and events functioning properly.

<hr>

**Dropdown Plugin Docs**

- Public, Static Methods

In contrast to the public method in the overlay component, the instance is correctly targeted in the dropdown, as indicated in the documentation. However, there's a discrepancy where the 'show' method is displayed instead of the 'open' method.

![Screenshot 2024-03-14 at 4 55 56 PM](https://github.com/themeselection/sneat-tailwindcss/assets/110282392/b8b68e6a-664a-4292-a8d2-5da9178caed1)

<hr>

**Select Plugin Docs** 

- Public, Static Methods

Unlike the public method in the overlay component, the instance is targeted correctly in the select, as indicated in the documentation (to select). However, there's an error in the documentation regarding the presence of the open method in the static method section. The open method is only available as a public method, whereas the `close` or `closeCurrentlyOpened` method should be listed instead.

![Screenshot 2024-03-14 at 5 16 16 PM](https://github.com/themeselection/sneat-tailwindcss/assets/110282392/02a2b314-d00b-4c43-bd93-9d6fb0a69e46)

I appreciate your attention to these matters and look forward to your feedback.

**Comment by jordan-orionfinity** [comment]
> Moreover, a larger question arises: Should event methods be linked with the modal (overlay) rather than the trigger, as they are in static and mixed methods? Additionally, why is the data-hs-overlay="#hs-basic-modal" attribute necessary for the button? Its absence renders JavaScript functionality ineffective.

@SHVM-09 I agree with the comment about the overlay plugin event methods linking to the physical overlay rather than the button. I have had a lot of trouble trying to get this working purely based off working on the overlay docs page. 

It wasn't until I dug into the preline JS `HSOverlay` code constructor and noticed that the line of code `this.overlayId = this.el.getAttribute('data-hs-overlay');` is actually looking for the button as this is what the docs say to do. My problem is that I don't want my buttons coupled to an overlay as I want to call them ad-hoc from code hence why I am writing my own JS to open and close the overlay.

For now I have had to add the `data-hs-overlay="#myid"` to my actual overlay element to get this working because as I mentioned above. I don't want to couple my button with an overlay element.

Thank you for this comment though as this pointed me in the right direction to get this working 😄

**Comment by jahaganiev** [comment]
Hey @SHVM-09 - you may check out issue [#300](https://github.com/htmlstreamofficial/preline/issues/300) for more details and examples as some of the above comments (overlay options) duplicated there.

The plugins might not cover all 100% use cases for everyone and designed in a way to support TailwindCSS in first place.

Cheers!
