### ISSUE TITLE
Steps on number input

### ISSUE THREAD

**Issue by ahl-asg** [htmlstreamofficial/preline#304]
Is there no way to configure the steps on the number input ? 
It looks like it is hardcoded to only allow 1 increment up or down. And it can't go negative.

Can this be configured to set the step, and allow negative numbers ?

**Comment by jahaganiev** [comment]
Hey @ahl-asg - steps feature has been added in v2.1.0 update. Thanks!

https://preline.co/docs/input-number.html#step-controls
