### ISSUE TITLE
Scrolling bug in the Scrollspy plugin in Chrome

### ISSUE THREAD

**Issue by idiked** [htmlstreamofficial/preline#307]
It often requires 2 clicks for the scroll to work.
The bug is reproduced when scrolling with the mouse (not Apple Magic Mouse).
If you use the keyboard's page up/down, the browser's scrollbar, or scroll with the touchpad, then scrolling works normally.

Mac OS: 14.3.1 (23D60)
Chrome: 122.0.6261.129 (arm64)

Tested on 2 macbooks with 2 different mouses

https://github.com/htmlstreamofficial/preline/assets/8687191/4172d4a8-5668-4cae-baed-a47b879bbe5f

**Comment by jahaganiev** [comment]
Thanks for sharing the video but unfortunately, we could't reproduce the issue.
