### ISSUE TITLE
Vertically centered modals don't work

### ISSUE THREAD

**Issue by pmax42** [htmlstreamofficial/preline#309]
I'm trying to use vertically centered modals but they don't work.

I've noticed that the `pointer-events-auto` class is missing from the third div of each modal. This isn't the case on the demo versions on Preline website, so I think it's a simple oversight.

I don't know if the problem is here, but when I add this class, the modals work correctly.

Note : I tried to illustrate the problem with a CodePen but I didn't make it (maybe some Tailwind configuration issues).

**Comment by jahaganiev** [comment]
Live example is working: https://preline.co/docs/modal.html#vertically-centered

<img width="1709" alt="image" src="https://github.com/htmlstreamofficial/preline/assets/5040828/83ab0eb4-baaa-4f94-96ab-327a678e60e7">

**Comment by jahaganiev** [comment]
Noted, will be updated in upcoming v2.1 update soon - thanks for sharing the details!
