### ISSUE TITLE
Modal backdrop z-index

### ISSUE THREAD

**Issue by frasza** [htmlstreamofficial/preline#31]
Hi,

In the app I am working on I utilized example of Application layout (https://preline.co/examples/layouts-application.html#application-layout-sidebar-and-header) so I can make use of collapsible sidebar on mobile view.

I am facing issues when I am using modal. 
As far as I understand the issue it is because sidebar has its own backdrop with z-50 so the sidebar itself has z-[60] class attached. Because of that, whenever I open the modal which also has z-50 for backdrop by default, it doesn't cover the sidebar.

Result:
![image](https://user-images.githubusercontent.com/22049682/206850500-3c2860e9-9f9f-4cd9-b89d-5960709bce71.png)

I played around configuring z-index classes but I believe I can not set z-index for backdrops and get around the issue.
Any ideas? Thanks!

**Comment by cody-baras** [comment]
We are facing same issue as of yesterday when we implemented the library into the ecosystem. Hopefully can be resolved soon, @jahaganiev ?

**Comment by Mr-Zafar** [comment]
@frasza @cody-baras Here's a working example just in case: https://preline.co/examples/html/application-layout-sidebar-and-header-with-modal.html
