### ISSUE TITLE
layout shift due to removal of scroll bar in browser

### ISSUE THREAD

**Issue by ilsyaa** [htmlstreamofficial/preline#310]
this happens when you open the modal and remove the scrollbar.

I got a reference from
https://adminlte.io/themes/v3/pages/UI/modals.html 
when the modal is opened, the body will be given some padding according to the size of the scrollbar and make it better

**Comment by ilsyaa** [comment]
https://github.com/twbs/bootstrap/blob/main/js/src/util/scrollbar.js

**Comment by jahaganiev** [comment]
irrelevant to Preline UI

**Comment by ile** [comment]
Is this really irrelevant to Preline UI, @jahaganiev?

For example, if the `overflow` is not set to `hidden` on `body`, the scrollbar will not disappear and the layout shift will not happen.

There could be other ways to keep the layout from shifting (managing scrollbar width and setting body margin).

**Comment by jahaganiev** [comment]
Yes, the shared links and examples are nothing to do with Preline UI.

If there’s specific issues related to Preline UI, we welcome to open an issue with more details.

Cheers!
Jaha

**Comment by ilsyaa** [comment]
`class ScrollbarHelper {
    private _element: any

    constructor() {
        this._element = document.body
    }

    getWidth(){
        const documentWidth = document.documentElement.clientWidth
        return Math.abs(window.innerWidth - documentWidth)
    }

    hide(){
        const widthScrollbar = this.getWidth()
        this._element.style.overflow = 'hidden'
        this._element.style.paddingRight = `${widthScrollbar}px`
    }

    reset(){
        this._element.style.overflow = ''
        this._element.style.paddingRight = ''
    }
}

export default ScrollbarHelper`

**Comment by ile** [comment]
Let's make sure we are talking about the same thing.

The shift that happens, is the body element/webpage content below the modal wrapper (below transparent layer), which shifts to the right when the modal is opened. It's quite distracting. There are ways to prevent that shift from happening. 

[preline-2024-05-18_21.48.28.webm](https://github.com/htmlstreamofficial/preline/assets/433707/534fe401-12fd-4551-9cdd-c010fa34eabc)

**Comment by ile** [comment]
Making sure you noticed this, @jahaganiev. :+1:

**Comment by jahaganiev** [comment]
The scrolling behaviour can be controlled if needed, here's an example demo:

https://preline.co/docs/modal.html#scrolling-behavior

Cheers!
Jaha

**Comment by ile** [comment]
All of these have the same layout shift problem.
