### ISSUE TITLE
Search Issue with Non-Latin Characters in Select Plugin

### ISSUE THREAD

**Issue by gsarigul84** [htmlstreamofficial/preline#313]
Hello,

I noticed that the select plugin does not allow searching for non-Latin characters in its search functionality. It appears that the issue lies in the plugin's use of toLowerCase instead of toLocaleLowerCase.

I tested this in my local copy, and after making the change to toLocaleLowerCase, the search function worked as expected with non-Latin characters.

Could this adjustment be implemented in the main codebase to support non-Latin character search? It would greatly improve the usability of the plugin for international users.

Thank you.

**Comment by jahaganiev** [comment]
Hey @gsarigul84, added your suggestion to v2.1.0 update. Thanks!
