### ISSUE TITLE
Functions not working in React-Inertia project

### ISSUE THREAD

**Issue by Mahdin-22** [htmlstreamofficial/preline#315]
After spending more than 6 hours still can't solve this problem: I use Laravel, Vite, React & Inertia as main technologies. I want to use Preline sidebar which has accordion NavLinks but as this sidebar is generated by HeadlessUI transition, no Preline function works. I know I can make a component which is rendered at page loading so all functions can run correctly but I'm pretty sure I will have same problems for other components or I guess it will happen on navigations between pages. So please help me to solve this and imagine I know nothing about programming!!! I mean please explain more than usual I'm tired of partial and single-line codes.
The best option is changing Inertia config file (app.jsx) in a way that Preline functions run after each render (navigation, transition, etc.)
```
import "./bootstrap";
import "../css/app.css";

import { createRoot } from "react-dom/client";
import { createInertiaApp } from "@inertiajs/react";
import { resolvePageComponent } from "laravel-vite-plugin/inertia-helpers";

const appName = import.meta.env.VITE_APP_NAME || "Laravel";

createInertiaApp({
    title: (title) => `${appName} | ${title}`,
    resolve: (name) =>
        resolvePageComponent(
            `./Pages/${name}.jsx`,
            import.meta.glob("./Pages/**/*.jsx")
        ),
    setup({ el, App, props }) {
        const root = createRoot(el);

        root.render(<App {...props} />);

        delete el.dataset.page;
    },
    progress: {
        color: "#fbbf24",
    },
});
```
Thanks a lot!

**Comment by Mahdin-22** [comment]
After 24 hours of trying different thing, finally found a solution.
I write it here so that it helps someone.
Add multiple lines to your code and make your app.jsx file (which has your Inertia config in it) like this and it's done:
```
import "./bootstrap";
import "../css/app.css";

import { createRoot } from "react-dom/client";
import { createInertiaApp } from "@inertiajs/react";
import { resolvePageComponent } from "laravel-vite-plugin/inertia-helpers";
import { HSStaticMethods } from "preline";

HSStaticMethods.autoInit();

const observer = new MutationObserver((mutationsList) => {
    for (const mutation of mutationsList) {
        HSStaticMethods.autoInit();
    }
});

observer.observe(document.body, {
    attributes: true,
    subtree: true,
    childList: true,
    characterData: true,
});

const appName = import.meta.env.VITE_APP_NAME || "Laravel";

createInertiaApp({
    title: (title) => `${appName} | ${title}`,
    resolve: (name) =>
        resolvePageComponent(
            `./Pages/${name}.jsx`,
            import.meta.glob("./Pages/**/*.jsx")
        ),
    setup({ el, App, props }) {
        const root = createRoot(el);

        root.render(<App {...props} />);

        delete el.dataset.page;
    },
    progress: {
        color: "#fbbf24",
    },
});
```
Special thanks to "biskoot" who answered same question about HSDropdown [here](https://laracasts.com/discuss/channels/inertia/can-you-tell-me-how-to-use-inertia-vue-3-with-external-script) and I could solve it for all tools in PrelineUI.

**Comment by jahaganiev** [comment]
Hey @Mahdin-22 - thanks for sharing your workaround. We've added a back link in our docs [here](https://preline.co/docs/frameworks-react.html).

**Comment by Mahdin-22** [comment]
Thanks @jahaganiev. I really appreciate your kindness and sorry for commenting on a closed thread. That's because I love your fantastic works (I mean this great UI) I want to help people solve their problems and never hesitate using this UI more and more.
So as a guidance, if anyone wants to use dynamic data fetch from database in Preline components with the code I provided before, they may see some errors on their dev tools (moreoften more than 20 which starts growing because we've used observers in our code). That's because Preline starts initializing components before having all data ready, so as a solution just forget about observers and make your app.jsx file like this again:
`
import "./bootstrap";
import "../css/app.css";

import { createRoot } from "react-dom/client";
import { createInertiaApp } from "@inertiajs/react";
import { resolvePageComponent } from "laravel-vite-plugin/inertia-helpers";

const appName = import.meta.env.VITE_APP_NAME || "Laravel";

createInertiaApp({
    title: (title) => `${appName} | ${title}`,
    resolve: (name) =>
        resolvePageComponent(
            `./Pages/${name}.jsx`,
            import.meta.glob("./Pages/**/*.jsx")
        ),
    setup({ el, App, props }) {
        const root = createRoot(el);

        root.render(<App {...props} />);

        delete el.dataset.page;
    },
    progress: {
        color: "#fbbf24", // anything you like as you know
    },
});
`
And build a component for your theme switcher like this and initialize it whenever it's rendered:
`
import { HSThemeSwitch } from "preline";
import { useEffect } from "react";

export default function ThemeSwitcher() {
    useEffect(() => {
        HSThemeSwitch.autoInit();
    }, []);
    return (
        <>
            // whatever you like
        </>
    );
}
`
And then initialize the specific Preline components you use after having all data ready.
As an example if you use axios like me, a header component containing categories in tabs inside a Preline mega menu will look like this:
`
import { Link } from "@inertiajs/react";
import { useEffect, useState } from "react";
import axios from "axios";
import ThemeSwitcher from "@/Components/ThemeSwitcher";
import { HSDropdown, HSTabs } from "preline";

export default function DesktopMegaMenu() {
    const [categories, setCategories] = useState([]);

    useEffect(() => {
        axios
            .get("/api/categories")
            .then((response) => {
                setCategories(response.data);
            })
            .catch((error) => {
                console.error(error);
            })
            .finally(() => {
                HSDropdown.autoInit();
                HSTabs.autoInit();
            });
    });

    return (
        <div className="...">
            <nav className="...">
                <div className="....">
                    <div className="hs-dropdown [--strategy:absolute] [--adaptive:none] [--trigger:hover] [--auto-close:false]">
                        <button>Categories</button>
                        <div className="hs-dropdown-menu transition-opacity hs-dropdown-open:opacity-100 opacity-0...">
                            <div className="...">
                                <nav className="..." aria-label="Tabs" role="tablist" data-hs-tabs-vertical="true">
                                    {categories.map((category, key) => (
                                        <button
                                            key={key}
                                            type="button"
                                            className={`...${key === 0 ? "active" : ""}`}
                                            id={`vertical-tab-item-${key + 1}`}
                                            data-hs-tab={`#vertical-tab-${key + 1}`}
                                            aria-controls={`vertical-tab-${key + 1}`}
                                            role="tab"
                                        >
                                            <div className="...">
                                                {category.pername}
                                            </div>
                                        </button>
                                    ))}
                                </nav>
                                <div className="...">
                                    {categories.map((category, key) => (
                                        <div
                                            key={key}
                                            id={`vertical-tab-${key + 1}`}
                                            role="tabpanel"
                                            className={key === 0 ? "flex" : "hidden"}
                                            aria-labelledby={`vertical-tab-item-${key + 1}`}
                                        >
                                            .
                                            .
                                            .
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                    .
                    .
                    .
                </div>
                <div className="...">
                    <ThemeSwitcher /> // As an example :)
                </div>
            </nav>
        </div>
    );
}
`
At the end as a suggestion, just forget about initializing whole package at once, initialize them separately wherever needed and enjoy this UI. ;)
