### ISSUE TITLE
Preline Javascript plugin not working

### ISSUE THREAD

**Issue by frantzof** [htmlstreamofficial/preline#317]
**Context:**

 can't open the dropdown for the ["1st Base Mega Menu" navbar](https://preline.co/examples/navigations-mega-menu.html) template.

**Reproducing steps:**

1. created a new project
2. installed tailwing with CLI
3. tested it was working with a basic [Tailblocks](https://tailblocks.cc/) components = all good on live server
4. then moved on with the Preline installation
5. edited the tailwind.config.js file accordingly
6. added the script tag for the preline plugin at the end of the body tag in my html file
7. replaced the tailblocks code with the Preline Base Mega menu
8. launched live server again = it shows up but the dropdown doesnt work = issue with javascript

**here are the path of all the files and screenshots below:**

- /Users/frantzopf/coding/brides/test2/dist/index.html
- /Users/frantzopf/coding/brides/test2/dist/output.css

- /Users/frantzopf/coding/brides/test2/tailwind.config.js
- /Users/frantzopf/coding/brides/test2/src/input.css
- /Users/frantzopf/coding/brides/test2/node_modules/preline/preline.js

<img width="527" alt="Screenshot 2024-03-24 at 08 36 51" src="https://github.com/htmlstreamofficial/preline/assets/64052069/1ca88b22-72d6-43e9-b725-51807bd58ba1">
<img width="679" alt="Screenshot 2024-03-24 at 08 36 57" src="https://github.com/htmlstreamofficial/preline/assets/64052069/d129aff4-0717-4aa4-90aa-2aaa1466f0c5">
<img width="715" alt="Screenshot 2024-03-24 at 08 36 35" src="https://github.com/htmlstreamofficial/preline/assets/64052069/2d823c4c-b9b3-4972-a08d-71b687aca1cb">
<img width="1785" alt="Screenshot 2024-03-24 at 08 36 42" src="https://github.com/htmlstreamofficial/preline/assets/64052069/b9d2cb72-0074-4d55-9b10-933c10d4e13c">
<img width="1296" alt="Screenshot 2024-03-24 at 08 37 14" src="https://github.com/htmlstreamofficial/preline/assets/64052069/327b786a-720b-4817-a187-d0ac987911aa">
<img width="1800" alt="Screenshot 2024-03-24 at 08 39 12" src="https://github.com/htmlstreamofficial/preline/assets/64052069/ecb4f04b-cf00-4f75-8371-85d2beb4be09">
<img width="1800" alt="Screenshot 2024-03-24 at 08 39 21" src="https://github.com/htmlstreamofficial/preline/assets/64052069/fcf891de-abf0-4c15-b476-0a0405a9bb1e">

**Comment by frantzof** [comment]
@jahaganiev hi, please let me know if i need to add anything else 🙏🏾

**Comment by bizarf** [comment]
Hi, I had the same issue as well where my dropdown menu stopped working after I updated an old project to the latest version of Preline. The temporary fix I saw being recommended is to downgrade Preline to 1.9.0 which worked for me. Try that.

**Comment by jahaganiev** [comment]
It seems in tailwind.config.js file the content path should be `./src/**/*.{html,js}` instead of `./dist/**/*.{html,js}`

ref. https://tailwindcss.com/docs/installation
