### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by bakeiro** [htmlstreamofficial/preline#32]
Hi!
I just tried this and worked pretty well! I liked the design and the components! 👍

Still, I put this in a React component and I got some warnings
![imagen](https://user-images.githubusercontent.com/16777161/207120597-c7dc3f1b-4dec-4b90-b1a3-ee8414102bee.png)
![imagen](https://user-images.githubusercontent.com/16777161/207120632-696a8a9b-82ce-4eb2-8556-9ed85a3eaa33.png)

Will be React supported in the future? (based on this I decided whether going fordward with this)

P.S: thanks for the UI Kit!

**Comment by jahaganiev** [comment]
Hey @bakeiro!

Glad to hear you like Preline UI!

We will check out the warnings - thanks for sharing it!

Regarding the React and other framework integrations, we'd love to do but currently we are focused on the core UI components and not able to give ETA for it.

Thanks!

**Comment by fred-transitiv** [comment]
Google is your friend. Preline "supports React" just fine.

https://stackoverflow.com/questions/59840919/warning-a-future-version-of-react-will-block-javascript

You do have to get good at find/replace though since html != jsx or tsx.
