### ISSUE TITLE
Conflict using Splide JS with Preline Tabs

### ISSUE THREAD

**Issue by shamssujon** [htmlstreamofficial/preline#321]
I am getting the console error "`Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')`" when trying to use the [Splide JS](https://splidejs.com/) in a project where Preline is installed. 

![Screenshot 2024-03-29 070247](https://github.com/htmlstreamofficial/preline/assets/9370979/38e9c945-553d-425c-9fc1-e9ef47fd7455)

I believe this is because of a conflict with the Tabs plugin. It requires `role="tablist", role="tab", role="tabpanel"` and it is conflicting with the Splide JS. I looked into the Preline codes and found this:

`document.querySelectorAll('[role="tablist"]:not(select):not(.--prevent-on-load-init)').forEach()`

which is not a good way to target the tabs in my opinion. Because there might be other elements using the same role attribute. 

Any suggestion on how to fix this?

**Comment by zhi8617** [comment]
Same problem, when I introduce.

**Comment by umaraziz0** [comment]
Same issue here, in my case it's conflicting with shadcn-vue's Tabs, which is based on radix-ui tabs

**Comment by umaraziz0** [comment]
Update: 

I've found a temporary fix is to use `autoInit()` only on components that you use, and since I only use the Advanced Select, my configuration on nuxt.js would be:

```
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook('page:finish', () => {
    window.HSStaticMethods.autoInit(['select']);
  });
});

**Comment by jahaganiev** [comment]
We will revisit role="tablist" init approach in v3.0 Preline.

Meanwhile, you may add `--prevent-on-load-init` class where tablist is used for this specific case.

Cheers!

**Comment by koorukuroo** [comment]
> We will revisit role="tablist" init approach in v3.0 Preline.
> 
> Meanwhile, you may add `--prevent-on-load-init` class where tablist is used for this specific case.
> 
> Cheers!

OMG.. I almost give up on using preline, but you save me...

Just in case someone else runs into the same issue, here’s an Next.js example ( it's for search engine ;) )
```
<TabsList className="flex flex-wrap justify-start --prevent-on-load-init">
                    {categories.map((category) => (
                        <TabsTrigger
                            key={category}
                            value={category}
                            onClick={() => setSelectedCategory(category)}
                            className="px-4 py-2 m-1"
                        >
                            {category}
                        </TabsTrigger>
                    ))}
</TabsList>
```


Make sure to add `--prevent-on-load-init` at the end of your TabsList classname.

Hope this helps! 😊
