### ISSUE TITLE
Advanced Select not working in Nuxt.js (Vue.js)

### ISSUE THREAD

**Issue by oliver-savi** [htmlstreamofficial/preline#325]
On first load, the select component gets rendered correctly. If page or component in v-if change, then it reinitializes the select and adds double element. I have followed the steps from framework guides, but the solution there does not even initialize it on first load.

plugins/preline.client.ts:

```
import 'preline/preline'

declare var HSStaticMethods: {
  autoInit(collection?: string | string[]): void
}

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook('page:finish', () => {
    setInterval(() => {
      HSStaticMethods.autoInit()
    }, 1000)
  })
})
```

After second load of component, it will look like this:

![image](https://github.com/htmlstreamofficial/preline/assets/71636456/f88d638c-31f1-4333-abed-d152a907525e)

EDIT:
Added a basic demo: https://nuxt-preline-test.netlify.app/test
Code: https://github.com/oliver-savi/preline-test

**Comment by jahaganiev** [comment]
Hey @oliver-savi - please check out the latest version, the issue has been fixed. Thanks!

**Comment by omar-shaheen** [comment]
Same issue NUXT 3 after reload

**Comment by jahaganiev** [comment]
Dear @omar-shaheen - could you please open a new issue with more details? This issue has been addressed long time ago. We will need more details in order to be able to debug the issue.

**Comment by jahaganiev** [comment]
Thanks Omar, our team will check out and will follow up on the issue page.
