### ISSUE TITLE
Request for Tree View Component

### ISSUE THREAD

**Issue by KVeschgini** [htmlstreamofficial/preline#330]
Request to add a Tree View component to Preline UI for displaying hierarchical structures. This component is crucial for projects that involve nested data, such as file systems or organizational charts.

**Suggested Features:**
- Expand/Collapse nodes
- Customizable icons
- Selection (single or multiple)

**Comment by jahaganiev** [comment]
Accordion plugin/component supports nested collaps - https://preline.co/docs/accordion.html#nested

Wouldn't it work for Tree View?

**Comment by KVeschgini** [comment]
> Accordion plugin/component supports nested collaps - https://preline.co/docs/accordion.html#nested
> 
> Wouldn't it work for Tree View?

The accordion component doesn't fully align with the typical expectations for a Tree View, such as node selection and node-specific actions. Take for example the tree component of Blueprint.js as a reference: [https://blueprintjs.com/docs/#core/components/tree](https://blueprintjs.com/docs/#core/components/tree)

**Comment by jahaganiev** [comment]
Hey @KVeschgini - the Tree View component is live, you may check it out here:

https://preline.co/docs/tree-view.html

**Comment by jet10000** [comment]
> Hey [@KVeschgini](https://github.com/KVeschgini) - the Tree View component is live, you may check it out here:
> 
> https://preline.co/docs/tree-view.html

How to convert json tree data to preline tree view?
