### ISSUE TITLE
Preline not works sometime in Vuejs

### ISSUE THREAD

**Issue by tarunkorat** [htmlstreamofficial/preline#333]
I have added Preline in Vue latest version but its works sometime and sometime not. I have followed all documentation steps.

**Comment by tarunkorat** [comment]
> not enough information

I have followed all steps to use this in Vuejs but seems getting issue like sometimes dropdown opens sometimes not.

**Comment by noelc10** [comment]
I'm agree with @tarunkorat in Nuxt.js, sometimes when hard-reload the page, there's an error on the console. And I'm using the latest 2.1 version.
