### ISSUE TITLE
Scrollspy: jump-clicked element remains highlighted even if scrolled elsewhere

### ISSUE THREAD

**Issue by RSchmitzHH** [htmlstreamofficial/preline#334]
Hi guys! 

I noticed an absolutely minor issue in your scrollspy component [https://preline.co/docs/scrollspy.html#item-2](url): 

If one clicks on any item A in the list on the left, the scrollable content column on the right automatically scrolls there (as intended). The clicked element (item A) in the left list is highlighted (also as intended). 

If one scrolls the content column elsewhere, say to a section B, the new scroll location (item B) is highlighted in the list on the left (still as intended). 

However, beside the newly highlighted item B, also the originally clicked item A remains highlighted. This is not intended.

**Comment by jahaganiev** [comment]
Hey @RSchmitzHH - in real life use case that shouldn't be issue as usually Scrollspy is not intended to use that way as our demo display. If there's an edge case real life examples, please feel free to let us know and we will re-visit the issue. Thanks!
