### ISSUE TITLE
Advanced select disappears after Livewire second render

### ISSUE THREAD

**Issue by BigBlockStudios** [htmlstreamofficial/preline#336]
Copied and pasted the Advanced multi-select component from the docs,  The component works properly when the page first renders but if any other element on the page that triggers the render method a second time is interacted with. (clicked - whatever)  The advanced select control disappears,  it's still there in the dom, but hidden.   I have not done anything with this other than paste in the HTML for the control and imported preline 

Laravel 10, Livewire 3  tested in Firefox and Edge - same behaviour both browsers.

**Comment by Kane-R-G** [comment]
Came across this same issue. Putting `wire:ignore` on the parent element solves this issue.

**Comment by jahaganiev** [comment]
Hey @BigBlockStudios - we suggest to walkthrough Livewire docs as every framework comes with its ins and outs and we can't know the exact issue.

Please try our the suggestion by @Kane-R-G.

Cheers!
