### ISSUE TITLE
I can't use preline with Headless UI

### ISSUE THREAD

**Issue by ilhamsa1** [htmlstreamofficial/preline#337]
Hey Preline team, I got an error while using the headless UI component with preline. I'm not sure how to fix it.  Could you kindly assist me in identifying what I might be missing? Your help would be greatly appreciate

`TypeError: Cannot read properties of undefined (reading 'getAttribute')`

![image](https://github.com/htmlstreamofficial/preline/assets/33473051/2f8369b6-2a11-42f7-ab5f-e33c227cd51f)

And it works fine without the headless UI

![image](https://github.com/htmlstreamofficial/preline/assets/33473051/037c867d-4ba0-49e3-b932-a4352c897305)

library installed
-  "next": "14.1.4",
- "preline": "^2.1.0",
- "@headlessui/react": "^1.7.18",

**Comment by LeonLiu2020** [comment]
I'm having a similar problem using preline in next.js.
My scenario is static export.
Using the official recommended method,  `window.HSStaticMethods.autoInit();" ` seems to cause an error because the window object is used during preRender.
I tried to introduce the` /dist/preline.js` file in another way
For example adding `<script src=". ./node_modules/preline/dist/preline.js"></script> `in the root layout file, which results in a 404
If  `import "preline/dist/preline"` directly,  will result in a similar error as in the static export build process: 
`Error: self is not defined`

Anyone have any suggestions on how to do this?

Translated with DeepL.com (free version)

**Comment by jahaganiev** [comment]
Hey @ilhamsa1, @LeonLiu2020 - it's almost impossible to guess what could be the issue from our side. Please provide a Stackblitz demo and our team will be happy to walkthrough.

Cheers!

**Comment by im-not-developer** [comment]
Hello.
I think I have the same symptoms.

How can we solve it?
I'm sharing the pictures and the environment.
<img width="631" alt="스크린샷 2024-06-15 오후 1 44 29" src="https://github.com/htmlstreamofficial/preline/assets/118448040/5d93f103-9bc2-4a9c-92bb-4d61d3bb21c6">

```
{
  "name": "test-fe",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@hookform/resolvers": "^3.6.0",
    "@iconify/react": "^5.0.1",
    "@tanstack/react-query": "^5.45.0",
    "@tanstack/react-table": "^8.17.3",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@trivago/prettier-plugin-sort-imports": "^4.3.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.98",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "axios": "^1.7.2",
    "clsx": "^2.1.1",
    "dayjs": "^1.11.11",
    "dompurify": "^3.1.5",
    "iconify": "^1.4.0",
    "lodash": "^4.17.21",
    "object-to-formdata": "^4.5.1",
    "preline": "^2.3.0",
    "prettier": "^3.3.2",
    "prettier-plugin-tailwindcss": "^0.6.4",
    "rc-pagination": "^4.1.0",
    "react": "^18.3.1",
    "react-app-rewired": "^2.2.1",
    "react-cookie": "^7.1.4",
    "react-dom": "^18.3.1",
    "react-helmet-async": "^2.0.5",
    "react-hook-form": "^7.51.5",
    "react-jwt": "^1.2.1",
    "react-quill": "^2.0.0",
    "react-router-dom": "^6.23.1",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4",
    "yup": "^1.4.0"
  },
  "scripts": {
    "start": "react-app-rewired  start",
    "build": "react-app-rewired  build",
    "test": "react-app-rewired  test",
    "eject": "react-app-rewired  eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/lodash": "^4.17.5",
    "autoprefixer": "^10.4.19",
    "customize-cra": "^1.0.0",
    "postcss": "^8.4.38",
    "postcss-loader": "^8.1.1",
    "tailwindcss": "^3.4.4"
  }
}
```

App.tsx
```
import React, { useEffect } from 'react';
import { Route, Routes, useLocation } from 'react-router-dom';

import 'preline/preline';
import { IStaticMethods } from 'preline/preline';

import DashboardPage from '~/pages/DashboardPage';
import LoginPage from '~/pages/LoginPage';

declare global {
  interface Window {
    HSStaticMethods: IStaticMethods;
  }
}

function App() {
  const location = useLocation();

  useEffect(() => {
    window.HSStaticMethods.autoInit();
  }, [location.pathname]);

  return (
    <Routes>
      <Route path={'/*'} element={<DashboardPage />} />
      <Route path={'login'} element={<LoginPage />} />
    </Routes>
  );
}

export default App;

```

index.tsx
```
import React from 'react';
import { CookiesProvider } from 'react-cookie';
import ReactDOM from 'react-dom/client';
import { HelmetProvider } from 'react-helmet-async';
import { BrowserRouter } from 'react-router-dom';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import { apiQuery } from '~/api/apiQuery';

import App from './App';
import reportWebVitals from './reportWebVitals';
import './styles/tailwind.css';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      queryFn: apiQuery,
      refetchOnMount: false,
      refetchOnWindowFocus: false,
    },
  },
});

root.render(
  <React.StrictMode>
    <BrowserRouter>
      <HelmetProvider>
        <CookiesProvider>
          <QueryClientProvider client={queryClient}>
            <App />
          </QueryClientProvider>
        </CookiesProvider>
      </HelmetProvider>
    </BrowserRouter>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

```

**Comment by yusuphudaygulyyev** [comment]
Same issue in vue 3

![Screenshot 2024-06-20 at 01 43 01](https://github.com/htmlstreamofficial/preline/assets/114348038/2eeacb98-eecb-4d22-9533-e69667cf7489)

**Comment by ilhamsa1** [comment]
Hi @jahaganiev, it looks like Preline doesn't support [Headless UI](https://headlessui.com/react/popover). Could you recommend a headless library that can be used with Preline?

**Comment by princeajuzie7** [comment]
i was having this issue so i have to get the id of the element and also the attribute,  

`"use client";

import { usePathname } from "next/navigation";
import { useEffect } from "react";

import { IStaticMethods } from "preline/preline";
declare global {
  interface Window {
    HSStaticMethods: IStaticMethods;
  }
}

export  function PrelineScript() {
  const path = usePathname();

  useEffect(() => {
    const loadPreline = async () => {
      await import("preline/preline");
      if (
        typeof window !== "undefined" &&
        typeof document
          .getElementById('"data-hs-tab"')
          ?.getAttribute('"data-hs-tab"') !== "undefined"
      ) {
        window.HSStaticMethods.autoInit();
      }
    };

    loadPreline();
  }, [path]);

  return null;
}
`

this is what i did here 

`  if (
        typeof window !== "undefined" &&
        typeof document
          .getElementById('"data-hs-tab"')
          ?.getAttribute('"data-hs-tab"') !== "undefined"
      ) {
        window.HSStaticMethods.autoInit();
      }
    };
`

firstly checking the typeof window if it not equal to undefined and typeof document then i get the id of the element that is throwing the error and anlso the attribute after that then i initialize the Hstatic method. 

and it worked for me, hopefully it will work for you.

**Comment by amourlanne** [comment]
Preline `tabs` plugin `autoInit()` method initialize all `role="tablist"` elements as preline HSTabs, and try to get `data-hs-tab` attribut to child elements after https://github.com/htmlstreamofficial/preline/blob/main/src/plugins/tabs/index.ts#L204

So, remove all `role="tablist"` elements or remove `tabs` plugin on autoinit plugin collection list

```js
import {COLLECTIONS} from "preline/src/spa";

const collectionKeysWithoutTabsKey = COLLECTIONS
                .map(({ key }) => key)
                .filter(key => key !== 'tabs');

window.HSStaticMethods.autoInit(collectionKeysWithoutTabsKey);

```

The Preline `tabs` plugin's `autoInit()` method initializes all elements with` role="tablist"` as Preline `HSTabs`, and attempts to retrieve the `data-hs-tab` attribute from their child elements. See: https://github.com/htmlstreamofficial/preline/blob/main/src/plugins/tabs/index.ts#L204

To avoid this behavior, either remove all `role="tablist"` elements from your markup or exclude the `tabs` plugin from the `autoInit` plugin collection list.

```js
import { COLLECTIONS } from "preline/src/spa";

const collectionKeysWithoutTabsKey = COLLECTIONS
  .map(({ key }) => key)
  .filter(key => key !== 'tabs');

window.HSStaticMethods.autoInit(collectionKeysWithoutTabsKey);
```
