### ISSUE TITLE
Fetch Request Reopens Modal Backdrop Problem

### ISSUE THREAD

**Issue by fe** [htmlstreamofficial/preline#339]
---

**Description:**

When clicking the button, I expect to send a fetch request to the backend and display the modal element returned by the backend on the screen. I have managed to handle these parts so far, but after closing the modal, if the button is clicked again, the modal body gets appended, but the z-index value of the backdrop does not come, and since the newly appended modal does not work again, the second modal does not work.

**Steps to reproduce:**

1. Click the button triggering the fetch request to the backend.
2. Modal is displayed with the content returned from the backend.
3. Close the modal.
4. Click the button again to trigger another fetch request.

**Expected behavior:**

- The modal should be displayed again with the content returned from the backend.
- Backdrop z-index should be set properly to overlay the content underneath.
- The modal should work as expected after being appended again.

**Current behavior:**

- After closing the modal and clicking the button again, the modal body gets appended but the backdrop z-index is missing, and the modal does not function properly.

**After the second click, two backdrops are opened as a result of the request sent.**

![image](https://github.com/htmlstreamofficial/preline/assets/6671835/010d86b7-1e78-4d23-99f5-744944e2b0b5)

**Code Snippets:**

**HTML:**
```html
<button type="button"
    data-post="&id=1" //Custom Attr
    data-modal="#verifyMail" //Custom Attr
    data-hs-overlay="#verifyMail"
    data-href="backend_file" //Custom Attr
    class="btn">
    Verify Email Address
</button>
```

**JS:**
```javascript
import { HSStaticMethods, HSOverlay } from "preline";

window.HSOverlay = HSOverlay;
window.HSStaticMethods = HSStaticMethods;

document.addEventListener('DOMContentLoaded', function () {
    const modals = document.querySelectorAll('[data-modal]');
    modals.forEach(modal => {
        const modalHref = modal.getAttribute('data-href');
        let modalElement = '#defaultModal';
        let post = modal.getAttribute('data-post');
        if (modal.getAttribute('data-modal')) {
            modalElement = modal.getAttribute('data-modal');
        }
        modal.addEventListener('click', (event) => {
            getModal(modalHref, modalElement, post);
        });
    });
});

function getModal(href, modalElement, post = "") {
    const formData = new FormData();
    formData.append('modalElement', modalElement);
    formData.append('post', post);
    formData.append('action', 'getModal');
    formData.append('href', href);
    if (post) {
        post = post.split('&');
        post.forEach(data => {
            const dataSplit = data.split('=');
            formData.append(dataSplit[0], dataSplit[1]);
        });
    }

    if (document.querySelector(modalElement)) {
        document.querySelector(modalElement).remove();
    }

    fetch(customerModal, {
        method: 'POST',
        body: formData,
    })
        .then(response => {
            return response.text();
        })
        .then(html => {
            try {
                let parser = new DOMParser();
                let doc = parser.parseFromString(html, "text/html");
                const modal = doc.querySelector(modalElement);
                if (modal) {
                    document.body.prepend(modal);
                    HSStaticMethods.autoInit(['overlay']);
                    HSOverlay.open(modalElement);
                } else {
                    console.error('Modal not found');
                }
            } catch (e) {
                console.error(e);
            }
        })
        .catch(error => {
            console.error('Error:', error);
        });
}
```

**Backend Modal HTML:**
```html
<div id="verifyMail" class="hs-overlay hs-overlay-open:opacity-100 hs-overlay-open:duration-500 hidden size-full fixed top-0 start-0 z-[80] opacity-0 overflow-x-hidden transition-all overflow-y-auto pointer-events-none">
    <div class="sm:max-w-lg sm:w-full m-3 sm:mx-auto">
        <div class="flex flex-col bg-white border shadow-sm rounded-xl pointer-events-auto dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
            <div class="flex justify-between items-center py-3 px-4 border-b dark:border-gray-700">
                <h3 class="font-bold text-gray-800 dark:text-white">
                    Modal title
                </h3>
                <button type="button" class="flex justify-center items-center size-7 text-sm font-semibold rounded-full border border-transparent text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none dark:text-white dark:hover:bg-gray-700" data-hs-overlay="#verifyMail">
                    <span>Close</span>
                </button>
            </div>
            <div class="p-4 overflow-y-auto">
                Modal Content
            </div>
            <div class="flex justify-end items-center gap-x-2 py-3 px-4 border-t dark:border-gray-700">
                <button type="button" class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none">
                    Save changes
                </button>
            </div>
        </div>
    </div>
</div>
```

---

**Comment by olegpix** [comment]
> **Description:**
> 
> When clicking the button, I expect to send a fetch request to the backend and display the modal element returned by the backend on the screen. I have managed to handle these parts so far, but after closing the modal, if the button is clicked again, the modal body gets appended, but the z-index value of the backdrop does not come, and since the newly appended modal does not work again, the second modal does not work.
> 
> **Steps to reproduce:**
> 
> 1. Click the button triggering the fetch request to the backend.
> 2. Modal is displayed with the content returned from the backend.
> 3. Close the modal.
> 4. Click the button again to trigger another fetch request.
> 
> **Expected behavior:**
> 
> * The modal should be displayed again with the content returned from the backend.
> * Backdrop z-index should be set properly to overlay the content underneath.
> * The modal should work as expected after being appended again.
> 
> **Current behavior:**
> 
> * After closing the modal and clicking the button again, the modal body gets appended but the backdrop z-index is missing, and the modal does not function properly.
> 
> **After the second click, two backdrops are opened as a result of the request sent.**
> 
> ![image](https://private-user-images.githubusercontent.com/6671835/321315734-010d86b7-1e78-4d23-99f5-744944e2b0b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjc2MDQsIm5iZiI6MTcxNzA2NzMwNCwicGF0aCI6Ii82NjcxODM1LzMyMTMxNTczNC0wMTBkODZiNy0xZTc4LTRkMjMtOTlmNS03NDQ5NDRlMmIwYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMTEwODI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ3ZDZjOWI1MjJhOGIwZTQ3ZDNmNTdmYmNmM2IwMTQ2NTMzZGQ1ODYyNDExYTk2MmUwMTUwYjU1YzEyNDBhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s5loLF3D2v7d91TSx7agnz1mmbFwXMwBOhQXNCZfWDk)
> 
> **Code Snippets:**
> 
> **HTML:**
> 
> ```
> <button type="button"
>     data-post="&id=1" //Custom Attr
>     data-modal="#verifyMail" //Custom Attr
>     data-hs-overlay="#verifyMail"
>     data-href="backend_file" //Custom Attr
>     class="btn">
>     Verify Email Address
> </button>
> ```
> 
> **JS:**
> 
> ```js
> import { HSStaticMethods, HSOverlay } from "preline";
> 
> window.HSOverlay = HSOverlay;
> window.HSStaticMethods = HSStaticMethods;
> 
> document.addEventListener('DOMContentLoaded', function () {
>     const modals = document.querySelectorAll('[data-modal]');
>     modals.forEach(modal => {
>         const modalHref = modal.getAttribute('data-href');
>         let modalElement = '#defaultModal';
>         let post = modal.getAttribute('data-post');
>         if (modal.getAttribute('data-modal')) {
>             modalElement = modal.getAttribute('data-modal');
>         }
>         modal.addEventListener('click', (event) => {
>             getModal(modalHref, modalElement, post);
>         });
>     });
> });
> 
> function getModal(href, modalElement, post = "") {
>     const formData = new FormData();
>     formData.append('modalElement', modalElement);
>     formData.append('post', post);
>     formData.append('action', 'getModal');
>     formData.append('href', href);
>     if (post) {
>         post = post.split('&');
>         post.forEach(data => {
>             const dataSplit = data.split('=');
>             formData.append(dataSplit[0], dataSplit[1]);
>         });
>     }
> 
>     if (document.querySelector(modalElement)) {
>         document.querySelector(modalElement).remove();
>     }
> 
>     fetch(customerModal, {
>         method: 'POST',
>         body: formData,
>     })
>         .then(response => {
>             return response.text();
>         })
>         .then(html => {
>             try {
>                 let parser = new DOMParser();
>                 let doc = parser.parseFromString(html, "text/html");
>                 const modal = doc.querySelector(modalElement);
>                 if (modal) {
>                     document.body.prepend(modal);
>                     HSStaticMethods.autoInit(['overlay']);
>                     HSOverlay.open(modalElement);
>                 } else {
>                     console.error('Modal not found');
>                 }
>             } catch (e) {
>                 console.error(e);
>             }
>         })
>         .catch(error => {
>             console.error('Error:', error);
>         });
> }
> ```
> 
> **Backend Modal HTML:**
> 
> ```
> <div id="verifyMail" class="hs-overlay hs-overlay-open:opacity-100 hs-overlay-open:duration-500 hidden size-full fixed top-0 start-0 z-[80] opacity-0 overflow-x-hidden transition-all overflow-y-auto pointer-events-none">
>     <div class="sm:max-w-lg sm:w-full m-3 sm:mx-auto">
>         <div class="flex flex-col bg-white border shadow-sm rounded-xl pointer-events-auto dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
>             <div class="flex justify-between items-center py-3 px-4 border-b dark:border-gray-700">
>                 <h3 class="font-bold text-gray-800 dark:text-white">
>                     Modal title
>                 </h3>
>                 <button type="button" class="flex justify-center items-center size-7 text-sm font-semibold rounded-full border border-transparent text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none dark:text-white dark:hover:bg-gray-700" data-hs-overlay="#verifyMail">
>                     <span>Close</span>
>                 </button>
>             </div>
>             <div class="p-4 overflow-y-auto">
>                 Modal Content
>             </div>
>             <div class="flex justify-end items-center gap-x-2 py-3 px-4 border-t dark:border-gray-700">
>                 <button type="button" class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none">
>                     Save changes
>                 </button>
>             </div>
>         </div>
>     </div>
> </div>
> ```

Hi,
`if (document.querySelector(modalElement)) {
        document.querySelector(modalElement).remove();
        document.querySelector('#verifyMail-backdrop').remove();
    }`
here also try to remove the background.
