### ISSUE TITLE
Changing Arrow color on select box

### ISSUE THREAD

**Issue by JMKelley** [htmlstreamofficial/preline#341]
Within dark mode, `<select>` dropdown arrow icon is not visible. Docs do not illustrate how to change this.

**Comment by jahaganiev** [comment]
not enough information

**Comment by JMKelley** [comment]
@jahaganiev 

On your dark mode docs, the `<select>` input has a caret icon in a light text colour, when adding this `<select>` input to a page which has dark mode enabled, the caret icon disappears and is not rendered in the same text colour as the docs.
