### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by MuhammadSawalhy** [htmlstreamofficial/preline#343]
My Preline version is `^2.0.3`. This is the first time to see this issue. Happened after navigating from one page to another.

![image](https://github.com/htmlstreamofficial/preline/assets/42011920/63590741-4d6e-4ebd-b450-b0b35df72b0f)

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'length')

Call Stack
length
node_modules/preline/preline.js (49:6295)
accessibility
node_modules/preline/preline.js (49:5382)
```

The exact line of code is too long to put here, but here is a screenshot:

![image](https://github.com/htmlstreamofficial/preline/assets/42011920/8c564e8e-b659-495c-9453-27aa7b446d73)

```
t.element.el.classList.contains("open")}));if(e&&(c.DROPDOWN_ACCESSIBILITY_KEY_SET.includes(t.code)||4===t.code.length&&t.co
// exactly at (t.code.length)
```

**Comment by jahaganiev** [comment]
Please try out with the latest version. If you are still having an issue, please provide a link to StackBlitz with your setup sources for other members to debug. Thanks!
