### ISSUE TITLE
how to use the steps plugin in angular?

### ISSUE THREAD

**Issue by aaron-za-dev** [htmlstreamofficial/preline#345]
I have tried to use preline ui in an angular application, but I cannot understand how to use the plugin steps, can you provide an example of implementation

**Comment by hanafiprasyah** [comment]
> I have tried to use preline ui in an angular application, but I cannot understand how to use the plugin steps, can you provide an example of implementation

Why don't you put this on discussion section please? This section is only for Issue ✨

**Comment by jahaganiev** [comment]
Hey @aaron-za-dev - you may find the example [here](https://stackblitz.com/edit/preline-v2-angular?file=tailwind.config.js).
