### ISSUE TITLE
Advance Select and multiple option value not detected using Livewire 3

### ISSUE THREAD

**Issue by hanafiprasyah** [htmlstreamofficial/preline#346]
**Livewire variable declared**
`public array $selectedPermissions;`

**then here is the mount** :
`$this->fill([
            'selectedPermissions' => []
        ]);`

**Livewire function (saveMultiplePermission)** :
`dd($this->selectedPermissions);` <- for printout the selected array result
`$role = Role::find($this->roleId);`
`$role->permissions()->attach($this->selectedPermissions);`

**The native form**
`<form wire:submit.prevent="saveMultiplePermission">`

**Advance Select** :
`<select id="selectedPermissions" multiple="" data-hs-select='{
_here the JS options behavior declared_
}' wire:model="selectedPermissions">`

**My options get the data from database** :
`@foreach ($notInRelationPermissions as $permission)
            <option value="{{ $permission->id }}">
                {{ $permission->name}}
            </option>
            @endforeach`

I have followed the Advance Select instruction here : https://preline.co/plugins/html/advanced-select.html. But when I try to submit the form to livewire function, it return an empty array :
`[] // app\Livewire\Form\AddPermissionToRole.php:42`

![Screenshot 2024-04-16 154309](https://github.com/htmlstreamofficial/preline/assets/74239181/96ed8fc4-5713-4885-8672-7a3bdd8e4916)

When I delete the data-hs-select, it worked with multiple selected array and give me the selected options in array. 

![Screenshot 2024-04-16 154410](https://github.com/htmlstreamofficial/preline/assets/74239181/6a3f3af5-5159-4a4d-a9af-901ae5504d44)

Something wrong with my code? Or it is a bug from HSSelect?

### Please help me to solve this issue. Thank you

**Comment by olegpix** [comment]
> **Livewire variable declared** `public array $selectedPermissions;`
> 
> **then here is the mount** : `$this->fill([ 'selectedPermissions' => [] ]);`
> 
> **Livewire function (saveMultiplePermission)** : `dd($this->selectedPermissions);` <- for printout the selected array result `$role = Role::find($this->roleId);` `$role->permissions()->attach($this->selectedPermissions);`
> 
> **The native form** `<form wire:submit.prevent="saveMultiplePermission">`
> 
> **Advance Select** : `<select id="selectedPermissions" multiple="" data-hs-select='{ _here the JS options behavior declared_ }' wire:model="selectedPermissions">`
> 
> **My options get the data from database** : `@foreach ($notInRelationPermissions as $permission) <option value="{{ $permission->id }}"> {{ $permission->name}} </option> @endforeach`
> 
> I have followed the Advance Select instruction here : https://preline.co/plugins/html/advanced-select.html. But when I try to submit the form to livewire function, it return an empty array : `[] // app\Livewire\Form\AddPermissionToRole.php:42`
> 
> ![Screenshot 2024-04-16 154309](https://private-user-images.githubusercontent.com/74239181/322770661-96ed8fc4-5713-4885-8672-7a3bdd8e4916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjc2MDUsIm5iZiI6MTcxNzA2NzMwNSwicGF0aCI6Ii83NDIzOTE4MS8zMjI3NzA2NjEtOTZlZDhmYzQtNTcxMy00ODg1LTg2NzItN2EzYmRkOGU0OTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZWM3NzA2OGU3ZmZlMmU1M2JjZDcwMTkwYzYyZmNhMWIwZDIwNGUzNDIwYmQzNGQ3Nzg0ZWMxYWUxMGFmNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EdwHA7hffuxmJXh9Qsf1o10vuwFxXjM0vpy0Rd1Dm6Y)
> 
> When I delete the data-hs-select, it worked with multiple selected array and give me the selected options in array.
> 
> ![Screenshot 2024-04-16 154410](https://private-user-images.githubusercontent.com/74239181/322771161-6a3f3af5-5159-4a4d-a9af-901ae5504d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjc2MDUsIm5iZiI6MTcxNzA2NzMwNSwicGF0aCI6Ii83NDIzOTE4MS8zMjI3NzExNjEtNmEzZjNhZjUtNTE1OS00YTRkLWE5YWYtOTAxYWU1NTA0ZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NmM1MjFkYzkxMGQ5MTg2M2VhMjE3NzYwM2IxOGIzOTgyNTkxZDFiMWIxZWI5MzcxNzY2NzlhZjhkNDBkNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bB3T2zDvqIjD3LEytezSMHKrMxaraNIw5cE0OS_KymM)
> 
> Something wrong with my code? Or it is a bug from HSSelect?
> 
> ### Please help me to solve this issue. Thank you

Hi,
to get the current value from `HSSelect` you can use the following code:
```
<form id="form" method="post" action="/">
    <select name="select" multiple data-hs-select='{
      "placeholder": "Placeholder...",
      ...rest of the options
    }' class="hidden">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
    </select>

    <button type="submit">Submit a value</button>
</form>
      
<script>
    window.addEventListener('load', () => {
        const form = document.querySelector('#form');

        form.addEventListener('submit', (evt) => {
            evt.preventDefault();
            
            const { element } = HSSelect.getInstance('[name="select"]', true);
            
            console.log(element.value);
        });
    });
</script>
```
the console will return an array with values, for example. `['1', '2', '3']`.

**Comment by hanafiprasyah** [comment]
Thanks a lot sensei 🔥
