### ISSUE TITLE
Mega Menu with hover effect is flickering when trying to get cursor from link to menu

### ISSUE THREAD

**Issue by holubar** [htmlstreamofficial/preline#347]
If there is hover effect used and the themega menu is wider, like 3 column, user natuarally goes with cursor across the next link which will cause flickering of the open menu and it actually closes before the user gets to the menu. If users goes with cursor straight down, behaviour is OK.

Is there a way to prevent this?

https://preline.co/docs/mega-menu.html
![benzing sk - benzing sk](https://github.com/htmlstreamofficial/preline/assets/34790487/d933b15e-ee50-4db5-9e1f-0c00ff43f18c)

**Comment by Bootstrap-Paradox** [comment]
Hey @holubar, had this issue, there was an issue with the bounding area for the element that there was space between the Hover element and the Dropdown element.

Try removing the offset between the two elements either through padding or the Offset Options

**Comment by olegpix** [comment]
> If there is hover effect used and the themega menu is wider, like 3 column, user natuarally goes with cursor across the next link which will cause flickering of the open menu and it actually closes before the user gets to the menu. If users goes with cursor straight down, behaviour is OK.
> 
> Is there a way to prevent this?
> 
> https://preline.co/docs/mega-menu.html ![benzing sk - benzing sk](https://private-user-images.githubusercontent.com/34790487/322783511-d933b15e-ee50-4db5-9e1f-0c00ff43f18c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjc2MDYsIm5iZiI6MTcxNzA2NzMwNiwicGF0aCI6Ii8zNDc5MDQ4Ny8zMjI3ODM1MTEtZDkzM2IxNWUtZWU1MC00ZGI1LTllMWYtMGMwMGZmNDNmMThjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMGQ2OWVhZDE1YzgzNmYzMjZjMTE2NWI2ZTFkNDJlZTE4Yzk1M2E3MjM1MWI2YjhiN2QxNmVkODIzMGQ1ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WgdHnVY4_k2f-IQonOMe_UUBqjU9HZ2VY9uA3SnxDyU) [ ![benzing sk - benzing sk](https://private-user-images.githubusercontent.com/34790487/322783511-d933b15e-ee50-4db5-9e1f-0c00ff43f18c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjc2MDYsIm5iZiI6MTcxNzA2NzMwNiwicGF0aCI6Ii8zNDc5MDQ4Ny8zMjI3ODM1MTEtZDkzM2IxNWUtZWU1MC00ZGI1LTllMWYtMGMwMGZmNDNmMThjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMGQ2OWVhZDE1YzgzNmYzMjZjMTE2NWI2ZTFkNDJlZTE4Yzk1M2E3MjM1MWI2YjhiN2QxNmVkODIzMGQ1ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WgdHnVY4_k2f-IQonOMe_UUBqjU9HZ2VY9uA3SnxDyU) ](https://private-user-images.githubusercontent.com/34790487/322783511-d933b15e-ee50-4db5-9e1f-0c00ff43f18c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjc2MDYsIm5iZiI6MTcxNzA2NzMwNiwicGF0aCI6Ii8zNDc5MDQ4Ny8zMjI3ODM1MTEtZDkzM2IxNWUtZWU1MC00ZGI1LTllMWYtMGMwMGZmNDNmMThjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMGQ2OWVhZDE1YzgzNmYzMjZjMTE2NWI2ZTFkNDJlZTE4Yzk1M2E3MjM1MWI2YjhiN2QxNmVkODIzMGQ1ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WgdHnVY4_k2f-IQonOMe_UUBqjU9HZ2VY9uA3SnxDyU) [ ](https://private-user-images.githubusercontent.com/34790487/322783511-d933b15e-ee50-4db5-9e1f-0c00ff43f18c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjc2MDYsIm5iZiI6MTcxNzA2NzMwNiwicGF0aCI6Ii8zNDc5MDQ4Ny8zMjI3ODM1MTEtZDkzM2IxNWUtZWU1MC00ZGI1LTllMWYtMGMwMGZmNDNmMThjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMGQ2OWVhZDE1YzgzNmYzMjZjMTE2NWI2ZTFkNDJlZTE4Yzk1M2E3MjM1MWI2YjhiN2QxNmVkODIzMGQ1ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WgdHnVY4_k2f-IQonOMe_UUBqjU9HZ2VY9uA3SnxDyU)

Hi,
please, try to use and modify the example from this page [https://preline.co/examples/page-pricing.html](https://preline.co/examples/page-pricing.html).
The main idea is to change the height and position of the `before:` pseudo-element of the dropdown list (see screenshot).

![_01](https://github.com/htmlstreamofficial/preline/assets/20664129/e5b8ca5b-fbfe-47e8-acc9-00b0481fa02b)
