### ISSUE TITLE
Get advanced select tags in array

### ISSUE THREAD

**Issue by Linrador** [htmlstreamofficial/preline#352]
Hi there!

When using [advanced select tags](https://preline.co/docs/advanced-select.html#tags) I can't seem to be able to get the items that have been added to the input field. Is it possible to get these or store them in a string array when they have been added / removed?

Like `items: string[] = ['item1', 'item2']` etc?

![item](https://github.com/htmlstreamofficial/preline/assets/68631622/ccc356b7-71d2-453a-b965-954b694622e2)

**Comment by olegpix** [comment]
> Hi there!
> 
> When using [advanced select tags](https://preline.co/docs/advanced-select.html#tags) I can't seem to be able to get the items that have been added to the input field. Is it possible to get these or store them in a string array when they have been added / removed?
> 
> Like `items: string[] = ['item1', 'item2']` etc?
> 
> ![item](https://private-user-images.githubusercontent.com/68631622/324871656-ccc356b7-71d2-453a-b965-954b694622e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDg4NzksIm5iZiI6MTcxNDc0ODU3OSwicGF0aCI6Ii82ODYzMTYyMi8zMjQ4NzE2NTYtY2NjMzU2YjctNzFkMi00NTNhLWI5NjUtOTU0YjY5NDYyMmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE1MDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNGYyYzVjNmE3ZjYzNjU3N2RlYmYxZGM3NDM2YWRiMDZmYjEyZDQyYzgyZmEzMmEwYzY4NTYzMjU4OWYwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kdn4ZVZ_ZJk30S4lx8rAKsBnYjJHFeesQlnNboRkcjk)

Hi!
Yes, the plugin provides this ability. Please check the code:
```
const select = HSSelect.getInstance('#hs-as-tags', true);

select.element.on('change', (val) => {
  console.log(val);
});
```

**Comment by bluefire2121** [comment]
@olegpix  This answer is different from the [documentation](https://preline.co/plugins/html/advanced-select.html#js-events). 

Is it what you shared above?

```
const select = HSSelect.getInstance('#hs-as-tags', true);

select.element.on('change', (val) => {
  console.log(val);
});
```
or is it what's in the documentation?
```
const el = HSSelect.getInstance('#select');

el.on('change', (val) => {...});
```
