### ISSUE TITLE
Combobox selection of ahref items using keyboard

### ISSUE THREAD

**Issue by sswany** [htmlstreamofficial/preline#353]
When using the Combobox plugin and the output items are anchor tags, if you use the keyboard to navigate the combobox and select one, it always goes to the URL of the first output item in the list rather than the one selected.

The Searchbox, Dropdown example (https://preline.co/docs/searchbox.html#html-example-in-dropdown) has the same behavior if you use that as the baseline and change the href attribute to replicate the issue.

Thank you!

**Comment by jahaganiev** [comment]
Hey @sswany - the issue has been fixed in 2.3.0 update. Thanks!
