### ISSUE TITLE
Angular version of Accordion doesn't work

### ISSUE THREAD

**Issue by AnassL** [htmlstreamofficial/preline#360]
<div class="hs-accordion-group">
    <div class="hs-accordion active" id="hs-unstyled-heading-one">
        <button class="hs-accordion-toggle" aria-controls="hs-unstyled-collapse-one">
        Accordion #1
        </button>
        <div id="hs-unstyled-collapse-one" class="hs-accordion-content overflow-hidden transition-[height] duration-300" aria-labelledby="hs-unstyled-heading-one">
        It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element.
        </div>
    </div>
    
    <div class="hs-accordion" id="hs-unstyled-heading-two">
        <button class="hs-accordion-toggle" aria-controls="hs-unstyled-collapse-two">
        Accordion #2
        </button>
        <div id="hs-unstyled-collapse-two" class="hs-accordion-content hidden overflow-hidden transition-[height] duration-300" aria-labelledby="hs-unstyled-heading-two">
        It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element.
        </div>
    </div>
    
    <div class="hs-accordion" id="hs-unstyled-heading-three">
        <button class="hs-accordion-toggle" aria-controls="hs-unstyled-collapse-three">
        Accordion #3
        </button>
        <div id="hs-unstyled-collapse-three" class="hs-accordion-content hidden overflow-hidden transition-[height] duration-300" aria-labelledby="hs-unstyled-heading-three">
        It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element.
        </div>
    </div>
</div>

The above is the simplest sample from the Angular version of Accordion documentation. I followed the instructions for the installation, but was not able to get the second, and third item content to show after clicked their relative buttons.

How to fix this, please ?

**Comment by jahaganiev** [comment]
You may check out Angular playground demos on [StackBlitz](https://stackblitz.com/edit/preline-v2-angular?file=tailwind.config.js)

If you are still having any issues, please fork the example from StackBlitz and provide live demo.

Thanks!
