### ISSUE TITLE
Searchable advanced select throws error when searching for value not in list

### ISSUE THREAD

**Issue by MattMonet** [htmlstreamofficial/preline#363]
With a searchable advanced select if you type in a value that does not exist as an option in the search box and press enter on the keyboard the below error is thrown because that value does not exist.

Error
`Cannot read properties of undefined (reading 'classList')`

Is there a way to handle this error?

**Comment by jahaganiev** [comment]
Hey @MattMonet - our team released v2.4.0 update which includes the fixes. Thanks!
