### ISSUE TITLE
Add support to escape ID for React's useId hook

### ISSUE THREAD

**Issue by elasticizer** [htmlstreamofficial/preline#366]
### Current behavior

I'm encountering a `SyntaxError` when using the `useId` hook with the `data-hs-overlay` attribute.

```
SyntaxError: Failed to execute 'querySelector' on 'Document': '#:Rm:-backdrop' is not a valid selector.
```

### Cause

The colon (`:`) character in the generated ID (`#::Rm:-backdrop`) is causing the error. Colons have a special meaning in CSS selectors and need to be escaped when used within an ID. [^1]

https://github.com/htmlstreamofficial/preline/blob/8b83c1f51c9c6c61a2de78c812a1af28d4e8824b/src/plugins/overlay/index.ts#L204-L206

### Proposed solution

I propose adding support for React's `useId` hook while ensuring compatibility with the `data-hs-overlay` attribute. Here are two possible approaches: [^2]

1. Attribute selector

	```js
	`[id="${this.overlay.id}-backdrop"]`
	```

	This approach uses an attribute selector to target the element with an ID matching the generated ID from `useId` followed by `-backdrop`. This avoids the colon issue entirely.

2. Escaped ID

	```js
	`#${CSS.escape(this.overlay.id)}-backdrop`
	```

	This approach leverages the `CSS.escape` function to escape the colon in the generated ID. This ensures the ID is valid and can be used as a CSS selector.

### Expected behavior

I'd like to see support for `useId` with `data-hs-overlay` implemented in a solution that addresses the colon issue effectively.

Thank you for considering this issue!

[^1]: https://stackoverflow.com/questions/73894096/react-useid-creates-invalid-selector
[^2]: https://stackoverflow.com/questions/45110893/select-elements-by-attributes-with-colon

**Comment by jahaganiev** [comment]
Hey @elasticizer - unfortunately, we can't rewrite Preline plugins explicitly for React framework but please feel free to change and adjust the source code based on your needs.
