### ISSUE TITLE
Combobox will skip at least one item if arrowdown/up in vue3

### ISSUE THREAD

**Issue by APshZ** [htmlstreamofficial/preline#369]
### Background
While using the example from https://preline.co/docs/combobox.html and put it under the vue component, find that after input value in the input field, the keydown event will trigger more than once
from Argentina step to China instead of Brazil
<img width="509" alt="image" src="https://github.com/htmlstreamofficial/preline/assets/140894800/609d66bd-ad69-4bd4-a1d2-1b1c78b49f3f">
The dropdown in example also have same issue for skipping items.
https://stackblitz.com/edit/preline-v2-vue-and-vue-router?file=src%2Frouter%2Findex.ts,README.md

so i debug the prelinejs for combobox and find that every time route to the component which contains combobox, the autoinit function triggered and duplicate the combobox in window.$hsComboBoxCollection
<img width="1129" alt="image" src="https://github.com/htmlstreamofficial/preline/assets/140894800/c5e6c18b-1dec-4e11-8f24-9b6a7c834706">
which will lead to the more item count being skipped 

### Browser
Chrome, Edge

wait for fix or is it my code problem

**Comment by APshZ** [comment]
and my temp solution for vue
`<div class="relative" data-hs-combo-box="" @keydown.down.stop="combobox.onArrow(false)" @keydown.up.stop="combobox.onArrow(true)">`

**Comment by jahaganiev** [comment]
Hey @APshZ  - please check out the latest version, the issue has been fixed. Thanks!
