### ISSUE TITLE
Interactivity missing in Umbraco CMS

### ISSUE THREAD

**Issue by wpplumber** [htmlstreamofficial/preline#375]
Welcome,

I'm using Preline in a custom dashboard where the CDN initiated by jquery but interactivity not working. (dropdown show fine but doesn't open)

Note: not console error.

**Comment by jahaganiev** [comment]
Hey @wpplumber,

Please note, Preline doesn't support CDNs for development but can be used for production.

However, if you are having any specific issues, please open a new issue with step by step details so other community members can reproduce the issue.

Hope that helps!
