### ISSUE TITLE
Cannot read properties of undefined (reading 'getAttribute')    In Next JS 14

### ISSUE THREAD

**Issue by princeajuzie7** [htmlstreamofficial/preline#379]
my code has been working well then suddenly  this error message started popping up. 

"use client";

import { usePathname } from "next/navigation";
import { useEffect } from "react";

import { IStaticMethods } from "preline/preline";
declare global {
  interface Window {
    HSStaticMethods: IStaticMethods;
  }
}

export  function PrelineScript() {
  const path = usePathname();

  useEffect(() => {
    const loadPreline = async () => {
      await import("preline/preline");
      if (typeof window !== "undefined") {
        
         
        window.HSStaticMethods?.autoInit();
       }
    };

    loadPreline();
  }, [path]);

  return null;
}

**Comment by jahaganiev** [comment]
Hey @princeajuzie7 - could you please provide working Stackblitz live demo and step by step details? You may fork the example demo [here](https://stackblitz.com/edit/preline-v2-nextjs?file=tailwind.config.ts) if needed.
