### ISSUE TITLE
data-hs-combo-box-output-item attribute hydration issues

### ISSUE THREAD

**Issue by bluefire2121** [htmlstreamofficial/preline#382]
### Summary

data-hs-combo-box-output-item attribute adds a style attribute to its element which causes hydration issues. 

### Steps to Reproduce

1. Follow the basic example for [combobox](https://preline.co/docs/combobox.html)
2. Hydration issues occur when used with SSR frameworks (Next / Remix) on the element with the `data-hs-combo-box-output-item`. 
3. Client contains style={{display: "block"}}. Server does not.

### Demo Link

https://preline.co/docs/combobox.html

### Expected Behavior

- No hydration errors. 
- Style attribute isn't added. Either use the Tailwindcss class` hidden` or remove style altogether.

### Actual Behavior

- Hydration issues occur

### Screenshots

![Screenshot 2024-06-02 171233](https://github.com/htmlstreamofficial/preline/assets/4358275/8776ec48-c328-4ad6-9a40-b092b95ffe14)

**Comment by bluefire2121** [comment]
The work around is to add `style={{display: 'none'}}` to elements that contain the `data-hs-combo-box-output-item` attribute.

**Comment by olegpix** [comment]
> ### Summary
> data-hs-combo-box-output-item attribute adds a style attribute to its element which causes hydration issues.
> 
> ### Steps to Reproduce
> 1. Follow the basic example for [combobox](https://preline.co/docs/combobox.html)
> 2. Hydration issues occur when used with SSR frameworks (Next / Remix) on the element with the `data-hs-combo-box-output-item`.
> 3. Client contains style={{display: "block"}}. Server does not.
> 
> ### Demo Link
> https://preline.co/docs/combobox.html
> 
> ### Expected Behavior
> * No hydration errors.
> * Style attribute isn't added. Either use the Tailwindcss class` hidden` or remove style altogether.
> 
> ### Actual Behavior
> * Hydration issues occur
> 
> ### Screenshots
> ![Screenshot 2024-06-02 171233](https://private-user-images.githubusercontent.com/4358275/335907430-8776ec48-c328-4ad6-9a40-b092b95ffe14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDg3ODEsIm5iZiI6MTcxNzQwODQ4MSwicGF0aCI6Ii80MzU4Mjc1LzMzNTkwNzQzMC04Nzc2ZWM0OC1jMzI4LTRhZDYtOWE0MC1iMDkyYjk1ZmZlMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMDk1NDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNjZDhkODNiOTVjNjI1NjZkMjY3NGY5MTk2NTE3YzE5NDU4ZjE4NGYwMzk1YzNmMjBkNzlkMmMzZTdlNWIzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p5OE5XxbrN5k3Nl3O-3X0EH_Zwdwu--9YgCylEYv-7Y)

Hey @bluefire2121,
Could you please provide a Stacklblitz demo?
Thanks!
