### ISSUE TITLE
In Sveltekit Combox and other components 

### ISSUE THREAD

**Issue by PriyanshIotWiz** [htmlstreamofficial/preline#387]
### Summary

In component where inline <div class="relative" data-hs-combo-box='{ }'> use it show error Expected }svelte(unexpected-token)

### Steps to Reproduce

Copy from [Dropdown](https://preline.co/docs/searchbox.html#json-example-in-dropdown)
Using JSON example in dropdown.
![refrence](https://github.com/htmlstreamofficial/preline/assets/119488371/80188617-e992-4883-a93a-ed988e0a674d)
 and paste in sveltekit html

it show error like this
![bug](https://github.com/htmlstreamofficial/preline/assets/119488371/2a893733-f70b-4356-a478-40e39825a471)
 So I have to relace this red mark
![orignal](https://github.com/htmlstreamofficial/preline/assets/119488371/d66e8d48-0181-4091-ae93-ca3abaec132c)
with this and its working

![final](https://github.com/htmlstreamofficial/preline/assets/119488371/c532c57a-9130-4fda-89f1-e1cab4913101)

### Demo Link

sad

**Comment by PriyanshIotWiz** [comment]
![carousel](https://github.com/htmlstreamofficial/preline/assets/119488371/39b83fb1-3cf0-4261-ab28-f49f9943d263)
![same error](https://github.com/htmlstreamofficial/preline/assets/119488371/a6c2e86b-06c7-4de4-bbca-33ec51bf64f8)

In each component where  data-hs-XXX ='{
    "loadingClasses": "opacity-0"
  }'
it show error like this in sveltekit 
Expected }svelte(unexpected-token)
Expected }ts(-1)

For example:
<div data-hs-carousel='{
    "loadingClasses": "opacity-0"
  }' class="relative">

**Comment by PriyanshIotWiz** [comment]
For example:
<div data-hs-carousel='{
    "loadingClasses": "opacity-0"
  }' class="relative">

**Comment by olegpix** [comment]
@PriyanshIotWiz Hi,
Try using data attributes like this 
```data-hs-*={`{...rest of the parameters}`}```
You need to put the options object (as a string) between the curly braces.
We have an example of using data options on the "Select" [demo](https://stackblitz.com/edit/dev-preline-2-svelte?file=src%2Fcomponents%2FSelectItem.svelte) page.
