### ISSUE TITLE
Bring the design system to Penpot 

### ISSUE THREAD

**Issue by cmdaltctr** [htmlstreamofficial/preline#388]
### Summary

Bring the open source design system to a versatile, open source design app: Penpot

### Detailed Description

Penpot is an open-source alternative to Figma. Since this is also an open-source design system, I think it's very good to have it on Penpot. I believe Penpot is more robust than Figma, and the concepts of flex and grid, amongst other basic CSS concepts, are not rebranded or "renamed" from the design process at all (i.e. auto layout, looking at you). It allows smooth transition from design to development. The CSS generated from the design is also very good and useable.

### Use Cases

Improving the process from design to development.
No vendor-locking from Figma.

**Comment by jahaganiev** [comment]
Hey @cmdaltctr - thanks for the suggestion!  

Unfortunately, recreating everything on Penpot is not on our radar at the moment.

Hope for your kind understanding!
