### ISSUE TITLE
BUG: Carousel doesn't work when placed unter tab navigation

### ISSUE THREAD

**Issue by coolusaHD** [htmlstreamofficial/preline#392]
### Summary

Carousel doesn't work when placed unter tab navigation.

### Steps to Reproduce

1. Open Demo
2. Run
3. Click trough the tab navigation

![image](https://github.com/htmlstreamofficial/preline/assets/56646413/da120569-93c6-43ba-8b49-a458aefa3d2e)

### Demo Link

https://stackblitz.com/edit/withastro-astro-fzqgqu?file=src%2Fpages%2Findex.astro

**Comment by olegpix** [comment]
> ### Summary
> Carousel doesn't work when placed unter tab navigation.
> 
> ### Steps to Reproduce
> 1. Open Demo
> 2. Run
> 3. Click trough the tab navigation
> 
> ![image](https://private-user-images.githubusercontent.com/56646413/339792183-da120569-93c6-43ba-8b49-a458aefa3d2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MTUwODYsIm5iZiI6MTcyMDcxNDc4NiwicGF0aCI6Ii81NjY0NjQxMy8zMzk3OTIxODMtZGExMjA1NjktOTNjNi00M2JhLThiNDktYTQ1OGFlZmEzZDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE2MTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiOGI0NmU5Njg1MGRmYzc4YmFlZTIzODg5ZDc3NmVmYmIxNjljZjdlZGMzOTQ4OWZhMjFjZWU0MjE0ZDgyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.30QvtoW-zGgR3oUn6UYr3PwK5ETP8Tz-BvNhx3EKN0U)
> 
> ### Demo Link
> https://stackblitz.com/edit/withastro-astro-fzqgqu?file=src%2Fpages%2Findex.astro
> 
> ### Expected Behavior
> _No response_
> 
> ### Actual Behavior
> _No response_
> 
> ### Screenshots
> _No response_

Hi,
You need to recalculate the carousel width every time you change tab (check the full code in the [demo](https://stackblitz.com/edit/withastro-astro-n5kx9l?file=src%2Fpages%2Findex.astro))

```
<script type="module">
  window.addEventListener('load', () => {
    const tabs = HSTabs.getInstance("#tabs-01", true);
    tabs.element.on('change', ({ current }) => {
      const carousel = HSCarousel.getInstance(`${current} [data-hs-carousel]`, true);
      carousel.element.recalculateWidth();
    });
  });
</script>
```
