### ISSUE TITLE
HSOverlay.on not working

### ISSUE THREAD

**Issue by pastc** [htmlstreamofficial/preline#393]
### Summary

The event listeners on the overlay is not working.

Using Vue3

### Steps to Reproduce

```
import { HSOverlay } from 'preline'

onMounted(() => {
  const modalElement = document.querySelector('#hs-scan') as HTMLElement
  const modal = new HSOverlay(modalElement)

  console.log(modal)

  if (modal) {
    modal.on('open', () => {
      console.log('Modal opened')
      // modalIsOpen.value = true
      // console.log(modalIsOpen.value)
    })

    modal.on('close', () => {
      console.log('Modal closed')
      // modalIsOpen.value = false
      // console.log(modalIsOpen.value)
    })
  }
})
```

### Expected Behavior

Should print the corresponding strings when opened and closed

### Actual Behavior

Doesn't print anything

**Comment by pastc** [comment]
I ended up using vueuse to check if its open.
https://vueuse.org/core/useElementVisibility/

**Comment by Fed3x** [comment]
Can you share your solution?

**Comment by pastc** [comment]
@Fed3x 
> I ended up using vueuse to check if its open. https://vueuse.org/core/useElementVisibility/
