### ISSUE TITLE
Programatically show/hide accordion: bug or am I doing it wrong? 

### ISSUE THREAD

**Issue by RSchmitzHH** [htmlstreamofficial/preline#394]
### Summary

Programatically opening and closing accordion works once, then stops working.

### Steps to Reproduce

I have this accordion

``` <div class="hs-accordion-group flex min-w-full w-full max-w-full ">
    <div
      class="hs-accordion active group cursor-pointer p-4 min-w-full w-full max-w-full flex flex-col justify-center bg-white border border-gray-200 rounded-xl dark:bg-neutral-800 dark:border-neutral-700"
      :id="accordionId"
    >
```

In my onMounted, I (sucessfully) create a ref 

```
onMounted(async () => {
  await nextTick(async () => {
    HSStaticMethods.autoInit();
    accordion.value = new HSAccordion(document.getElementById(accordionId.value));
...
```  

I can now show and hide this accordion using `accordion.value.hide()` and `accordion.value.hide()`. 

However, this cycle works only once. The second time I want to show, nothing happens. `accordion.value` is still valid and references the accordion. 

A functioning workaround is 

```
    <div
      class="hs-accordion group cursor-pointer p-4 min-w-full w-full max-w-full flex flex-col justify-center bg-white border border-gray-200 rounded-xl dark:bg-neutral-800 dark:border-neutral-700"
      :class="{
        'active': showAccordiong,
      }"
      :id="accordionId"
    >
```
where I additionally with calling show() and hide(), I set showAccordiong to true and false, respectively.

However, following your documentation, this should not be necessary, should it? 

Am I doing something wrong? 

Cheers

### Demo Link

N/A

### Expected Behavior

Calling `accordion.value.show()` and 'accordion.value.hide()' shall show and hide the accordion, respectively. 

### Actual Behavior

Calling `accordion.value.show()` and 'accordion.value.hide()' shows and hide the accordion once, but then stops working. Additionally setting/ removing 'active' as a conditional class functions as a workaround (c.f. above).

**Comment by olegpix** [comment]
> ### Summary
> Programatically opening and closing accordion works once, then stops working.
> 
> ### Steps to Reproduce
> I have this accordion
> 
> ```
>     <div
>       class="hs-accordion active group cursor-pointer p-4 min-w-full w-full max-w-full flex flex-col justify-center bg-white border border-gray-200 rounded-xl dark:bg-neutral-800 dark:border-neutral-700"
>       :id="accordionId"
>     >
> ```
> 
> In my onMounted, I (sucessfully) create a ref
> 
> ```
> onMounted(async () => {
>   await nextTick(async () => {
>     HSStaticMethods.autoInit();
>     accordion.value = new HSAccordion(document.getElementById(accordionId.value));
> ...
> ```
> 
> I can now show and hide this accordion using `accordion.value.hide()` and `accordion.value.hide()`.
> 
> However, this cycle works only once. The second time I want to show, nothing happens. `accordion.value` is still valid and references the accordion.
> 
> A functioning workaround is
> 
> ```
>     <div
>       class="hs-accordion group cursor-pointer p-4 min-w-full w-full max-w-full flex flex-col justify-center bg-white border border-gray-200 rounded-xl dark:bg-neutral-800 dark:border-neutral-700"
>       :class="{
>         'active': showAccordiong,
>       }"
>       :id="accordionId"
>     >
> ```
> 
> where I additionally with calling show() and hide(), I set showAccordiong to true and false, respectively.
> 
> However, following your documentation, this should not be necessary, should it?
> 
> Am I doing something wrong?
> 
> Cheers
> 
> ### Demo Link
> N/A
> 
> ### Expected Behavior
> Calling `accordion.value.show()` and 'accordion.value.hide()' shall show and hide the accordion, respectively.
> 
> ### Actual Behavior
> Calling `accordion.value.show()` and 'accordion.value.hide()' shows and hide the accordion once, but then stops working. Additionally setting/ removing 'active' as a conditional class functions as a workaround (c.f. above).
> 
> ### Screenshots
> _No response_

Hi,
This may be due to the fact that you are using `HSStaticMethods.autoInit()` and at the same time creating the component using the constructor ("new HSAccordion"). To better understand the problem, could you fork one of our demo versions and add your code please.
You can find demos here [https://stackblitz.com/@jahaganiev](https://stackblitz.com/@jahaganiev), just create a fork and add your code. It's important for us to understand your specific problem, which is why it's so important when you fork and add code that doesn't work for you.

**Comment by RSchmitzHH** [comment]
Hi @olegpix ,
many thanks for your reply, will try without autoInit. I will also do the fork and add my code for your experiments -- highly appreciated that you want to look into it in detail. However, this will take some time. 
Cheers!

**Comment by jahaganiev** [comment]
Hey @RSchmitzHH - we will revisit once the StackBlitz link is shared. Thanks!

**Comment by RSchmitzHH** [comment]
Hi @olegpix & @jahaganiev ,

using your StackBlitz, I do not manage to get a version running where I programatically open and close the accordion using Vue. 

Can you please share a fork which demonstrates how this shall be achieved? 



P.S. 

I once had the following version fully functional: 
```
const accordion = ref(null);
const idSuffix = ref(uuidv4());   // the ref is of course unecessary in this example
const accordionId = computed(() => {
  return 'hs-basic-with-arrow-heading-' + idSuffix.value;
});
const isOpen = ref(false); 

onMounted(async () => {
  await nextTick(async () => {

    console.log('accordionId: ', accordionId.value);  // logs: hs-basic-with-arrow-heading-b8de2ec5-308d-4155-be25-cc244380e174 etc

    accordion.value = new HSAccordion(document.getElementById(accordionId.value));
    // so without the unnecessary autoInit. Was once working, breaks now. 

    console.log('accordion: ', accordion.value);
})

[....]
<template>

   <div class="hs-accordion-group">

       <div
      @click="toggle"
      class="hs-accordion"
      :class="{
        active: isOpen,
      }"
      :id="accordionId"
    >

        <!-- Note: removed "hs-accordion-toggle" to open/close functionally only -->
         <button class="">

        </button>
    </div>

  </div>

</template>
```

However, with one of your recent updates, this stopped working. What was once working now breaks at 
```
accordion.value = new HSAccordion(document.getElementById(accordionId.value));
```
with 
```
Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```

As I neither get any of the versions documented at https://preline.co/plugins/html/accordion.html working, I am left with the hope for your help. 

And, I must say, I start getting extremely frustrated on how many breaking changes or instabilities I experience with the combination of preline and Vue in my production system. 

I keep getting problem whenever I go beyond your pure js examples and try to programatically interfere with your components. Quite often, only some of the approaches in your documentation work and, what's even worse, this changes with your updates. 

So, you could please share a full code of a working version of how one shall **programatically** interfere with your components (dropdowns, accordions, modals/overlay, ...) using Vue? So to speak, what is the recommended approach to fill a ref in the onMounted using an element id and then programatically show/open, close/hide, ... the thing? There must be one recommended approach?

**Comment by RSchmitzHH** [comment]
You'll now find the once-working-but-not-anymore and now-working-but-not-documented-and-not-desired constructor versions here: 

https://stackblitz.com/edit/preline-v2-vue-and-vue-router-3zsxujqi?file=src%2Fcomponents%2FAccordionItem.vue

Why is the working version not desired? 

Apart from the fact that one would need a hidden button with hs-accordiom-toggle, which is a bit hacky, this does not really achieve the desired behavior here as the accordion does not really collapse to the desired state (=only showing the button content).

**Comment by RSchmitzHH** [comment]
Please reopen @olegpix @jahaganiev - thanks in advance!
