### ISSUE TITLE
Switching screen size causes error

### ISSUE THREAD

**Issue by daninus14** [htmlstreamofficial/preline#397]
Switching screen size causes an error

```jsx
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at autoCloseResizeFn (preline.js?v=6be11204:2538:36)
    at preline.js?v=6be11204:2562:3
```

**Steps to reproduce:**

1. Open a view
2. resize the screen (with chrome or firefox) to mobile from desktop sized or vice versa

Any ideas on how to approach this?

**Comment by jahaganiev** [comment]
Hey @daninus14 - on which Preline's live page you're see that?

**Comment by daninus14** [comment]
I saw it on my own local app.

**Comment by jajabo** [comment]
I have the same problem when resizing the screen,  

TypeError: Cannot read properties of undefined (reading 'length') 
node_modules/@preline/overlay/index.js (17:10220)
version 2.4.1

![截圖 2024-07-29 下午4 37 36](https://github.com/user-attachments/assets/bc3ec90c-9328-44eb-98c7-d3807f461d4d)
any suggestions

**Comment by daninus14** [comment]
I started removing the preline js plugins and implementing them on my own on react or using adobe's react aria package and all the errors are gone...

**Comment by jajabo** [comment]
> I started removing the preline js plugins and implementing them on my own on react or using adobe's react aria package and all the errors are gone...

How to implement it? Is there any information that I can refer to?
