### ISSUE TITLE
Request for Carousel

### ISSUE THREAD

**Issue by ICTLAYER** [htmlstreamofficial/preline#4]
Hello dev team,

Great Job yet. Hope your team is working on Carousel. Though I refer you 
https://tailwindcss.com/docs/scroll-snap-stop
https://daisyui.com/components/carousel/

Please give the update ASAP.
Also, give an update for NUXT v3 Compatibility.

Good Luck & Thank you.

**Comment by Mr-Zafar** [comment]
Hi, @ICTLAYER -

We will take this into account in future updates, but for now, you can consider using [Swiper JS](https://swiperjs.com/)

As for full compatibility with NUXT v3, it's on our roadmap, but at the moment we can't give an ETA for this feature.

Thanks!

**Comment by jahaganiev** [comment]
Hey @ICTLAYER - we've just released v2.0 which features a Carousel component https://preline.co/docs/carousel.html

Please feel free to share if you have more suggestions for future updates!

Cheers!
