### ISSUE TITLE
Sveltekit Error : Property 'HSStaticMethods' does not exist on type 'Window & typeof globalThis'

### ISSUE THREAD

**Issue by P00HB33R** [htmlstreamofficial/preline#401]
### Summary

Getting the error "Property 'HSStaticMethods' does not exist on type 'Window & typeof globalThis'" when adding the afterNavigate function as per documentation for sveltekit

### Steps to Reproduce

1. Create new sveltekit project as per docs.
2. Add afterNavigate function HSStatic

### Demo Link

#

### Expected Behavior

There should be no error

### Actual Behavior

Property 'HSStaticMethods' does not exist on type 'Window & typeof globalThis'

**Comment by olegpix** [comment]
> ### Summary
> Getting the error "Property 'HSStaticMethods' does not exist on type 'Window & typeof globalThis'" when adding the afterNavigate function as per documentation for sveltekit
> 
> ### Steps to Reproduce
> 1. Create new sveltekit project as per docs.
> 2. Add afterNavigate function HSStatic
> 
> ### Demo Link
> ### Expected Behavior
> There should be no error
> 
> ### Actual Behavior
> Property 'HSStaticMethods' does not exist on type 'Window & typeof globalThis'
> 
> ### Screenshots
> _No response_

Hi,
For now you can declare static methods in a file. We'll add it globally in future versions.

```
import { IStaticMethods } from 'preline/src/static/interfaces';

declare global {
	interface Window {
		HSStaticMethods: IStaticMethods;
	}
}
```

**Comment by bonclairvoyante** [comment]
> > ### Summary
> > Getting the error "Property 'HSStaticMethods' does not exist on type 'Window & typeof globalThis'" when adding the afterNavigate function as per documentation for sveltekit
> > ### Steps to Reproduce
> > 
> > 1. Create new sveltekit project as per docs.
> > 2. Add afterNavigate function HSStatic
> > 
> > ### Demo Link
> > ### Expected Behavior
> > There should be no error
> > ### Actual Behavior
> > Property 'HSStaticMethods' does not exist on type 'Window & typeof globalThis'
> > ### Screenshots
> > _No response_
> 
> Hi, For now you can declare static methods in a file. We'll add it globally in future versions.
> 
> ```
> import { IStaticMethods } from 'preline/src/static/interfaces';
> 
> declare global {
> 	interface Window {
> 		HSStaticMethods: IStaticMethods;
> 	}
> }
> ```

You comment is timely. Thank you. However, I have a question ... decalring static methods in a file. Which file should this be done in?

**Comment by bonclairvoyante** [comment]
> > ### Summary
> > Getting the error "Property 'HSStaticMethods' does not exist on type 'Window & typeof globalThis'" when adding the afterNavigate function as per documentation for sveltekit
> > ### Steps to Reproduce
> > 
> > 1. Create new sveltekit project as per docs.
> > 2. Add afterNavigate function HSStatic
> > 
> > ### Demo Link
> > ### Expected Behavior
> > There should be no error
> > ### Actual Behavior
> > Property 'HSStaticMethods' does not exist on type 'Window & typeof globalThis'
> > ### Screenshots
> > _No response_
> 
> Hi, For now you can declare static methods in a file. We'll add it globally in future versions.
> 
> ```
> import { IStaticMethods } from 'preline/src/static/interfaces';
> 
> declare global {
> 	interface Window {
> 		HSStaticMethods: IStaticMethods;
> 	}
> }
> ```

You comment is timely as I also had a similar issue. Thank you.

**Comment by jahaganiev** [comment]
Hey @P00HB33R - please check out the latest version, the issue has been fixed. Thanks!

**Comment by bonclairvoyante** [comment]
Thank you.
Barry Sande.
