### ISSUE TITLE
Accordion button doesn't toggle with open accordion

### ISSUE THREAD

**Issue by craigharman** [htmlstreamofficial/preline#403]
### Summary

Clicking an accordion button to open it doesn't rotate the ^

### Steps to Reproduce

1. Copy the accordion HTML from this example: https://preline.co/docs/accordion.html#with-title-and-arrow-stretched
2. Install preline via `npm i preline`
3. Import via `import preline from 'preline/dist/preline'`
4. Load the page

### Demo Link

https://codesandbox.io/p/devbox/competent-thompson-fcfyzj?file=/src/index.mjs:3,1&welcome=true

### Expected Behavior

The ^ character should turn upside down when a panel is opened (like it does on the demo page).

### Actual Behavior

The character stays the same.

All other behaviour works as expected.

**Comment by olegpix** [comment]
> ### Summary
> Clicking an accordion button to open it doesn't rotate the ^
> 
> ### Steps to Reproduce
> 1. Copy the accordion HTML from this example: https://preline.co/docs/accordion.html#with-title-and-arrow-stretched
> 2. Install preline via `npm i preline`
> 3. Import via `import preline from 'preline/dist/preline'`
> 4. Load the page
> 
> ### Demo Link
> https://codesandbox.io/p/devbox/competent-thompson-fcfyzj?file=/src/index.mjs:3,1&welcome=true
> 
> ### Expected Behavior
> The ^ character should turn upside down when a panel is opened (like it does on the demo page).
> 
> ### Actual Behavior
> The character stays the same.
> 
> All other behaviour works as expected.
> 
> ### Screenshots
> _No response_

Hi,
It seems you forgot to add the `preline/plugin.js` file to the `the tailwind.config.js`.

```
export default {
  content: ["src/index.html"],
  theme: {},
  plugins: [require("./node_modules/preline/plugin")],
};
```

**Comment by craigharman** [comment]
I've added that to the demo via:

```ts
import preline from 'preline/plugin'

export default {
  content: ["src/index.html"],
  theme: {},
  plugins: [preline],
};
```

Still doesn't seem to work.
