### ISSUE TITLE
Dropdown is positioned wrong with backdrop-blur-md on navbar

### ISSUE THREAD

**Issue by fsmeier** [htmlstreamofficial/preline#405]
### Summary

If you use the dropdown together with backdrop-blur-md the dropdown is positioned wrong within the navbar.

### Steps to Reproduce

1.  Use a navbar with dropdown, for example https://preline.co/examples/navigations-navbars.html#header-floating-dark
2. Add `backdrop-blur-md` to the navbar element
3. Dropdown menu is no longer positioned under the trigger-element

### Demo Link

https://stackblitz.com/edit/preline-v2-astro-ljhc4h?file=src%2Flayouts%2FLayout.astro

### Expected Behavior

The dropdown-menu should be positioned correctly (like without the backdrop-blur class)

### Actual Behavior

The dropdown-menu is positioned wrongly when backdrop-blur-md is used.

### Screenshots

![Screenshot 2024-07-12 at 20 55 06](https://github.com/user-attachments/assets/52021c2e-03fc-43d9-a347-3a643e6ee73a)
![Screenshot 2024-07-12 at 20 49 10](https://github.com/user-attachments/assets/520bf78d-658e-4a0d-a2bb-00cfcf7ea270)

**Comment by olegpix** [comment]
@fsmeier Hi,
Internally we use Popper.js for positioning the dropdowns. We assume that
Popper.js or similar positioning libraries often rely on the calculated position and dimensions of elements to calculate the popper placement. If the parent element has a `backdrop-filter` property, the browser may handle rendering of this element in a different layer, causing small shifts or miscalculations in how Popper.js interprets the position.
We propose to use a separate element that will contain the necessary styles for such cases, and position it relative to the parent.
I created a [fork](https://stackblitz.com/edit/preline-v2-astro-zxrnln?file=src%2Flayouts%2FLayout.astro) where I showed how this can be implemented.
