### ISSUE TITLE
Typo in ComboBox plugin instruction

### ISSUE THREAD

**Issue by hieuhuynh93** [htmlstreamofficial/preline#408]
Hi,
During researching the [ComboBox plugin](https://preline.co/plugins/html/combobox.html), I found the typo in the `Open item (mixed)` section. 

It must be `HSComboBox` instead of  `HSCopyMarkup`

![Qae5GJ3e-20240717102815@2x](https://github.com/user-attachments/assets/642e9565-8275-4890-bef0-24b920879606)

**Comment by jahaganiev** [comment]
Hey @hieuhuynh93 - thanks for pointing out, it's been fixed with v2.4.0 update.
