### ISSUE TITLE
The examples page is missing necessary CSS.

### ISSUE THREAD

**Issue by f3liiix** [htmlstreamofficial/preline#409]
### Summary

The examples page is missing necessary CSS

### Detailed Description

This will result in some interactive effects not working.

For example, this one: [https://preline.co/examples/html/mega-menu-header.html](https://preline.co/examples/html/mega-menu-header.html)

Simply copying the HTML code will not achieve the expected results. You must copy the CSS for the "hs-dropdown" section from this file([https://preline.co/assets/css/main.min.css?v=2.3.0](https://preline.co/assets/css/main.min.css?v=2.3.0)) to my own CSS file.

### Use Cases

I suggest adding the CSS code to  each example page if it is necessary.

**Comment by jahaganiev** [comment]
Hey @f3liiix,

Please note that Preline does not include a CSS file, as it requires you to first install and run Tailwind CSS. Once Tailwind CSS is installed and running, Preline's styles will be automatically added to your CSS file.

Cheers!
