### ISSUE TITLE
Unable to use conditional render with Preline Js features

### ISSUE THREAD

**Issue by luanfonsecap** [htmlstreamofficial/preline#410]
### Summary

Js features not work on components that conditionally render

### Steps to Reproduce

I will use `Accordion` component to reproduce this bug, but any component that requires Preline Js to properly work's will fail.

1. Setup `Accordion` in a React component;
2. Import and render this component, work`s fine;
3. Add a conditional rendering using a button to change some state and render's the `Accordion` when it's value's is `true`.
4. Start the `useState` with `true`.
5. Interact with  `Accordion`, still working.
6. Click on button to change state for `false`.
7. Click again to to change state for `true` and component appears.
8. Interact with  `Accordion`, not working js features anymore.

### Demo Link
https://codesandbox.io/p/devbox/preline-ui-k9nsvg?file=%2Fapp%2Fpage.tsx%3A19%2C17

### Expected Behavior

Still working js features when need conditional rendering.

### Actual Behavior

Js features stop working when component appears.

**Comment by ebraheemijaz** [comment]
i noticed same behaviour for "modal" as well

**Comment by luanfonsecap** [comment]
@langscot @ebraheemijaz Thank you, it helped a lot!
