### ISSUE TITLE
drop down below each other appear under the following button

### ISSUE THREAD

**Issue by EssaAlshammri** [htmlstreamofficial/preline#415]
### Summary

drop down below each other appear under the following button

### Steps to Reproduce

add multiple dropdown below each other in a table row for example 
then click on any of them to see the issue

### Demo Link

no

### Expected Behavior

add z-10 to the hs-dropdown-menu z-10

### Screenshots

![image](https://github.com/user-attachments/assets/1acc3b6a-69bc-4384-8bf4-71cead1657a6)

when I add z-10 

![image](https://github.com/user-attachments/assets/4b62e1ca-97a9-470a-8895-9b08910373f6)

**Comment by olegpix** [comment]
@EssaAlshammri Hi,
That's true, but as I see, our [demo](https://preline.co/docs/advanced-select.html#basic-usage) already contains this class (`z-50`).
