### ISSUE TITLE
Can't select the last item when the Dropdown item list to long to extend out of the screen

### ISSUE THREAD

**Issue by yashika** [htmlstreamofficial/preline#42]
Can't select the last item when the Dropdown item list to long to extend out of the short screen.
for example:
Dropdown have 100 items. but the current web page only 500px height.

the dropdown list will extend out of the screen but can not select or scroll to the last one.

**Comment by Mr-Zafar** [comment]
Set the dropdown menu position to [[--strategy:absolute]](http://localhost:3002/plugins/html/dropdown.html#js-options) to be able to scroll. You cannot scroll when it is fixed.
