### ISSUE TITLE
ApiHeaders from combobox are not api headers

### ISSUE THREAD

**Issue by bartosz-stafiej** [htmlstreamofficial/preline#424]
### Summary

Hi I just spot a little problem with the docs / implementation of the Combobox.

### Steps to Reproduce

https://preline.co/plugins/html/combobox.html#js-behavior

Here in the description you have option `apiHeaders`, it is kinda misleading, because I saw in your implementation that this option does not allow to set apiHeaders but request config.
Please change the description or option name, because it is not a apiHeaders but apiOptions

### Demo Link

https://github.com/htmlstreamofficial/preline/blob/3f8c2fcbc24b2572350fa88499e9c917da2ea470/src/plugins/combobox/index.ts#L327C4-L327C50

### Expected Behavior

I want to configure:

```
  const comboBoxConfig = {
    // config
    apiHeaders: { Authorization: `Bearer ${token}` },
  }
```

  or
  
    const comboBoxConfig = {
    // config
    apiConfig: { headers: { Authorization: `Bearer ${token}` } },
  }

### Actual Behavior

I had to configure:

```
  const comboBoxConfig = {
    // config
    apiHeaders: { headers: { Authorization: `Bearer ${token}` } },
  }
```

**Comment by olegpix** [comment]
@bartosz-stafiej Hi,
Thank you for your comment, but at the moment we cannot change the name, because probably some users are already using this parameter name and it can lead to bugs when updating for these users. We will probably return to this in version 3.
