### ISSUE TITLE
`HSFileUpload.getInstance` cannot be instantiated to receive events from Dropzone

### ISSUE THREAD

**Issue by luishiguera** [htmlstreamofficial/preline#425]
### Summary

I cannot instantiate HSFileUpload to receive events and responses from the upload endpoint to store the URLs

### Steps to Reproduce

1. Import preline, lodash, dropzone and tailwind
2. Use the data-hs-file-upload attribute: Follow the instructions from [https://preline.co/plugins/html/file-upload.html](https://preline.co/plugins/html/file-upload.html)
3. Initialize HSFileUpload `<script>
    window.addEventListener('load', () => {
        const { element } = HSFileUpload.getInstance('#hs-file-upload', true);
        console.log(element);
    });
</script>`

### Demo Link

https://stackblitz.com/edit/vitejs-vite-gk4mac?file=index.html&terminal=dev

### Expected Behavior

Use the HSFileUpload wrapper to access Dropzone methods

### Actual Behavior

TypeError: Cannot read properties of null (reading 'getInstance')

### Screenshots

![image](https://github.com/user-attachments/assets/fb966ee8-03ae-4012-90c3-abbcf16e19ed)
![image](https://github.com/user-attachments/assets/9750a7a2-32c0-45e8-9fe7-801fcd55a9fa)

**Comment by luishiguera** [comment]
it worked, thank you

**Comment by billpebert** [comment]
@langscot Hi, the suggested solution doesn't working on my code
![image](https://github.com/user-attachments/assets/349b93f7-a5ae-47f6-bd99-6d44c6372536)

![image](https://github.com/user-attachments/assets/975ec252-2dd4-495b-a84a-c7e7bca34d5d)
![image](https://github.com/user-attachments/assets/5a7480d7-8a36-4e49-805b-a211e34ba83b)

**Comment by FordSmh** [comment]
> @langscot Hi, the suggested solution doesn't working on my code regarding this doc https://preline.co/docs/file-upload.html#error
> 
> i've also installed these following packages: _npm i lodash dropzone @preline/file-upload_
> 
> ![image](https://private-user-images.githubusercontent.com/70867121/387457482-349b93f7-a5ae-47f6-bd99-6d44c6372536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzAyODcsIm5iZiI6MTczMzcyOTk4NywicGF0aCI6Ii83MDg2NzEyMS8zODc0NTc0ODItMzQ5YjkzZjctYTVhZS00N2Y2LWJkOTktNmQ0NGM2MzcyNTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA3Mzk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMGVkZDE4OTBjMTExMjg3Nzk0Yjg0Njk1YmY1NWEwYmRlN2VmYzVmNDcwODMyMzlkYzg4Zjc1MGNkN2QxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.phWicrDnQsrHQSRT25TgzZPgolkdXkw5C4aPsCovYtE)
> 
> ![image](https://private-user-images.githubusercontent.com/70867121/387457537-975ec252-2dd4-495b-a84a-c7e7bca34d5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzAyODcsIm5iZiI6MTczMzcyOTk4NywicGF0aCI6Ii83MDg2NzEyMS8zODc0NTc1MzctOTc1ZWMyNTItMmRkNC00OTViLWE4NGEtYzdlN2JjYTM0ZDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA3Mzk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMmYwMTI2MzEwNjljMGY3MWQ3ZWM1NjJkMjJjZjZiNWIyZDI1MmQ3YTU3Y2I5YjA0MTcxYjdhNTFhMDQ5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ft-P4hTCjAK_f504qenEIq8xsTHE_d5UZ42wCw5J9cw)
> 
> this is the config on resources\js\app.js ![image](https://private-user-images.githubusercontent.com/70867121/387457616-5a7480d7-8a36-4e49-805b-a211e34ba83b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzAyODcsIm5iZiI6MTczMzcyOTk4NywicGF0aCI6Ii83MDg2NzEyMS8zODc0NTc2MTYtNWE3NDgwZDctOGEzNi00ZTQ5LTgwNWItYTIxMWUzNGJhODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA3Mzk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZGM0OTgzZDA4NTcyYTlhOTdmZjc3NjJlNDIzYjkxNjk4NmRkNmE0NzNlMTAwMzhjMWQwMTc0N2IxYzM0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ciLi5jOOHvhpG8zkm6dCHWpgNriCKw_YZViu7x9ITgM)

have you managed to fix this? I have the same problem

**Comment by mathewhborja** [comment]
Same issue here. Need a fix asap.

**Comment by Vladimir-Vorontsov** [comment]
import "preline";
import "@preline/file-upload";
