### ISSUE TITLE
"JSX" code tab for the examples

### ISSUE THREAD

**Issue by langscot** [htmlstreamofficial/preline#428]
### Summary

Provide a "JSX" code version of the examples

### Detailed Description

Currently, in the example component, there's a "Preview" and "HTML" tab. The HTML tab shows you the raw HTML source code. It would be extremely useful to have a "JSX" tab for React developers. The JSX tab would show the same raw HTML source code, but conform to JSX syntax, for example:

className, htmlFor, strokeWidth, strokeLinejoin, strokeLinecap, making `input` and `img` tags self-closing, etc. Chaning the `<!-- -->` comments to JSX `{/* */}`

This would make the copy-paste experience a lot nicer for React developers and speed up productivity, as currently I need to manually clean the pasted code each time I use a snippet.

### Use Cases

React developers, or anyone making use of JSX

**Comment by jahaganiev** [comment]
duplicated #398 

Our main concern is the user experience. Adding a JSX option might significantly confuse users into thinking that Preline UI is a React component library. However, we might consider this feature in the future.

You may consider using third party plugins in your code editor to address this issue.

**Comment by TorbenHammes** [comment]
Maybe you could do it like  HyperUI: https://www.hyperui.dev/components/application-ui/dropdown

I would appreciate a JSX feature next to HTML.

Greetings from Berlin, Torben
