### ISSUE TITLE
Need Help Adding Action Buttons in DataTable Fetching Data from JSON

### ISSUE THREAD

**Issue by PruthviPraj00** [htmlstreamofficial/preline#430]
Hi @olegpix,

I'm working on creating a DataTable that fetches data from a JSON file and need help integrating action buttons (like checkboxes) into the table. Currently, I can successfully render regular data, but I want to enhance it with action buttons and other functionalities. Here's what I'm aiming to achieve:

1. **JSON Data Source:** The data should be dynamically loaded from a JSON file.
2. **Action Buttons:** I need to include action buttons (e.g., checkboxes) in each row of the table, similar to the example image provided.
   ![Screenshot 2024-08-07 at 7 30 58 PM](https://github.com/user-attachments/assets/7c539d5b-b2e9-4211-bf19-823cd27b5ad3)

Below is the code I have so far, which successfully renders the regular data from a JSON file:
![Screenshot 2024-08-07 at 7 32 24 PM](https://github.com/user-attachments/assets/b8376d65-f6cb-4619-95e6-43662884c7e9)

```html
<div class="flex flex-col w-full" id="assdatatable" data-hs-datatable='{
  "pageLength": 10,
  "pagingOptions": {
    "pageBtnClasses": "min-w-[40px] flex justify-center items-center text-gray-800 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 py-2.5 text-sm rounded-full disabled:opacity-50 disabled:pointer-events-none"
  },
  "ajax": "/json/user-list.json",
  "columns": [
    { "data": "full_name" },
    { "data": "role" },
    { "data": "current_plan" },
    { "data": "billing" },
    { "data": "status" },
  ]
}'>
  <table class="table">
    <thead>
      <tr>
        <th>User</th>
        <th>Role</th>
        <th>Plan</th>
        <th>Billing</th>
        <th>Status</th>
      </tr>
    </thead>
  </table>
  <!-- Pagination code -->
</div>
```

I would appreciate any guidance on how to:

1. **Integrate Action Buttons:** Add action buttons or checkboxes to each row.
2. **Customize DataTable Behavior:** Ensure that these buttons interact properly with the DataTable functionalities.

If possible, please provide an example in your documentation.

Thanks in advance for your help!

**Comment by olegpix** [comment]
@PruthviPraj00 Hi,
I will try to describe the steps that I hope will solve your problem:
1. Add class `--prevent-on-load-init` to initialized element to prevent automatic initialization, add identifier
```
<div id="hs-test-dt" class="--prevent-on-load-init" data-hs-datatable='{
 ... data options here
}'>
```
2. Initialize table with js
```
new HSDataTable('#hs-test-dt', {
  columnDefs: [
    {
      targets: 0,
      orderable: false,
      searchable: false,
      render: function (data, type, row) {
        return '<input type="checkbox" class="row-checkbox">';
      },
    },
    {
      targets: -1,
      orderable: false,
      searchable: false,
      render: function (data, type, row) {
        return '<button class="delete-row">Delete</button>';
      },
    },
  ],
  ... rest of the options here
});
```

`columnDefs` parameter will help you add additional markup

**Comment by PruthviPraj00** [comment]
@olegpix,

I'm sorry, but I cannot get your solution to work. Could you please provide an example on Stackblitz?
