### ISSUE TITLE
Dropdown doesn't work after hot reload in SvelteKit

### ISSUE THREAD

**Issue by rstcruzo** [htmlstreamofficial/preline#437]
### Summary

When you edit a dropdown and hot reload triggers, the dropdown does not work anymore

### Steps to Reproduce

1. Go to the example in the documentation https://stackblitz.com/edit/preline-v2-svelte-btpdf2?file=src%2Fcomponents%2FDropdownItem.svelte
2. Change a dropdown item. For instance, rename Newsletter to Edited
3. Try to click the dropdown again

### Demo Link

https://stackblitz.com/edit/preline-v2-svelte-btpdf2?file=src%2Fcomponents%2FDropdownItem.svelte

### Expected Behavior

The dropdown should still work after hot reloading

### Actual Behavior

The dropdown does not work anymore

**Comment by oliverhaas** [comment]
It probably does not get properly initialized again. I guess Svelte HMR does not fully reload the page.

Just to test it you can add

```html
  <script>
    HSDropdown.autoInit();
    </script>
```

to your html. I wouldn't even call it a hacky solution though. See other issues regarding ajax and (re-)initialization; I think there are quite some flaws in preline regarding this.

**Comment by digitalit** [comment]
Hi guys,

A bit late to the party but i just bought a pro license and started implement Preline to SvelteKit/Svelte 5 and this is how i got Preline to work flawless:

1. copy all files from node_modules/preline/dist to static/preline
2. in tailwwind.config.ts:
```
import typography from '@tailwindcss/typography';
import type { Config } from 'tailwindcss';
export default {
	content: ['./src/**/*.{html,js,svelte,ts}', './src/preline/*.js'],

	// darkMode: 'class',
	theme: {
		extend: {}
	},

	plugins: [typography, require('preline/plugin')]
} satisfies Config;
```
3. in app.html:
```
	<script src="%sveltekit.assets%/preline/preline.js"></script>
	</body>
```
4. in routes/+layout.ts:
```
import type { IStaticMethods } from 'preline/src/static/interfaces';

declare global {
	interface Window {
		HSStaticMethods: IStaticMethods;
	}
}
```
5. in +layout.svelte:
```
<script lang="ts">
	import '../app.css';
	import { afterNavigate } from '$app/navigation'; 

	let { children } = $props();

	afterNavigate(() => {
		window.HSStaticMethods.autoInit();
	});
</script>
 
<div class="pb-[20px] px-[10px] sm:px-[50px] mt-2  sm:mt-8">
	{@render children()}
</div>
```
6. in every xxxx.svelte file:
```
<script lang="ts">
	$effect(() => {
		window.HSStaticMethods.autoInit();
	});
</script>
<div data-hs-stepper>
.........
```

**Comment by oliverhaas** [comment]
I'm not familiar with Svelte at all, so I don't know what's the most efficient way to go about this.

You just have to make sure that autoInit() is called every time something (specifically a preline component) is added to the DOM. For that I'd expect to find something like an event listener/handler in a somewhat global file that takes care of that. So your `afterNavigation` in your `layout.svelte` sounds correct, while adding something to all .svelte files sounds not clean/efficient, but could work.

Unsubscribing, since it is not really my ballpark.

**Comment by digitalit** [comment]
> adding something to all .svelte files sounds not clean/efficient

well, this is only for hot module reload in development and only in the *.svelte files where Preline js is used. 

Other wise it's not needed.
