### ISSUE TITLE
Change backdrop color for offcanvas and modals

### ISSUE THREAD

**Issue by koossaayy** [htmlstreamofficial/preline#44]
Hello, 
First of all, Thank you so much for preline, it's really amazing. 
How ever, I have a little issue, 
I want to change the color of the backdrop container. 
I was able to do so using javascript, but opening the offcanvas, there's a flickering for the initial color. 
```js
let $offcanvasEl = document.getElementById('hs-overlay-bottom');
$offcanvasEl.addEventListener('open.hs.overlay', (event) => {
    let element = document.querySelector('[data-hs-overlay-backdrop-template]');
    element.classList.remove('bg-gray-900');
    element.classList.add('bg-[#0a0a0a99]');
});
```
I want to know if there's another way to change this option, initially I mean. 
And Thank you again.

**Comment by Mr-Zafar** [comment]
You can use class `hs-overlay-backdrop-open:bg-*`

![photo_2023-02-16 16 39 42](https://user-images.githubusercontent.com/5662351/219355248-066341b2-3348-47af-a2b4-18f5ec1983c2.jpeg)
![photo_2023-02-16 16 39 37](https://user-images.githubusercontent.com/5662351/219355257-7a83e8b7-ee43-47a1-a68f-c48429283b1e.jpeg)

**Comment by koossaayy** [comment]
Thank you ♥
