### ISSUE TITLE
Advanced Select: Search inside dropdown 

### ISSUE THREAD

**Issue by shanke-pvex** [htmlstreamofficial/preline#445]
### Summary

onNoResultsClick / customize search

### Detailed Description

Good Morning.

1. Is it possible to inlcude onNoResultsClick to get the possibility to trigger a click-action in case of no result?
2. Is it possible to include a custom search functionality? (eg. entered term is: qcells and the option in the select is: Q.Cells SE)
3. Can you add floating label like on input?

### Use Cases

In my current project i have a workaround with an input for searching with custom search functionality and a custom dropdown list with clickhandler in case of no result.
![Bildschirmfoto 2024-08-19 um 11 11 49](https://github.com/user-attachments/assets/26604716-3e1e-4761-8307-4c87852456eb)
![Bildschirmfoto 2024-08-19 um 11 11 39](https://github.com/user-attachments/assets/1df90fb0-b37a-4558-b533-55eab2ac3c5d)

**Comment by olegpix** [comment]
@shanke-pvex Hi,
We added option 2 in version 2.5.0, please update to use it ([demo](https://preline.co/docs/advanced-select.html#direct-match-searching-off)).
Regarding option 1, I think you can pass as a parameter `searchNoResultTemplate` markup with a `click` function, on which you can hang the functionality you need
