### ISSUE TITLE
Property 'dropzone' is private and only accessible within class 'HSFileUpload'.

### ISSUE THREAD

**Issue by ryanpantk** [htmlstreamofficial/preline#448]
### Summary

Unable to access dropzone property to observe events in Nextjs Typescript Project

### Steps to Reproduce

1. Set up preline and HSFileUpload component according to stackblitz below
2. Tried to add this part of the code in the documentation
`const { element } = HSFileUpload.getInstance('#hs-file-upload', true);
const { dropzone } = element;

dropzone.on('complete', () => {
  console.log('Item uploaded!');
});`

### Demo Link

https://stackblitz.com/edit/preline-v2-nextjs-fmp5tr?file=src%2Fapp%2Fcomponents%2FPrelineScript.tsx

### Expected Behavior

Console log "item uploaded!" when the file is uploaded

### Actual Behavior

Error Property 'dropzone' is private and only accessible within class 'HSFileUpload'.

**Comment by olegpix** [comment]
@ryanpantk Hi,
Thanks for the heads up! We'll fix this in the next update.

**Comment by jahaganiev** [comment]
Hey @ryanpantk - please check out the latest version, the issue has been fixed. Thanks!
