### ISSUE TITLE
the simple-invite-users modal section does not showing

### ISSUE THREAD

**Issue by Alirezaaraby** [htmlstreamofficial/preline#450]
### Summary

the mentioned section does not showing

### Steps to Reproduce

1- go to https://preline.co/pro/examples/modals-share-and-invite.html#simple-invite-users

### Demo Link

https://preline.co/pro/examples/modals-share-and-invite.html#simple-invite-users

**Comment by jahaganiev** [comment]
Thank you for letting us know, it will be fixed in the next version. Meanwhile, you may get the demo from the Chat Template demo.

<img width="1233" alt="image" src="https://github.com/user-attachments/assets/4c429ee5-7a53-4822-b1f8-1008bc39a6de">
