### ISSUE TITLE
3rd-party plugins not working with Laravel as per docs

### ISSUE THREAD

**Issue by zaxwebs** [htmlstreamofficial/preline#456]
### Summary

Not able to use components like Charts in Laravel

### Steps to Reproduce

1. Implement 3rd-party Preline components like Chart as in [Docs](https://preline.co/docs/charts.html)

### Demo Link

https://preline.co/docs/charts.html

### Expected Behavior

The docs should cover usage of such plugins/components for frameworks like Laravel

**Comment by jahaganiev** [comment]
You may learn more about Charts [here](https://apexcharts.com/)

**Comment by zaxwebs** [comment]
Thanks. Seems like when using it with Preline and integrating it as per docs. It doesn't work, not in Laravel. The script tag won't load as documented in the Preline docs.

**Comment by jahaganiev** [comment]
Could you please provide more details so others can reproduce the issue? Thanks!

**Comment by zaxwebs** [comment]
Sure, the docs state adding styles like `<link rel="stylesheet" href="./node_modules/apexcharts/dist/apexcharts.css">` and scripts like `<script src="./node_modules/apexcharts/dist/apexcharts.min.js"></script>` but this does not work in Laravel. Preline framework docs also do not cover how to get components like Charts working.

E.g when trying when trying to implement [File Upload](https://preline.co/docs/file-upload.html), the docs are potentially missing a step or gotcha on making this work with Frameworks like Laravel as adding `<script src="./node_modules/lodash/lodash.min.js"></script>` & `<script src="./node_modules/dropzone/dist/dropzone-min.js"></script>` will do nothing, configuring or importing the same via app.js doesn't help as HS expects Dropzone to be initialized (how to and where?). Maybe some hint on how to get this setup in the docs would be nice.

PS: This maybe niche but thanks for going through it.
