### ISSUE TITLE
NavBar with collapse not work in react + vite

### ISSUE THREAD

**Issue by 13RTK** [htmlstreamofficial/preline#460]
### Summary

Responsive NavBar with collapse does not work in React + Vite

### Steps to Reproduce

Tech stack: React | Vite | JavaScript (without react router)

My steps:
1. Create a react project by vite
2. Install tailwind and add config
3. Install Preline and add config in tailwind.config.js
4. Copy the code from preline [navbar](https://preline.co/docs/navbar.html#with-collapse) part, and try to run it
![image](https://github.com/user-attachments/assets/e92c3118-614a-48df-885d-7fec7d6911d9)

The very strange thing is that the same code is working well in my Vue + vite project, so I can make sure my tailwind config is correct😅

This is the [vue demo](https://stackblitz.com/~/github.com/13RTK/preline-vue-demo)

### Demo Link

https://stackblitz.com/edit/vitejs-vite-hf7tig?file=src%2Fcomponents%2FNavBar.jsx

### Expected Behavior

The collapse should popup like the demo in preline doc
![image](https://github.com/user-attachments/assets/77c34c46-d156-4bd8-ab45-ba79cf720926)

### Actual Behavior

Even when I click the button, the collapse still does not popup like official docs
![image](https://github.com/user-attachments/assets/5bb9c54a-83cb-4887-80f8-7db0d0598ff9)
does

**Comment by olegpix** [comment]
@13RTK Hi,
Please check out the [demo](https://stackblitz.com/edit/dev-preline-2-vite-react?file=src%2FApp.tsx) for React on Stackblitz, which is specifically setup for the Vite.
I also [forked](https://stackblitz.com/edit/vitejs-vite-c7bec7?file=src%2FApp.jsx) the demo you provided and tweaked it.

**Comment by 13RTK** [comment]
@olegpix Thank you for your patient response, the problem is that I missed the script:
<script src="./node_modules/preline/dist/preline.js"></script>
