### ISSUE TITLE
Custom Combobox Options Trigger Errors

### ISSUE THREAD

**Issue by michaelnabil230** [htmlstreamofficial/preline#464]
### Summary

When using the combobox as shown on the website, it functions correctly with the provided API. However, customizing the options to be displayed in the combobox leads to errors.

### Steps to Reproduce

When using the combobox as demonstrated on the website, it works perfectly with the provided API. However, when attempting to customize the options (elements) displayed in the combobox, an error occurs: chunk-BLKX25ZG.js?v=aa93edf8:10453 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore'). Additionally, another error appears: chunk-BLKX25ZG.js?v=aa93edf8:8704 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions') . Another error: Uncaught (in promise) TypeError: Cannot set properties of null (setting '__vnode')

### Demo Link

https://stackblitz.com/edit/issue-combobox

**Comment by jahaganiev** [comment]
Hey @michaelnabil230, the issue has been resolved in the latest v2.6.0 release. Thanks!
