### ISSUE TITLE
Modal Scroll inside viewport - Iphone not scrolling

### ISSUE THREAD

**Issue by doreybenjamin** [htmlstreamofficial/preline#465]
### Summary

Impossible to scroll inside the modal

### Steps to Reproduce

[Use your iphone with preline exemple in https://preline.co/docs/modal.html](https://preline.co/docs/modal.html)

### Demo Link

https://preline.co/docs/modal.html

### Actual Behavior

Hi,

It is impossible to use this modal example on my iPhone 12 I have tested all browsers, but scroll inside body work.

**Comment by jahaganiev** [comment]
Please try out [this](https://preline.co/docs/modal.html#scrolling-behavior) demo from the docs.

**Comment by doreybenjamin** [comment]
> Please try out [this](https://preline.co/docs/modal.html#scrolling-behavior) demo from the docs.

Hi,  "Scroll inside viewport" not working on my iphone.
