### ISSUE TITLE
Snooze examples are blank

### ISSUE THREAD

**Issue by kalafut** [htmlstreamofficial/preline#469]
### Summary

The Snooze examples don't show anything

### Steps to Reproduce

1. Visit https://www.preline.co/pro/examples/modals-date-and-time.html
2. The "Custom Recurrence Event" works, but the other two are just blank screens on both Chrome and Firefox

### Demo Link

https://www.preline.co/pro/examples/modals-date-and-time.html

### Screenshots

<img width="1120" alt="image" src="https://github.com/user-attachments/assets/20f50965-81a9-4604-9014-85e042b1152e">

**Comment by jahaganiev** [comment]
Hey @kalafut - thanks for catching the issue. It has been fixed with the latest v2.5.0 update. Cheers!

**Comment by kalafut** [comment]
@jahaganiev Thanks for the prompt response! Looks good, but I'd suggest adding the Open button to these two like you've done with the first one. Otherwise, if you click away or press the dialog close button, there is no way to open the dialogs back up without reloading the page (I think?)

**Comment by jahaganiev** [comment]
@kalafut noted, seems we've missed to add - usually, we add to all modals in Example pages. Thanks for letting us know!
