### ISSUE TITLE
The mega menu behaves incorrectly on narrow screens.

### ISSUE THREAD

**Issue by 4bntw** [htmlstreamofficial/preline#474]
### Summary

The mega menu behaves incorrectly on narrow screens.

### Steps to Reproduce

1. Go to https://preline.co/docs/mega-menu.html
2. Go to columns demo
3. Drag to resize the screen to a narrower width.
4. Click hambergur icon to open the menu.
5. Click the menu-item twice

### Demo Link

https://preline.co/docs/mega-menu.html

### Expected Behavior

Click the menu item, and click it again to close.
![Screenshot 2024-10-04 at 16-24-07 Tailwind CSS Mega Menu Preline UI crafted with Tailwind CSS](https://github.com/user-attachments/assets/55467a8d-231e-4f82-ab3b-ac9403378a17)

### Actual Behavior

When clicking the menu item, the menu doesn't close, but its content disappears.
![Screenshot 2024-10-04 at 14-24-12 Tailwind CSS Mega Menu Preline UI crafted with Tailwind CSS](https://github.com/user-attachments/assets/fbe7b263-e0d6-48f9-9583-1b3e9402f049)

**Comment by 4bntw** [comment]
Thank you for addressing this! Looking forward to the next update.

**Comment by jahaganiev** [comment]
Hey @4bntw - the issue has been fixed a while back with the v2.5.1 release. Please feel to open a new issue, if you come accros with any bugs. Thanks!
