### ISSUE TITLE
tooltips do not work inside of table

### ISSUE THREAD

**Issue by avlemos** [htmlstreamofficial/preline#477]
### Summary

tooltips can work outside of a table, but not inside

### Steps to Reproduce

Create a simple table and try to add a tooltip on one of the cells

### Demo Link

https://www.carcostinsight.com/records

### Expected Behavior

when you hover the i

![image](https://github.com/user-attachments/assets/9af869a5-3a9f-420f-b360-675883e0efe6)

a tooltip was expected

### Actual Behavior

no tooltip comes up, unless you create the tooltip outside the <table>

**Comment by olegpix** [comment]
@avlemos Hi,
You need to initialize (using `HSStaticMethods.autoInit(['tooltip'])`) the tooltips after the table has been generated. As I can see, the rows are generated after the page has loaded. Secondly, we recommend placing the Preline script at the bottom of the page (after the closing body tag), not at the top.

**Comment by avlemos** [comment]
it's odd. it only works some times, not everytime :/
