### ISSUE TITLE
plugin.ts file missing type definition

### ISSUE THREAD

**Issue by joelthorner** [htmlstreamofficial/preline#478]
### Summary

The plugin.ts file is missing a type definition on line 267.

### Steps to Reproduce

When I make a build in react, it crashes when it reaches that line because it is missing the type IAddVariantOptions.

https://github.com/htmlstreamofficial/preline/blob/0c521a3c454f2ce345cad137473b77a89ed50a33/plugin.ts#L267C1-L268C1

![image](https://github.com/user-attachments/assets/7c3a6368-dec3-4515-9696-ade15fb45139)

### Demo Link

/

**Comment by thebossza101** [comment]
same issue

**Comment by jahaganiev** [comment]
Hey everyone, the issue has been fixed in the latest v2.6.0 release. Thanks!
