### ISSUE TITLE
Adding two or more instances of paging and info to datatables

### ISSUE THREAD

**Issue by AnaRita** [htmlstreamofficial/preline#494]
### Summary

Add possibility to have two or more instances of paging and info elements in datatables plugin

### Detailed Description

Right now only one paging or info element is permitted. It would be nice to be able to have more instances of both elements.

### Use Cases

if implemented, it would be possible, for example, to have paging both at the top and at the bottom of the datatable.

**Comment by olegpix** [comment]
@AnaRita  Hi,
Thanks for the suggestion, we'll add it to our backlog.

**Comment by jahaganiev** [comment]
@AnaRita we've added all the requested features at v2.7.0 release, please check out the changelog page for more details https://preline.co/docs/changelog.html
