### ISSUE TITLE
Can't pass a function in data-hs-file-upload for Upload File component

### ISSUE THREAD

**Issue by ahmedkhabar** [htmlstreamofficial/preline#495]
### Summary

I used the File Upload example code and when I want to add success function in the data-hs-file-upload configuration obj I face a problem while passing a function because JSON.stringify and JSON.parse doesn't support functions, I suggest to use JSONfn [http://www.eslinstructor.net/jsonfn] instead.

### Steps to Reproduce

1. Open Demo Link
2. Uncomment the JSON approche & comment to JSONfn approche

### Demo Link

https://stackblitz.com/edit/vitejs-vite-67svyt?file=index.html&terminal=dev

### Expected Behavior

Passing call backs in data-hs-file-upload for Upload File component without a problem

### Actual Behavior

an errro said that success is not a function

**Comment by olegpix** [comment]
@ahmedkhabar Hi,
Data attributes cannot set functions as parameters. Instead, you need to exclude the element from automatic initialization by adding the `--prevent-on-load-init` class to the element, and then initialize it using the constructor, where you can call any functions available in Dropzone.

HTML:
```
<div id="file-upload" class="--prevent-on-load-init" data-hs-file-upload>...</div>
```

JS:
```
 const newFileUpload = new HSFileUpload(document.querySelector('#file-upload'), {
                        "url": "/upload",
                        "maxFilesize": 1,
                        "extensions": {
                          "default": {
                            "class": "shrink-0 size-5"
                          },
                          "xls": {
                            "class": "shrink-0 size-5"
                          },
                          "zip": {
                            "class": "shrink-0 size-5"
                          },
                          "csv": {
                            "icon": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 22h14a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v4\"/><path d=\"M14 2v4a2 2 0 0 0 2 2h4\"/><path d=\"m5 12-3 3 3 3\"/><path d=\"m9 18 3-3-3-3\"/></svg>",
                            "class": "shrink-0 size-5"
                          }
                        }
                      })
```
