### ISSUE TITLE
Search after X characters

### ISSUE THREAD

**Issue by kevinnivek** [htmlstreamofficial/preline#496]
### Summary

Display results after X characters input

### Detailed Description

Would love to see the search results only show up after X number of characters input 

### Use Cases

Limit number of results, more accurate results

**Comment by olegpix** [comment]
@kevinnivek Hi,
Thanks for the suggestion, we'll add it to our backlog.

**Comment by jahaganiev** [comment]
@kevinnivek `minSearchLength` parameter  has been added for both Advanced Select and Combobox in v2.7.0 release.
