### ISSUE TITLE
Having Issues Installing with Rails 7 ESbuild

### ISSUE THREAD

**Issue by spacerobotTR** [htmlstreamofficial/preline#5]
I get an error that says ActionController::RoutingError (No route matches [GET] "/node_modules/preline/dist/hs-ui.bundle.js"):

Using Rails 7 here is my tailwind config:

```
module.exports = {
  plugins: [
   require('preline/plugin')
 ],
  content: [
    './app/views/**/*.html.erb',
    './app/helpers/**/*.rb',
    './app/assets/stylesheets/**/*.css',
    './app/javascript/**/*.js'
  ]
}

```

Any ideas on how to get this working?

**Comment by Mr-Zafar** [comment]
Hi, @spacerobotTR  -

It looks like we missed including the following code in the README file:

```
content: [
  'node_modules/preline/distance/*.js'
]
```

This is how your tailwind.config.js file should look like:

```
module.exports = {
  content: [
    'node_modules/preline/dist/*.js'
  ],
  plugins: [
    require('preline/plugin')
  ],
}
```

Also, we have just updated our README file.

Thanks!
