### ISSUE TITLE
Mega Menu has bad behaviour on mobile

### ISSUE THREAD

**Issue by sgazzola80** [htmlstreamofficial/preline#504]
### Summary

When you resize the page to mobile size, the mega menu doesnt work as expected. It opens the submenus but then when you try to close it it doesn work anymore

### Steps to Reproduce

You can see the problem on the online version too, if you navigate to 

https://preline.co/docs/mega-menu.html

and you open the submenu, you can see that when you choose another submenu the current one gets blank and you can close it anymore

![image](https://github.com/user-attachments/assets/b6af6ce4-d507-4947-a6ee-34b0d1ee0549)

### Demo Link

https://preline.co/docs/mega-menu.html

### Screenshots

![image](https://github.com/user-attachments/assets/b6af6ce4-d507-4947-a6ee-34b0d1ee0549)

**Comment by jahaganiev** [comment]
Hey @sgazzola80, the issue has been resolved in the latest v2.6.0 release. Thanks!
