### ISSUE TITLE
Popover/Tooltip not working perfectly

### ISSUE THREAD

**Issue by eirfaniskandar123** [htmlstreamofficial/preline#512]
### Summary

My popover caption not appearing when hover or click etc.

### Steps to Reproduce

1. recently i was interested with preline popover design. so i install the preline by package
2. based on preline documentation i don't need to install anything if i already install preline by package
3. so i copy and paste tooltip and popover code in my file just to test what it looks like
4. but soon i realized my tooltip and popover not working
5. i try to inspect and i see some changes of the code when hovering or clicking or etc but not appear
6. i wonder if i miss any steps of the preline installation 

### Demo Link

https://preline.co/plugins/html/tooltip.html

### Expected Behavior

I was expecting the tooltip to work normally. based on the preline documentation that's all

### Actual Behavior

the tooltip not working normally. the tooltip content not appear after i click or hover

**Comment by olegpix** [comment]
@eirfaniskandar123 Hi,
Could you please provide more details? This could be because you haven't included Preline as a dependency of Tailwind in `tailwind.config.js` or something else. Either way, more details are needed. A link to your website or a demo on Stackblitz or similar would also help.

**Comment by eirfaniskandar123** [comment]
[tailwind.config file.txt](https://github.com/user-attachments/files/17942953/tailwind.config.file.txt)
this is my tailwind config file in txt. i already include preline on my content section. if my way is wrong i hope you can guide me more
