### ISSUE TITLE
Advanced Select: SVG icons do not show up in the selected item

### ISSUE THREAD

**Issue by b-ggs** [htmlstreamofficial/preline#514]
### Summary

SVG icons do not show up in the selected item of Advanced Select components

### Steps to Reproduce

1. Use the latest version of Preline (2.5.1)
2. Copy in the component for [Custom template with icons](https://preline.co/docs/advanced-select.html#custom-template-with-icons)

### Demo Link

https://stackblitz.com/edit/stackblitz-starters-vzdmb1?file=index.html

### Expected Behavior

The globe icon appears before the "Anyone" text.

### Actual Behavior

The globe icon does not appear before the "Anyone" text.

### Screenshots

Expected behavior as in Preline 2.4.1:

![Screenshot 2024-11-23 at 5 36 47 PM](https://github.com/user-attachments/assets/02552b4f-c681-4856-adb5-e9552fcb6a8b)

Actual behavior in Preline 2.5.1:

![Screenshot 2024-11-23 at 5 30 13 PM](https://github.com/user-attachments/assets/4b96c064-aec2-4bcd-a735-101ceb19dca3)

---

These are also available on StackBlitz:
- [Preline 2.4.1 expected behavior demonstration](https://stackblitz.com/edit/stackblitz-starters-bqyraq?file=package.json)
- [Preline 2.5.0 issue reproduction demonstration](https://stackblitz.com/edit/stackblitz-starters-q9d1cv?file=package.json)
- [Preline 2.5.1 issue reproduction demonstration](https://stackblitz.com/edit/stackblitz-starters-vzdmb1?file=package.json)

**Comment by rifkywaw** [comment]
y

**Comment by jahaganiev** [comment]
Hey everyone, the issue has been resolved in the latest v2.6.0 release. Thanks!
