### ISSUE TITLE
Keydown event causing input lag?

### ISSUE THREAD

**Issue by olumidesan** [htmlstreamofficial/preline#517]
### Summary

Input text fields (or textarea) fields eventually become laggy after a while

### Steps to Reproduce

1. Have a form nested in a modal with input text fields or textarea fields
2. Use the application/website repeatedly for a while, filling forms here and there.
3. After a while, typing into the input text fields or text area fields will begin to lag. 

### Demo Link

None

### Expected Behavior

The input text fields or text area fields should not lag

### Actual Behavior

There is a lag after typing each character. This happens when typing in input text fields and textarea fields. The lag increasingly becomes worse the more I type. And only gets better when the page is refereshed. But after using the application for a while again, it again becomes laggy.

### Screenshots

This is the Chrome Performance report when the lag is happening. The higlighted areas at the top in yellow are where the UI is visibly lagging. All I'm doing is typing into the input text field. And an example of my input text field is this:
```
<input
  id="title"
  type="text"
  v-model="form.title"
  class="py-2 px-3 block w-full bg-gray-50 border-gray-200 rounded-lg text-sm placeholder:text-gray-400 focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed"
  placeholder="Title of the match"
/>
```
![Screenshot from 2024-12-01 21-07-54](https://github.com/user-attachments/assets/2a99b8bf-004e-4049-a2c1-0ffe74fce064)

If you drill down into where the lag is the worst, you'll see it's just a bunch of tasks being fired
![Screenshot from 2024-12-01 21-09-49](https://github.com/user-attachments/assets/f485e918-461a-4fd1-a048-090dd01652d5)

Drilling further down, each task is a bunch of `keydown` events
![Screenshot from 2024-12-01 21-10-08](https://github.com/user-attachments/assets/293cef56-5a73-4520-8907-355694dceadc)

And finally, down to the Event itself. The `keydown` calling is firing multiple functions (I imagine for each character I type). This, I believe, is the primary cause of the lag. I'm not binding the `keydown` event; the only bind I have on the input is the standard `v-model`.
![Screenshot from 2024-12-01 21-10-26](https://github.com/user-attachments/assets/590b99fc-543f-4b8b-bf56-a5f5da72ee18)

I'm seeing the function calls have to do with accessiblity checks. Is there any way I can disable the accessibility checks or even prevent the `keydown` event from firing? The application becomes unusable after a while because of this.

**Comment by oliverhaas** [comment]
You can override the accessibility function with an empty one to do nothing.

This issue is probably fixed in v2.6.0 though.

**Comment by olumidesan** [comment]
Thanks. I solved it by disabling the `overlay` plug-in and writing my own overlay component as a substitute. My application's forms are mostly embedded in modals, so it was imperative I solved this issue. Since switching to my custom overlay component, the issue has disappeared -- even though the `keydown` events still fire multiple times.

I like to think there's a leak somewhere in preline's `overlay` plug-in, but I unfortunately have no substantial proof. 

@oliverhaas, for reference, how does one override the accessibility function?

**Comment by oliverhaas** [comment]
For example something like

```js
window.addEventListener("load", () => {
    HSOverlay.accessibility = function (evt) {
        // Do nothing
    };
});
```

but just for all Preline components that you use which have accessibility features.

This means accessiblity, i.e. keyboard controls, will not work anymore for those components.
Also this only mitigates the underlying issue, but does not completely/technically fix it.

I really would recommend checking out Preline >2.6.0. As far as I can see, the underlying issue is fixed there. And then close this issue. 

Hopefully that helps.

**Comment by olumidesan** [comment]
Thank you, @oliverhaas. It definitely helps. I'll update to `v2.6.0`, and see how that goes. 
Closing this for now.
