### ISSUE TITLE
Cannot require the preline UI inside _app.ts, NextJS 13.2

### ISSUE THREAD

**Issue by bncal** [htmlstreamofficial/preline#52]
Hi. I've followed the documenation  at https://preline.co/docs/frameworks-nextjs.html to fully install Preline but I face an error when I require preline inside `app/_app.ts` file.

Error: `implicitly has an 'any' type.
Try npm i --save-dev @types/preline if it exists or add a new declaration (.d.ts) file containing `declare module 'preline';`ts(7016)`.
Also, if I try the above solution I get that the module cannot be found.

There are my dependencies if you need them: `  "dependencies": {
    "@prisma/client": "^4.10.1",
    "@types/node": "18.14.1",
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
    "eslint": "8.35.0",
    "eslint-config-next": "13.2.1",
    "next": "13.2.1",
    "preline": "^1.7.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.43.2",
    "typescript": "4.9.5"
  },
  "devDependencies": {
    "@tailwindcss/forms": "^0.5.3",
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.21",
    "prisma": "^4.10.1",
    "tailwindcss": "^3.2.7"
  }`

I was told to open an issue here.

**Comment by lutfiblog** [comment]
you need to create type definition, in my case i add type.d.ts in root folder, and add this line `declare module 'preline';`

**Comment by o2sevruk** [comment]
@bncal Hi,
you need to add a .d.ts file, like @lutfiblog mentioned above, or just // @ts-ignore before the import.
Preline isn't ready for TS yet.

**Comment by jahaganiev** [comment]
Hey @bncal, hope the issue has been resolved. You may also check out live playground demo here https://stackblitz.com/edit/preline-nextjs?file=pages%2F_app.tsx

Meanwhile, I am closing this issue. Please let us know if the issue still exist and we'll re-open it.

Cheers!
