### ISSUE TITLE
Facing Problem integrating with Laravel

### ISSUE THREAD

**Issue by ssmathivanan402** [htmlstreamofficial/preline#525]
### Summary

Facing Problem integrating with Laravel

### Steps to Reproduce

Trying to use Preline in Laravel Framwork
Tried the instructions as per the documents. Still not able to figure out what I am missing. 
Advanced select not working
DataTable Not worked
Need some improvements in document as well
strugling to integrate with Laravel using mix 

### Demo Link

-

**Comment by ssmathivanan402** [comment]
After update into new preline version I got this issue

ERROR in ./node_modules/preline/src/index.ts 8:8
Module parse failed: Unexpected token (8:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
|
> declare var _: any;
| declare var DataTable: any;
| declare var Dropzone: any;

webpack compiled with 1 error

**Comment by MRFD** [comment]
I ran into the same problem. I finally solved it by modifying this in `app.js`:
 ```js
// change
import 'preline'
// into
import "preline/preline";
```
Hopefully it helps you.

**Comment by ssmathivanan402** [comment]
> ```js
> import "preline/preline";
> ```

Thank you so much buddy
