### ISSUE TITLE
Consider removing drop shadow from switch handles

### ISSUE THREAD

**Issue by MrHBS** [htmlstreamofficial/preline#53]
Consider removing drop shadow from switch handles and use fill colors, like bg-gray-400 or bg-gray-500.

**Comment by jahaganiev** [comment]
Hey @MrHBS - thanks for the feedback. 

Thank you for bringing this to our attention. While we don't currently see a reason to make any changes, we encourage you to use an approach that best suits your projects. Please feel free to reach us if you have more suggestions.

Cheers!
