### ISSUE TITLE
Backdrop does not work when using "important" config with a selector

### ISSUE THREAD

**Issue by cpgo** [htmlstreamofficial/preline#539]
### Summary

Backdrop does not work when using "important" config with a selector

### Steps to Reproduce

1. Click on `Overlay` to open the drawer demo
2. Note that the backdrop does not work because as far as I can tell its created as a new node at the bottom of `<body>` and not the div with `.tw` where the button is created.

### Demo Link

https://stackblitz.com/edit/preline-v2-svelte-k1vdtnsv?file=tailwind.config.js

### Expected Behavior

Expected backdrop element to be scoped under my `.tw`

### Actual Behavior

Backdrop element is created at the bottom of the document

### Screenshots

![image](https://github.com/user-attachments/assets/74279b81-183c-484c-80c4-e54abee287c0)

**Comment by jahaganiev** [comment]
Please note that Preline plugins doesn't support prefixes.
