### ISSUE TITLE
Tooltip examples

### ISSUE THREAD

**Issue by jacobcoro** [htmlstreamofficial/preline#58]
In the figma components the tooltips have a carrot if you specify a direct, however in the documentation examples they don't. How can we add the carrot?

<img width="833" alt="Screenshot 2023-03-31 at 15 14 56" src="https://user-images.githubusercontent.com/52448067/229050036-f2cb964b-d230-4f1d-b206-d08effb69226.png">

<img width="823" alt="Screenshot 2023-03-31 at 15 15 12" src="https://user-images.githubusercontent.com/52448067/229050083-2b700f8f-f1ca-4611-9e72-1b53fa695821.png">

**Comment by jahaganiev** [comment]
Hey @jacobcoro, I've just replied to the similar question on the issue #60 with more details. Thanks!
