### ISSUE TITLE
When click on the link navbar doesn't close it needs to be closed,which is not a good user expreience.

### ISSUE THREAD

**Issue by ashishjaswal2002** [htmlstreamofficial/preline#59]
Especially when you are working with react app  replace <a href="#>Something</a> with <Navlink to="/">Helo</Navlink> it doesn't work.Navlink provided by the react router dom

**Comment by evici** [comment]
Can you provide example please?

**Comment by Mr-Zafar** [comment]
@ashishjaswal2002 @evici  marking it as closed for now. If you have more details to share in the future, feel free to re-open this issue or open a new one.
