### ISSUE TITLE
<body> is not displayed (README)

### ISSUE THREAD

**Issue by shinshin86** [htmlstreamofficial/preline#6]
Hello! I am touching Preline for the first time today.
I think this is very cool, and I am looking forward to using it.

<img width="811" alt="2022-06-19 22 11 22" src="https://user-images.githubusercontent.com/8216064/174483480-38dd39e8-2975-417e-bd72-76e2ac0b045a.png">

By the way, I was looking at the README and the `<body>` section is missing.
I don't see any mistakes, so this may be a GitHub markdown spec issue.

I was curious about this and tried to come up with a solution, and finally came up with the idea of using backquotes to deal with it, but I don't know if that is the best option.
(Also, changing only this part to backquotes may lack uniformity compared to the rest of the description, so I'm not sure about that either.)

This is a diff that I tried to fix.
https://github.com/shinshin86/preline/commit/4332f3b74622e0b9a4f5c5a2febac7b0df3b90c8

In any case, I am thinking of creating a PR for the solution if you don't mind, as I think this is the part I would like to see displayed correctly for first-time visitors to the Preline repository.

What do you think about this?

**Comment by Mr-Zafar** [comment]
Hi, @shinshin86 -

Thanks for pointing out the issue.

Also, we just updated our README file and fixed it.

Thanks!

**Comment by shinshin86** [comment]
Hi, @Mr-Zafar 
Thanks for the reply!
