### ISSUE TITLE
Switch figma example does not match docs

### ISSUE THREAD

**Issue by jacobcoro** [htmlstreamofficial/preline#60]
There is no documentation about the icons and how to add them.
There aren't any 'no icons' in the figma components. This is making it hard to match our deign document to our actual components which was the original motivation of using preline. 

<img width="1635" alt="Screenshot 2023-04-03 at 15 37 56" src="https://user-images.githubusercontent.com/52448067/229442667-59f8ec08-edb0-4482-ae96-b7eeaa3c8c2c.png">

IF you guys could update the figma document to reflect reality, or update the website docs component examples to match that would make the project much more useful. 
Ideally they should be entirely synced. 
Thanks!

Another problem I found:
for the Switch, the 'disabled' examples are not using tailwind `disabled` prefix. so I need to reimplement them all again by hand.

**Comment by NayamAmarshe** [comment]
I don't think we need those check or cross icons.

**Comment by jahaganiev** [comment]
Hey @jacobcoro, thank for providing feedback!

Please note, Preline UI Figma file comes with extra top-notch additions as we described it [here](https://preline.co/figma.html) but it includes 100% everything from the coded components.

You may check the Switch Examples components for non icon switches on the Figma:
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/5040828/233865883-bc835de2-0f58-4030-9d63-81e24bbbd03c.png">

> Another problem I found:
for the Switch, the 'disabled' examples are not using tailwind disabled prefix. so I need to reimplement them all again by hand.

We will address this issue in v2.0 update in future updates.

Please feel free to share if you come across with any issues. Once again, thank you for providing feedback and letting us know about the issues.

Cheers!

**Comment by jacobcoro** [comment]
Thanks for your reply. I just read the link again and see "extra top notch" but I'm not sure what that means. Are this available somewhere? I just know our team has had trouble matching the code to the design

**Comment by jahaganiev** [comment]
Hey @jacobcoro - thanks for getting back!

We mean by "...with extra top-notch additions.." on Figma page desiccation that Figma file includes more additional examples than the coded version. However, as I've mentioned previously Preline UI Figma covers 100% all components from the documentation - if you find anything that's missing, please feel free to let us know and we will update it.

Regarding the converting Design to Code issues, unfortunately we are not able to help much here but we will do our best to have a look. Best would be to open a new discussion for such issues here https://github.com/htmlstreamofficial/preline/discussions and others might guide as well.

Cheers!
Jaha

**Comment by jacobcoro** [comment]
I see. So you are saying all examples on the website are in the figma, but not all examples in the figma are on the website code examples. I would suggest deleting the examples from the figma that aren't on the website

**Comment by jahaganiev** [comment]
Hey @jacobcoro - thanks for the suggestion! 

We might consider adding in future mini version of Figma which would match coded components if we will receive more requests from other community members.

Please feel free to let us know if you have more suggestions.

Cheers!
Jaha

**Comment by borama** [comment]
Hi, thanks for Preline! 

I'd also vote for a "mini" version Figma file that would perfectly match the documentation because right now it is difficult for us to find the proper Figma variant in the documentation. It seems not even clear whether a given component in Figma is one of the documented ones or a "top-notch" (undocumented) one and we have to resort to finding a similar-enough component in the docs and elaborately compare the styling classes in Figma vs. the docs. A "mini" Figma file would push our designers to make their changes to the original (documented) components explicit which we would like much better.

**Comment by jacobcoro** [comment]
While I respect the need for devs to get paid, and I realize this is part of your upselling strategy, I suggest being more explicit/transparent about it. I think you would get more initial adoption if the Figma matched perfectly.

**Comment by Mr-Zafar** [comment]
@jacobcoro @borama you asked and we did it. enjoy them!

**Comment by jahaganiev** [comment]
Hey @jacobcoro, @borama - overall we did our best to close the gap between Figma and coded components, might not be 100% perfect but with v2.0 components UIs mainly covered. As always, please feel free to share any feedback.

Cheers for your input!
