### ISSUE TITLE
Request to correct Preline integration with Astro

### ISSUE THREAD

**Issue by krankos** [htmlstreamofficial/preline#61]
The docs are wrong about how the Preline javascript should be included in an Astro project. The fault is in the last step of the integration. Specifically this line: 
```html
<script is:inline src="./assets/vendor/preline/dist/preline.js"></script>
```
This is from [docs](https://preline.co/docs/frameworks-astro.html)

Using `is:inline` here is the first issue. `is:inline` means that Astro will not bundle preline.js when building, which means that preline.js will only exist in the dev environment. This import as is will never resolve as mentioned in the Astro docs.
[To avoid bundling the script, you can use the is:inline directive.](https://docs.astro.build/en/guides/client-side-scripts/#client-side-scripts)

The second issue is the path to preline.js. In my case, the path didn't work even in dev mode. The path to preline.js was `../../node_modules/preline/dist/preline.js`.

**An elegant solution tested in production is:**
```html
<script>import "preline/dist/preline.js";</script>
```

I'd like to thank @MoustaphaDev for suggesting this solution.

**Comment by Rush-er** [comment]
> ```
> <script>import "preline/dist/preline.js";</script>
> ```

This fix also error with Cloudflare pages not correctly working since no script can be found.

Thanks ! @krankos

**Comment by lilyplw** [comment]
This error troubled me for 3 hours last night.

However, this post saved 3 products.

Thank you very much.

**Comment by krismawan4** [comment]
see the astro documentation here
https://docs.astro.build/en/guides/client-side-scripts/#client-side-scripts

copy paste folder preline in node_modules to folder src and then add this script
```
<script src="../preline/dist/preline.js"></script>
```

in my file src/layouts/Layout.astro
```
---
interface Props {
    title: string;
}

const { title } = Astro.props;
---

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="description" content="Astro description" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <meta name="generator" content={Astro.generator} />
        <title>{title}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet" />
    </head>
    <body class="bg-black-800 font-[Poppins] light">
        <slot />
    </body>
</html>

<!-- relative path to script at `src/preline/dist/preline.js` -->
<script src="../preline/dist/preline.js"></script>
```

**Comment by jahaganiev** [comment]
Hey @krankos  - thanks for sharing workaround, we've added a backlink to our [docs](https://preline.co/docs/frameworks-astro.html) for this workaround solution. 

Cheers!

**Comment by fr33dr4g0n** [comment]
Has anyone managed to get this working with View Transtions?

**Comment by zanhk** [comment]
Why not just update the docs instead of including a workaround at the bottom of the page?

https://preline.co/docs/frameworks-astro.html

**Comment by Rush-er** [comment]
> Why not just update the docs instead of including a workaround at the bottom of the page?
> 
> https://preline.co/docs/frameworks-astro.html

Hahaha ciao Zank sono Glad[I]a[T]or 7, guarda dove ti trovo

**Comment by marekbrze** [comment]
Does the solution work for you in the newest versions of Astro (4.12.2)? 

I have problems and the Hero section looks like this:

<img width="1380" alt="Screenshot 2024-07-26 at 16 11 01" src="https://github.com/user-attachments/assets/47e5879c-35c2-4aeb-9fc7-f09d2444332d">

Here is the repo with the code -> https://github.com/marekbrze/preline-astro-2024

**Comment by jmartsch** [comment]
The issue should be re-opened and the documentation should be updated instead of linking to a workaround. Are there any concerns?

**Comment by alberto-gomez-munity** [comment]
I have this error in my console when i tried add any component with JS like a Advanced Select or File Uploader. 
I'm Preline Pro adquired

`VM45:14 Uncaught SyntaxError: Expected ',' or '}' after property value in JSON at position 529 (line 14 column 50)
    at JSON.parse (<anonymous>)
    at new e3 (preline_dist_preline__js.js?v=703cbe16:1841:80)
    at preline_dist_preline__js.js?v=703cbe16:1916:21
    at NodeList.forEach (<anonymous>)
    at e3.autoInit (preline_dist_preline__js.js?v=703cbe16:1912:166)
    at preline_dist_preline__js.js?v=703cbe16:1921:397`



package.json:
`"dependencies": {
    "@astrojs/netlify": "^5.5.2",
    "@astrojs/react": "^3.6.2",
    "@astrojs/tailwind": "^5.0.4",
    "@popperjs/core": "^2.11.8",
    "@preline/select": "^2.4.1",
    "@supabase/supabase-js": "^2.39.1",
    "@types/react": "^18.3.5",
    "@types/react-dom": "^18.3.0",
    "astro": "^4.15.4",
    "dropzone": "^6.0.0-beta.2",
    "lodash": "^4.17.21",
    "micromatch": "^4.0.5",
    "preline": "^2.4.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "tailwindcss": "^3.4.0"
  },
  "devDependencies": {
    "@tailwindcss/forms": "^0.5.9",
    "@types/micromatch": "^4.0.6",
    "prettier": "^3.1.1",
    "prettier-plugin-astro": "^0.12.2"
  }`

**Comment by codiini** [comment]
@alberto-gomez-munity  Did you find a workaround?

**Comment by fsmeier** [comment]
> @alberto-gomez-munity Did you find a workaround?
> 
> EDIT: I FOUND A SOLUTION It's caused by a JSON syntax error. Replace the content of the `data-hs-file-upload`. The difference is the double escaped quotes in the SVG string (using `\\"` instead of `\"`)
> 
> ```
> data-hs-file-upload='{
>   "url": "/upload",
>   "extensions": {
>     "default": {
>       "class": "shrink-0 size-5"
>     },
>     "xls": {
>       "class": "shrink-0 size-5"
>     },
>     "zip": {
>       "class": "shrink-0 size-5"
>     },
>     "csv": {
>       "icon": "<svg xmlns=\\"http://www.w3.org/2000/svg\\" width=\\"24\\" height=\\"24\\" viewBox=\\"0 0 24 24\\" fill=\\"none\\" stroke=\\"currentColor\\" stroke-width=\\"2\\" stroke-linecap=\\"round\\" stroke-linejoin=\\"round\\"><path d=\\"M4 22h14a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v4\\"/><path d=\\"M14 2v4a2 2 0 0 0 2 2h4\\"/><path d=\\"m5 12-3 3 3 3\\"/><path d=\\"m9 18 3-3-3-3\\"/></svg>",
>       "class": "shrink-0 size-5"
>     }
>   }
> }'
> ```

This helped me soo much! thank you @codiini
