### ISSUE TITLE
integration with remixjs

### ISSUE THREAD

**Issue by johannchen2021** [htmlstreamofficial/preline#62]
Is there an example to integrate preline with remixjs?

**Comment by jahaganiev** [comment]
Hey @johannchen2021! 

Currently, we don't have ready example page but we've just added to our roadmap and we will keep you updated.

Meanwhile, please feel free to reach us if you have more suggestions!

Cheers!

**Comment by fred-transitiv** [comment]
You can just follow the nextjs tutorial. It's almost the same exact steps. The import in the useEffect goes in root.tsx instead of app.

**Comment by jahaganiev** [comment]
Hey @johannchen2021 - we've just shipped v1.9.0 update and added Framework Guides for Remix [here](https://preline.co/docs/frameworks-remix.html).

Cheers!
