### ISSUE TITLE
Placing the Tabs under the Accordion forces all Tab items to be active as initial when click the Accordion item.

### ISSUE THREAD

**Issue by yktsuji** [htmlstreamofficial/preline#63]
Placing the Tabs under the Accordion forces all Tab items to be active as initial when click the Accordion item.
+ Accordion
    ------------------
    [Tab1] [Tab2]

https://preline.co/docs/accordion.html
https://preline.co/docs/tabs.html

**Comment by BigBlockStudios** [comment]
I am having this problem as well, the tabs appear to be inheriting the active class from the accordion. \\

but they satay active even after clicking

**Comment by jahaganiev** [comment]
Hey @yktsuji & @BigBlockStudios, thanks for letting us know about the issue. We will fix and include in the next upcoming update soon.

Cheers!
Jaha

**Comment by jahaganiev** [comment]
Hey @yktsuji, @BigBlockStudios - we've just pushed v1.9.0 update which includes the fix for it.

Cheers!

**Comment by yktsuji** [comment]
@jahaganiev Thank you for the fix!! I'll be using Preline more and more in the future.
