### ISSUE TITLE
Documentation: Integration with Qwik

### ISSUE THREAD

**Issue by brandiqa** [htmlstreamofficial/preline#64]
Hello,

Kindly add to your documentation guide on how to integrate with  [Qwik](https://qwik.builder.io). The steps are similar to the default [installation guide](https://preline.co/docs/index.html) except for the last step which is as follows:

## 3. Add the Preline UI JavaScript 

Update `root.tsx` as follows:

```tsx
...
export default component$(() => {
  return (
    <QwikCityProvider>
      <head>
      </head>
      <body lang="en">
        ...
        <script
          type="text/javascript"
          src="/node_modules/preline/dist/preline.js"
        ></script>
      </body>
    </QwikCityProvider>
  );
});
```

**Comment by brandiqa** [comment]
I've realized PartyTown is not applicable in this context since `preline.js` is a first party script required for the functioning of the web app, hence I've updated the proposal.

I would also suggest having typescript support. Can discuss that on a separate thread

**Comment by Easy-Cloud-in** [comment]
In QWIK @types/preline is required to run properly.

**Comment by jahaganiev** [comment]
Thanks for the input @brandiqa! 

We've made online playground demo Preline UI + QWIK here: https://stackblitz.com/edit/preline-qwik?file=tailwind.config.js 

Step by step [Framework Guides](https://preline.co/docs/frameworks.html) will be available soon with the next update.

Cheers!
Jaha

**Comment by brandiqa** [comment]
In regards to TypeScript support, I've come up with a workaround. 

I've created the file `src/types/preline/index.d.ts` within my Qwik project with the following code:

```ts
export {};

declare global {
  interface Window {
    HSAccordion: {
      show(accordionEL: HTMLElement): void;
      hide(accordionEL: HTMLElement): void;
    };
    HSCollapse: {
      toggle(collapseEL: HTMLElement): void;
      show(collapseEL: HTMLElement): void;
      hide(collapseEL: HTMLElement): void;
    };
    HSDropdown: {
      open(dropdownEl: HTMLElement): void;
      close(dropdownEl: HTMLElement, noAnimation: boolean): void;
      toggle(dropdownEl: HTMLElement): void;
    };
    HSOverlay: {
      toggle(overlayEL: HTMLElement): void;
      open(overlayEL: HTMLElement): void;
      close(overlayEL: HTMLElement): Promise;
    };
    HSTabs: {
      open(tabToggleEL: HTMLElement): void;
    };
    HSTooltip: {
      show(tooltipEL: HTMLElement): void;
      hide(tooltipEL: HTMLElement): void;
    };
  }
}
```

Then I've updated `tsconfig.json` to include the above defintion:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "target": "ES2017",
    "module": "ES2022",
    "lib": ["es2022", "DOM", "WebWorker", "DOM.Iterable"],
    "jsx": "react-jsx",
    "jsxImportSource": "@builder.io/qwik",
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "incremental": true,
    "isolatedModules": true,
    "outDir": "tmp",
    "noEmit": true,
    "types": ["node", "vite/client", "./src/types/preline"],
    "paths": {
      "~/*": ["./src/*"]
    }
  },
  "files": ["./.eslintrc.cjs"],
  "include": ["src", "./*.d.ts"]
}
```

VSCode Eslint plugin no longer throws warnings when programmatically calling HS functions. Below is an example of how I've used it in Qwik:

```ts
export const closeSidebar = () => {
  const sidebarEl = document.getElementById("application-sidebar");
  if (sidebarEl) window.HSOverlay.close(sidebarEl);
};
```

**Comment by jahaganiev** [comment]
Hey folks,

We've just shipped v1.9.0 update with Framework Guides for Qwik [here](https://preline.co/docs/frameworks-qwik.html). Thanks a lot @brandiqa for the request and sharing your work around solutions.

Cheers!

**Comment by brandiqa** [comment]
There's a typo in the description:

> "Qwick is an instant-loading framework with minimal overhead"

**Comment by brunocrosier** [comment]
came here to say the same.. it says `Qwick` instead of `Qwik`

![image](https://github.com/user-attachments/assets/bbf0edf0-737f-4238-98b8-9bd28c779825)
