### ISSUE TITLE
Self is not defined 

### ISSUE THREAD

**Issue by felipesabino** [htmlstreamofficial/preline#67]
I am using preline `1.7.0` with NextJS and am noticing the following error logs

```
error - node_modules/preline/dist/preline.js (2:223) @ self
error - unhandledRejection: Error [ReferenceError]: self is not defined
    at eval (webpack-internal:///(sc_server)/./node_modules/preline/dist/preline.js:5:3)
    at (sc_server)/./node_modules/preline/dist/preline.js (/Users/felipesabino/projects/lang-app/.next/server/_sc_server_node_modules_preline_dist_preline_js.js:20:1)
    at __webpack_require__ (/Users/felipesabino/projects/lang-app/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__.t (/Users/felipesabino/projects/lang-app/.next/server/webpack-runtime.js:73:38) {
  digest: undefined
}
```

I am using NextJS `13.3.0` with the new `appDir` approach and loading preline on my template as follows

```
  useEffect(() => {
    const initPreline = async () => {
      // @ts-ignore
      await import('preline')
    }
    initPreline()
  }, [])
```

I also tried to load is via 

```
  useEffect(() => {
    // @ts-ignore
    import('preline')
  })
```

And I set up my layout template to be client side to see if it prevents the issue by `'use client'`.

Any idea on what is causing and how to fix it?

**Comment by olegpix** [comment]
Please check the following sandbox - https://stackblitz.com/edit/olegpix-preline-next-fb6xhb , it's working well. 
Please, provide more details about your problem. Please notice, that the Preline is manipulated with DOM elements, it's not ready yet for Next.js and don't using Next.js concepts.
In general, the “_self is not defined” error occurs if the script is included in the head or if the document (DOM) has not yet loaded, you need to look for the problem in this.

**Comment by jahaganiev** [comment]
Closing this issue since the issue has been addressed with v2.x releases. If you are still having any issues, please open a new issue with more details. Thanks for sharing workarounds with everyone!
