### ISSUE TITLE
Typography concerns

### ISSUE THREAD

**Issue by stormynight9** [htmlstreamofficial/preline#68]
I've been browsing Preline components and I love it. But one thing was missing that I need which is typography.
Do you guys have an opinion on typography?

**Comment by jahaganiev** [comment]
Hey @stormynight9! Thank for the suggestion, we will add Typography examples in future updates.

Meanwhile, you may check out TailwindCSS docs Typography section for full set of utility classes e.g.  https://tailwindcss.com/docs/font-family

Please feel free to let us know if you have more suggestions.

Cheers!
