### ISSUE TITLE
Mega menu doesn't work in Safari 15.5

### ISSUE THREAD

**Issue by polkabrothers** [htmlstreamofficial/preline#7]
Mega menu on [https://preline.co/examples/html/mega-menu-header.html#](url) doesn't show in Safari 15.5, could be a browser extension interfering but I've tried disabling adguard and the few other plugins I have in incognito mode and it still doesn't show up when hovering over the link.

When investigating further, none of the click events on the preline.co page works. Menus, popovers, menus, etc. works just fine in Firefox, Chrome, Edge etc. but not in Safari, modals does not show either, just the gray faded backdrop.

**Comment by Mr-Zafar** [comment]
Hi, @polkabrothers -

It looks like we missed including the following code in the README file:

```
content: [
  'node_modules/preline/distance/*.js'
]
```

This is how your tailwind.config.js file should look like:

```
module.exports = {
  content: [
    'node_modules/preline/dist/*.js'
  ],
  plugins: [
    require('preline/plugin')
  ],
}
```

Also, we have just updated our README file.

Thanks!
