### ISSUE TITLE
Tooltip not cloing in firefox 112.0.2 - javascript console error

### ISSUE THREAD

**Issue by BigBlockStudios** [htmlstreamofficial/preline#71]
The tool tip will pop open, but does not close (javascript error) Seems to work just fine in edge and chrome, not FireFox (112) 

I get the same error in my inspector on your demo page as well: https://preline.co/docs/tooltip.html

Funny, looking at alternatives - your popover with the hover event throws the same javascript error (in Firefox) just the one example with the hover - the rest work.

Uncaught TypeError: n.toElement is undefined
    o https://preline.co/assets/vendor/preline/preline.js:2
    value https://preline.co/assets/vendor/preline/preline.js:2
    value https://preline.co/assets/vendor/preline/preline.js:2
    value https://preline.co/assets/vendor/preline/preline.js:2
    185 https://preline.co/assets/vendor/preline/preline.js:2
    o https://preline.co/assets/vendor/preline/preline.js:2
    <anonymous> https://preline.co/assets/vendor/preline/preline.js:2
    <anonymous> https://preline.co/assets/vendor/preline/preline.js:2
    <anonymous> https://preline.co/assets/vendor/preline/preline.js:2
    <anonymous> https://preline.co/assets/vendor/preline/preline.js:2
2 [preline.js:2:37025](https://preline.co/assets/vendor/preline/preline.js)
    o https://preline.co/assets/vendor/preline/preline.js:2
    (Async: EventListener.handleEvent)
    value https://preline.co/assets/vendor/preline/preline.js:2
    value https://preline.co/assets/vendor/preline/preline.js:2
    (Async: EventListener.handleEvent)
    value https://preline.co/assets/vendor/preline/preline.js:2
    185 https://preline.co/assets/vendor/preline/preline.js:2
    o https://preline.co/assets/vendor/preline/preline.js:2
    <anonymous> https://preline.co/assets/vendor/preline/preline.js:2
    <anonymous> https://preline.co/assets/vendor/preline/preline.js:2
    <anonymous> https://preline.co/assets/vendor/preline/preline.js:2
    <anonymous> https://preline.co/assets/vendor/preline/preline.js:2

**Comment by jahaganiev** [comment]
Hey @BigBlockStudios - we've just shipped v1.9.0 update with the fix.

Cheers!
