### ISSUE TITLE
Using it with svelte presents SSR issues

### ISSUE THREAD

**Issue by ziedHamdi** [htmlstreamofficial/preline#72]
I loved the preline styles and component offer, so I'm trying to make it work with SvelteKit. Before I continue the advancement, I'm facing an initialization bug sometimes:

I added script loading directly in the component script section (checking if we are running in a browser before executing it).

Sometimes while in dev mode (hot reload), the script doesn't load, I'm not sure if that's the right place to put the script initialization.

I moved that init code to the AccordionItem component, checking i'm in the browser before initializing like follows:

```
<script>
	import Accordion from './Accordion';

	if(typeof window !== 'undefined') {
		console.log(  "initializing accordion" )
		window.HSAccordion = new Accordion();
		window.HSAccordion.init();
	}
	export let name;
</script>
```

I made the library available [here](https://github.com/ziedHamdi/preline-svelte) (actually only porting the accordion component), and wrote a [blog post describing the process](https://dev.to/zhamdi/how-i-integrated-preline-to-work-in-sveltekit-16kj) for others to benefit from it.

**Comment by jahaganiev** [comment]
Thanks for the input and sharing the article @ziedHamdi!

We've made online playground demo Preline UI + Svelte here: https://stackblitz.com/edit/preline-svelte?file=tailwind.config.js

Step by step [Framework Guides](https://preline.co/docs/frameworks.html) will be available soon with the next update.

Cheers!
Jaha
