### ISSUE TITLE
Problems installing Preline in Remix

### ISSUE THREAD

**Issue by EpsilonOrionis** [htmlstreamofficial/preline#76]
Hi there,

I just wanted to reach out and let you know that I'm currently facing some difficulties installing Preline on Remix. I've been following the guide for installing Preline on React, but it doesn't seem to be working for me.

I've carefully followed the steps outlined in the guide, but I keep encountering errors or issues that prevent me from successfully installing Preline on Remix. I've double-checked my code and made sure that I've followed all the necessary instructions, but the problem persists.

I was wondering if you could provide me with any additional guidance or suggestions to help resolve this issue. I really appreciate your assistance and expertise in troubleshooting this problem.

Thank you so much for your time and support.

**Comment by jahaganiev** [comment]
Hey @EpsilonOrionis, 

You may check out this playground demo for Preline UI + Remix https://stackblitz.com/edit/preline-remix?file=package.json

We're soon adding Framework Guides in our docs for the Remix, along with several other major frameworks.

Hope that helps!

Cheers!

**Comment by EpsilonOrionis** [comment]
Hi @jahaganiev, thank you!

I managed to solve the problem by following the existing Next.js guide on the website.
I really appreciate your help. 

Thanks again for your support.

**Comment by jahaganiev** [comment]
Hey @EpsilonOrionis,

We've just shipped v1.9.0 update and added Framework Guides for Remix [here](https://preline.co/docs/frameworks-remix.html).

Cheers!
