### ISSUE TITLE
Request for RTL Edition

### ISSUE THREAD

**Issue by abolfazlakbarzadeh** [htmlstreamofficial/preline#8]
hey :)

do you have any plan for RTL edition release ?

**Comment by Mr-Zafar** [comment]
Hi, @abolfazlakbarzadeh -

Preline UI extends Tailwind CSS and fully supports RTL by default. You can follow Tailwind CSS docs to achieve this [RTL support](https://tailwindcss.com/docs/hover-focus-and-other-states#rtl-support)

Thanks!
