### ISSUE TITLE
Docs: Update Next.js installation guide to use app directory

### ISSUE THREAD

**Issue by hb20007** [htmlstreamofficial/preline#83]
On this page: https://preline.co/docs/frameworks-nextjs.html

The following is mentioned:
> Add the Preline UI JavaScript in your app entry point `_app.tsx` or `_app.js` according to the Next.js version.

There are no instructions for a project using the[ Next.js App router](https://nextjs.org/docs/app), where there would be no `_app.tsx` or `_app.js` file. Also, the instructions need to mention adding `'use client;'` in this case for the `useEffect()` to work.

**Comment by kateusz** [comment]
Is there any workaround for typescript users?

**Comment by ksmelnad** [comment]
I checked their codebase. Couldn't find types or type definitions.

**Comment by beestinger72** [comment]
Also facing this same situation * thumb

**Comment by acanimal** [comment]
any fix on this?

**Comment by smyja** [comment]
same issue.

**Comment by deepmeena70** [comment]
My solution: 

if you are using App Router the use this 👇 :
useEffect(() => require("preline"), []); 
 add this  to top level layout.tsx file in 'ProjectRootDirectory/src/app/layout.tsx' and don't use import here because it will tell you about type declaration module so instead using 'import' use 'require'. and then the things will run smoothly. 

if you are using Page Router then you have nothing do as told in the Preline UI Doc 😎

**Comment by Nevemoire** [comment]
Is there any workaround to import preline without "use client" ?

**Comment by amrfateem** [comment]
> > Is there any workaround to import preline without `'use client;'` ?
> 
> Just use `require()’

Still needs the use client for useEffect. what am I missing ?

**Comment by lemonjp** [comment]
I use app directory and layout.tsx on nextjs 13.
I still got this error. any solution?
```
Warning: useEffect must not return anything besides a function, which is used for clean-up. You returned: [object Module]
```

```
destroy is not a function
Try again
```

**Comment by lemonjp** [comment]
> > Is there any workaround to import preline without `'use client;'` ?
> 
> Just use `require()’

now i understand. doesn't need useEffect() just use `"use client";` and  `require("preline");` on each pages you want.
it's working now.

**Comment by lemonjp** [comment]
> > Is there any workaround to import preline without `'use client;'` ?
> 
> Just use `require()’

I solved this way. put each components you want.

```ts
"use client";

export default function SidebarNav() {

  useEffect(() => {
    require('preline');
  }, []);

  return (
    <div className="mt-5">
      <Sidebar/>
    </div>
  );
}

```

refer this issue 
#67

**Comment by coler-j** [comment]
https://github.com/htmlstreamofficial/preline/issues/83#issuecomment-1671325442 wouldn't work as the root layout is a server side component by default and cannot be made a client side component (so you can't use `use client`

**Comment by coler-j** [comment]
Looks like you can do the following in your root layout (note this uses a CDN, you could also have the script copied with webpack into your public dir)

```
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script
        src="https://cdn.jsdelivr.net/npm/preline@2.0.0/dist/preline.min.js"
        strategy="lazyOnload"
      />
    </html>
  );
}

```

**Comment by jahaganiev** [comment]
Closing this issue since the issue has been addressed with v2.x releases. If you are still having any issues, please open a new issue with more details. Thanks for sharing workarounds with everyone!
