### ISSUE TITLE
Backdrop doesn't close modal in mobile

### ISSUE THREAD

**Issue by stormynight9** [htmlstreamofficial/preline#84]
The vertically centered modal's backdrop doesn't close the modal on click on mobile view
https://preline.co/docs/modal.html#sizes

**Comment by Mr-Zafar** [comment]
Adding the `pointer-events-none` class to the parent div fixes the issue. Will push it in the next update.

```
<div id="modal-id" class="hs-overlay hidden w-full h-full fixed top-0 left-0 z-[60] overflow-x-hidden overflow-y-auto pointer-events-none">
  ...
</div>
```

**Comment by Mr-Zafar** [comment]
> > Adding the `pointer-events-none` class to the parent div fixes the issue. Will push it in the next update.
> > ```
> > <div id="modal-id" class="hs-overlay hidden w-full h-full fixed top-0 left-0 z-[60] overflow-x-hidden overflow-y-auto pointer-events-none">
> >   ...
> > </div>
> > ```
> 
> This will cause closing the modal even when you click inside of it.

`.pointer-events-auto` to the content resolves that.

```
<div id="modal-id" class="hs-overlay hidden w-full h-full fixed top-0 left-0 z-[60] overflow-x-hidden overflow-y-auto pointer-events-none">
  <div class="hs-overlay-open:mt-7 hs-overlay-open:opacity-100 hs-overlay-open:duration-500 mt-0 opacity-0 ease-out transition-all sm:max-w-lg sm:w-full m-3 sm:mx-auto min-h-[calc(100%-3.5rem)] flex items-center">
    <div class="w-full flex flex-col bg-white border shadow-sm rounded-xl pointer-events-auto dark:bg-gray-800 dark:border-gray-700 dark:shadow-slate-700/[.7]">
      ...
    </div>
  </div>
</div>
```

**Comment by stormynight9** [comment]
@Mr-Zafar Thank you!
