### ISSUE TITLE
Problem input border validation states colors

### ISSUE THREAD

**Issue by ibm-luq95** [htmlstreamofficial/preline#87]
Hello,

I have an issue, the error colors not working

`<input type="email" name="email" class="block w-full px-4 py-3 text-sm border-red-500 focus:border-red-500 focus:ring-red-500" autocomplete="new-password" required="" id="id_email">`

When I click on the input, it shows 2 colors error and the default color 

Can I know what is the issue please

Thanks.

![inputs](https://github.com/htmlstreamofficial/preline/assets/58939669/021df121-3adf-4f6d-ab09-7aff70a5db0c)
![input_f](https://github.com/htmlstreamofficial/preline/assets/58939669/e49cecb9-2249-4401-a907-a1885b6d4ae3)

**Comment by Mr-Zafar** [comment]
By default, Preline UI uses [Tailwind CSS Forms](https://github.com/tailwindlabs/tailwindcss-forms) plugin. Don't forget to install it!

**Comment by ibm-luq95** [comment]
@Mr-Zafar Tailwind CSS Forms plugin already installed.

**Comment by Mr-Zafar** [comment]
@ibm-luq95 I copied the above-mentioned code and here's how it looks on our end:

Default:
<img width="369" alt="Screenshot 2023-08-08 at 09 36 41" src="https://github.com/htmlstreamofficial/preline/assets/5662351/0f05253e-549e-46ca-be66-4999d625a6f6">

Focus:
<img width="371" alt="Screenshot 2023-08-08 at 09 36 58" src="https://github.com/htmlstreamofficial/preline/assets/5662351/febe67e0-6ed6-4a19-957b-fd0a6f4c09f3">

It might be a reason, where you have something installed in your project.
