### ISSUE TITLE
(Feture Request) Make Vue 3 compatible components available

### ISSUE THREAD

**Issue by alnahian2003** [htmlstreamofficial/preline#88]
Hey, I'm a huge fan of Preline's simplicity and elegance and plan to build a large-scale web application using it.
However, I've realized that Preline lacks compatibility with Vue 3 components, which is the framework I've chosen for the project. Therefore, I kindly request the addition of Vue 3 compatible components in Preline, as it would greatly improve the development experience for Vue 3 users and attract a wider range of developers to both Preline and Vue 3.

In the meantime, I'm trying to make reusable vue 3 components on my own based on Preline components: 
![image](https://github.com/htmlstreamofficial/preline/assets/61485238/1542393b-438e-4387-a3c2-420452d7871a)

Thank you for considering this **feature request.**

_I'm also available to contribute_

**Comment by jahaganiev** [comment]
Hey @alnahian2003 - thanks for sharing about Preline UI on [Twitter](https://twitter.com/alnahian2003/status/1668880424662372353), we truly appreciate it!

At the moment, we are not able to give ETA for Preline Vue Components but we do have plans in future.

Meanwhile, please feel free to let us know if you have any suggestions for future updates.

Cheers!
Jaha

**Comment by alnahian2003** [comment]
Hi @jahaganiev,

Thank you for your response! I'm thrilled to hear that Vue 3 compatible components are in the plans for Preline. That's fantastic news!

In the meantime, may I continue creating my own reusable Vue 3 components based on Preline for personal use? (I'll be using those components for a side project.) It's already an exciting challenge, and I'm enjoying it.

If I have any suggestions for future updates, I'll let you know.

Preline has already impressed me, and I'm excited to see its evolution.

Thanks again for your support!


Cheers,
Al Nahian
