### ISSUE TITLE
may I ask what's new in update 1.1.2?

### ISSUE THREAD

**Issue by yashika** [htmlstreamofficial/preline#9]
I checked the release README.md but got empty content.

Thank you

**Comment by Mr-Zafar** [comment]
Hi, @yashika -

We have updated the README to address the following issues:
[https://github.com/htmlstreamofficial/preline/issues/5](https://github.com/htmlstreamofficial/preline/issues/5)
[https://github.com/htmlstreamofficial/preline/issues/6#event-6865778566](https://github.com/htmlstreamofficial/preline/issues/6#event-6865778566)

Thanks!

**Comment by yashika** [comment]
thanks
