### ISSUE TITLE
replace full utility classes with custom component

### ISSUE THREAD

**Issue by Medmly20208** [htmlstreamofficial/preline#90]
I just wanna add a code enhancement , for example instead of writing full utility classes we can create component like this

```
@layer components {
    .mainBtn {
        @apply bg-main-red border cursor-pointer transition-all duration-100 text-white border-main-red rounded-md px-[15px] py-[8px] hover:text-main-red hover:bg-white;
    }
}
```

and we replace it in component
```
<a className="mainBtn">click </a>
```

I am interesed to work on this issue

**Comment by olegpix** [comment]
> I just wanna add a code enhancement , for example instead of writing full utility classes we can create component like this
> 
> ```
> @layer components {
>     .mainBtn {
>         @apply bg-main-red border cursor-pointer transition-all duration-100 text-white border-main-red rounded-md px-[15px] py-[8px] hover:text-main-red hover:bg-white;
>     }
> }
> ```
> 
> and we replace it in component
> 
> ```
> <a className="mainBtn">click </a>
> ```
> 
> I am interesed to work on this issue

Hi,
Our approach to creating components is different. If you want, you can do this in the Tailwind configuration.
This is not a issue and it will be closed.

**Comment by Mr-Zafar** [comment]
@Medmly20208 as @olegpix mentioned, you can do this with [Component classes](https://tailwindcss.com/docs/adding-custom-styles#adding-component-classes).
