### ISSUE TITLE
Sidebar menu backdrop doesn't clear our on mobile

### ISSUE THREAD

**Issue by generalzodo** [htmlstreamofficial/preline#92]
Sidebar menu dark backdrop doesn't clear out when a menu item is clicked
![image](https://github.com/htmlstreamofficial/preline/assets/9429946/512b7c55-09f4-4caa-b658-2681dbb2746a)
 on mobile view

**Comment by allaghi** [comment]
Same issue here, any solution ?

**Comment by allaghi** [comment]
Hi @generalzodo, have you got any solution for this

**Comment by iFireKing** [comment]
Same issue, can you fix the problem please?
@generalzodo

**Comment by Mr-Zafar** [comment]
@generalzodo @iFireKing @allaghi somebody please share an example code

**Comment by allaghi** [comment]
> @generalzodo @iFireKing @allaghi somebody please share an example code

The code same examples in application examples section,  personally  I use one of them with laravel and inertia js

**Comment by Mr-Zafar** [comment]
> > @generalzodo @iFireKing @allaghi somebody please share an example code
> 
> The code same examples in application examples section, personally I use one of them with laravel and inertia js

I can't replicate the issue. Can you share a video example?

**Comment by jahaganiev** [comment]
Hey folks, 

We gave it a shot but couldn't recreate the issue on our end. Meanwhile, closing the issue and If you run into it again, please feel free to open up a new issue and let us know. We really appreciate the extra details you can provide.

Cheers!
