### ISSUE TITLE
Does it support vanilla html? ReferenceError: self is not defined

### ISSUE THREAD

**Issue by Bitomancer** [htmlstreamofficial/preline#93]
Does it support vanilla html (maybe add my custom js logic)? 

Ok, I'm not using any javascript framework, just plain html and tailwind css, 
tried the collapse plugin, followed the guide to add content and plugin in config file,
but always get this error.

ReferenceError: self is not defined
    at E:\workspace\turbo_tw\node_modules\@preline\collapse\index.js:2:224
    at jiti (E:\workspace\turbo_tw\node_modules\jiti\dist\jiti.js:1:245784)
    at E:\workspace\turbo_tw\tailwind.config.js:996:5
    at jiti (E:\workspace\turbo_tw\node_modules\jiti\dist\jiti.js:1:245784)
    at E:\workspace\turbo_tw\node_modules\tailwindcss\lib\lib\load-config.js:37:30
    at loadConfig (E:\workspace\turbo_tw\node_modules\tailwindcss\lib\lib\load-config.js:39:6)
    at Object.loadConfig (E:\workspace\turbo_tw\node_modules\tailwindcss\lib\cli\build\plugin.js:135:49)
    at Object.getContext (E:\workspace\turbo_tw\node_modules\tailwindcss\lib\cli\build\plugin.js:204:27)
    at E:\workspace\turbo_tw\node_modules\tailwindcss\lib\cli\build\plugin.js:254:38
    at E:\workspace\turbo_tw\node_modules\tailwindcss\lib\processTailwindFeatures.js:48:11

here is the installation and configuration I was referencing:
https://preline.co/docs/index.html
https://preline.co/docs/configuration.html

and the config is like below:
content: [
    'node_modules/preline/dist/*.js',
    "./public/**/*.{html,js}",
  ],

plugins: [
    require('@tailwindcss/aspect-ratio'),
    // require('@preline/accordion'),
    require('@preline/collapse'),
    require('preline/plugin'),
  ],

**Comment by olegpix** [comment]
> Does it support vanilla html (maybe add my custom js logic)?
> 
> Ok, I'm not using any javascript framework, just plain html and tailwind css, tried the collapse plugin, followed the guide to add content and plugin in config file, but always get this error.
> 
> ReferenceError: self is not defined at E:\workspace\turbo_tw\node_modules@preline\collapse\index.js:2:224 at jiti (E:\workspace\turbo_tw\node_modules\jiti\dist\jiti.js:1:245784) at E:\workspace\turbo_tw\tailwind.config.js:996:5 at jiti (E:\workspace\turbo_tw\node_modules\jiti\dist\jiti.js:1:245784) at E:\workspace\turbo_tw\node_modules\tailwindcss\lib\lib\load-config.js:37:30 at loadConfig (E:\workspace\turbo_tw\node_modules\tailwindcss\lib\lib\load-config.js:39:6) at Object.loadConfig (E:\workspace\turbo_tw\node_modules\tailwindcss\lib\cli\build\plugin.js:135:49) at Object.getContext (E:\workspace\turbo_tw\node_modules\tailwindcss\lib\cli\build\plugin.js:204:27) at E:\workspace\turbo_tw\node_modules\tailwindcss\lib\cli\build\plugin.js:254:38 at E:\workspace\turbo_tw\node_modules\tailwindcss\lib\processTailwindFeatures.js:48:11
> 
> here is the installation and configuration I was referencing: https://preline.co/docs/index.html https://preline.co/docs/configuration.html
> 
> and the config is like below: content: [ 'node_modules/preline/dist/_.js', "./public/**/_.{html,js}", ],
> 
> plugins: [ require('@tailwindcss/aspect-ratio'), // require('@preline/accordion'), require('@preline/collapse'), require('preline/plugin'), ],

Hi,
In our examples we did not use any frameworks. The provided code is incorrect:
```
plugins: [
require('@tailwindcss/aspect-ratio'),
// require('@preline/accordion'),
require('@preline/collapse'),
require('preline/plugin'),
],
```
You should import scripts like the example below:
```
<script src="../assets/vendor/preline/preline.js"></script>

```

**Comment by jahaganiev** [comment]
Hey @Bitomancer - Closing this issue for the moment. Once you've got more details, please feel free to open a new issue. Thanks!
