### ISSUE TITLE
Update Docs for Nuxt 3.0

### ISSUE THREAD

**Issue by JMKelley** [htmlstreamofficial/preline#94]
Having issues installing Preline on Nuxt 3.

**Comment by RonaldJair19** [comment]
Yeah, I ran into this problem today, the documentation is out of date. For those of you who run into this dilemma I have solved it by copying the example they present in Stackblitz, where they create a folder public/assets/preline/dist/ and there add the file preline.js . 

![image](https://github.com/htmlstreamofficial/preline/assets/59004281/3f0af9b6-beb1-478f-80be-2deac494594a)

Then in nuxt.config.js they add the address of the script.

![image](https://github.com/htmlstreamofficial/preline/assets/59004281/4435cf1c-7c0f-4a0b-b0f3-36459cea3fb9)

The tricky thing here is that you have to manually download the preline.js or look for it in the node_modules. It would be nice if this configuration could be improved. Preline is an excellent library.

Note: Don't forget the tailwind.config.js file!

![image](https://github.com/htmlstreamofficial/preline/assets/59004281/3f8133ef-6d4a-4ffa-b92f-230c04fd5e62)

**Comment by JMKelley** [comment]
Thanks for replying. Still not working :( . Just tried this, placed the file in `public/assets/preline/dist/preline.js` then added the following in the nuxt config:

```
  head: {
    script: [
        {
          src: '/assets/preline/dist/preline.js',
          body: true,
          defer: true
        }
    ]
  },
  ```
  
  
  Then changed my tailwind config to to be:
  
```
  /** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    '/assets/preline/dist/preline.js',
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('preline/plugin'),
  ],
}

```

**Comment by RonaldJair19** [comment]
Estas utilizando el módulo @nuxtjs/tailwindcss? Yo recomendaría realizar la instalación directa de tailwind como sale en la documentación oficial: https://tailwindcss.com/docs/guides/nuxtjs

En tu tailwind.config debes tener: 
`module.exports = {
    content: [
      './components/**/*.{js,vue,ts}',
      './layouts/**/*.vue',
      './pages/**/*.vue',
      './plugins/**/*.{js,ts}',
      './nuxt.config.{js,ts}',
      'node_modules/preline/dist/*.js',
    ],
    darkMode: 'class',
    theme: {
      extend: {
        fontFamily: {
          sans: [
            'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji',
          ],
        },
      },
    },
    plugins: [require('preline/plugin')],
  };`

**Comment by Ghustavh97** [comment]
Any update on this?

**Comment by JMKelley** [comment]
Couldn't get it to work myself. Gave up in the end.

**Comment by Ghustavh97** [comment]
@JMKelley where you getting an error? cause I wasn't getting an error but the templates looked weird when I loaded the page. It turns out that it was dark mode that was on by default and the white background I had made it look broken. I used the official nuxt tailwind btw. https://tailwindcss.nuxtjs.org/getting-started/setup

**Comment by karateel** [comment]
If u still trying, this is how i solved it:
tailwind like in docs:
`
  content: [
    './node_modules/preline/dist/*.js',
],
  plugins: [
    require('preline/plugin')
  ]
`


nuxt.config.ts:
`      script: [
        {
          src: '/_nuxt/node_modules/preline/dist/preline.js',
          defer: true
        }
 ]`
Solition: add /_nuxt/

**Comment by jahaganiev** [comment]
Closing this issue for the moment. Once there's any test link with the source code - please feel free to open a new issue. Thanks!
