### ISSUE TITLE
Background SVG not showing for Hero examples

### ISSUE THREAD

**Issue by nickczh** [htmlstreamofficial/preline#95]
Background SVG for Hero Section examples:

1. Polygon Background element 
2. Squared Background element

are not showing. They appear during preview, but disappear once deployed locally.

**Comment by Mr-Zafar** [comment]
@nickczh I will address that issue in the next update. For now, here's a list of missing files:
[Polygon](https://preline.co/assets/svg/component/polygon-bg-element.svg)
[Polygon Dark](https://preline.co/assets/svg/component/polygon-bg-element-dark.svg)
[Squared](https://preline.co/assets/svg/component/squared-bg-element.svg)
[Squared Dark](https://preline.co/assets/svg/component/squared-bg-element-dark.svg)
[Abstract 1](https://preline.co/assets/svg/component/abstract-1.svg)
[Abstract Bg 1](https://preline.co/assets/svg/component/abstract-bg-1.svg)
