### ISSUE TITLE
All examples in example page have a unnecessary `,nav` closing tag

### ISSUE THREAD

**Issue by pc-codersbox** [htmlstreamofficial/preline#97]
The examples in your [Navigation example](https://preline.co/examples/navigations-mega-menu.html) page has HTML setup in following structure:
```
<header ...>
  <div ...>
    ...
  </nav> <!-- This is not correct. You should change the div after header to nav -->
</header>
```

**Comment by Mr-Zafar** [comment]
@pc-codersbox addressed and fixed in v2.0. thanks for the heads up.
