### ISSUE TITLE
Preline UI components that require JS do not work on Angular

### ISSUE THREAD

**Issue by RZMiRaN** [htmlstreamofficial/preline#98]
Dears,
The components that require plugins are not working. Any component that has the notice "Requires JS, Note that this component requires the use of our **** plugin...." doesn't work on Angular.

**Comment by MJ-One** [comment]
hey @RZMiRaN  hope you have found your solution by now. if not, here's what i've tried.

remove the script tag from the index.html file and use the path to prelin.js in node_modules in angular.json

 "scripts": [
              "./node_modules/preline/dist/preline.js"
            ]

like this

**Comment by RZMiRaN** [comment]
Hello @MJ-One 
Thank you for your reply, I really appreciate it. It works now <3

**Comment by ABNERMATHEUS** [comment]
Thanks!!

**Comment by codebangla** [comment]
> "scripts": [
> "./node_modules/preline/dist/preline.js"
> ]

Hello,

Your suggestion is not working for the JS behavior

I followed https://preline.co/docs/frameworks-angular.html

and instead of adding ```
// index.html
<script src="./node_modules/preline/dist/preline.js"></script>
```
I did add in angular.json

`"scripts": [
"./node_modules/preline/dist/preline.js"
]`

and tried

https://preline.co/plugins/html/sidebar.html#js-behavior

none of the JS is working. Please suggest.

**Comment by olegpix** [comment]
> Dears, The components that require plugins are not working. Any component that has the notice "Requires JS, Note that this component requires the use of our **** plugin...." doesn't work on Angular.

Hi,
Could you upload your code to some public service (replit, stackblitz, codepen)?
We will check the error and come back to you with an answer. Otherwise the issue will be closed.

**Comment by jahaganiev** [comment]
Closing this issue for the moment until further updates from others. Thanks!
