### ISSUE TITLE
Remove code that leads to some Error / Warning from the documentation

### ISSUE THREAD

**Issue by tanushm31** [htmlstreamofficial/preline#99]
Hi I was using Preline for some of my projects and I found that there are certain components which contain code like: 
```
<a href="javascript:;" ...
```
This code leads to a warning in the terminal: 
![image](https://github.com/htmlstreamofficial/preline/assets/22880384/266a9336-988b-42c2-8477-8df33b219828)

I think this href can be set to either href ="#" or some other tags can be used in its place. And I don't think its serves any purpose to use href="javascript:;"

**Comment by Mr-Zafar** [comment]
@tanushm31 we will be dropping all of them in Preline v2.

**Comment by jahaganiev** [comment]
Hey @tanushm31, we've just released v2.0 Preline which should have addressed this issue. If you happen to encounter it again with the new version of Preline, please feel free to open a new issue. Thanks!
